In [ ]:
import requests

# Get series information for KXHIGHNY
url = "https://external-api.kalshi.com/trade-api/v2/series/KXHIGHNY"
response = requests.get(url)
series_data = response.json()

print(type(series_data))

print(series_data)
print(f"Series Title: {series_data['series']['title']}")
print(f"Frequency: {series_data['series']['frequency']}")
print(f"Category: {series_data['series']['category']}")

<class 'dict'>
{'series': {'additional_prohibitions': ['Persons who are employed by any of the Source Agencies are not permitted to trade on the Contract.', 'Persons who hold any material, non-public information on the Underlying are not permitted to trade on the Contract.'], 'category': 'Climate and Weather', 'contract_terms_url': 'https://kalshi-public-docs.s3.amazonaws.com/contract_terms/NHIGH.pdf', 'contract_url': 'https://kalshi-public-docs.s3.us-east-1.amazonaws.com/regulatory/product-certifications/NHIGH.pdf', 'fee_multiplier': 1, 'fee_type': 'quadratic', 'frequency': 'daily', 'last_updated_ts': '2026-03-16T15:04:55.113254Z', 'product_metadata': {'important_info': {'id': 'WEATHER-2025-3-3', 'markdown': '**Important information:** Not all weather data is the same. See the rules for more details.', 'message': 'Not all weather data is the same. While checking a source like AccuWeather or Google Weather may help guide your decision, the official and final value used to determine this market is the highest temperature as reported by the relevant NWS Daily Climate Report linked in the rules.', 'title': 'Important information: '}}, 'settlement_sources': [{'name': 'NWS Climatological Report', 'url': 'https://forecast.weather.gov/product.php?site=OKX&product=CLI&issuedby=NYC'}], 'tags': ['Daily temperature'], 'ticker': 'KXHIGHNY', 'title': 'Highest temperature in NYC'}}
Series Title: Highest temperature in NYC
Frequency: daily
Category: Climate and Weather

In [ ]:
# Get all open markets for the KXHIGHNY series
markets_url = f"https://external-api.kalshi.com/trade-api/v2/markets?series_ticker=KXHIGHNY&"
markets_response = requests.get(markets_url)
markets_data = markets_response.json()
print(markets_data)


print(f"\nActive markets in KXHIGHNY series:")
for market in markets_data['markets']:
    print(f"- {market['ticker']}: {market['title']}")
    print(f"  Event: {market['event_ticker']}")
    print(f"  Yes Price: ${market['yes_bid_dollars']} | Volume: {market['volume_fp']}")
    print()

# Get details for a specific event if you have its ticker
if markets_data['markets']:
    # Let's get details for the first market's event
    event_ticker = markets_data['markets'][0]['event_ticker']
    event_url = f"https://external-api.kalshi.com/trade-api/v2/events/{event_ticker}"
    event_response = requests.get(event_url)
    event_data = event_response.json()

    print(f"Event Details:")
    print(f"Title: {event_data['event']['title']}")
    print(f"Category: {event_data['event']['category']}")

{'cursor': 'CgwIwtDV0AYQgNub0wMSFktYSElHSE5ZLTI2TUFZMjctQjgxLjU', 'markets': [{'can_close_early': True, 'close_time': '2026-06-13T04:59:00Z', 'created_time': '2026-06-11T09:30:48.09639Z', 'early_close_condition': 'The Last Trading Time will be 11:59 PM ET on June 12, 2026 regardless of any data releases or events occurring. Expiration will occur on the sooner of the first 7:00 or 8:00\nAM ET following the release of the data for June 12, 2026, or one week after June 12, 2026.', 'event_ticker': 'KXHIGHNY-26JUN12', 'expected_expiration_time': '2026-06-13T14:00:00Z', 'expiration_time': '2026-06-19T14:00:00Z', 'expiration_value': '', 'floor_strike': 97, 'fractional_trading_enabled': True, 'last_price_dollars': '0.0200', 'latest_expiration_time': '2026-06-19T14:00:00Z', 'liquidity_dollars': '0.0000', 'market_type': 'binary', 'no_ask_dollars': '0.9800', 'no_bid_dollars': '0.9700', 'no_sub_title': '98° or above', 'notional_value_dollars': '1.0000', 'occurrence_datetime': '2026-06-12T14:00:00Z', 'open_interest_fp': '680.00', 'open_time': '2026-06-11T14:00:00Z', 'previous_price_dollars': '0.0000', 'previous_yes_ask_dollars': '0.0000', 'previous_yes_bid_dollars': '0.0000', 'price_level_structure': 'linear_cent', 'price_ranges': [{'end': '1.0000', 'start': '0.0000', 'step': '0.0100'}], 'response_price_units': 'usd_cent', 'result': '', 'rules_primary': "If the highest temperature recorded in Central Park, New York for June 12, 2026 as reported by the National Weather Service's Climatological Report (Daily), is greater than 97°, then the market resolves to Yes.", 'rules_secondary': 'Not all weather data is the same. While checking a source like AccuWeather or Google Weather may help guide your decision, the official and final value used to determine this market is the highest temperature as reported by the corresponding NWS Climatological Report (Daily) linked in the rules above. Preliminary NWS reporting and measurement methods may be subject to underlying rounding and conversion nuances. Traders should exercise caution when interpreting preliminary NWS data.', 'settlement_timer_seconds': 3600, 'status': 'active', 'strike_type': 'greater', 'subtitle': '98° or above', 'ticker': 'KXHIGHNY-26JUN12-T97', 'title': 'Will the **high temp in NYC** be >97° on Jun 12, 2026?', 'updated_time': '2026-06-11T14:00:02.220846Z', 'volume_24h_fp': '1132.00', 'volume_fp': '1132.00', 'yes_ask_dollars': '0.0300', 'yes_ask_size_fp': '122.85', 'yes_bid_dollars': '0.0200', 'yes_bid_size_fp': '223.09', 'yes_sub_title': '98° or above'}, {'can_close_early': True, 'cap_strike': 90, 'close_time': '2026-06-13T04:59:00Z', 'created_time': '2026-06-11T09:30:48.09639Z', 'early_close_condition': 'The Last Trading Time will be 11:59 PM ET on June 12, 2026 regardless of any data releases or events occurring. Expiration will occur on the sooner of the first 7:00 or 8:00\nAM ET following the release of the data for June 12, 2026, or one week after June 12, 2026.', 'event_ticker': 'KXHIGHNY-26JUN12', 'expected_expiration_time': '2026-06-13T14:00:00Z', 'expiration_time': '2026-06-19T14:00:00Z', 'expiration_value': '', 'fractional_trading_enabled': True, 'last_price_dollars': '0.0400', 'latest_expiration_time': '2026-06-19T14:00:00Z', 'liquidity_dollars': '0.0000', 'market_type': 'binary', 'no_ask_dollars': '0.9800', 'no_bid_dollars': '0.9700', 'no_sub_title': '89° or below', 'notional_value_dollars': '1.0000', 'occurrence_datetime': '2026-06-12T14:00:00Z', 'open_interest_fp': '188.57', 'open_time': '2026-06-11T14:00:00Z', 'previous_price_dollars': '0.0000', 'previous_yes_ask_dollars': '0.0000', 'previous_yes_bid_dollars': '0.0000', 'price_level_structure': 'linear_cent', 'price_ranges': [{'end': '1.0000', 'start': '0.0000', 'step': '0.0100'}], 'response_price_units': 'usd_cent', 'result': '', 'rules_primary': "If the highest temperature recorded in Central Park, New York for June 12, 2026 as reported by the National Weather Service's Climatological Report (Daily), is less than 90°, then the market resolves to Yes.", 'rules_secondary': 'Not all weather data is the same. While checking a source like AccuWeather or Google Weather may help guide your decision, the official and final value used to determine this market is the highest temperature as reported by the corresponding NWS Climatological Report (Daily) linked in the rules above. Preliminary NWS reporting and measurement methods may be subject to underlying rounding and conversion nuances. Traders should exercise caution when interpreting preliminary NWS data.', 'settlement_timer_seconds': 3600, 'status': 'active', 'strike_type': 'less', 'subtitle': '89° or below', 'ticker': 'KXHIGHNY-26JUN12-T90', 'title': 'Will the **high temp in NYC** be <90° on Jun 12, 2026?', 'updated_time': '2026-06-11T14:00:02.220846Z', 'volume_24h_fp': '202.57', 'volume_fp': '202.57', 'yes_ask_dollars': '0.0300', 'yes_ask_size_fp': '12.00', 'yes_bid_dollars': '0.0200', 'yes_bid_size_fp': '292.00', 'yes_sub_title': '89° or below'}, {'can_close_early': True, 'cap_strike': 97, 'close_time': '2026-06-13T04:59:00Z', 'created_time': '2026-06-11T09:30:48.09639Z', 'early_close_condition': 'The Last Trading Time will be 11:59 PM ET on June 12, 2026 regardless of any data releases or events occurring. Expiration will occur on the sooner of the first 7:00 or 8:00\nAM ET following the release of the data for June 12, 2026, or one week after June 12, 2026.', 'event_ticker': 'KXHIGHNY-26JUN12', 'expected_expiration_time': '2026-06-13T14:00:00Z', 'expiration_time': '2026-06-19T14:00:00Z', 'expiration_value': '', 'floor_strike': 96, 'fractional_trading_enabled': True, 'last_price_dollars': '0.1200', 'latest_expiration_time': '2026-06-19T14:00:00Z', 'liquidity_dollars': '0.0000', 'market_type': 'binary', 'no_ask_dollars': '0.9000', 'no_bid_dollars': '0.8900', 'no_sub_title': '96° to 97°', 'notional_value_dollars': '1.0000', 'occurrence_datetime': '2026-06-12T14:00:00Z', 'open_interest_fp': '497.84', 'open_time': '2026-06-11T14:00:00Z', 'previous_price_dollars': '0.0000', 'previous_yes_ask_dollars': '0.0000', 'previous_yes_bid_dollars': '0.0000', 'price_level_structure': 'linear_cent', 'price_ranges': [{'end': '1.0000', 'start': '0.0000', 'step': '0.0100'}], 'response_price_units': 'usd_cent', 'result': '', 'rules_primary': "If the highest temperature recorded in Central Park, New York for June 12, 2026 as reported by the National Weather Service's Climatological Report (Daily), is between 96-97°, then the market resolves to Yes.", 'rules_secondary': 'Not all weather data is the same. While checking a source like AccuWeather or Google Weather may help guide your decision, the official and final value used to determine this market is the highest temperature as reported by the corresponding NWS Climatological Report (Daily) linked in the rules above. Preliminary NWS reporting and measurement methods may be subject to underlying rounding and conversion nuances. Traders should exercise caution when interpreting preliminary NWS data.', 'settlement_timer_seconds': 3600, 'status': 'active', 'strike_type': 'between', 'subtitle': '96° to 97°', 'ticker': 'KXHIGHNY-26JUN12-B96.5', 'title': 'Will the **high temp in NYC** be 96-97° on Jun 12, 2026?', 'updated_time': '2026-06-11T14:00:02.041974Z', 'volume_24h_fp': '588.69', 'volume_fp': '595.69', 'yes_ask_dollars': '0.1100', 'yes_ask_size_fp': '118.82', 'yes_bid_dollars': '0.1000', 'yes_bid_size_fp': '10.00', 'yes_sub_title': '96° to 97°'}, {'can_close_early': True, 'cap_strike': 95, 'close_time': '2026-06-13T04:59:00Z', 'created_time': '2026-06-11T09:30:48.09639Z', 'early_close_condition': 'The Last Trading Time will be 11:59 PM ET on June 12, 2026 regardless of any data releases or events occurring. Expiration will occur on the sooner of the first 7:00 or 8:00\nAM ET following the release of the data for June 12, 2026, or one week after June 12, 2026.', 'event_ticker': 'KXHIGHNY-26JUN12', 'expected_expiration_time': '2026-06-13T14:00:00Z', 'expiration_time': '2026-06-19T14:00:00Z', 'expiration_value': '', 'floor_strike': 94, 'fractional_trading_enabled': True, 'last_price_dollars': '0.2800', 'latest_expiration_time': '2026-06-19T14:00:00Z', 'liquidity_dollars': '0.0000', 'market_type': 'binary', 'no_ask_dollars': '0.7300', 'no_bid_dollars': '0.7100', 'no_sub_title': '94° to 95°', 'notional_value_dollars': '1.0000', 'occurrence_datetime': '2026-06-12T14:00:00Z', 'open_interest_fp': '627.33', 'open_time': '2026-06-11T14:00:00Z', 'previous_price_dollars': '0.0000', 'previous_yes_ask_dollars': '0.0000', 'previous_yes_bid_dollars': '0.0000', 'price_level_structure': 'linear_cent', 'price_ranges': [{'end': '1.0000', 'start': '0.0000', 'step': '0.0100'}], 'response_price_units': 'usd_cent', 'result': '', 'rules_primary': "If the highest temperature recorded in Central Park, New York for June 12, 2026 as reported by the National Weather Service's Climatological Report (Daily), is between 94-95°, then the market resolves to Yes.", 'rules_secondary': 'Not all weather data is the same. While checking a source like AccuWeather or Google Weather may help guide your decision, the official and final value used to determine this market is the highest temperature as reported by the corresponding NWS Climatological Report (Daily) linked in the rules above. Preliminary NWS reporting and measurement methods may be subject to underlying rounding and conversion nuances. Traders should exercise caution when interpreting preliminary NWS data.', 'settlement_timer_seconds': 3600, 'status': 'active', 'strike_type': 'between', 'subtitle': '94° to 95°', 'ticker': 'KXHIGHNY-26JUN12-B94.5', 'title': 'Will the **high temp in NYC** be 94-95° on Jun 12, 2026?', 'updated_time': '2026-06-11T14:00:02.220846Z', 'volume_24h_fp': '620.03', 'volume_fp': '730.11', 'yes_ask_dollars': '0.2900', 'yes_ask_size_fp': '98.37', 'yes_bid_dollars': '0.2700', 'yes_bid_size_fp': '19.34', 'yes_sub_title': '94° to 95°'}, {'can_close_early': True, 'cap_strike': 93, 'close_time': '2026-06-13T04:59:00Z', 'created_time': '2026-06-11T09:30:48.09639Z', 'early_close_condition': 'The Last Trading Time will be 11:59 PM ET on June 12, 2026 regardless of any data releases or events occurring. Expiration will occur on the sooner of the first 7:00 or 8:00\nAM ET following the release of the data for June 12, 2026, or one week after June 12, 2026.', 'event_ticker': 'KXHIGHNY-26JUN12', 'expected_expiration_time': '2026-06-13T14:00:00Z', 'expiration_time': '2026-06-19T14:00:00Z', 'expiration_value': '', 'floor_strike': 92, 'fractional_trading_enabled': True, 'last_price_dollars': '0.4600', 'latest_expiration_time': '2026-06-19T14:00:00Z', 'liquidity_dollars': '0.0000', 'market_type': 'binary', 'no_ask_dollars': '0.5400', 'no_bid_dollars': '0.5300', 'no_sub_title': '92° to 93°', 'notional_value_dollars': '1.0000', 'occurrence_datetime': '2026-06-12T14:00:00Z', 'open_interest_fp': '1780.48', 'open_time': '2026-06-11T14:00:00Z', 'previous_price_dollars': '0.0000', 'previous_yes_ask_dollars': '0.0000', 'previous_yes_bid_dollars': '0.0000', 'price_level_structure': 'linear_cent', 'price_ranges': [{'end': '1.0000', 'start': '0.0000', 'step': '0.0100'}], 'response_price_units': 'usd_cent', 'result': '', 'rules_primary': "If the highest temperature recorded in Central Park, New York for June 12, 2026 as reported by the National Weather Service's Climatological Report (Daily), is between 92-93°, then the market resolves to Yes.", 'rules_secondary': 'Not all weather data is the same. While checking a source like AccuWeather or Google Weather may help guide your decision, the official and final value used to determine this market is the highest temperature as reported by the corresponding NWS Climatological Report (Daily) linked in the rules above. Preliminary NWS reporting and measurement methods may be subject to underlying rounding and conversion nuances. Traders should exercise caution when interpreting preliminary NWS data.', 'settlement_timer_seconds': 3600, 'status': 'active', 'strike_type': 'between', 'subtitle': '92° to 93°', 'ticker': 'KXHIGHNY-26JUN12-B92.5', 'title': 'Will the **high temp in NYC** be 92-93° on Jun 12, 2026?', 'updated_time': '2026-06-11T14:00:02.041974Z', 'volume_24h_fp': '1960.29', 'volume_fp': '1988.76', 'yes_ask_dollars': '0.4700', 'yes_ask_size_fp': '46.53', 'yes_bid_dollars': '0.4600', 'yes_bid_size_fp': '349.00', 'yes_sub_title': '92° to 93°'}, {'can_close_early': True, 'cap_strike': 91, 'close_time': '2026-06-13T04:59:00Z', 'created_time': '2026-06-11T09:30:48.09639Z', 'early_close_condition': 'The Last Trading Time will be 11:59 PM ET on June 12, 2026 regardless of any data releases or events occurring. Expiration will occur on the sooner of the first 7:00 or 8:00\nAM ET following the release of the data for June 12, 2026, or one week after June 12, 2026.', 'event_ticker': 'KXHIGHNY-26JUN12', 'expected_expiration_time': '2026-06-13T14:00:00Z', 'expiration_time': '2026-06-19T14:00:00Z', 'expiration_value': '', 'floor_strike': 90, 'fractional_trading_enabled': True, 'last_price_dollars': '0.1300', 'latest_expiration_time': '2026-06-19T14:00:00Z', 'liquidity_dollars': '0.0000', 'market_type': 'binary', 'no_ask_dollars': '0.8900', 'no_bid_dollars': '0.8500', 'no_sub_title': '90° to 91°', 'notional_value_dollars': '1.0000', 'occurrence_datetime': '2026-06-12T14:00:00Z', 'open_interest_fp': '835.05', 'open_time': '2026-06-11T14:00:00Z', 'previous_price_dollars': '0.0000', 'previous_yes_ask_dollars': '0.0000', 'previous_yes_bid_dollars': '0.0000', 'price_level_structure': 'linear_cent', 'price_ranges': [{'end': '1.0000', 'start': '0.0000', 'step': '0.0100'}], 'response_price_units': 'usd_cent', 'result': '', 'rules_primary': "If the highest temperature recorded in Central Park, New York for June 12, 2026 as reported by the National Weather Service's Climatological Report (Daily), is between 90-91°, then the market resolves to Yes.", 'rules_secondary': 'Not all weather data is the same. While checking a source like AccuWeather or Google Weather may help guide your decision, the official and final value used to determine this market is the highest temperature as reported by the corresponding NWS Climatological Report (Daily) linked in the rules above. Preliminary NWS reporting and measurement methods may be subject to underlying rounding and conversion nuances. Traders should exercise caution when interpreting preliminary NWS data.', 'settlement_timer_seconds': 3600, 'status': 'active', 'strike_type': 'between', 'subtitle': '90° to 91°', 'ticker': 'KXHIGHNY-26JUN12-B90.5', 'title': 'Will the **high temp in NYC** be 90-91° on Jun 12, 2026?', 'updated_time': '2026-06-11T14:00:02.220846Z', 'volume_24h_fp': '1152.88', 'volume_fp': '1344.78', 'yes_ask_dollars': '0.1500', 'yes_ask_size_fp': '7.00', 'yes_bid_dollars': '0.1100', 'yes_bid_size_fp': '17.00', 'yes_sub_title': '90° to 91°'}, {'can_close_early': True, 'close_time': '2026-06-12T04:59:00Z', 'created_time': '2026-06-10T09:30:45.674884Z', 'early_close_condition': 'The Last Trading Time will be 11:59 PM ET on June 11, 2026 regardless of any data releases or events occurring. Expiration will occur on the sooner of the first 7:00 or 8:00\nAM ET following the release of the data for June 11, 2026, or one week after June 11, 2026.', 'event_ticker': 'KXHIGHNY-26JUN11', 'expected_expiration_time': '2026-06-12T14:00:00Z', 'expiration_time': '2026-06-18T14:00:00Z', 'expiration_value': '', 'floor_strike': 95, 'fractional_trading_enabled': True, 'last_price_dollars': '0.0100', 'latest_expiration_time': '2026-06-18T14:00:00Z', 'liquidity_dollars': '0.0000', 'market_type': 'binary', 'no_ask_dollars': '1.0000', 'no_bid_dollars': '0.9900', 'no_sub_title': '96° or above', 'notional_value_dollars': '1.0000', 'occurrence_datetime': '2026-06-11T14:00:00Z', 'open_interest_fp': '23644.65', 'open_time': '2026-06-10T14:00:00Z', 'previous_price_dollars': '0.0900', 'previous_yes_ask_dollars': '0.0900', 'previous_yes_bid_dollars': '0.0800', 'price_level_structure': 'linear_cent', 'price_ranges': [{'end': '1.0000', 'start': '0.0000', 'step': '0.0100'}], 'response_price_units': 'usd_cent', 'result': '', 'rules_primary': "If the highest temperature recorded in Central Park, New York for June 11, 2026 as reported by the National Weather Service's Climatological Report (Daily), is greater than 95°, then the market resolves to Yes.", 'rules_secondary': 'Not all weather data is the same. While checking a source like AccuWeather or Google Weather may help guide your decision, the official and final value used to determine this market is the highest temperature as reported by the corresponding NWS Climatological Report (Daily) linked in the rules above. Preliminary NWS reporting and measurement methods may be subject to underlying rounding and conversion nuances. Traders should exercise caution when interpreting preliminary NWS data.', 'settlement_timer_seconds': 3600, 'status': 'active', 'strike_type': 'greater', 'subtitle': '96° or above', 'ticker': 'KXHIGHNY-26JUN11-T95', 'title': 'Will the **high temp in NYC** be >95° on Jun 11, 2026?', 'updated_time': '2026-06-10T14:00:01.122376Z', 'volume_24h_fp': '27949.35', 'volume_fp': '30513.55', 'yes_ask_dollars': '0.0100', 'yes_ask_size_fp': '4565.35', 'yes_bid_dollars': '0.0000', 'yes_bid_size_fp': '0.00', 'yes_sub_title': '96° or above'}, {'can_close_early': True, 'cap_strike': 88, 'close_time': '2026-06-12T04:59:00Z', 'created_time': '2026-06-10T09:30:45.674884Z', 'early_close_condition': 'The Last Trading Time will be 11:59 PM ET on June 11, 2026 regardless of any data releases or events occurring. Expiration will occur on the sooner of the first 7:00 or 8:00\nAM ET following the release of the data for June 11, 2026, or one week after June 11, 2026.', 'event_ticker': 'KXHIGHNY-26JUN11', 'expected_expiration_time': '2026-06-12T14:00:00Z', 'expiration_time': '2026-06-18T14:00:00Z', 'expiration_value': '', 'fractional_trading_enabled': True, 'last_price_dollars': '0.0100', 'latest_expiration_time': '2026-06-18T14:00:00Z', 'liquidity_dollars': '0.0000', 'market_type': 'binary', 'no_ask_dollars': '1.0000', 'no_bid_dollars': '0.9900', 'no_sub_title': '87° or below', 'notional_value_dollars': '1.0000', 'occurrence_datetime': '2026-06-11T14:00:00Z', 'open_interest_fp': '17797.01', 'open_time': '2026-06-10T14:00:00Z', 'previous_price_dollars': '0.0100', 'previous_yes_ask_dollars': '0.0200', 'previous_yes_bid_dollars': '0.0100', 'price_level_structure': 'linear_cent', 'price_ranges': [{'end': '1.0000', 'start': '0.0000', 'step': '0.0100'}], 'response_price_units': 'usd_cent', 'result': '', 'rules_primary': "If the highest temperature recorded in Central Park, New York for June 11, 2026 as reported by the National Weather Service's Climatological Report (Daily), is less than 88°, then the market resolves to Yes.", 'rules_secondary': 'Not all weather data is the same. While checking a source like AccuWeather or Google Weather may help guide your decision, the official and final value used to determine this market is the highest temperature as reported by the corresponding NWS Climatological Report (Daily) linked in the rules above. Preliminary NWS reporting and measurement methods may be subject to underlying rounding and conversion nuances. Traders should exercise caution when interpreting preliminary NWS data.', 'settlement_timer_seconds': 3600, 'status': 'active', 'strike_type': 'less', 'subtitle': '87° or below', 'ticker': 'KXHIGHNY-26JUN11-T88', 'title': 'Will the **high temp in NYC** be <88° on Jun 11, 2026?', 'updated_time': '2026-06-10T14:00:00.71053Z', 'volume_24h_fp': '17158.26', 'volume_fp': '18834.40', 'yes_ask_dollars': '0.0100', 'yes_ask_size_fp': '159264.87', 'yes_bid_dollars': '0.0000', 'yes_bid_size_fp': '0.00', 'yes_sub_title': '87° or below'}, {'can_close_early': True, 'cap_strike': 95, 'close_time': '2026-06-12T04:59:00Z', 'created_time': '2026-06-10T09:30:45.674884Z', 'early_close_condition': 'The

In [ ]:
# Get orderbook for a specific market
# Replace with an actual market ticker from the markets list
if not markets_data['markets']:
    raise ValueError("No open markets found. Try removing status=open or choose another series.")

market_ticker = markets_data['markets'][0]['ticker']
orderbook_url = f"https://external-api.kalshi.com/trade-api/v2/markets/{market_ticker}/orderbook"

orderbook_response = requests.get(orderbook_url)
orderbook_data = orderbook_response.json()

print(f"\nOrderbook for {market_ticker}:")
print("YES BIDS:")
for price_dollars, count_fp in orderbook_data['orderbook_fp']['yes_dollars'][:5]:  # Show top 5
    print(f"  Price: ${price_dollars}, Quantity: {count_fp}")

print("\nNO BIDS:")
for price_dollars, count_fp in orderbook_data['orderbook_fp']['no_dollars'][:5]:  # Show top 5
    print(f"  Price: ${price_dollars}, Quantity: {count_fp}")

In [ ]:
#Getting Economics category tickers for all events
import requests
import pandas as pd
import time
from typing import Optional, Dict, Any, List

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"
CATEGORY = "Economics"


def kalshi_get(path: str, params: Optional[Dict[str, Any]] = None, max_retries: int = 3) -> Dict[str, Any]:
    """
    Simple GET helper with basic retry handling.
    Public market-data endpoints do not require authentication.
    """
    url = f"{BASE_URL}{path}"
    params = params or {}

    for attempt in range(max_retries):
        try:
            response = requests.get(url, params=params, timeout=30)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            if attempt == max_retries - 1:
                raise
            time.sleep(1.5 * (attempt + 1))


def get_series_by_category(category: str = "Economics") -> List[Dict[str, Any]]:
    """
    Get all Kalshi series in a category.
    """
    data = kalshi_get(
        "/series",
        params={
            "category": category,
            "include_product_metadata": "true",
            "include_volume": "true",
        },
    )
    return data.get("series", [])


def get_events_for_series(
    series_ticker: str,
    status: Optional[str] = None,
    with_nested_markets: bool = True,
) -> List[Dict[str, Any]]:
    """
    Get all events for one series ticker, handling cursor pagination.

    status options:
      None      -> all statuses
      "unopened"
      "open"
      "closed"
      "settled"
    """
    all_events = []
    cursor = None

    while True:
        params = {
            "series_ticker": series_ticker,
            "limit": 200,
            "with_nested_markets": str(with_nested_markets).lower(),
        }

        if status is not None:
            params["status"] = status

        if cursor:
            params["cursor"] = cursor

        data = kalshi_get("/events", params=params)

        events = data.get("events", [])
        all_events.extend(events)

        cursor = data.get("cursor")
        if not cursor:
            break

    return all_events


def economics_events_markets_df(
    category: str = "Economics",
    status: Optional[str] = None,
) -> pd.DataFrame:
    """
    Returns one row per market.

    If an event has no nested markets returned, it still creates one row
    with market fields set to None so you do not lose the event.
    """
    series_list = get_series_by_category(category)
    rows = []

    print(f"Found {len(series_list)} series in category={category!r}")

    for i, series in enumerate(series_list, start=1):
        series_ticker = series.get("ticker")
        series_title = series.get("title")

        print(f"[{i}/{len(series_list)}] Fetching events for {series_ticker}: {series_title}")

        events = get_events_for_series(
            series_ticker=series_ticker,
            status=status,
            with_nested_markets=True,
        )

        for event in events:
            markets = event.get("markets") or []

            event_base = {
                "category": event.get("category"),
                "series_ticker": event.get("series_ticker"),
                "series_title": series.get("title"),
                "series_frequency": series.get("frequency"),
                "series_tags": series.get("tags"),
                "event_ticker": event.get("event_ticker"),
                "event_title": event.get("title"),
                "event_sub_title": event.get("sub_title"),
                "event_strike_date": event.get("strike_date"),
                "event_strike_period": event.get("strike_period"),
                "event_last_updated_ts": event.get("last_updated_ts"),
                "event_product_metadata": event.get("product_metadata"),
            }

            if not markets:
                rows.append({
                    **event_base,
                    "market_ticker": None,
                    "market_question": None,
                    "market_title": None,
                    "market_subtitle": None,
                    "yes_sub_title": None,
                    "no_sub_title": None,
                    "market_status_open_time": None,
                    "market_close_time": None,
                    "market_expiration_time": None,
                    "yes_bid_dollars": None,
                    "yes_ask_dollars": None,
                    "no_bid_dollars": None,
                    "no_ask_dollars": None,
                    "last_price_dollars": None,
                    "volume_fp": None,
                    "volume_24h_fp": None,
                    "open_interest_fp": None,
                    "liquidity_dollars": None,
                    "rules_primary": None,
                    "rules_secondary": None,
                })
            else:
                for market in markets:
                    rows.append({
                        **event_base,
                        "market_ticker": market.get("ticker"),
                        # Kalshi's user-facing market question is usually the market title.
                        "market_question": market.get("title"),
                        "market_title": market.get("title"),
                        "market_subtitle": market.get("subtitle"),
                        "yes_sub_title": market.get("yes_sub_title"),
                        "no_sub_title": market.get("no_sub_title"),
                        "market_status_open_time": market.get("open_time"),
                        "market_close_time": market.get("close_time"),
                        "market_expiration_time": market.get("expiration_time"),
                        "yes_bid_dollars": market.get("yes_bid_dollars"),
                        "yes_ask_dollars": market.get("yes_ask_dollars"),
                        "no_bid_dollars": market.get("no_bid_dollars"),
                        "no_ask_dollars": market.get("no_ask_dollars"),
                        "last_price_dollars": market.get("last_price_dollars"),
                        "volume_fp": market.get("volume_fp"),
                        "volume_24h_fp": market.get("volume_24h_fp"),
                        "open_interest_fp": market.get("open_interest_fp"),
                        "liquidity_dollars": market.get("liquidity_dollars"),
                        "rules_primary": market.get("rules_primary"),
                        "rules_secondary": market.get("rules_secondary"),
                    })

    df = pd.DataFrame(rows)

    # Optional cleanup: remove duplicate market rows if pagination/API overlap ever occurs.
    if not df.empty:
        df = df.drop_duplicates(
            subset=["series_ticker", "event_ticker", "market_ticker"],
            keep="first",
        ).reset_index(drop=True)

    return df


# Use status=None for all events regardless of status.
# Use status="open" if you only want currently open economics markets.
df = economics_events_markets_df(
    category="Economics",
    status=None,
)

print("Rows:", len(df))
print("Unique series:", df["series_ticker"].nunique() if not df.empty else 0)
print("Unique events:", df["event_ticker"].nunique() if not df.empty else 0)
print("Unique markets:", df["market_ticker"].nunique() if not df.empty else 0)

Found 578 series in category='Economics'
[1/578] Fetching events for REALWAGES: Real wage growth
[2/578] Fetching events for KXCBDECISIONKOREA: Bank Of KOREA policy interest rate decision
[3/578] Fetching events for PCECORE: US Core PCE inflation
[4/578] Fetching events for KXUTILITYSOCAL: SoCal electricity prices
[5/578] Fetching events for KXCPICORE220: Will the BLS Core CPI YoY print below 2.20%
[6/578] Fetching events for KXBRAZILJOBS: Brazil New Caged net formal job creation
[7/578] Fetching events for KXECONSTATCORECPIYOY: year over year core inflation
[8/578] Fetching events for OILW: Price of oil weekly
[9/578] Fetching events for KXHOUSESTART: US housing starts rise
[10/578] Fetching events for KXEZCPIYOYF: Euro Area Inflation Rate YoY Flash
[11/578] Fetching events for NYCRENTSM: NYC rent monthly increase
[12/578] Fetching events for TBILL: Treasury bill rate
[13/578] Fetching events for CPIAPPAREL: CPI on apparel
[14/578] Fetching events for OIL: Price of oil monthly
[15/578] Fetching events for GASMIN: EIA Gas lowest price yearly
[16/578] Fetching events for KXUSGASCPI: US gasoline CPI in [month]
[17/578] Fetching events for KXUST30: UST30
[18/578] Fetching events for KXDIESELM: Diesel price this month
[19/578] Fetching events for SFRENTSY: SF yearly rent growth
[20/578] Fetching events for KXCHINACPI: CPI in China
[21/578] Fetching events for KXNYCBILLIONAIRES: Billionaires lost
[22/578] Fetching events for DIESELM: Diesel price this month
[23/578] Fetching events for KXCAIVEYPMI: Canada Ivey PMI s.a
[24/578] Fetching events for KXAAMMCAPEX: Amazon, Alphabet, Microsoft, and Meta combined capital expenditures for year
[25/578] Fetching events for KXMEDIANRENTHOU: MEDIAN RENT HOUSTON
[26/578] Fetching events for KXPROLLS: Jobs numbers
[27/578] Fetching events for KXTDEFFICITBY: Deficit Amount by Date
[28/578] Fetching events for AAAGASM: US gas price
[29/578] Fetching events for KXBOJDECISION: BOJ decision
[30/578] Fetching events for KXSAMSUNGSTRIKE: Samsung Electronics labor union strike
[31/578] Fetching events for KXPOWERKWH: Average US electricity price this month
[32/578] Fetching events for HOUSELENGTH: US house average sale length
[33/578] Fetching events for KXBARRLES: Oil barrels
[34/578] Fetching events for KX: KX
[35/578] Fetching events for KXUSIPMOM: US industrial production MoM
[36/578] Fetching events for KXCBDECISIONBRAZIL: Brazil
[37/578] Fetching events for KXCHCPIYOY: China Inflation Rate YoY
[38/578] Fetching events for KXHLENDREDM: Will BlackRock HLEND suspend repurchases by [date]
[39/578] Fetching events for KXCACPIYOY: Canada Inflation Rate YoY
[40/578] Fetching events for RECSSNBER: Recession
[41/578] Fetching events for KXCBDECISIONINDIA: Bank of India policy interest rate decision
[42/578] Fetching events for KXNETWORTHROYLEE: Will Roy Lee become a Billionaire by 2029
[43/578] Fetching events for KXFEAR: Fear and Greed index
[44/578] Fetching events for KXTARIFFREVENUE: Tariff revenue
[45/578] Fetching events for KXNFPDELAY: Jobs data released
[46/578] Fetching events for KXUSPSPEND: United States Personal Spending MoM
[47/578] Fetching events for RATECUTS: Number of rate cuts
[48/578] Fetching events for KXSPR: SPRMAX
[49/578] Fetching events for KXEASTCOASTPORTSTRIKE: ILA strike
[50/578] Fetching events for NYCRENTSY: NYC rent yearly increase
[51/578] Fetching events for WCPI-TR: Turkey inflation
[52/578] Fetching events for KXHLENDHALT: BlackRock HLEND suspend repurchases by [date]
[53/578] Fetching events for CPICORE: CPI core
[54/578] Fetching events for CPIAR: Argentina inflation
[55/578] Fetching events for KXMEDIANRENTCHI: MEDIAN RENT CHICAGO
[56/578] Fetching events for KXTORCONDO: Toronto condo price below $X in [year]?
[57/578] Fetching events for MORTGAGEDEF: Mortgage defaults
[58/578] Fetching events for HOMEUS: US housing price up monthly
[59/578] Fetching events for KXTRUFBPPI: Truflation Bitcoin Purchasing Power Index
[60/578] Fetching events for ECONPATH: State of the economy
[61/578] Fetching events for FXPESO: USD/Mexican peso exchange rate
[62/578] Fetching events for KXDEBTGROWTH: U.S. debt growth
[63/578] Fetching events for KXESGDPQOQF: Spain GDP Growth Rate QoQ Flash (quarterly)
[64/578] Fetching events for KXREALWAGES: Real wage growth
[65/578] Fetching events for KXAAAGASMINFL: Florida lowest gas price yearly
[66/578] Fetching events for KXCPIFOOD: CPI on food
[67/578] Fetching events for KXHOUHOMEVAL: Houston typical home value for date
[68/578] Fetching events for KXUTILITYNYC: NYC electricity prices
[69/578] Fetching events for KXEHSHARE: Existing home sales in time period
[70/578] Fetching events for KXSFHOMEVAL: San Francisco typical home value on date
[71/578] Fetching events for KXPCECORE: US Core PCE inflation
[72/578] Fetching events for KXECONSTATCPICORE: month over month core inflation
[73/578] Fetching events for KXDEBTLEVEL: U.S. debt level
[74/578] Fetching events for KXDECPIPREL: Germany Inflation Rate YoY Prel
[75/578] Fetching events for KXSHELTERCPI: US shelter CPI in [month]
[76/578] Fetching events for KXNYCRENTSM: NYC rent monthly increase
[77/578] Fetching events for KXFED: Fed funds rate
[78/578] Fetching events for FRMMAX: Mortgage rate high
[79/578] Fetching events for KXSEMIPRODH: US Semiconductor production
[80/578] Fetching events for KXMUSKTRILLION: Musk trillionaire
[81/578] Fetching events for KXSUEZTRAFFIC: Suez traffic
[82/578] Fetching events for KXAMSAVO: Hass avocado prices this week
[83/578] Fetching events for KXUSMICHCSP: United States Michigan Consumer Sentiment Prel
[84/578] Fetching events for KXCPICOREA: Core CPI annually
[85/578] Fetching events for KXACPICORE: Annual core inflation
[86/578] Fetching events for BANKRUPTS: Companies going bankrupt
[87/578] Fetching events for JOBLESS: Initial jobless claims
[88/578] Fetching events for KXGDPCN: China GDP growth
[89/578] Fetching events for KXFEDDECISION: Fed meeting
[90/578] Fetching events for KXCHGDPYOY: China GDP Growth Rate YoY (quarterly)
[91/578] Fetching events for CPI: CPI
[92/578] Fetching events for GASMAX: EIA Gas highest price yearly
[93/578] Fetching events for FEDFACILITY: Fed facility
[94/578] Fetching events for KXPPISEMI: Semiconductor PPI
[95/578] Fetching events for AAAGASMAXTX: Texas highest gas price yearly
[96/578] Fetching events for KXRBWSTRIKE: NYC RBW Strike
[97/578] Fetching events for KXGAS: Gas weekly
[98/578] Fetching events for KXEXPORTTARIFF: Export tariffs
[99/578] Fetching events for KXUSNFP: US nonfarm payrolls in [month]
[100/578] Fetching events for GDPUSMAX: US GDP peak
[101/578] Fetching events for KXBRAZILGDP: Brazilian GDP Growth
[102/578] Fetching events for CREDEFMINMAX: Commercial real estate lowest default rate
[103/578] Fetching events for KXTEMPHELP: Will temporary-help employment increase in [month]?
[104/578] Fetching events for KXGDPYEAR: Annual GDP
[105/578] Fetching events for CHINAUSGDP: China overtakes US GDP
[106/578] Fetching events for RATECUTCOUNT: Number of rate cuts
[107/578] Fetching events for RUBLE: Price of Ruble
[108/578] Fetching events for KXNURSESTRIKE: When will the NYC nurse strike end?
[109/578] Fetching events for KXCPICOREYOY: Core inflation
[110/578] Fetching events for KXNJDRONES: NJ DRONES
[111/578] Fetching events for KXPPICPI: PPI YoY exceeds CPI YoY for [time period]
[112/578] Fetching events for KXUSDIRR: USD/IRR exchange rate
[113/578] Fetching events for KXNYCSURP: Will New York City report a General Fund surplus for FY[year]?
[114/578] Fetching events for CPISHELTER: CPI on shelter
[115/578] Fetching events for KXGASD: Gas daily
[116/578] Fetching events for LCPIYOY: Inflation surge this year
[117/578] Fetching events for POWELLLEAVE: Powell leaving
[118/578] Fetching events for KXRATECUTE: Rate cut at November 2024 meeting
[119/578] Fetching events for KXDENHOMEVAL: Denver typical home value for date
[120/578] Fetching events for AAAGASMIN: US lowest gas price yearly
[121/578] Fetching events for KXISMPMI: ISM PMI
[122/578] Fetching events for KXFRGDPYOYP: France GDP Growth Rate YoY Prel (quarterly)
[123/578] Fetching events for ARINFLATIONM: Argentina inflation
[124/578] Fetching events for KXCANCUTS: Number of BoC rate cuts in [year]?
[125/578] Fetching events for KXSDHOMEVAL: San Diego typical home value on date
[126/578] Fetching events for KXCBRATEHIKE: Which central banks will hike this year?
[127/578] Fetching events for KXJOBREVISION: Job revisions
[128/578] Fetching events for KXTOP3WEALTH: Top 3 wealthiest people
[129/578] Fetching events for KXBOEGOLD: BOE gold withdrawals
[130/578] Fetching events for KXUSTM: USTM
[131/578] Fetching events for KXTOKENUST: Tokenized Treasuries
[132/578] Fetching events for KXFTAPER: Fed tapering
[133/578] Fetching events for ETHETF: ETH ETF listed
[134/578] Fetching events for KXAAAGASMAXTX: Texas highest gas price yearly
[135/578] Fetching events for KXCREDITCDEF: Credit card defaults up
[136/578] Fetching events for KXOILW: Price of oil weekly
[137/578] Fetching events for KXNBERRECESSQ: Next recession start
[138/578] Fetching events for KXTRUFHOUCPI: Truflation US CPI Housing Inflation Index
[139/578] Fetching events for KXLARGECUT: Large cuts
[140/578] Fetching events for KXNGDPQ: Quarterly NGDP growth
[141/578] Fetching events for KXMUSKNW: Elon Musk net worth on [date]
[142/578] Fetching events for KXTRUFTSA: Number of Airport Passenger Screened
[143/578] Fetching events for KXAAAGASY: US gas price up
[144/578] Fetching events for KXEZGDPYOYF: Euro Area GDP Growth Rate YoY Flash
[145/578] Fetching events for KXLAYOFFSYPBS: Professional and Business Services layoffs
[146/578] Fetching events for KXIRSCOLLECT: IRS tax collection
[147/578] Fetching events for KXTECHLAYOFF: Tech layoffs up
[148/578] Fetching events for KXUST2: UST2Y
[149/578] Fetching events for KXHPI: Housing Price Index
[150/578] Fetching events for KXCBDECISIONENGLAND: Bank Of ENGLAND policy interest rate decision
[151/578] Fetching events for FEDHIKE: Next Fed rate hike
[152/578] Fetching events for KXCCDELINQ: Credit-card delinquency rate above X% in QX?
[153/578] Fetching events for PROLLS: Jobs numbers
[154/578] Fetching events for KXNYCRENTSY: NYC rent yearly increase
[155/578] Fetching events for KXETHETF: ETH ETF listed
[156/578] Fetching events for KXCALHOME: Calgary home price below X in [year]
[157/578] Fetching events for AAAGASW: US gas price up
[158/578] Fetching events for KXAUTRADEBAL: Australia Balance of Trade
[159/578] Fetching events for KXU3MIN: Unemployment keeps falling
[160/578] Fetching events for TECHLAYOFF: Tech layoffs up
[161/578] Fetching events for KXEGGS: Egg prices
[162/578] Fetching events for CPIYOY: Inflation
[163/578] Fetching events for KXRETAIL: Retail sales growth
[164/578] Fetching events for SPRMAX: SPRMAX
[165/578] Fetching events for KXFRCPIPREL: France Inflation Rate YoY Prel
[166/578] Fetching events for KXCPICN: China inflation
[167/578] Fetching events for KXAIJOBLOSS: Total AI-linked job losses this week
[168/578] Fetching events for RHIKE: Rate hikes
[169/578] Fetching events for FXEURO: Euro/USD exchange rate
[170/578] Fetching events for KXAAAGASMINCA: California lowest gas price yearly
[171/578] Fetching events for U3MIN: Unemployment keeps falling
[172/578] Fetching events for KXOFAC: New Iran OFAC action by [date]
[173/578] Fetching events for KXUSRETAIL: US retail sales MoM
[174/578] Fetching events for KXDIESEL: Diesel price this week
[175/578] Fetching events for FED: Fed funds rate
[176/578] Fetching events for KXCANRECESSION: Canada recession in [year]?
[177/578] Fetching events for FRM: Mortgage 30-yr rate this week
[178/578] Fetching events for KXCPIGAS: CPI on gas
[179/578] Fetching events for CREDEFMAX: Commercial real estate highest default rate
[180/578] Fetching events for AAAGASMINCA: California lowest gas price yearly
[181/578] Fetching events for KXTDEFICITHALF: U.S. BOP
[182/578] Fetching events for KXCBDECISIONAUSTRALIA: Bank Of AUSTRALIA policy interest rate decision
[183/578] Fetching events for KXMLBSTRIKE: MLB STRIKE
[184/578] Fetching events for LAYOFFSY: layoffs
[185/578] Fetching events for KXHIGHINFLATION: Highest Inflation
[186/578] Fetching events for GAS: Gas weekly
[187/578] Fetching events for KXITGDPYOYA: Italy GDP Growth Rate YoY Adv (quarterly)
[188/578] Fetching events for CREDITRATING: US credit rating downgrade
[189/578] Fetching events for KXUKGDPMOM: United Kingdom GDP MoM
[190/578] Fetching events for WEALTHY: Wealthiest person in world
[191/578] Fetching events for KXHOUSINGSTART: Monthly housing starts
[192/578] Fetching events for KXSPRLVL: SPR level on date
[193/578] Fetching events for KXHICP: Euro Area inflation
[194/578] Fetching events for KXHOMEUS: US housing price up monthly
[195/578] Fetching events for PPISEMI: Semiconductor PPI
[196/578] Fetching events for KXCNGDP: China quarterly GDP change in 2021 Q2
[197/578] Fetching events for KXAUWPCC: Australia Westpac Consumer Confidence Change
[198/578] Fetching events for KXTRUFDEAD: Truflation Deadlift Index
[199/578] Fetching events for KXADP: ADP employment change
[200/578] Fetching events for GDPEU: European Union GDP growth
[201/578] Fetching events for KXOILRIGS: Oil rigs
[202/578] Fetching events for KXCANHOME: Will Canada’s national average home price exceed X in [month]?
[203/578] Fetching events for KXBUILDPERMS: Building permits for month
[204/578] Fetching events for KXTRILLIONAIRE: First trillionaire
[205/578] Fetching events for KXCBDECISIONJAPAN: Bank Of Japan policy interest rate decision
[206/578] Fetching events for LCPIMAX: Inflation surge
[207/578] Fetching events for KXAAAGASMINNY: NEW YORK LOWEST gas price yearly
[208/578] Fetching events for KXAKSALMON: Alaska salmon harvest
[209/578] Fetching events for CPICN: China inflation
[210/578] Fetching events for KXPESO: USD/Peso exchange rate
[211/578] Fetching events for KXCREDEFMAX: Commercial real estate highest default rate
[212/578] Fetching events for KXAAAGASW: US gas price up
[213/578] Fetching events for KXJPCONCONF: Japan Consumer Confidence
[214/578] Fetching events for KXCHIMPORTS: China Imports YoY
[215/578] Fetching events for KXUSISMSERV: United States ISM Services PMI
[216/578] Fetching events for KXARINFLATIONM: Argentina inflation
[217/578] Fetching events for KXSEAHOMEVAL: Seattle typical home value for date
[218/578] Fetching events for KXTRADEDEFFICIT: Deficit
[219/578] Fetching events for KXTOPBUSINESS: CNBC TOP STATES FOR BUSINESS
[220/578] Fetching events for AAAGASMAX: US highest gas price yearly
[221/578] Fetching events for KXITCPIPREL: Italy Inflation Rate YoY Prel
[222/578] Fetching events for KXTRUFCPIYE: Truflation U.S. CPI Inflation Index EOY
[223/578] Fetching events for KXINEQUALITY: US inequality
[224/578] Fetching events for CNGDP: China quarterly GDP change in 2021 Q2
[225/578] Fetching events for NGAS: Natural gas price max and min monthly
[226/578] Fetching events for NGASW: Natural gas price max and min weekly
[227/578] Fetching events for KXEDMHOME: Edmonton home price below x in [year]
[228/578] Fetching events for KXBRRATECUT: Number of Brazil rate cuts this year
[229/578] Fetching events for KXTRUFGAS: Truflation US CPI Gasoline Price Index
[230/578] Fetching events for KXFXEURO: Euro/USD exchange rate
[231/578] Fetching events for KXGDPW: Global GDP growth
[232/578] Fetching events for KXBRINFHIGH: How high will Brazil inflation rate get this year?
[233/578] Fetching events for KXCHINAUSGDP: China overtakes US GDP
[234/578] Fetching events for KXZERORATE: Zero rates
[235/578] Fetching events for KXGASMAX: EIA Gas highest price yearly
[236/578] Fetching events for NGASMIN: Natural gas yearly low
[237/578] Fetching events for KXEGGPRICEW: Egg prices weekly
[238/578] Fetching events for CPIUSEDCAR: CPI on used cars
[239/578] Fetching events for RATECUT: Fed rate cut
[240/578] Fetching events for CPIDELAY: CPI data released
[241/578] Fetching events for KXLAYOFFSY: layoffs
[242/578] Fetching events for KXWILDSHT: Which wildlife will appear on the BoE banknote shortlist
[243/578] Fetching events for KXARGINFLATIONM: Argentina inflation
[244/578] Fetching events for KXRATEHIKE: Number of Fed rate hikes
[245/578] Fetching events for WTAX: Wealth tax
[246/578] Fetching events for KXSPRUSE: SPR use
[247/578] Fetching events for KXBRAZILINF: Brazil inflation
[248/578] Fetching events for KXXINDIA: INDIAN ACCOUNTS X
[249/578] Fetching events for KXCHIPYOY: China Industrial Production YoY
[250/578] Fetching events for KXUSEDCARCPI: US used cars and trucks CPI in [month]
[251/578] Fetching events for KXJOBLESS: Initial jobless claims
[252/578] Fetching events for KXMUSKX: Musk Manipulating X
[253/578] Fetching events for KXCREDITRATING: US credit rating downgrade
[254/578] Fetching events for KXLAYOFFSYINFO: Tech layoffs
[255/578] Fetching events for WRECSS: World recessions
[256/578] Fetching events for KXMEDIANRENTLA: MEDIAN RENT LA
[257/578] Fetching events for KXSARETAIL: South Africa retail sales MoM
[258/578] Fetching events for KXQRECESS: Recession start
[259/578] Fetching events for KXWCPI-TR: Turkey inflation
[260/578] Fetching events for KXOIL: Price of oil monthly
[261/578] Fetching events for KXNHSALES: New home sales in time period
[262/578] Fetching events for KXRENTNYCM: Rent price increase in NYC monthly
[263/578] Fetching events for KXTRUFCPI: Truflation US CPI Inflation Index
[264/578] Fetching events for KXCBDECISIONEU: EU CENTRAL BANK POLICY INTEREST RATE
[265/578] Fetching events for KXFM30YMTG: Freddie Mac 30Y mortgage rate below x% in [year]
[266/578] Fetching events for KXMUSKTRILLION27: Musk Trillionaire by 2027
[267/578] Fetching events for EPOP: Employment-population ratio
[268/578] Fetching events for KXRATECUTCOUNT: Number of rate cuts
[269/578] Fetching events for KXFRM: Mortgage 30-yr rate this week
[270/578] Fetching events for KXLCPIYOY: Inflation surge this year
[271/578] Fetching events for KXUSPPIYOY: US PPI YoY in [month]
[272/578] Fetching events for KXTFP: Total factor productivity
[273/578] Fetching events for KXFRMMAX: Mortgage rate high
[274/578] Fetching events for KXUSDTTBILL: USDT reserve share in direct U.S. Treasury Bills above [X]%
[275/578] Fetching events for KXAAAGASMAX: US highest gas price yearly
[276/578] Fetching events for BIGBANKLAYOFF: Big banks layoffs
[277/578] Fetching events for KXBOSHOMEVAL: Boston typical home value for date
[278/578] Fetching events for KXCPIYOYBANK: Inflation
[279/578] Fetching events for KXJOBSRELEASE: When will the BLS release a jobs report?
[280/578] Fetching events for KXHOUSELENGTH: US house average sale length
[281/578] Fetching events for WEALTH: Person wealthiest
[282/578] Fetching events for KXCREDEF: Commercial real estate defaults
[283/578] Fetching events for KXMANHEIMUSEDCAR: Manheim Used Vehicle Value Index
[284/578] Fetching events for KXUSPINCOME: United States Personal Income MoM
[285/578] Fetching events for KXEFFR: Fed Funds (EFFR) above/below
[286/578] Fetching events for KXCREDITC: SOFR spike: Credit crunch
[287/578] Fetching events for KXSOLAR: Solar capcity installation
[288/578] Fetching events for BANKRUPTSY: Companies going bankrupt yearly
[289/578] Fetching events for KXMEDIANRENTMIA: MEDIAN RENT MIAMI
[290/578] Fetching events for KXHOME: New home sales
[291/578] Fetching events for U3MAX: Unemployment spike
[292/578] Fetching events for KXACPI: US annual inflation
[293/578] Fetching events for KXUE: Monthly Unemployment
[294/578] Fetching events for GASD: Gas daily
[295/578] Fetching events for KXBOE: Bank of England bank rate
[296/578] Fetching events for KXFRONTIERAI: FrontierMath
[297/578] Fetching events for COIN: Trillion dollar coin minted
[298/578] Fetching events for KXDEGFK: Germany GfK Consumer Confidence
[299/578] Fetching events for KXECONSTATCPI: month over month inflation
[300/578] Fetching events for KXBRAZILGRAIN: Conab grain estimate?

,category,series_ticker,series_title,series_frequency,series_tags,event_ticker,event_title,event_sub_title,event_strike_date,event_strike_period,...,yes_ask_dollars,no_bid_dollars,no_ask_dollars,last_price_dollars,volume_fp,volume_24h_fp,open_interest_fp,liquidity_dollars,rules_primary,rules_secondary
0,Economics,KXCBDECISIONKOREA,Bank Of KOREA policy interest rate decision,custom,[Global Central Banks],KXCBDECISIONKOREA-26JUL15,Bank of Korea rate decision in July,"Jul 15, 2026 meeting",None,,...,0.0100,0.9900,1.0000,0.0100,2245.04,0.00,2044.99,0.0000,If the Bank of Korea takes the action of Cut m...,The market resolves based on the official poli...
1,Economics,KXCBDECISIONKOREA,Bank Of KOREA policy interest rate decision,custom,[Global Central Banks],KXCBDECISIONKOREA-26JUL15,Bank of Korea rate decision in July,"Jul 15, 2026 meeting",None,,...,0.0500,0.9500,0.9800,0.0400,2393.00,0.00,1522.00,0.0000,If the Bank of Korea takes the action of Cut 1...,The market resolves based on the official poli...
2,Economics,KXCBDECISIONKOREA,Bank Of KOREA policy interest rate decision,custom,[Global Central Banks],KXCBDECISIONKOREA-26JUL15,Bank of Korea rate decision in July,"Jul 15, 2026 meeting",None,,...,0.3100,0.6900,0.7600,0.2800,2914.00,138.00,975.00,0.0000,If the Bank of Korea takes the action of Maint...,The market resolves based on the official poli...
3,Economics,KXCBDECISIONKOREA,Bank Of KOREA policy interest rate decision,custom,[Global Central Banks],KXCBDECISIONKOREA-26JUL15,Bank of Korea rate decision in July,"Jul 15, 2026 meeting",None,,...,0.7100,0.2900,0.3500,0.6500,4023.14,254.00,2175.57,0.0000,If the Bank of Korea takes the action of Hike ...,The market resolves based on the official poli...
4,Economics,KXCBDECISIONKOREA,Bank Of KOREA policy interest rate decision,custom,[Global Central Banks],KXCBDECISIONKOREA-26JUL15,Bank of Korea rate decision in July,"Jul 15, 2026 meeting",None,,...,0.0500,0.9500,0.9900,0.0100,914.05,0.00,862.05,0.0000,If the Bank of Korea takes the action of Hike ...,The market resolves based on the official poli...

In [ ]:
df.head(90)

,category,series_ticker,series_title,series_frequency,series_tags,event_ticker,event_title,event_sub_title,event_strike_date,event_strike_period,...,yes_ask_dollars,no_bid_dollars,no_ask_dollars,last_price_dollars,volume_fp,volume_24h_fp,open_interest_fp,liquidity_dollars,rules_primary,rules_secondary
0,Economics,KXCBDECISIONKOREA,Bank Of KOREA policy interest rate decision,custom,[Global Central Banks],KXCBDECISIONKOREA-26JUL15,Bank of Korea rate decision in July,"Jul 15, 2026 meeting",None,,...,0.0100,0.9900,1.0000,0.0100,2245.04,0.00,2044.99,0.0000,If the Bank of Korea takes the action of Cut m...,The market resolves based on the official poli...
1,Economics,KXCBDECISIONKOREA,Bank Of KOREA policy interest rate decision,custom,[Global Central Banks],KXCBDECISIONKOREA-26JUL15,Bank of Korea rate decision in July,"Jul 15, 2026 meeting",None,,...,0.0500,0.9500,0.9800,0.0400,2393.00,0.00,1522.00,0.0000,If the Bank of Korea takes the action of Cut 1...,The market resolves based on the official poli...
2,Economics,KXCBDECISIONKOREA,Bank Of KOREA policy interest rate decision,custom,[Global Central Banks],KXCBDECISIONKOREA-26JUL15,Bank of Korea rate decision in July,"Jul 15, 2026 meeting",None,,...,0.3100,0.6900,0.7600,0.2800,2914.00,138.00,975.00,0.0000,If the Bank of Korea takes the action of Maint...,The market resolves based on the official poli...
3,Economics,KXCBDECISIONKOREA,Bank Of KOREA policy interest rate decision,custom,[Global Central Banks],KXCBDECISIONKOREA-26JUL15,Bank of Korea rate decision in July,"Jul 15, 2026 meeting",None,,...,0.7100,0.2900,0.3500,0.6500,4023.14,254.00,2175.57,0.0000,If the Bank of Korea takes the action of Hike ...,The market resolves based on the official poli...
4,Economics,KXCBDECISIONKOREA,Bank Of KOREA policy interest rate decision,custom,[Global Central Banks],KXCBDECISIONKOREA-26JUL15,Bank of Korea rate decision in July,"Jul 15, 2026 meeting",None,,...,0.0500,0.9500,0.9900,0.0100,914.05,0.00,862.05,0.0000,If the Bank of Korea takes the action of Hike ...,The market resolves based on the official poli...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Economics,KXECONSTATCORECPIYOY,year over year core inflation,custom,[Inflation],KXECONSTATCORECPIYOY-26JUN,CPI core year-over-year in Jun 2026?,In Jun 2026,None,,...,0.0100,0.9900,1.0000,0.0100,1510.00,0.00,657.00,0.0000,If the CPI core year-over-year is exactly 2.5%...,
86,Economics,KXECONSTATCORECPIYOY,year over year core inflation,custom,[Inflation],KXECONSTATCORECPIYOY-26JUN,CPI core year-over-year in Jun 2026?,In Jun 2026,None,,...,0.0400,0.9600,1.0000,0.0400,1499.00,20.00,944.00,0.0000,If the CPI core year-over-year is exactly 2.6%...,
87,Economics,KXECONSTATCORECPIYOY,year over year core inflation,custom,[Inflation],KXECONSTATCORECPIYOY-26JUN,CPI core year-over-year in Jun 2026?,In Jun 2026,None,,...,0.1100,0.8900,0.9000,0.1700,4279.85,0.00,1709.80,0.0000,If the CPI core year-over-year is exactly 2.7%...,
88,Economics,KXECONSTATCORECPIYOY,year over year core inflation,custom,[Inflation],KXECONSTATCORECPIYOY-26JUN,CPI core year-over-year in Jun 2026?,In Jun 2026,None,,...,0.2500,0.7500,0.7900,0.2100,4813.82,0.00,3292.37,0.0000,If the CPI core year-over-year is exactly 2.8%...,
89,Economics,KXECONSTATCORECPIYOY,year over year core inflation,custom,[Inflation],KXECONSTATCORECPIYOY-26JUN,CPI core year-over-year in Jun 2026?,In Jun 2026,None,,...,0.3200,0.6800,0.6900,0.3400,4021.20,0.00,2562.64,0.0000,If the CPI core year-over-year is exactly 2.9%...,

In [ ]:
df['category']

0        Economics
1        Economics
2        Economics
3        Economics
4        Economics
           ...
14141    Economics
14142    Economics
14143    Economics
14144        World
14145    Economics
Name: category, Length: 14146, dtype: object

In [ ]:
filtered = df[df["series_ticker"].str.contains("KXNJDRONES", na=False)]
filtered

,category,series_ticker,series_title,series_frequency,series_tags,event_ticker,event_title,event_sub_title,event_strike_date,event_strike_period,...,yes_ask_dollars,no_bid_dollars,no_ask_dollars,last_price_dollars,volume_fp,volume_24h_fp,open_interest_fp,liquidity_dollars,rules_primary,rules_secondary
1714,Financials,KXNJDRONES,NJ DRONES,custom,None,KXNJDRONES-25,Will the New Jersey Drone Sightings reoccur in...,In 2025,None,,...,None,None,None,None,None,None,None,None,None,None

In [ ]:
filtered_df = df[df["category"].str.contains("Financials", na=False)]
filtered_df

,category,series_ticker,series_title,series_frequency,series_tags,event_ticker,event_title,event_sub_title,event_strike_date,event_strike_period,...,yes_ask_dollars,no_bid_dollars,no_ask_dollars,last_price_dollars,volume_fp,volume_24h_fp,open_interest_fp,liquidity_dollars,rules_primary,rules_secondary
1714,Financials,KXNJDRONES,NJ DRONES,custom,None,KXNJDRONES-25,Will the New Jersey Drone Sightings reoccur in...,In 2025,None,,...,None,None,None,None,None,None,None,None,None,None
4606,Financials,KXXINDIA,INDIAN ACCOUNTS X,custom,None,KXXINDIA-25,Will a story be published that at least 70% of...,In 2025,None,,...,None,None,None,None,None,None,None,None,None,None
4719,Financials,KXMUSKX,Musk Manipulating X,one_off,None,KXMUSKX-25,Will a report about Musk manipulating X to ben...,In 2025,None,,...,None,None,None,None,None,None,None,None,None,None
5606,Financials,KXCREDITC,SOFR spike: Credit crunch,annual,[Fed],KXCREDITC-25DEC31,Will SOFR spike in 2025?,"By Dec 31, 2025",None,,...,None,None,None,None,None,None,None,None,None,None
5607,Financials,KXCREDITC,SOFR spike: Credit crunch,annual,[Fed],CREDITC-24DEC31,"SOFR spike: Credit crunch by Dec 31, 2024?","By Dec 31, 2024",None,,...,None,None,None,None,None,None,None,None,None,None
5608,Financials,KXCREDITC,SOFR spike: Credit crunch,annual,[Fed],CREDITC-23DEC31,"SOFR spike: Credit crunch, 2023?",2023,None,,...,None,None,None,None,None,None,None,None,None,None
12792,Financials,KXNYSEOPEN,Will NYSE be open?,one_off,None,KXNYSEOPEN-26,Will the New York Stock Exchange be Open for t...,In 2026,None,,...,None,None,None,None,None,None,None,None,None,None
12860,Financials,KXFOMCDISSENTCOUNT,FOMC dissent count,custom,[Fed],KXFOMCDISSENTCOUNT-25DEC,How many dissenting votes at the next Fed meet...,December FOMC meeting,None,,...,None,None,None,None,None,None,None,None,None,None
12861,Financials,KXFOMCDISSENTCOUNT,FOMC dissent count,custom,[Fed],KXFOMCDISSENTCOUNT-25JUL,How many dissenting votes at the next Fed meet...,Before 2025,None,,...,None,None,None,None,None,None,None,None,None,None

In [ ]:
df['category'].value_counts()

category
Economics                 13780
Transportation              197
Science and Technology       76
World                        54
Politics                     29
Financials                    9
Health                        1
Name: count, dtype: int64

In [ ]:
df.to_csv("kalshi_economics_events_markets.csv", index=False)

In [ ]:
import requests
import pandas as pd
import time
from typing import Dict, Any, Optional, List

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

CATEGORY = "Economics"
START_DATE = "2024-01-01"
END_DATE   = "2026-04-14"

# For "closed markets in the time window", close_time is usually the right filter.
# Change to "settlement_ts" if you want settlement date instead.
DATE_FIELD = "close_time"


def kalshi_get(
    path: str,
    params: Optional[Dict[str, Any]] = None,
    max_retries: int = 4,
    sleep_base: float = 1.5,
) -> Dict[str, Any]:
    url = f"{BASE_URL}{path}"
    params = params or {}

    for attempt in range(max_retries):
        try:
            r = requests.get(url, params=params, timeout=30)

            if not r.ok:
                print("Failed URL:", url)
                print("Params:", params)
                print("Status code:", r.status_code)
                print("Response text:", r.text[:1000])

            r.raise_for_status()
            return r.json()

        except requests.exceptions.RequestException:
            if attempt == max_retries - 1:
                raise
            time.sleep(sleep_base * (attempt + 1))


def paginate(path: str, params: Dict[str, Any], result_key: str) -> List[Dict[str, Any]]:
    rows = []
    cursor = None

    while True:
        query = dict(params)
        if cursor:
            query["cursor"] = cursor

        data = kalshi_get(path, query)
        rows.extend(data.get(result_key, []))

        cursor = data.get("cursor")
        if not cursor:
            break

    return rows


def get_historical_cutoff() -> Dict[str, Any]:
    return kalshi_get("/historical/cutoff")


def get_economics_series() -> pd.DataFrame:
    """
    Step 1:
    Get all series_ticker values for the Economics category.
    """
    data = kalshi_get(
        "/series",
        {
            "category": CATEGORY,
            "include_product_metadata": "true",
            "include_volume": "true",
        },
    )

    df = pd.DataFrame(data.get("series", []))

    if df.empty:
        return df

    df = df.rename(columns={
        "ticker": "series_ticker",
        "title": "series_title",
        "frequency": "series_frequency",
        "category": "series_category",
        "product_metadata": "series_product_metadata",
        "volume_fp": "series_volume_fp",
    })

    return df


def get_historical_markets_for_series(series_ticker: str) -> List[Dict[str, Any]]:
    """
    Step 2:
    Get historical markets for a single series_ticker.

    IMPORTANT:
    Do NOT pass mve_filter here.
    /historical/markets treats series_ticker and mve_filter as mutually exclusive.
    """
    params = {
        "series_ticker": series_ticker,
        "limit": 1000,
    }

    return paginate("/historical/markets", params, "markets")


def get_events_for_series(series_ticker: str) -> List[Dict[str, Any]]:
    """
    Step 3:
    Get event metadata. Events remain accessible from /events even when
    their markets are historical.
    """
    params = {
        "series_ticker": series_ticker,
        "limit": 200,
        "with_nested_markets": "false",
    }

    return paginate("/events", params, "events")


def filter_by_date_window(df: pd.DataFrame, date_field: str = DATE_FIELD) -> pd.DataFrame:
    if df.empty:
        return df

    if date_field not in df.columns:
        raise ValueError(
            f"Column {date_field!r} not found. Available columns include: "
            f"{list(df.columns)[:40]}"
        )

    dt = pd.to_datetime(df[date_field], utc=True, errors="coerce")

    start = pd.Timestamp(START_DATE, tz="UTC")
    end = pd.Timestamp(END_DATE, tz="UTC") + pd.Timedelta(days=1) - pd.Timedelta(seconds=1)

    return df[(dt >= start) & (dt <= end)].copy()


def build_economics_closed_historical_df():
    cutoff = get_historical_cutoff()
    market_cutoff = pd.to_datetime(cutoff["market_settled_ts"], utc=True)

    print("Kalshi historical cutoff:")
    print("  market_settled_ts:", market_cutoff)
    print()
    print(f"Target category: {CATEGORY}")
    print(f"Target window: {START_DATE} through {END_DATE}")
    print(f"Date field used for filtering: {DATE_FIELD}")
    print()

    series_df = get_economics_series()

    if series_df.empty:
        raise RuntimeError("No Economics series found.")

    print(f"Found {len(series_df)} Economics series.")
    print("Example series tickers:")
    print(series_df["series_ticker"].head(20).to_list())
    print()

    market_dfs = []
    event_rows = []
    failed_series = []

    for i, row in series_df.iterrows():
        series_ticker = row["series_ticker"]
        series_title = row.get("series_title", "")

        print(f"[{i + 1}/{len(series_df)}] {series_ticker} — {series_title}")

        try:
            markets = get_historical_markets_for_series(series_ticker)

            if markets:
                mdf = pd.json_normalize(markets)
                mdf["series_ticker"] = series_ticker
                mdf["data_source"] = "historical"
                market_dfs.append(mdf)

            events = get_events_for_series(series_ticker)

            for event in events:
                event["series_ticker"] = series_ticker

            event_rows.extend(events)

        except requests.exceptions.HTTPError as e:
            failed_series.append({
                "series_ticker": series_ticker,
                "series_title": series_title,
                "error": str(e),
            })
            print(f"  Skipped because of error: {e}")

        time.sleep(0.1)

    failed_df = pd.DataFrame(failed_series)

    if not market_dfs:
        return pd.DataFrame(), series_df, failed_df

    markets_df = pd.concat(market_dfs, ignore_index=True)

    # Historical endpoint may include more than your requested window,
    # so filter locally.
    markets_df = filter_by_date_window(markets_df, DATE_FIELD)

    if markets_df.empty:
        return markets_df, series_df, failed_df

    # Keep closed/settled markets only if the status field exists.
    if "status" in markets_df.columns:
        markets_df = markets_df[
            markets_df["status"].isin(["closed", "settled"])
        ].copy()

    # Deduplicate by market ticker.
    if "ticker" in markets_df.columns:
        markets_df = markets_df.drop_duplicates("ticker", keep="first")

    # Join series metadata.
    series_keep_cols = [
        c for c in [
            "series_ticker",
            "series_title",
            "series_frequency",
            "series_category",
            "tags",
            "series_product_metadata",
            "series_volume_fp",
        ]
        if c in series_df.columns
    ]

    markets_df = markets_df.merge(
        series_df[series_keep_cols],
        on="series_ticker",
        how="left",
    )

    # Join event metadata.
    events_df = pd.json_normalize(event_rows) if event_rows else pd.DataFrame()

    if not events_df.empty and "event_ticker" in events_df.columns:
        event_keep_cols = [
            c for c in [
                "event_ticker",
                "title",
                "sub_title",
                "category",
                "strike_date",
                "strike_period",
                "product_metadata",
                "last_updated_ts",
            ]
            if c in events_df.columns
        ]

        event_meta = events_df[event_keep_cols].drop_duplicates("event_ticker")

        markets_df = markets_df.merge(
            event_meta,
            on="event_ticker",
            how="left",
            suffixes=("_market", "_event"),
        )

    # Friendly column names.
    markets_df = markets_df.rename(columns={
        "ticker": "market_ticker",
        "title_market": "market_question",
        "title": "market_question",
        "subtitle": "market_subtitle",
        "title_event": "event_title",
        "sub_title": "event_sub_title",
        "category": "event_category",
    })

    markets_df["requested_category"] = CATEGORY
    markets_df["requested_start_date"] = START_DATE
    markets_df["requested_end_date"] = END_DATE
    markets_df["historical_cutoff_market_settled_ts"] = market_cutoff

    # Useful columns first.
    first_cols = [
        "requested_category",
        "data_source",
        "series_ticker",
        "series_title",
        "series_frequency",
        "series_category",
        "event_ticker",
        "event_title",
        "event_sub_title",
        "market_ticker",
        "market_question",
        "market_subtitle",
        "yes_sub_title",
        "no_sub_title",
        "status",
        "open_time",
        "close_time",
        "expiration_time",
        "expected_expiration_time",
        "settlement_ts",
        "settlement_value_dollars",
        "last_price_dollars",
        "yes_bid_dollars",
        "yes_ask_dollars",
        "no_bid_dollars",
        "no_ask_dollars",
        "volume_fp",
        "volume_24h_fp",
        "open_interest_fp",
        "liquidity_dollars",
        "rules_primary",
        "rules_secondary",
        "requested_start_date",
        "requested_end_date",
        "historical_cutoff_market_settled_ts",
    ]

    first_cols = [c for c in first_cols if c in markets_df.columns]
    other_cols = [c for c in markets_df.columns if c not in first_cols]

    markets_df = markets_df[first_cols + other_cols].reset_index(drop=True)

    # Unique series tickers that actually had markets in the requested window.
    series_tickers_df = (
        markets_df[[
            "series_ticker",
            "series_title",
            "series_frequency",
            "series_category",
        ]]
        .drop_duplicates()
        .sort_values("series_ticker")
        .reset_index(drop=True)
    )

    return markets_df, series_tickers_df, failed_df


df_markets, df_series_tickers, df_failed_series = build_economics_closed_historical_df()

print()
print("Final output")
print("Rows / markets:", len(df_markets))

if not df_markets.empty:
    print("Unique series_tickers:", df_markets["series_ticker"].nunique())
    print("Unique event_tickers:", df_markets["event_ticker"].nunique())
    print("Unique market_tickers:", df_markets["market_ticker"].nunique())

print("Failed series:", len(df_failed_series))

df_markets.head()

Kalshi historical cutoff:
  market_settled_ts: 2026-04-16 00:00:00+00:00

Target category: Economics
Target window: 2024-01-01 through 2026-04-14
Date field used for filtering: close_time

Found 578 Economics series.
Example series tickers:
['KXUTILITYSOCAL', 'KXNDEBTSHRINK', 'KXAAAGASMAXNY', 'LCPIYOY', 'KXHELIUMIMP', 'KXNFPDELAY', 'KXACPICORE', 'KXCREDITRATING', 'KXAUNABCONF', 'NGDPQ', 'KXPSAVERT', 'KXCPIUSEDCAR', 'KXSPRMAX', 'PESO', 'KXFEDMEET', 'KXGDPUSMAX', 'KXDEBTGROWTH26', 'KXLCPIYOY', 'KXTRUFTSA', 'KXGDPYEAR']

[1/578] KXUTILITYSOCAL — SoCal electricity prices
[2/578] KXNDEBTSHRINK — national debt shrinking
[3/578] KXAAAGASMAXNY — NEW YORK highest gas price yearly
[4/578] LCPIYOY — Inflation surge this year
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'LCPIYOY', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[5/578] KXHELIUMIMP — US helium imports
[6/578] KXNFPDELAY — Jobs data released
[7/578] KXACPICORE — Annual core inflation
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'KXACPICORE', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[8/578] KXCREDITRATING — US credit rating downgrade
[9/578] KXAUNABCONF — Australia NAB Business Confidence
[10/578] NGDPQ — Quarterly NGDP growth
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'NGDPQ', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[11/578] KXPSAVERT — US personal saving rate below x% in [year]?
[12/578] KXCPIUSEDCAR — CPI on used cars
[13/578] KXSPRMAX — SPRMAX
[14/578] PESO — USD/Peso exchange rate
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'PESO', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[15/578] KXFEDMEET — Fed emergency meeting
[16/578] KXGDPUSMAX — US GDP peak
[17/578] KXDEBTGROWTH26 — U.S. debt growth in 2026
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXDEBTGROWTH26', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[18/578] KXLCPIYOY — Inflation surge this year
[19/578] KXTRUFTSA — Number of Airport Passenger Screened
[20/578] KXGDPYEAR — Annual GDP
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'KXGDPYEAR', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[21/578] KXCNIMPORT — US imports of goods from China
[22/578] KXFEDDECISION — Fed meeting
[23/578] KXFTAPER — Fed tapering
[24/578] GDPW — Global GDP growth
[25/578] HOMEUSY — US housing prices up
[26/578] KXRUBLE — Price of Ruble
[27/578] RENTNYCM — Rent price increase in NYC monthly
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'RENTNYCM', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[28/578] NYCRENTSM — NYC rent monthly increase
[29/578] KXFAOFPI — FAO Food Price Index in [month]?
[30/578] KXDEBTGROWTH25 — U.S. debt growth IN 2025
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXDEBTGROWTH25', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[31/578] KXGDPCN — China GDP growth
[32/578] KXUKGDPMOM — United Kingdom GDP MoM
[33/578] KXRATECUTCOUNT — Number of rate cuts
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'KXRATECUTCOUNT', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[34/578] KXCREDEF — Commercial real estate defaults
[35/578] KX3MTBILL — Treasury 3-month yield above/below
[36/578] HOUSELENGTH — US house average sale length
[37/578] KXHOUSESTART — US housing starts rise
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXHOUSESTART', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[38/578] SEMIPRODH — US Semiconductor production
[39/578] KXCHEXPORTS — China Exports YoY
[40/578] KXAAMMCAPEX — Amazon, Alphabet, Microsoft, and Meta combined capital expenditures for year
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'KXAAMMCAPEX', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[41/578] KXAAAGASMINNY — NEW YORK LOWEST gas price yearly
[42/578] KXGDPW — Global GDP growth
[43/578] KXCCCHGOFF — Credit-card charge-off rate above X% in QX?
[44/578] KXU3MAX — Unemployment spike
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXU3MAX', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[45/578] KXBOSHOMEVAL — Boston typical home value for date
[46/578] KXPOWERKWH — Average US electricity price this month
[47/578] KXRUCRUDEX — Russia crude exports in [month] below x.x mbpd?
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXRUCRUDEX', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[48/578] KXCHRETAIL — China Retail Sales YoY
[49/578] PROLLS — Jobs numbers
[50/578] KXPESO — USD/Peso exchange rate
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXPESO', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[51/578] FEDRATEMIN — How low will the Fed rate go
[52/578] KXSPRMIN — SPRMIN
[53/578] KXNGASMAX — Natural gas price peak
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXNGASMAX', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[54/578] BOE — Bank of England bank rate
[55/578] KXESGDPQOQF — Spain GDP Growth Rate QoQ Flash (quarterly)
[56/578] CHINAUSGDP — China overtakes US GDP
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'CHINAUSGDP', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[57/578] KXUSPPI — United States PPI MoM
[58/578] LCPIMAXYOY — Inflation surge this year
[59/578] RATECUTS — Number of rate cuts
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'RATECUTS', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[60/578] KXNFPROD — US nonfarm productivity exceeds X% YoY in any quarter reported during [year]
[61/578] GASMIN — EIA Gas lowest price yearly
[62/578] KXMANUCON — U.S. manufacturing construction spending
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXMANUCON', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[63/578] KXPCECORE — US Core PCE inflation
[64/578] KXWCPI-TR — Turkey inflation
[65/578] DIESEL — Diesel price this week
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'DIESEL', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[66/578] KXBANKRUPTCY — Bankruptcy
[67/578] KXDEGFK — Germany GfK Consumer Confidence
[68/578] WCPI-TR — Turkey inflation
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'WCPI-TR', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[69/578] HOUSESTART — US housing starts rise
[70/578] KXCPI — CPI
[71/578] KXVANCONDO — Will the average Vancouver condo price fall below X by year-end?
[72/578] KXJPMOMINF — Japan inflation MoM in [month]
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'KXJPMOMINF', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[73/578] KXARGINFLATIONM — Argentina inflation
[74/578] NYCRENTSY — NYC rent yearly increase
[75/578] RUBLE — Price of Ruble
[76/578] KXXINDIA — INDIAN ACCOUNTS X
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXXINDIA', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[77/578] KXCPIDELAY — CPI data released
[78/578] KXSKEXPYOY — South Korea exports YoY
[79/578] KXCBDECISIONINDIA — Bank of India policy interest rate decision
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXCBDECISIONINDIA', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[80/578] KXMUSKWEALTH — Musk wealth
[81/578] KXJOBLESS — Initial jobless claims
[82/578] LCPIMIN — High inflation ends
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'LCPIMIN', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[83/578] KXINEQUALITY — US inequality
[84/578] KXCANCUTS — Number of BoC rate cuts in [year]?
[85/578] KXDEFGDP — U.S. federal deficit-to-GDP above/below X% in year
[86/578] KXUSIPMOM — US industrial production MoM
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXUSIPMOM', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[87/578] KXEFFTARIFF — What will the US effective tariff rate be?
[88/578] KXSPRUSE — SPR use
[89/578] KXJOBLESSCLAIMS — Weekly initial jobless claims
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXJOBLESSCLAIMS', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[90/578] KXTRUFBPPI — Truflation Bitcoin Purchasing Power Index
[91/578] KXNURSESTRIKE — When will the NYC nurse strike end?
[92/578] OIL — Price of oil monthly
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'OIL', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[93/578] KXSATRADEBAL — South Africa balance of trade for [month]
[94/578] KXTSLAYOFF — Will Tesla announce layoffs by [date]?
[95/578] KXMIAHOMEVAL — Miami typical home value for date
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'KXMIAHOMEVAL', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[96/578] KXTERMINALRATE — Fed funds highest rate
[97/578] KXHOUHOMEVAL — Houston typical home value for date
[98/578] AAAGASMAX — US highest gas price yearly
[99/578] KXZERORATE — Zero rates
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXZERORATE', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[100/578] KXTRADEDEFICIT — Trade Deficit by Date
[101/578] KXMLBSTRIKE — MLB STRIKE
[102/578] FEDMEET — Fed emergency meeting
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'FEDMEET', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[103/578] KXEZDEPRATE — Euro Area Deposit Facility Rate (varied dates)
[104/578] KXNGASMIN — Natural gas yearly low
[105/578] KXUKRETAIL — UK retail sales MoM
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXUKRETAIL', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[106/578] KXMEDIANRENTCHI — MEDIAN RENT CHICAGO
[107/578] KXGDPUSMIN — Negative US GDP growth
[108/578] FRM — Mortgage 30-yr rate this week
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'FRM', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[109/578] KXTRUMPTRADEGAP — Will Trump close the China trade gap?
[110/578] RATECUT — Fed rate cut
[111/578] KXMORTGAGERATE — Mortgage Rate
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'KXMORTGAGERATE', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[112/578] KXHICP — Euro Area inflation
[113/578] KXUSNFP — US nonfarm payrolls in [month]
[114/578] RENTNYCY — Rent price increase in NYC yearly
[115/578] KXREALWAGES — Real wage growth
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXREALWAGES', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[116/578] KXUSGASCPI — US gasoline CPI in [month]
[117/578] PCECORE — US Core PCE inflation
[118/578] GDPCN — China GDP growth
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'GDPCN', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[119/578] CPIDELAY — CPI data released
[120/578] KXHPI — Housing Price Index
[121/578] KXEFFR — Fed Funds (EFFR) above/below
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXEFFR', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[122/578] KXAILABDIS — AI disrupt labor market
[123/578] KXAAAGASW — US gas price up
[124/578] KXFRMMAX — Mortgage rate high
[125/578] KXAAAGASMAX — US highest gas price yearly
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXAAAGASMAX', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[126/578] CPIFOOD — CPI on food
[127/578] USEDCAR — US CPI print on used cars
[128/578] PPISEMI — Semiconductor PPI
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'PPISEMI', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[129/578] KXCREDITCDEF — Credit card defaults up
[130/578] RECSSNBER — Recession
[131/578] KXMSTRSELL — Will MicroStrategy sell any Bitcoin before date
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXMSTRSELL', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[132/578] KXFEDCHGCOUNT — Number of rate changes
[133/578] KXJPTRADEBAL — Japan Balance of Trade
[134/578] KXITCPIPREL — Italy Inflation Rate YoY Prel
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXITCPIPREL', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[135/578] KXUST5 — UST5
[136/578] ACPI — US annual inflation
[137/578] KXSAMOMINF — South Africa MoM inflation
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXSAMOMINF', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[138/578] KXFOMCDISSENTCOUNT — FOMC dissent count
[139/578] KXAMERICAPROFIT — America profit
[140/578] KXCREDEFMAX — Commercial real estate highest default rate
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'KXCREDEFMAX', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[141/578] KXAAAGASY — US gas price up
[142/578] KXNYCRENTSY — NYC rent yearly increase
[143/578] KXMUSKTRILLION27 — Musk Trillionaire by 2027
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'KXMUSKTRILLION27', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[144/578] DIESELM — Diesel price this month
[145/578] KXBOJDECISION — BOJ decision
[146/578] KXFEAR — Fear and Greed index
[147/578] KXDEGDPQOQF — Germany GDP Growth Rate QoQ Flash (quarterly)
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXDEGDPQOQF', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[148/578] KXCPIAR — Argentina inflation
[149/578] KXWRECSS — World recessions
[150/578] KXDEFAULT — US defaults
Failed URL: https://external-api.kalshi.com/trade-api/v2/events
Params: {'series_ticker': 'KXDEFAULT', 'limit': 200, 'with_nested_markets': 'false'}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[151/578] KXYOUTHUN — Youth unemployment below X% in [year]?
[152/578] KXUSPPIYOY — US PPI YoY in [month]
[153/578] WEALTHY — Wealthiest person in world
[154/578] KXUSEDCARCPI — US used cars and trucks CPI in [month]
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXUSEDCARCPI', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[155/578] U3MAX — Unemployment spike
[156/578] KXWCPI-RU — Russian inflation
[157/578] KXMUSKNW — Elon Musk net worth on [date]
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXMUSKNW', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[158/578] EPOP — Employment-population ratio
[159/578] KXAAAGASMINTX — Texas lowest gas price yearly
[160/578] KXEGGPRICEM — Egg prices monthly
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'KXEGGPRICEM', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[161/578] KXBRAZILINF — Brazil inflation
[162/578] KXNYCCBDENTRY — NYC CBD Vehicle Entries
[163/578] AAAGASM — US gas price
Failed URL: https://external-api.kalshi.com/trade-api/v2/historical/markets
Params: {'series_ticker': 'AAAGASM', 'limit': 1000}
Status code: 429
Response text: {"error":{"code":"too_many_requests","message":"too many requests"}}
[164/578] KXSFHOMEVAL — San Francisco typical home value on date

Empty DataFrame
Columns: [requested_category, data_source, series_ticker, series_title, series_frequency, series_category, event_ticker, event_title, event_sub_title, market_ticker, market_question, market_subtitle, yes_sub_title, no_sub_title, status, open_time, close_time, expiration_time, expected_expiration_time, settlement_ts, settlement_value_dollars, last_price_dollars, yes_bid_dollars, yes_ask_dollars, no_bid_dollars, no_ask_dollars, volume_fp, volume_24h_fp, open_interest_fp, liquidity_dollars, rules_primary, rules_secondary, requested_start_date, requested_end_date, historical_cutoff_market_settled_ts, can_close_early, created_time, early_close_condition, expiration_value, fractional_trading_enabled, latest_expiration_time, market_type, notional_value_dollars, previous_price_dollars, previous_yes_ask_dollars, previous_yes_bid_dollars, price_level_structure, price_ranges, response_price_units, result, settlement_timer_seconds, updated_time, yes_ask_size_fp, yes_bid_size_fp, floor_strike, strike_type, fee_waiver_expiration_time, cap_strike, custom_strike.Hike, custom_strike.Cut, occurrence_datetime, custom_strike.No change, custom_strike.Value, custom_strike.Country, custom_strike.Action, custom_strike.Inflation, custom_strike.Unemployment, custom_strike.Date, custom_strike.Expo_Date, custom_strike.Interest Rate, custom_strike.Count, tags, series_product_metadata, series_volume_fp, event_category, strike_date, strike_period, last_updated_ts]
Index: []

[0 rows x 78 columns]

**16 June 2026 Work**

***Historical Cutoff***

A closed market means trading has ended -- People can no longer buy or sell contracts in that market.

A settled market means the final result has been resolved.

There can be a short period where a market is closed but not yet settled.

Kalshi moves older ***settled*** markets into the historical endpoint.

For series and events data - no historical endpoint in API needed



**Kalshi Hierarchy**

Category: X

Series:
KXCPI

Event:
CPI report for March 2025

Markets:


*   Will CPI be above 2.5%?
*   Will CPI be above 3.0%?



Orders:
Buy YES at 40 cents
Sell YES at 45 cents

Trades:
YES traded at 42 cents
YES traded at 43 cents

***Nested markets***

        
            "events":

            "event_ticker": "KXCPI-25MAR",
            "series_ticker": "KXCPI",
            "title": "CPI inflation for March 2025",
            "markets":
                {
                    "ticker": "KXCPI-25MAR-B2.5",
                    "title": "Will CPI be above 2.5%?",
                    "status": "settled",
                    "open_time": "2025-03-01T00:00:00Z",
                    "close_time": "2025-03-12T13:30:00Z"
                },
                {
                    "ticker": "KXCPI-25MAR-B3.0",
                    "title": "Will CPI be above 3.0%?",
                    "status": "settled",
                    "open_time": "2025-03-01T00:00:00Z",
                    "close_time": "2025-03-12T13:30:00Z"
                }

Kalshi’s historical cutoff for markets is based on settlement time, not close time. Kalshi’s docs define market_settled_ts as the cutoff: markets that settled before that timestamp must be accessed through /historical/markets; markets that settled after that cutoff should be available through /markets.

The warning is that this nested markets list is not guaranteed to include old historical markets. Kalshi says that historical markets settled before the historical cutoff are not included when using with_nested_markets=true on /events.


event: KXCPI-24JAN

It may have had 10 markets. But if those markets settled before Kalshi’s historical cutoff, then this request:

GET /events?series_ticker=KXCPI&with_nested_markets=true

might return the event, but with zero markets or only some newer market


If the market settled after the historical cutoff, then it should still be available through the normal live/recent endpoint:

GET /markets

Market settled before cutoff  → /historical/markets

Market settled after cutoff   → /markets

A closed market means trading has ended.

People can no longer buy or sell contracts.

A settled market means the final result has been resolved.

Kalshi knows whether YES or NO won, and payouts can happen.

Category
  → Series
      → Event
          → Market
              → Orders
              → Trades

Category: X / Economics

Series (a series is a recurring family of related events): KXCPI

Event (an event is one specific occurrence inside a series): CPI report for March 2025

Markets (one specific tradable question inside an event):
  - Will CPI be above 2.5%?
  - Will CPI be above 3.0%?

Orders (An order is someone trying to buy or sell):
  - Buy YES at 40 cents
  - Sell YES at 45 cents

Trades (A trade is when an order actually matches and executes):
  - YES traded at 42 cents
  - YES traded at 43 cents

Nested markets means that Kalshi includes the market objects directly inside each event response. Normally, when you call /events?series_ticker=KXCPI, Kalshi returns event-level information, such as the event_ticker, series_ticker, and event title.

{
  "event_ticker": "KXCPI-25MAR",

  "series_ticker": "KXCPI",

  "title": "CPI inflation for March 2025"
}



If you add with_nested_markets=true, like /events?series_ticker=KXCPI&with_nested_markets=true, each event can also include a markets field containing the markets that belong to that event.


If you add with_nested_markets=true, Kalshi also includes the markets inside each event.

Example:

GET /events?series_ticker=KXCPI&with_nested_markets=true

Then the event response may include a markets field:

{
  "event_ticker": "KXCPI-25MAR",

  "title": "CPI inflation for March 2025",

  "markets":
    
      "ticker": "KXCPI-25MAR-B2.5",

      "title": "Will CPI be above 2.5%?"
    
    
      "ticker": "KXCPI-25MAR-B3.0",

      "title": "Will CPI be above 3.0%?"
    
  
}


Important warning: with_nested_markets=true does not include historical markets that settled before Kalshi’s historical cutoff. Those older settled markets have moved to:

GET /historical/markets

Therefore, /events?with_nested_markets=true may return an event but still miss some older markets. To reliably find all markets for a series across a historical date range, use both:

GET /markets
GET /historical/markets

Orders are requests to buy or sell contracts. For example, someone might place an order saying: “I want to buy 10 YES contracts at 40 cents” or “I want to sell 5 YES contracts at 45 cents.” An order is just an offer or instruction. It may sit there waiting, get canceled, or eventually get matched.

Trades are completed transactions. A trade happens when a buy order and a sell order match at a price. For example, if one person wants to buy YES at 42 cents and another person is willing to sell YES at 42 cents, the orders match and a trade occurs. Kalshi describes a trade as a completed transaction between two users on a specific market, including the market ticker, price, quantity, and timestamp.


Order = someone wants to buy or sell
Trade = the buy/sell actually happened

Kalshi operates like an order book exchange, not like a store with a fixed pile of contracts already sitting there.

Kalshi creates the market question, for example:

Will CPI be above 3.0%?

Then traders create the available offers by placing orders. An order might be:

I want to buy YES at 40 cents.
I want to sell YES at 45 cents.

Those orders sit in the order book until someone accepts them or places a matching order. Kalshi’s order book shows active bid orders for YES and NO sides. Because Kalshi markets are binary, a YES bid at one price is economically related to a NO offer at the opposite price. For example, Kalshi notes that a YES bid at 7 cents is equivalent to a NO ask at 93 cents.

So there usually is not an initial fixed amount of offers created by Kalshi. Instead, liquidity comes from users and market makers placing orders.

Buying a side = you want that side to win.

Selling a side = you want that side to lose.

Buy YES and sell NO both mean you are leaning YES.

Buy NO and sell YES both mean you are leaning NO.

_______________________________________________________________

Will CPI be above 3.0%?

There are two outcomes:

YES = CPI is above 3.0%

NO = CPI is not above 3.0%

________________________________

Buying YES = betting YES happens.

You make money if the answer is YES.

Example: you buy YES because you think CPI will be above 3.0%.
You buy 1 YES contract for $0.40.

__

Winning case:

CPI is above 3.0%.
YES wins.
Your YES contract pays $1.
$1.00 - $0.40 = $0.60 profit

Losing case:

CPI is not above 3.0%.
NO wins.
Your YES contract pays $0.
loss is $0.40

_______________________________________________________________


Selling YES = betting YES does not happen.

You make money if the answer is NO.

Example: you sell YES because you think CPI will not be above 3.0%.

_______________________________________________________________


Buying NO = betting NO happens.

You make money if the answer is NO.

Example: you buy NO because you think CPI will not be above 3.0%.

_______________________________________________________________


Selling NO = betting NO does not happen.

You make money if the answer is YES.

Example: you sell NO because you think CPI will be above 3.0%.

why both sell and buy exist: So why choose one over the other? Because one side may have a better available price or more liquidity. Maybe there is someone willing to sell YES at 0.42 dollars but someone else willing to buy NO at 0.61 dollars. You would choose the better deal.

# Cutoff

In [ ]:
import requests
import pandas as pd

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

resp = requests.get(f"{BASE_URL}/historical/cutoff")
resp.raise_for_status()

cutoff = resp.json()
cutoff

{'market_settled_ts': '2026-04-24T00:00:00Z',
 'orders_updated_ts': '2026-04-24T00:00:00Z',
 'trades_created_ts': '2026-04-24T00:00:00Z'}

PLAN:

If you want all markets/events for a series_ticker in a date range, do not rely only on nested markets.

Use this safer process:

1. Query /markets for live/recent markets
2. Query /historical/markets for older settled markets
3. Combine them
4. Deduplicate by market ticker
5. Filter by open_time and close_time
6. Extract event_ticker values
7. Optionally fetch event details from /events

In one sentence:

Use /events to describe events, but use /markets plus /historical/markets to reliably find all markets across your time period.

So when you get series from:

GET /series?category=Economics

you are getting Economics series definitions, not necessarily live tradable markets.

A series may be:

currently active with open markets

still listed but no open markets right now

old/inactive

recurring over time

one-off (happens once) or limited (repeats only during a specific period)

# Live Markets Code -  takes too much time to run

In [ ]:
import time
import requests
import pandas as pd
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-live-markets-colab/1.0"
})


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        if 500 <= resp.status_code < 600:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Server error {resp.status_code}. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        resp.raise_for_status()
        return resp.json()

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def paginate(path, collection_key, params=None, limit=1000, sleep_s=0.25):
    params = dict(params or {})
    params["limit"] = limit

    rows = []
    cursor = None

    while True:
        if cursor:
            params["cursor"] = cursor
        else:
            params.pop("cursor", None)

        data = get_json(path, params=params)
        rows.extend(data.get(collection_key, []))

        cursor = data.get("cursor")
        if not cursor:
            break

        time.sleep(sleep_s)

    return rows


# 1. Get all currently open/live markets
live_markets = paginate(
    "/markets",
    "markets",
    params={
        "status": "open"
    },
    limit=1000
)

df_live_markets = pd.DataFrame(live_markets)

print("Number of live/open markets:", len(df_live_markets))
display(df_live_markets.head())
print(df_live_markets.columns.tolist())

KeyboardInterrupt:

# Economics Series Only

1. Get Economics series.
2. Get events for each Economics series.
3. For each event, get historical markets.
4. Extract the market tickers.

In [ ]:
import time
import requests
import pandas as pd
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-economics-series-colab/1.0"
})


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        resp.raise_for_status()
        return resp.json()

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def paginate(path, collection_key, params=None, limit=1000, sleep_s=0.25):
    params = dict(params or {})
    params["limit"] = limit

    rows = []
    cursor = None

    while True:
        if cursor:
            params["cursor"] = cursor
        else:
            params.pop("cursor", None)

        data = get_json(path, params=params)
        rows.extend(data.get(collection_key, []))

        cursor = data.get("cursor")
        if not cursor:
            break

        time.sleep(sleep_s)

    return rows

In [ ]:
economics_series = paginate(
    "/series",
    "series",
    params={
        "category": "Economics"
    },
    limit=1000
)

df_economics_series = pd.DataFrame(economics_series)

print("Economics series found:", len(df_economics_series))
display(df_economics_series.head())
print(df_economics_series.columns.tolist())

Economics series found: 590

,additional_prohibitions,category,contract_terms_url,contract_url,fee_multiplier,fee_type,frequency,last_updated_ts,settlement_sources,tags,ticker,title
0,[Persons who are employed by any of the Source...,Economics,https://kalshi-public-docs.s3.amazonaws.com/co...,https://kalshi-public-docs.s3.us-east-1.amazon...,1,quadratic,monthly,2026-02-26T08:50:31.901806Z,"[{'name': 'Eurostat', 'url': 'https://ec.europ...",None,KXHICP,Euro Area inflation
1,[Persons who are employed by any of the Source...,Economics,https://kalshi-public-docs.s3.amazonaws.com/co...,https://kalshi-public-docs.s3.us-east-1.amazon...,1,quadratic,annual,2026-02-26T08:50:31.901806Z,"[{'name': 'Bureau of Economic Analysis', 'url'...",[Growth],GDPUSMAX,US GDP peak
2,[Persons who are employed by any of the Source...,Economics,https://kalshi-public-docs.s3.amazonaws.com/co...,https://kalshi-public-docs.s3.us-east-1.amazon...,1,quadratic,one_off,2026-02-26T08:50:31.901806Z,"[{'name': 'Bureau of Labor Statistics', 'url':...",[Inflation],KXCPIYOYBANK,Inflation
3,[Persons who are employed by any of the Source...,Economics,https://kalshi-public-docs.s3.amazonaws.com/co...,https://kalshi-public-docs.s3.us-east-1.amazon...,1,quadratic,custom,2026-06-21T19:10:34.801666Z,[{'name': 'Bureau of Labor Statistics- Employm...,[Growth],KXTRADEDEFICIT,Trade Deficit by Date
4,[Persons who are employed by any of the Source...,Economics,https://kalshi-public-docs.s3.amazonaws.com/co...,https://kalshi-public-docs.s3.us-east-1.amazon...,1,quadratic,monthly,2026-02-26T08:50:31.901806Z,"[{'name': 'Bureau of Labor Statistics', 'url':...",[Inflation],CPIAPPAREL,CPI on apparel

['additional_prohibitions', 'category', 'contract_terms_url', 'contract_url', 'fee_multiplier', 'fee_type', 'frequency', 'last_updated_ts', 'settlement_sources', 'tags', 'ticker', 'title']

In [ ]:
import numpy as np
arr = df_economics_series.ticker.values
print(type(df_economics_series.ticker.values))

<class 'numpy.ndarray'>

In [ ]:
values, counts = np.unique(arr, return_counts=True)
print("Unique values:", values)  # [1 2 3 4]
print("Occurrences:", counts)
print(len(counts))

Unique values: ['AAAGASD' 'AAAGASM' 'AAAGASMAX' 'AAAGASMAXCA' 'AAAGASMAXTX' 'AAAGASMIN'
 'AAAGASMINCA' 'AAAGASMINTX' 'AAAGASW' 'AAAGASY' 'ACPI' 'ACPICORE'
 'ACPICORE-' 'ARGINFLATIONM' 'ARINFLATIONM' 'BANKRUPTS' 'BANKRUPTSY'
 'BIGBANKLAYOFF' 'BIGTECHLAYOFF' 'BOE' 'CHINAUSGDP' 'CNGDP' 'CNY' 'COIN'
 'COSTCOHOTDOG' 'COSTCOMEMBER' 'CPI' 'CPIAPPAREL' 'CPIAR' 'CPICN'
 'CPICORE' 'CPICOREYOY' 'CPIDELAY' 'CPIEU' 'CPIFOOD' 'CPIGAS' 'CPISHELTER'
 'CPIUSEDCAR' 'CPIYOY' 'CREDEF' 'CREDEFMAX' 'CREDEFMINMAX' 'CREDITCDEF'
 'CREDITRATING' 'DIESEL' 'DIESELM' 'DOTPLOT' 'ECB' 'ECONPATH' 'EPOP'
 'ETHETF' 'FED' 'FEDDECISION' 'FEDFACILITY' 'FEDHIKE' 'FEDMEET'
 'FEDRATEMIN' 'FRM' 'FRMMAX' 'FRMMIN' 'FTAPER' 'FXEURO' 'FXPESO' 'GAS'
 'GAS-MONTH' 'GASD' 'GASMAX' 'GASMIN' 'GDP' 'GDPCN' 'GDPEU' 'GDPUSMAX'
 'GDPUSMIN' 'GDPW' 'HOME' 'HOMEUS' 'HOMEUSY' 'HOUSELENGTH' 'HOUSESTART'
 'HPI' 'JOBLESS' 'JPY' 'KX25U3SEP' 'KX2YFOMC' 'KX30YUSTW' 'KX3MTBILL'
 'KXAAAGASD' 'KXAAAGASED' 'KXAAAGASM' 'KXAAAGASMAX' 'KXAAAGASMAXCA'
 'KXAAAGASMAXFL' 'KXAAAGASMAXNY' 'KXAAAGASMAXTX' 'KXAAAGASMIN'
 'KXAAAGASMINCA' 'KXAAAGASMINFL' 'KXAAAGASMINNY' 'KXAAAGASMINTX'
 'KXAAAGASW' 'KXAAAGASY' 'KXAAMMCAPEX' 'KXACPI' 'KXACPICORE' 'KXACPICORE-'
 'KXADP' 'KXAIJOBLOSS' 'KXAILABDIS' 'KXAIRCANADASTRIKE' 'KXAIRFARECPI'
 'KXAKSALMON' 'KXAMERICAPROFIT' 'KXAMSAVO' 'KXARGINFLATIONM'
 'KXARINFLATIONM' 'KXARMOMINF' 'KXAUNABCONF' 'KXAUTODELQ' 'KXAUTRADEBAL'
 'KXAUWPCC' 'KXAVGTARIFF' 'KXBALANCESHEET' 'KXBANKRUPTCY' 'KXBANKRUPTS'
 'KXBANKRUPTSY' 'KXBARRELS' 'KXBARRLES' 'KXBOE' 'KXBOEGOLD'
 'KXBOJDECISION' 'KXBOSHOMEVAL' 'KXBRAZILGDP' 'KXBRAZILGRAIN'
 'KXBRAZILINF' 'KXBRAZILJOBS' 'KXBRAZILU' 'KXBRINFHIGH' 'KXBRRATECUT'
 'KXBUILDPERMS' 'KXCACPIYOY' 'KXCAIVEYPMI' 'KXCALHOME' 'KXCANCUTS'
 'KXCANHOME' 'KXCANHOUSTART' 'KXCANOREOY' 'KXCANRECESSION' 'KXCANUSTRIPS'
 'KXCBDECISIONAUSTRALIA' 'KXCBDECISIONBRAZIL' 'KXCBDECISIONCANADA'
 'KXCBDECISIONCHINA' 'KXCBDECISIONENGLAND' 'KXCBDECISIONEU'
 'KXCBDECISIONINDIA' 'KXCBDECISIONJAPAN' 'KXCBDECISIONKOREA'
 'KXCBDECISIONMEXICO' 'KXCBDECISIONRUSSIA' 'KXCBDISRAEL' 'KXCBDSA'
 'KXCBRATEHIKE' 'KXCBRATEHIKES' 'KXCCCHGOFF' 'KXCCDELINQ' 'KXCH11'
 'KXCHAICUTS' 'KXCHCPIYOY' 'KXCHCUTS' 'KXCHEXPORTS' 'KXCHGDPYOY'
 'KXCHIMPORTS' 'KXCHINACPI' 'KXCHINAUSGDP' 'KXCHIPYOY' 'KXCHNBSPMI'
 'KXCHRETAIL' 'KXCHTRADEBAL' 'KXCNGDP' 'KXCNIMPORT' 'KXCNUSGDP' 'KXCNY'
 'KXCOIN' 'KXCOREUND' 'KXCPI' 'KXCPIAPPAREL' 'KXCPIAR' 'KXCPICN'
 'KXCPICORE' 'KXCPICORE220' 'KXCPICOREA' 'KXCPICOREYOY' 'KXCPIDELAY'
 'KXCPIEU' 'KXCPIFOOD' 'KXCPIGAS' 'KXCPISHELTER' 'KXCPIUSEDCAR' 'KXCPIYOY'
 'KXCPIYOYBANK' 'KXCREDEF' 'KXCREDEFMAX' 'KXCREDEFMINMAX' 'KXCREDITC'
 'KXCREDITCDEF' 'KXCREDITRATING' 'KXDCHOMEVAL' 'KXDEBTGROWTH'
 'KXDEBTGROWTH25' 'KXDEBTGROWTH26' 'KXDEBTLEVEL' 'KXDEBTSHRINK'
 'KXDECPIPREL' 'KXDEFAULT' 'KXDEFGDP' 'KXDEGDPQOQF' 'KXDEGDPYOYF'
 'KXDEGFK' 'KXDEIFO' 'KXDENHOMEVAL' 'KXDETRADEBAL' 'KXDEZEW' 'KXDIESEL'
 'KXDIESELM' 'KXDOTPLOT' 'KXDOTPLOTPUB' 'KXDXYFOMC'
 'KXEASTCOASTPORTSTRIKE' 'KXECB' 'KXECONPATH' 'KXECONSTATCORECPIYOY'
 'KXECONSTATCPI' 'KXECONSTATCPICORE' 'KXECONSTATCPIYOY' 'KXECONSTATU3'
 'KXEDMHOME' 'KXEFFR' 'KXEFFTARIFF' 'KXEGGPRICEM' 'KXEGGPRICEW' 'KXEGGS'
 'KXEHSALES' 'KXEHSHARE' 'KXEMERCUTS' 'KXEPOP' 'KXESGDPQOQF' 'KXESGDPYOYF'
 'KXETHETF' 'KXEXPORTTARIFF' 'KXEZCPIYOYF' 'KXEZDEPRATE' 'KXEZGDPQOQF'
 'KXEZGDPYOYF' 'KXFAOFPI' 'KXFEAR' 'KXFED' 'KXFEDCHGCOUNT' 'KXFEDDECISION'
 'KXFEDDISSENT' 'KXFEDEMPLOYEES' 'KXFEDFACILITY' 'KXFEDHIKE' 'KXFEDMEET'
 'KXFEDRATEMIN' 'KXFEDTWEETS' 'KXFERT' 'KXFM30YMTG' 'KXFOMCDISSENTCOUNT'
 'KXFOMCGUIDE' 'KXFRCPIPREL' 'KXFRGDPQOQP' 'KXFRGDPYOYP' 'KXFRM'
 'KXFRMMAX' 'KXFRMMIN' 'KXFRONTIERAI' 'KXFTAPER' 'KXFWFOMC' 'KXFXEURO'
 'KXFXPESO' 'KXGAS' 'KXGAS-MONTH' 'KXGASD' 'KXGASMAX' 'KXGASMIN' 'KXGDP'
 'KXGDPCN' 'KXGDPEU' 'KXGDPNOM' 'KXGDPSHAREMANU' 'KXGDPUSMAX' 'KXGDPUSMIN'
 'KXGDPW' 'KXGDPYEAR' 'KXGOVTCUTS' 'KXGOVTSPEND' 'KXH200CHINA'
 'KXHALFTRIL' 'KXHELIUMIMP' 'KXHICP' 'KXHIGHINFLATION' 'KXHLENDHALT'
 'KXHLENDREDM' 'KXHOME' 'KXHOMEUS' 'KXHOMEUSY' 'KXHOUHOMEVAL'
 'KXHOUSELENGTH' 'KXHOUSESTART' 'KXHOUSINGSTART' 'KXHPI' 'KXILPENDEBT'
 'KXIMFRECESS' 'KXINDIAVJAPAN' 'KXINEQUALITY' 'KXIRANCPI' 'KXIRANCRUDE'
 'KXIRANIMPORTS' 'KXIRSCOLLECT' 'KXISMPMI' 'KXISMSERVICES' 'KXITCPIPREL'
 'KXITGDPQOQA' 'KXITGDPYOYA' 'KXJETFUEL' 'KXJOBLESS' 'KXJOBLESSCLAIMS'
 'KXJOBREVISION' 'KXJOBSRELEASE' 'KXJPCONCONF' 'KXJPCPIYOY' 'KXJPMOMINF'
 'KXJPTRADEBAL' 'KXJPY' 'KXJPYINT' 'KXJUSTATEST' 'KXLARGECUT' 'KXLAYOFFSY'
 'KXLAYOFFSYINFO' 'KXLAYOFFSYPBS' 'KXLCPIMAX' 'KXLCPIMAXYOY' 'KXLCPIMIN'
 'KXLCPIYOY' 'KXLIRRSTRIKE' 'KXLOWESTRATE' 'KXMAJORPROTEST'
 'KXMANHEIMUSEDCAR' 'KXMANUCON' 'KXMEDIANRENTCHI' 'KXMEDIANRENTHOU'
 'KXMEDIANRENTLA' 'KXMEDIANRENTMIA' 'KXMEXCUBOIL' 'KXMIAHOMEVAL'
 'KXMLBSTRIKE' 'KXMORTGAGEDEF' 'KXMORTGAGERATE' 'KXMSTRSELL' 'KXMTLHOME'
 'KXMUSKNW' 'KXMUSKTRILLION' 'KXMUSKTRILLION27' 'KXMUSKWEALTH' 'KXMUSKX'
 'KXNBERRECESSQ' 'KXNDEBTSHRINK' 'KXNETWORTHKAICENAT' 'KXNETWORTHROYLEE'
 'KXNEXTTRILLIONAIRE' 'KXNFPDELAY' 'KXNFPROD' 'KXNGAS' 'KXNGASMAX'
 'KXNGASMIN' 'KXNGASW' 'KXNGDP' 'KXNGDPQ' 'KXNHSALES' 'KXNJDRONES'
 'KXNURSESTRIKE' 'KXNWSAYLOR' 'KXNYCBILLIONAIRES' 'KXNYCCBDENTRY'
 'KXNYCRENTSM' 'KXNYCRENTSY' 'KXNYCSURP' 'KXNYSECIRCUIT' 'KXNYSEOPEN'
 'KXOFAC' 'KXOIL' 'KXOILRIGS' 'KXOILW' 'KXOPECCUTS' 'KXOTTAWAHOME'
 'KXPAYROLLCANCEL' 'KXPAYROLLS' 'KXPAYROLLSREV' 'KXPCECORE' 'KXPESO'
 'KXPHXHOMEVAL' 'KXPOWERKWH' 'KXPPICPI' 'KXPPISEMI' 'KXPPIVSCPI'
 'KXPRIMESPEND' 'KXPROLLS' 'KXPSAVERT' 'KXQATARLNGPROD' 'KXQRECESS'
 'KXQTEND' 'KXRATECUT' 'KXRATECUTCOUNT' 'KXRATECUTE' 'KXRATECUTS'
 'KXRATEHIKE' 'KXRBADECISION' 'KXRBWSTRIKE' 'KXREALWAGES' 'KXRECSSNBER'
 'KXRENTNYCM' 'KXRENTNYCY' 'KXRETAIL' 'KXREVETH' 'KXREVSOL' 'KXRUBLE'
 'KXRUCRUDEX' 'KXSAGDPQOQ' 'KXSAHM' 'KXSAMOMINF' 'KXSAMSUNGSTRIKE'
 'KXSARETAIL' 'KXSATRADEBAL' 'KXSDHOMEVAL' 'KXSEAHOMEVAL' 'KXSEMIPRODH'
 'KXSFHOMEVAL' 'KXSFRENTSY' 'KXSHELTERCPI' 'KXSKEXPYOY' 'KXSOLAR' 'KXSPR'
 'KXSPRLVL' 'KXSPRMAX' 'KXSPRMIN' 'KXSPRUSE' 'KXSPXFOMC' 'KXSUEZTRAFFIC'
 'KXTARIFFREVENUE' 'KXTDEFFICITBY' 'KXTDEFICITHALF' 'KXTECHLAYOFF'
 'KXTEMPHELP' 'KXTERMINALRATE' 'KXTFP' 'KXTOBACCPI' 'KXTOKENUST'
 'KXTOP3WEALTH' 'KXTOPBUSINESS' 'KXTORCONDO' 'KXTRADEDEFFICIT'
 'KXTRADEDEFICIT' 'KXTRDDEFCN' 'KXTRILLIONAIRE' 'KXTRUEV' 'KXTRUFAIDP'
 'KXTRUFBFST' 'KXTRUFBPPI' 'KXTRUFCCI' 'KXTRUFCMC' 'KXTRUFCPI'
 'KXTRUFCPIYE' 'KXTRUFDEAD' 'KXTRUFEGGS' 'KXTRUFGAS' 'KXTRUFHOUCPI'
 'KXTRUFPDEBT' 'KXTRUFTSA' 'KXTRUMPTRADEGAP' 'KXTSAW' 'KXTSLAYOFF' 'KXU3'
 'KXU3MAX' 'KXU3MIN' 'KXUE' 'KXUKCPIYOY' 'KXUKGDPMOM' 'KXUKRETAIL'
 'KXUKUNRATE' 'KXUMICHOVR' 'KXUSDEBT' 'KXUSDEBTMON' 'KXUSDIRR'
 'KXUSDTTBILL' 'KXUSDURABLE' 'KXUSEDCAR' 'KXUSEDCARCPI' 'KXUSFLYCAN'
 'KXUSGASCPI' 'KXUSGBEEF' 'KXUSHOMEVAL' 'KXUSIPMOM' 'KXUSISMSERV'
 'KXUSMICHCSP' 'KXUSNFP' 'KXUSPINCOME' 'KXUSPPI' 'KXUSPPIYOY' 'KXUSPSPEND'
 'KXUSRETAIL' 'KXUST10' 'KXUST2' 'KXUST30' 'KXUST5' 'KXUSTM' 'KXUSTYLD'
 'KXUTILITYERCOT' 'KXUTILITYNYC' 'KXUTILITYPJMWEST' 'KXUTILITYSOCAL'
 'KXVANCONDO' 'KXWAGESAT' 'KXWCPI-RU' 'KXWCPI-TR' 'KXWHCA2' 'KXWHEAT'
 'KXWILDSHT' 'KXWRECSS' 'KXXINDIA' 'KXYOUTHUN' 'KXZERORATE' 'LAYOFFSY'
 'LAYOFFSYINFO' 'LCPIMAX' 'LCPIMAXYOY' 'LCPIMIN' 'LCPIYOY' 'LEAVEPOWELL'
 'LOWESTRATE' 'MANHEIMUSEDCAR' 'MORTGAGEDEF' 'NFPDELAY' 'NGAS' 'NGASMAX'
 'NGASMIN' 'NGASW' 'NGDP' 'NGDPQ' 'NYCRENTSM' 'NYCRENTSY' 'OIL' 'OILW'
 'PAYROLLS' 'PCECORE' 'PESO' 'POWELLLEAVE' 'PPISEMI' 'PROLLS' 'RATECUT'
 'RATECUTCOUNT' 'RATECUTS' 'RATEHIKE' 'REALWAGES' 'RECSSNBER' 'RENTNYCM'
 'RENTNYCY' 'RETAIL' 'RHIKE' 'RUBLE' 'SEMIPRODH' 'SFRENTSY' 'SPR' 'SPRMAX'
 'SPRMIN' 'TBILL' 'TECHLAYOFF' 'TERMINALRATE' 'TRDDEFCN' 'U3' 'U3MAX'
 'U3MIN' 'USEDCAR' 'WCPI-RU' 'WCPI-TR' 'WEALTH' 'WEALTHY' 'WHEAT' 'WRECSS'
 'WTAX' 'YINVERT']
Occurrences: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
590

In [ ]:
categories_array = df_economics_series.category.values
values, counts = np.unique(categories_array, return_counts=True)
print("Unique values:", values)  # [1 2 3 4]
print("Occurrences:", counts)

Unique values: ['Companies' 'Economics' 'Financials' 'Politics' 'Science and Technology'
 'World']
Occurrences: [  1 574   5   3   1   6]

## Getting Events for the economics series

In [ ]:
import time
import pandas as pd

# If you already have a Python list, use it here:
# economics_series_tickers = ["KXCPI", "KXFED", "KXGDP"]

# If your tickers are in a DataFrame from the previous step, use this:
economics_series_tickers = (
    df_economics_series["ticker"]
    .dropna()
    .drop_duplicates()
    .sort_values()
    .tolist()
)

print("Economics series tickers:", len(economics_series_tickers))

Economics series tickers: 590

In [ ]:
import time
import requests
import pandas as pd
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-economics-events-colab/1.0"
})

# Use your existing list if you already have one:
# economics_series_tickers = ["KXCPI", "KXFED", "KXGDP"]

# Or use this if your Economics series are in df_economics_series:
economics_series_tickers = (
    df_economics_series["ticker"]
    .dropna()
    .drop_duplicates()
    .sort_values()
    .tolist()
)


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        if 500 <= resp.status_code < 600:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Server error {resp.status_code}. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        if resp.status_code >= 400:
            print("Bad request URL:", resp.url)
            print("Kalshi response:", resp.text)
            resp.raise_for_status()

        return resp.json()

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def paginate(path, collection_key, params=None, limit=200, sleep_s=0.25):
    params = dict(params or {})
    params["limit"] = limit

    rows = []
    cursor = None

    while True:
        if cursor:
            params["cursor"] = cursor
        else:
            params.pop("cursor", None)

        data = get_json(path, params=params)
        rows.extend(data.get(collection_key, []))

        cursor = data.get("cursor")
        if not cursor:
            break

        time.sleep(sleep_s)

    return rows


all_economics_events = []
failed_series = []

print("Economics series tickers:", len(economics_series_tickers))

for i, series_ticker in enumerate(economics_series_tickers, start=1):
    print(f"[{i}/{len(economics_series_tickers)}] Getting events for {series_ticker}...")

    try:
        events = paginate(
            "/events",
            "events",
            params={
                "series_ticker": series_ticker,
                "with_nested_markets": False
            },
            limit=200,
            sleep_s=0.25
        )

        for event in events:
            event["series_ticker_searched"] = series_ticker
            event["category"] = "Economics"

        all_economics_events.extend(events)

    except requests.exceptions.HTTPError as e:
        print(f"Skipping {series_ticker}: {e}")
        failed_series.append(series_ticker)
        continue

    time.sleep(0.25)


df_economics_events = pd.DataFrame(all_economics_events)

print("Total event rows:", len(df_economics_events))
print("Failed series:", len(failed_series))

if not df_economics_events.empty:
    event_id_col = "event_ticker" if "event_ticker" in df_economics_events.columns else "ticker"

    df_economics_events = (
        df_economics_events
        .drop_duplicates(subset=[event_id_col])
        .sort_values(event_id_col)
        .reset_index(drop=True)
    )

    print("Unique Economics events:", len(df_economics_events))
    display(df_economics_events.head(50))

    df_economics_events.to_csv(
        "kalshi_economics_events.csv",
        index=False
    )

if failed_series:
    df_failed_series = pd.DataFrame({"failed_series_ticker": failed_series})
    display(df_failed_series)
    df_failed_series.to_csv(
        "kalshi_failed_economics_series_for_events.csv",
        index=False
    )

Economics series tickers: 590
[1/590] Getting events for AAAGASD...
[2/590] Getting events for AAAGASM...
[3/590] Getting events for AAAGASMAX...
[4/590] Getting events for AAAGASMAXCA...
[5/590] Getting events for AAAGASMAXTX...
[6/590] Getting events for AAAGASMIN...
[7/590] Getting events for AAAGASMINCA...
[8/590] Getting events for AAAGASMINTX...
[9/590] Getting events for AAAGASW...
[10/590] Getting events for AAAGASY...
[11/590] Getting events for ACPI...
[12/590] Getting events for ACPICORE...
[13/590] Getting events for ACPICORE-...
[14/590] Getting events for ARGINFLATIONM...
[15/590] Getting events for ARINFLATIONM...
[16/590] Getting events for BANKRUPTS...
[17/590] Getting events for BANKRUPTSY...
[18/590] Getting events for BIGBANKLAYOFF...
[19/590] Getting events for BIGTECHLAYOFF...
[20/590] Getting events for BOE...
[21/590] Getting events for CHINAUSGDP...
[22/590] Getting events for CNGDP...
[23/590] Getting events for CNY...
[24/590] Getting events for COIN...
[25/590] Getting events for COSTCOHOTDOG...
[26/590] Getting events for COSTCOMEMBER...
[27/590] Getting events for CPI...
[28/590] Getting events for CPIAPPAREL...
[29/590] Getting events for CPIAR...
[30/590] Getting events for CPICN...
[31/590] Getting events for CPICORE...
[32/590] Getting events for CPICOREYOY...
[33/590] Getting events for CPIDELAY...
[34/590] Getting events for CPIEU...
[35/590] Getting events for CPIFOOD...
[36/590] Getting events for CPIGAS...
[37/590] Getting events for CPISHELTER...
[38/590] Getting events for CPIUSEDCAR...
[39/590] Getting events for CPIYOY...
[40/590] Getting events for CREDEF...
[41/590] Getting events for CREDEFMAX...
[42/590] Getting events for CREDEFMINMAX...
[43/590] Getting events for CREDITCDEF...
[44/590] Getting events for CREDITRATING...
[45/590] Getting events for DIESEL...
[46/590] Getting events for DIESELM...
[47/590] Getting events for DOTPLOT...
[48/590] Getting events for ECB...
[49/590] Getting events for ECONPATH...
[50/590] Getting events for EPOP...
[51/590] Getting events for ETHETF...
[52/590] Getting events for FED...
[53/590] Getting events for FEDDECISION...
[54/590] Getting events for FEDFACILITY...
[55/590] Getting events for FEDHIKE...
[56/590] Getting events for FEDMEET...
[57/590] Getting events for FEDRATEMIN...
[58/590] Getting events for FRM...
[59/590] Getting events for FRMMAX...
[60/590] Getting events for FRMMIN...
[61/590] Getting events for FTAPER...
[62/590] Getting events for FXEURO...
[63/590] Getting events for FXPESO...
[64/590] Getting events for GAS...
[65/590] Getting events for GAS-MONTH...
[66/590] Getting events for GASD...
[67/590] Getting events for GASMAX...
[68/590] Getting events for GASMIN...
[69/590] Getting events for GDP...
[70/590] Getting events for GDPCN...
[71/590] Getting events for GDPEU...
[72/590] Getting events for GDPUSMAX...
[73/590] Getting events for GDPUSMIN...
[74/590] Getting events for GDPW...
[75/590] Getting events for HOME...
[76/590] Getting events for HOMEUS...
[77/590] Getting events for HOMEUSY...
[78/590] Getting events for HOUSELENGTH...
[79/590] Getting events for HOUSESTART...
[80/590] Getting events for HPI...
[81/590] Getting events for JOBLESS...
[82/590] Getting events for JPY...
[83/590] Getting events for KX25U3SEP...
[84/590] Getting events for KX2YFOMC...
[85/590] Getting events for KX30YUSTW...
[86/590] Getting events for KX3MTBILL...
[87/590] Getting events for KXAAAGASD...
[88/590] Getting events for KXAAAGASED...
[89/590] Getting events for KXAAAGASM...
[90/590] Getting events for KXAAAGASMAX...
[91/590] Getting events for KXAAAGASMAXCA...
[92/590] Getting events for KXAAAGASMAXFL...
[93/590] Getting events for KXAAAGASMAXNY...
[94/590] Getting events for KXAAAGASMAXTX...
[95/590] Getting events for KXAAAGASMIN...
[96/590] Getting events for KXAAAGASMINCA...
[97/590] Getting events for KXAAAGASMINFL...
[98/590] Getting events for KXAAAGASMINNY...
[99/590] Getting events for KXAAAGASMINTX...
[100/590] Getting events for KXAAAGASW...
[101/590] Getting events for KXAAAGASY...
[102/590] Getting events for KXAAMMCAPEX...
[103/590] Getting events for KXACPI...
[104/590] Getting events for KXACPICORE...
[105/590] Getting events for KXACPICORE-...
[106/590] Getting events for KXADP...
[107/590] Getting events for KXAIJOBLOSS...
[108/590] Getting events for KXAILABDIS...
[109/590] Getting events for KXAIRCANADASTRIKE...
[110/590] Getting events for KXAIRFARECPI...
[111/590] Getting events for KXAKSALMON...
[112/590] Getting events for KXAMERICAPROFIT...
[113/590] Getting events for KXAMSAVO...
[114/590] Getting events for KXARGINFLATIONM...
[115/590] Getting events for KXARINFLATIONM...
[116/590] Getting events for KXARMOMINF...
[117/590] Getting events for KXAUNABCONF...
[118/590] Getting events for KXAUTODELQ...
[119/590] Getting events for KXAUTRADEBAL...
[120/590] Getting events for KXAUWPCC...
[121/590] Getting events for KXAVGTARIFF...
[122/590] Getting events for KXBALANCESHEET...
[123/590] Getting events for KXBANKRUPTCY...
[124/590] Getting events for KXBANKRUPTS...
[125/590] Getting events for KXBANKRUPTSY...
[126/590] Getting events for KXBARRELS...
[127/590] Getting events for KXBARRLES...
[128/590] Getting events for KXBOE...
[129/590] Getting events for KXBOEGOLD...
[130/590] Getting events for KXBOJDECISION...
[131/590] Getting events for KXBOSHOMEVAL...
[132/590] Getting events for KXBRAZILGDP...
[133/590] Getting events for KXBRAZILGRAIN...
[134/590] Getting events for KXBRAZILINF...
[135/590] Getting events for KXBRAZILJOBS...
[136/590] Getting events for KXBRAZILU...
[137/590] Getting events for KXBRINFHIGH...
[138/590] Getting events for KXBRRATECUT...
[139/590] Getting events for KXBUILDPERMS...
[140/590] Getting events for KXCACPIYOY...
[141/590] Getting events for KXCAIVEYPMI...
[142/590] Getting events for KXCALHOME...
[143/590] Getting events for KXCANCUTS...
[144/590] Getting events for KXCANHOME...
[145/590] Getting events for KXCANHOUSTART...
[146/590] Getting events for KXCANOREOY...
[147/590] Getting events for KXCANRECESSION...
[148/590] Getting events for KXCANUSTRIPS...
[149/590] Getting events for KXCBDECISIONAUSTRALIA...
[150/590] Getting events for KXCBDECISIONBRAZIL...
[151/590] Getting events for KXCBDECISIONCANADA...
[152/590] Getting events for KXCBDECISIONCHINA...
[153/590] Getting events for KXCBDECISIONENGLAND...
[154/590] Getting events for KXCBDECISIONEU...
[155/590] Getting events for KXCBDECISIONINDIA...
[156/590] Getting events for KXCBDECISIONJAPAN...
[157/590] Getting events for KXCBDECISIONKOREA...
[158/590] Getting events for KXCBDECISIONMEXICO...
[159/590] Getting events for KXCBDECISIONRUSSIA...
[160/590] Getting events for KXCBDISRAEL...
[161/590] Getting events for KXCBDSA...
[162/590] Getting events for KXCBRATEHIKE...
[163/590] Getting events for KXCBRATEHIKES...
[164/590] Getting events for KXCCCHGOFF...
[165/590] Getting events for KXCCDELINQ...
[166/590] Getting events for KXCH11...
[167/590] Getting events for KXCHAICUTS...
[168/590] Getting events for KXCHCPIYOY...
[169/590] Getting events for KXCHCUTS...
[170/590] Getting events for KXCHEXPORTS...
[171/590] Getting events for KXCHGDPYOY...
[172/590] Getting events for KXCHIMPORTS...
[173/590] Getting events for KXCHINACPI...
[174/590] Getting events for KXCHINAUSGDP...
[175/590] Getting events for KXCHIPYOY...
[176/590] Getting events for KXCHNBSPMI...
[177/590] Getting events for KXCHRETAIL...
[178/590] Getting events for KXCHTRADEBAL...
[179/590] Getting events for KXCNGDP...
[180/590] Getting events for KXCNIMPORT...
[181/590] Getting events for KXCNUSGDP...
[182/590] Getting events for KXCNY...
[183/590] Getting events for KXCOIN...
[184/590] Getting events for KXCOREUND...
[185/590] Getting events for KXCPI...
[186/590] Getting events for KXCPIAPPAREL...
[187/590] Getting events for KXCPIAR...
[188/590] Getting events for KXCPICN...
[189/590] Getting events for KXCPICORE...
[190/590] Getting events for KXCPICORE220...
[191/590] Getting events for KXCPICOREA...
[192/590] Getting events for KXCPICOREYOY...
[193/590] Getting events for KXCPIDELAY...
[194/590] Getting events for KXCPIEU...
[195/590] Getting events for KXCPIFOOD...
[196/590] Getting events for KXCPIGAS...
[197/590] Getting events for KXCPISHELTER...
[198/590] Getting events for KXCPIUSEDCAR...
[199/590] Getting events for KXCPIYOY...
[200/590] Getting events for KXCPIYOYBANK...
[201/590] Getting events for KXCREDEF...
[202/590] Getting events for KXCREDEFMAX...
[203/590] Getting events for KXCREDEFMINMAX...
[204/590] Getting events for KXCREDITC...
[205/590] Getting events for KXCREDITCDEF...
[206/590] Getting events for KXCREDITRATING...
[207/590] Getting events for KXDCHOMEVAL...
[208/590] Getting events for KXDEBTGROWTH...
[209/590] Getting events for KXDEBTGROWTH25...
[210/590] Getting events for KXDEBTGROWTH26...
[211/590] Getting events for KXDEBTLEVEL...
[212/590] Getting events for KXDEBTSHRINK...
[213/590] Getting events for KXDECPIPREL...
[214/590] Getting events for KXDEFAULT...
[215/590] Getting events for KXDEFGDP...
[216/590] Getting events for KXDEGDPQOQF...
[217/590] Getting events for KXDEGDPYOYF...
[218/590] Getting events for KXDEGFK...
[219/590] Getting events for KXDEIFO...
[220/590] Getting events for KXDENHOMEVAL...
[221/590] Getting events for KXDETRADEBAL...
[222/590] Getting events for KXDEZEW...
[223/590] Getting events for KXDIESEL...
[224/590] Getting events for KXDIESELM...
[225/590] Getting events for KXDOTPLOT...
[226/590] Getting events for KXDOTPLOTPUB...
[227/590] Getting events for KXDXYFOMC...
[228/590] Getting events for KXEASTCOASTPORTSTRIKE...
[229/590] Getting events for KXECB...
[230/590] Getting events for KXECONPATH...
[231/590] Getting events for KXECONSTATCORECPIYOY...
[232/590] Getting events for KXECONSTATCPI...
[233/590] Getting events for KXECONSTATCPICORE...
[234/590] Getting events for KXECONSTATCPIYOY...
[235/590] Getting events for KXECONSTATU3...
[236/590] Getting events for KXEDMHOME...
[237/590] Getting events for KXEFFR...
[238/590] Getting events for KXEFFTARIFF...
[239/590] Getting events for KXEGGPRICEM...
[240/590] Getting events for KXEGGPRICEW...
[241/590] Getting events for KXEGGS...
[242/590] Getting events for KXEHSALES...
[243/590] Getting events for KXEHSHARE...
[244/590] Getting events for KXEMERCUTS...
[245/590] Getting events for KXEPOP...
[246/590] Getting events for KXESGDPQOQF...
[247/590] Getting events for KXESGDPYOYF...
[248/590] Getting events for KXETHETF...
[249/590] Getting events for KXEXPORTTARIFF...
[250/590] Getting events for KXEZCPIYOYF...
[251/590] Getting events for KXEZDEPRATE...
[252/590] Getting events for KXEZGDPQOQF...
[253/590] Getting events for KXEZGDPYOYF...
[254/590] Getting events for KXFAOFPI...
[255/590] Getting events for KXFEAR...
[256/590] Getting events for KXFED...
[257/590] Getting events for KXFEDCHGCOUNT...
[258/590] Getting events for KXFEDDECISION...
[259/590] Getting events for KXFEDDISSENT...
[260/590] Getting events for KXFEDEMPLOYEES...
[261/590] Getting events for KXFEDFACILITY...
[262/590] Getting events for KXFEDHIKE...
[263/590] Getting events for KXFEDMEET...
[264/590] Getting events for KXFEDRATEMIN...
[265/590] Getting events for KXFEDTWEETS...
[266/590] Getting events for KXFERT...
[267/590] Getting events for KXFM30YMTG...
[268/590] Getting events for KXFOMCDISSENTCOUNT...
[269/590] Getting events for KXFOMCGUIDE...
[270/590] Getting events for KXFRCPIPREL...
[271/590] Getting events for KXFRGDPQOQP...
[272/590] Getting events for KXFRGDPYOYP...
[273/590] Getting events for KXFRM...
[274/590] Getting events for KXFRMMAX...
[275/590] Getting events for KXFRMMIN...
[276/590] Getting events for KXFRONTIERAI...
[277/590] Getting events for KXFTAPER...
[278/590] Getting events for KXFWFOMC...
[279/590] Getting events for KXFXEURO...
[280/590] Getting events for KXFXPESO...
[281/590] Getting events for KXGAS...
[282/590] Getting events for KXGAS-MONTH...
[283/590] Getting events for KXGASD...
[284/590] Getting events for KXGASMAX...
[285/590] Getting events for KXGASMIN...
[286/590] Getting events for KXGDP...
[287/590] Getting events for KXGDPCN...
[288/590] Getting events for KXGDPEU...
[289/590] Getting events for KXGDPNOM...
[290/590] Getting events for KXGDPSHAREMANU...
[291/590] Getting events for KXGDPUSMAX...
[292/590] Getting events for KXGDPUSMIN...
[293/590] Getting events for KXGDPW...
[294/590] Getting events for KXGDPYEAR...
[295/590] Getting events for KXGOVTCUTS...
[296/590] Getting events for KXGOVTSPEND...
[297/590] Getting events for KXH200CHINA...
[298/590] Getting events for KXHALFTRIL...
[299/590] Getting events for KXHELIUMIMP...
[300/590] Getting events for KXHICP...
[301/590] Getting events for KXHIGHINFLATION...
[302/590] Getting events for KXHLENDHALT...
[303/590] Getting events for KXHLENDREDM...
[304/590] Getting events for KXHOME...
[305/590] Getting events for KXHOMEUS...
[306/590] Getting events for KXHOMEUSY...
[307/590] Getting events for KXHOUHOMEVAL...
[308/590] Getting events for KXHOUSELENGTH...
[309/590] Getting events for KXHOUSESTART...
[310/590] Getting events for KXHOUSINGSTART...
[311/590] Getting events for KXHPI...
[312/590] Getting events for KXILPENDEBT...
[313/590] Getting events for KXIMFRECESS...
[314/590] Getting events for KXINDIAVJAPAN...
[315/590] Getting events for KXINEQUALITY...
[316/590] Getting events for KXIRANCPI...
[317/590] Getting events for KXIRANCRUDE...
[318/590] Getting events for KXIRANIMPORTS...
[319/590] Getting events for KXIRSCOLLECT...
[320/590] Getting events for KXISMPMI...
[321/590] Getting events for KXISMSERVICES...
[322/590] Getting events for KXITCPIPREL...
[323/590] Getting events for KXITGDPQOQA...
[324/590] Getting events for KXITGDPYOYA...
[325/590] Getting events for KXJETFUEL...
[326/590] Getting events for KXJOBLESS...
[327/590] Getting events for KXJOBLESSCLAIMS...
[328/590] Getting events for KXJOBREVISION...
[329/590] Getting events for KXJOBSRELEASE...
[330/590] Getting events for KXJPCONCONF...
[331/590] Getting events for KXJPCPIYOY...
[332/590] Getting events for KXJPMOMINF...
[333/590] Getting events for KXJPTRADEBAL...
[334/590] Getting events for KXJPY...
[335/590] Getting events for KXJPYINT...
[336/590] Getting events for KXJUSTATEST...
[337/590] Getting events for KXLARGECUT...
[338/590] Getting events for KXLAYOFFSY...
[339/590] Getting events for KXLAYOFFSYINFO...
[340/590] Getting events for KXLAYOFFSYPBS...
[341/590] Getting events for KXLCPIMAX...
[342/590] Getting events for KXLCPIMAXYOY...
[343/590] Getting events for KXLCPIMIN...
[344/590] Getting events for KXLCPIYOY...
[345/590] Getting events for KXLIRRSTRIKE...
[346/590] Getting events for KXLOWESTRATE...
[347/590] Getting events for KXMAJORPROTEST...
[348/590] Getting events for KXMANHEIMUSEDCAR...
[349/590] Getting events for KXMANUCON...
[350/590] Getting events for KXMEDIANRENTCHI...
[351/590] Getting events for KXMEDIANRENTHOU...
[352/590] Getting events for KXMEDIANRENTLA...
[353/590] Getting events for KXMEDIANRENTMIA...
[354/590] Getting events for KXMEXCUBOIL...
[355/590] Getting events for KXMIAHOMEVAL...
[356/590] Getting events for KXMLBSTRIKE...
[357/590] Getting events for KXMORTGAGEDEF...
[358/590] Getting events for KXMORTGAGERATE...
[359/590] Getting events for KXMSTRSELL...
[360/590] Getting events for KXMTLHOME...
[361/590] Getting events for KXMUSKNW...
[362/590] Getting events for KXMUSKTRILLION...
[363/590] Getting events for KXMUSKTRILLION27...
[364/590] Getting events for KXMUSKWEALTH...
[365/590] Getting events for KXMUSKX...
[366/590] Getting events for KXNBERRECESSQ...
[367/590] Getting events for KXNDEBTSHRINK...
[368/590] Getting events for KXNETWORTHKAICENAT...
[369/590] Getting events for KXNETWORTHROYLEE...
[370/590] Getting events for KXNEXTTRILLIONAIRE...
[371/590] Getting events for KXNFPDELAY...
[372/590] Getting events for KXNFPROD...
[373/590] Getting events for KXNGAS...
[374/590] Getting events for KXNGASMAX...
[375/590] Getting events for KXNGASMIN...
[376/590] Getting events for KXNGASW...
[377/590] Getting events for KXNGDP...
[378/590] Getting events for KXNGDPQ...
[379/590] Getting events for KXNHSALES...
[380/590] Getting events for KXNJDRONES...
[381/590] Getting events for KXNURSESTRIKE...
[382/590] Getting events for KXNWSAYLOR...
[383/590] Getting events for KXNYCBILLIONAIRES...
[384/590] Getting events for KXNYCCBDENTRY...
[385/590] Getting events for KXNYCRENTSM...
[386/590] Getting events for KXNYCRENTSY...
[387/590] Getting events for KXNYCSURP...
[388/590] Getting events for KXNYSECIRCUIT...
[389/590] Getting events for KXNYSEOPEN...
[390/590] Getting events for KXOFAC...
[391/590] Getting events for KXOIL...
[392/590] Getting events for KXOILRIGS...
[393/590] Getting events for KXOILW...
[394/590] Getting events for KXOPECCUTS...
[395/590] Getting events for KXOTTAWAHOME...
[396/590] Getting events for KXPAYROLLCANCEL...
[397/590] Getting events for KXPAYROLLS...
[398/590] Getting events for KXPAYROLLSREV...
[399/590] Getting events for KXPCECORE...
[400/590] Getting events for KXPESO...
[401/590] Getting events for KXPHXHOMEVAL...
[402/590] Getting events for KXPOWERKWH...
[403/590] Getting events for KXPPICPI...
[404/590] Getting events for KXPPISEMI...
[405/590] Getting events for KXPPIVSCPI...
[406/590] Getting events for KXPRIMESPEND...
[407/590] Getting events for KXPROLLS...
[408/590] Getting events for KXPSAVERT...
[409/590] Getting events for KXQATARLNGPROD...
[410/590] Getting events for KXQRECESS...
[411/590] Getting events for KXQTEND...
[412/590] Getting events for KXRATECUT...
[413/590] Getting events for KXRATECUTCOUNT...
[414/590] Getting events for KXRATECUTE...
[415/590] Getting events for KXRATECUTS...
[416/590] Getting events for KXRATEHIKE...
[417/590] Getting events for KXRBADECISION...
[418/590] Getting events for KXRBWSTRIKE...
[419/590] Getting events for KXREALWAGES...
[420/590] Getting events for KXRECSSNBER...
[421/590] Getting events for KXRENTNYCM...
[422/590] Getting events for KXRENTNYCY...
[423/590] Getting events for KXRETAIL...
[424/590] Getting events for KXREVETH...
[425/590] Getting events for KXREVSOL...
[426/590] Getting events for KXRUBLE...
[427/590] Getting events for KXRUCRUDEX...
[428/590] Getting events for KXSAGDPQOQ...
[429/590] Getting events for KXSAHM...
[430/590] Getting events for KXSAMOMINF...
[431/590] Getting events for KXSAMSUNGSTRIKE...
[432/590] Getting events for KXSARETAIL...
[433/590] Getting events for KXSATRADEBAL...
[434/590] Getting events for KXSDHOMEVAL...
[435/590] Getting events for KXSEAHOMEVAL...
[436/590] Getting events for KXSEMIPRODH...
[437/590] Getting events for KXSFHOMEVAL...
[438/590] Getting events for KXSFRENTSY...
[439/590] Getting events for KXSHELTERCPI...
[440/590] Getting events for KXSKEXPYOY...
[441/590] Getting events for KXSOLAR...
[442/590] Getting events for KXSPR...
[443/590] Getting events for KXSPRLVL...
[444/590] Getting events for KXSPRMAX...
[445/590] Getting events for KXSPRMIN...
[446/590] Getting events for KXSPRUSE...
[447/590] Getting events for KXSPXFOMC...
[448/590] Getting events for KXSUEZTRAFFIC...
[449/590] Getting events for KXTARIFFREVENUE...
[450/590] Getting events for KXTDEFFICITBY...
[451/590] Getting events for KXTDEFICITHALF...
[452/590] Getting events for KXTECHLAYOFF...
[453/590] Getting events for KXTEMPHELP...
[454/590] Getting events for KXTERMINALRATE...
[455/590] Getting events for KXTFP...
[456/590] Getting events for KXTOBACCPI...
[457/590] Getting events for KXTOKENUST...
[458/590] Getting events for KXTOP3WEALTH...
[459/590] Getting events for KXTOPBUSINESS...
[460/590] Getting events for KXTORCONDO...
[461/590] Getting events for KXTRADEDEFFICIT...
[462/590] Getting events for KXTRADEDEFICIT...
[463/590] Getting events for KXTRDDEFCN...
[464/590] Getting events for KXTRILLIONAIRE...
[465/590] Getting events for KXTRUEV...

,available_on_brokers,category,collateral_return_type,event_ticker,last_updated_ts,mutually_exclusive,series_ticker,settlement_sources,strike_period,sub_title,title,series_ticker_searched,strike_date,product_metadata
0,False,Economics,,AAAGASD-23OCT03-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 3, 2023","US gas price up on Oct 3, 2023?",KXAAAGASD,2023-10-03T14:00:00Z,NaN
1,False,Economics,,AAAGASD-23OCT04-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 4, 2023","US gas price up on Oct 4, 2023?",KXAAAGASD,2023-10-04T14:00:00Z,NaN
2,False,Economics,,AAAGASD-23OCT05-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 5, 2023","US gas price up on Oct 5, 2023?",KXAAAGASD,2023-10-05T14:00:00Z,NaN
3,False,Economics,,AAAGASD-23OCT06-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 6, 2023","US gas price up on Oct 6, 2023?",KXAAAGASD,2023-10-06T14:00:00Z,NaN
4,False,Economics,,AAAGASD-23OCT07-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 7, 2023","US gas price up on Oct 7, 2023?",KXAAAGASD,2023-10-07T14:00:00Z,NaN
5,False,Economics,,AAAGASD-23OCT10-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 10, 2023","US gas price up on Oct 10, 2023?",KXAAAGASD,2023-10-10T14:00:00Z,NaN
6,False,Economics,,AAAGASD-23OCT11-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 11, 2023","US gas price up on Oct 11, 2023?",KXAAAGASD,2023-10-11T14:00:00Z,NaN
7,False,Economics,,AAAGASD-23OCT12-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 12, 2023","US gas price up on Oct 12, 2023?",KXAAAGASD,2023-10-12T14:00:00Z,NaN
8,False,Economics,,AAAGASD-23OCT13-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 13, 2023","US gas price up on Oct 13, 2023?",KXAAAGASD,2023-10-13T14:00:00Z,NaN
9,False,Economics,,AAAGASD-23OCT17-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 17, 2023","US gas price up on Oct 17, 2023?",KXAAAGASD,2023-10-17T14:00:00Z,NaN
10,False,Economics,,AAAGASD-23OCT18-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 18, 2023","US gas price up on Oct 18, 2023?",KXAAAGASD,2023-10-18T14:00:00Z,NaN
11,False,Economics,,AAAGASD-23OCT20-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 20, 2023","US gas price up on Oct 20, 2023?",KXAAAGASD,2023-10-20T14:00:00Z,NaN
12,False,Economics,,AAAGASD-23SEP18-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Sep 18, 2023","US gas price up on Sep 18, 2023?",KXAAAGASD,2023-09-18T14:00:00Z,NaN
13,False,Economics,,AAAGASD-23SEP19-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Sep 19, 2023","US gas price up on Sep 19, 2023?",KXAAAGASD,2023-09-19T14:00:00Z,NaN
14,False,Economics,,AAAGASD-23SEP20-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Sep 20, 2023","US gas price up on Sep 20, 2023?",KXAAAGASD,2023-09-20T14:00:00Z,NaN
15,False,Economics,,AAAGASD-23SEP21-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Sep 21, 2023","US gas price up on Sep 21, 2023?",KXAAAGASD,2023-09-21T14:00:00Z,NaN
16,False,Economics,,AAAGASD-23SEP22-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Sep 22, 2023","US gas price up on Sep 22, 2023?",KXAAAGASD,2023-09-22T14:00:00Z,NaN
17,False,Economics,,AAAGASD-23SEP25-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Sep 25, 2023","US gas price up on Sep 25, 2023?",KXAAAGASD,2023-09-25T14:00:00Z,NaN
18,False,Economics,,AAAGASD-23SEP26-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Sep 26, 2023","US gas price up on Sep 26, 2023?",KXAAAGASD,2023-09-26T14:00:00Z,NaN
19,False,Economics,,AAAGASD-23SEP27-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Sep 27, 2023","US gas price up on Sep 27, 2023?",KXAAAGASD,2023-09-27T14:00:00Z,NaN
20,False,Economics,,AAAGASD-23SEP28-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Sep 28, 2023","US gas price up on Sep 28, 2023?",KXAAAGASD,2023-09-28T14:00:00Z,NaN
21,False,Economics,,AAAGASD-23SEP29-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Sep 29, 2023","US gas price up on Sep 29, 2023?",KXAAAGASD,2023-09-29T14:00:00Z,NaN
22,False,Economics,,AAAGASD-23SEP30-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Sep 30, 2023","US gas price up on Sep 30, 2023?",KXAAAGASD,2023-09-30T14:00:00Z,NaN
23,False,Economics,,AAAGASD-24MAY07-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASD,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On May 7, 2024","Gas prices up on May 7, 2024?",KXAAAGASD,2024-05-07T14:00:00Z,NaN
24,False,Economics,,AAAGASM-23DEC31-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASM,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In Dec 2023,Gas prices up in the US in Dec 2023?,KXAAAGASM,2023-12-31T15:00:00Z,NaN
25,False,Economics,,AAAGASM-23NOV30-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASW,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In Nov 2023,US gas price up in Nov 2023?,KXAAAGASW,2023-12-01T04:59:00Z,NaN
26,False,Economics,,AAAGASM-23OCT31-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASW,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In Oct 2023,US gas price up in Oct 2023?,KXAAAGASW,2023-10-31T14:00:00Z,NaN
27,False,Economics,,AAAGASM-24APR30-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASM,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In Apr 2024,Gas prices in the US in Apr 2024?,KXAAAGASM,2024-04-30T14:00:00Z,NaN
28,False,Economics,,AAAGASM-24AUG31-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASM,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,Aug 2024,Gas prices in the US in Aug 2024?,KXAAAGASM,2024-08-31T14:00:00Z,NaN
29,False,Economics,,AAAGASM-24FEB29-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASM,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,On Feb 2024,Gas prices in the US in Feb 2024?,KXAAAGASM,2024-02-29T15:00:00Z,NaN
30,False,Economics,,AAAGASM-24JAN31-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASM,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In Jan 2024,Gas prices in the US in Jan 2024?,KXAAAGASM,2024-01-31T15:00:00Z,NaN
31,False,Economics,,AAAGASM-24JUL31-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASM,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,Jul 2024,Gas prices in the US in Jul 2024?,KXAAAGASM,2024-07-31T14:00:00Z,NaN
32,False,Economics,,AAAGASM-24JUN30-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASM,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,Jun 2024,Gas prices in the US in Jun 2024?,KXAAAGASM,2024-06-30T14:00:00Z,NaN
33,False,Economics,,AAAGASM-24MAR31-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASM,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In Mar 2024,Gas prices up in the US in Mar 2024?,KXAAAGASM,2024-03-31T14:00:00Z,NaN
34,False,Economics,,AAAGASM-24MAY31-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASM,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In May 2024,Gas prices in the US in May 2024?,KXAAAGASM,2024-05-31T14:00:00Z,NaN
35,False,Economics,,AAAGASM-24OCT31-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASM,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Oct 31, 2024",Gas prices in the US in Oct 2024?,KXAAAGASM,2024-10-31T14:00:00Z,NaN
36,False,Economics,,AAAGASM-24SEP30-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASM,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,On Sep 2024,Gas prices in the US in Sep 2024?,KXAAAGASM,2024-09-30T14:00:00Z,NaN
37,False,Economics,,AAAGASMAX-23DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMAX,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2023,Highest gas price in the US in 2023?,KXAAAGASMAX,2023-12-31T15:00:00Z,NaN
38,False,Economics,,AAAGASMAX-24DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMAX,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2024,How high will gas prices in the US get in 2024?,KXAAAGASMAX,2024-12-31T15:00:00Z,NaN
39,False,Economics,,AAAGASMAXCA-23DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMAXCA,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2023,Highest gas price in California in 2023?,KXAAAGASMAXCA,2023-12-31T15:00:00Z,NaN
40,False,Economics,,AAAGASMAXCA-24DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMAXCA,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2024,How high will gas prices in California get in ...,KXAAAGASMAXCA,2024-12-31T15:00:00Z,NaN
41,False,Economics,,AAAGASMAXTX-23DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMAXTX,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2023,Texas highest gas price in 2023?,KXAAAGASMAXTX,2023-12-31T15:00:00Z,NaN
42,False,Economics,,AAAGASMAXTX-24DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMAXTX,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2024,How high will gas prices in Texas get in 2024?,KXAAAGASMAXTX,2024-12-31T15:00:00Z,NaN
43,False,Economics,,AAAGASMIN-23DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMIN,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2023,Lowest gas price in the US in 2023?,KXAAAGASMIN,2023-12-31T15:00:00Z,NaN
44,False,Economics,,AAAGASMIN-24DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMIN,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2024,How low will gas prices in the US get in 2024?,KXAAAGASMIN,2024-12-31T15:00:00Z,NaN
45,False,Economics,,AAAGASMINCA-23DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMINCA,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2023,Lowest gas price in California in 2023?,KXAAAGASMINCA,2023-12-31T15:00:00Z,NaN
46,False,Economics,,AAAGASMINCA-24DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMINCA,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2024,How low will gas prices in California get in 2...,KXAAAGASMINCA,2024-12-31T15:00:00Z,NaN
47,False,Economics,,AAAGASMINTX-23DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMINTX,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2023,Lowest gas price in Texas in 2023?,KXAAAGASMINTX,2023-12-31T15:00:00Z,NaN
48,False,Economics,,AAAGASMINTX-24DEC31,2026-02-26T08:50:31.901806Z,False,KXAAAGASMINTX,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,In 2024,How low will gas prices in Texas get in 2024?,KXAAAGASMINTX,2024-12-31T15:00:00Z,NaN
49,False,Economics,,AAAGASW-23DEC04-US,2026-02-26T08:50:31.901806Z,False,KXAAAGASW,"[{'name': 'AAA', 'url': 'https://gasprices.aaa...",,"On Dec 4, 2023","US gas price up on Dec 4, 2023?",KXAAAGASW,2023-12-04T15:00:00Z,NaN

In [ ]:
df_economics_events.shape

(2840, 14)

## For each event, filter and get historical markets only.

In [ ]:
#for an event - historical markets

import time
import requests
import pandas as pd
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-historical-markets-by-event-colab/1.0"
})


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        if 500 <= resp.status_code < 600:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Server error {resp.status_code}. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        if resp.status_code >= 400:
            print("Bad request URL:", resp.url)
            print("Kalshi response:", resp.text)
            resp.raise_for_status()

        return resp.json()

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def paginate(path, collection_key, params=None, limit=200, sleep_s=0.25):
    params = dict(params or {})
    params["limit"] = limit

    rows = []
    cursor = None

    while True:
        if cursor:
            params["cursor"] = cursor
        else:
            params.pop("cursor", None)

        data = get_json(path, params=params)
        rows.extend(data.get(collection_key, []))

        cursor = data.get("cursor")
        if not cursor:
            break

        time.sleep(sleep_s)

    return rows


# df_economics_events should already exist from your previous step.
event_id_col = "event_ticker" if "event_ticker" in df_economics_events.columns else "ticker"

event_rows = (
    df_economics_events
    .dropna(subset=[event_id_col])
    .drop_duplicates(subset=[event_id_col])
    .reset_index(drop=True)
)

all_historical_markets = []
failed_events = []

print("Events to check:", len(event_rows))

for i, row in event_rows.iterrows():
    event_ticker = row[event_id_col]
    event_title = row.get("title")
    series_ticker = row.get("series_ticker", row.get("series_ticker_searched"))
    series_title = row.get("series_title")
    category = row.get("category", "Economics")

    print(f"[{i+1}/{len(event_rows)}] Getting historical markets for {event_ticker}...")

    try:
        historical_markets = paginate(
            "/historical/markets",
            "markets",
            params={
                "event_ticker": event_ticker
            },
            limit=200,
            sleep_s=0.25
        )

        for market in historical_markets:
            market["event_ticker_searched"] = event_ticker
            market["event_title"] = event_title
            market["series_ticker_searched"] = series_ticker
            market["series_title"] = series_title
            market["category"] = category

        all_historical_markets.extend(historical_markets)

    except requests.exceptions.HTTPError as e:
        print(f"Skipping {event_ticker}: {e}")
        failed_events.append(event_ticker)
        continue

    time.sleep(0.25)


df_historical_economics_markets = pd.DataFrame(all_historical_markets)

print("Historical market rows:", len(df_historical_economics_markets))
print("Failed events:", len(failed_events))

if not df_historical_economics_markets.empty:
    df_historical_economics_markets = (
        df_historical_economics_markets
        .drop_duplicates(subset=["ticker"])
        .sort_values("ticker")
        .reset_index(drop=True)
    )

    print("Unique historical market tickers:", len(df_historical_economics_markets))
    display(df_historical_economics_markets.head(50))

    df_historical_economics_markets.to_csv(
        "kalshi_historical_economics_markets_by_event.csv",
        index=False
    )

    df_historical_economics_market_tickers = df_historical_economics_markets[[
        c for c in [
            "ticker",
            "event_ticker",
            "event_ticker_searched",
            "event_title",
            "series_ticker",
            "series_ticker_searched",
            "series_title",
            "category",
            "title",
            "subtitle",
            "status",
            "open_time",
            "close_time",
            "expiration_time",
            "settlement_ts",
            "volume",
            "open_interest",
            "liquidity",
            "yes_bid",
            "yes_ask",
            "no_bid",
            "no_ask",
            "last_price"
        ]
        if c in df_historical_economics_markets.columns
    ]].copy()

    display(df_historical_economics_market_tickers.head(50))

    df_historical_economics_market_tickers.to_csv(
        "kalshi_historical_economics_market_tickers_by_event.csv",
        index=False
    )

if failed_events:
    df_failed_events = pd.DataFrame({"failed_event_ticker": failed_events})
    display(df_failed_events)
    df_failed_events.to_csv(
        "kalshi_failed_events_for_historical_markets.csv",
        index=False
    )

Events to check: 2840
[1/2840] Getting historical markets for AAAGASD-23OCT03-US...
[2/2840] Getting historical markets for AAAGASD-23OCT04-US...
[3/2840] Getting historical markets for AAAGASD-23OCT05-US...
[4/2840] Getting historical markets for AAAGASD-23OCT06-US...
[5/2840] Getting historical markets for AAAGASD-23OCT07-US...
[6/2840] Getting historical markets for AAAGASD-23OCT10-US...
[7/2840] Getting historical markets for AAAGASD-23OCT11-US...
[8/2840] Getting historical markets for AAAGASD-23OCT12-US...
[9/2840] Getting historical markets for AAAGASD-23OCT13-US...
[10/2840] Getting historical markets for AAAGASD-23OCT17-US...
[11/2840] Getting historical markets for AAAGASD-23OCT18-US...
[12/2840] Getting historical markets for AAAGASD-23OCT20-US...
[13/2840] Getting historical markets for AAAGASD-23SEP18-US...
[14/2840] Getting historical markets for AAAGASD-23SEP19-US...
[15/2840] Getting historical markets for AAAGASD-23SEP20-US...
[16/2840] Getting historical markets for AAAGASD-23SEP21-US...
[17/2840] Getting historical markets for AAAGASD-23SEP22-US...
[18/2840] Getting historical markets for AAAGASD-23SEP25-US...
[19/2840] Getting historical markets for AAAGASD-23SEP26-US...
[20/2840] Getting historical markets for AAAGASD-23SEP27-US...
[21/2840] Getting historical markets for AAAGASD-23SEP28-US...
[22/2840] Getting historical markets for AAAGASD-23SEP29-US...
[23/2840] Getting historical markets for AAAGASD-23SEP30-US...
[24/2840] Getting historical markets for AAAGASD-24MAY07-US...
[25/2840] Getting historical markets for AAAGASM-23DEC31-US...
[26/2840] Getting historical markets for AAAGASM-23NOV30-US...
[27/2840] Getting historical markets for AAAGASM-23OCT31-US...
[28/2840] Getting historical markets for AAAGASM-24APR30-US...
[29/2840] Getting historical markets for AAAGASM-24AUG31-US...
[30/2840] Getting historical markets for AAAGASM-24FEB29-US...
[31/2840] Getting historical markets for AAAGASM-24JAN31-US...
[32/2840] Getting historical markets for AAAGASM-24JUL31-US...
[33/2840] Getting historical markets for AAAGASM-24JUN30-US...
[34/2840] Getting historical markets for AAAGASM-24MAR31-US...
[35/2840] Getting historical markets for AAAGASM-24MAY31-US...
[36/2840] Getting historical markets for AAAGASM-24OCT31-US...
[37/2840] Getting historical markets for AAAGASM-24SEP30-US...
[38/2840] Getting historical markets for AAAGASMAX-23DEC31...
[39/2840] Getting historical markets for AAAGASMAX-24DEC31...
[40/2840] Getting historical markets for AAAGASMAXCA-23DEC31...
[41/2840] Getting historical markets for AAAGASMAXCA-24DEC31...
[42/2840] Getting historical markets for AAAGASMAXTX-23DEC31...
[43/2840] Getting historical markets for AAAGASMAXTX-24DEC31...
[44/2840] Getting historical markets for AAAGASMIN-23DEC31...
[45/2840] Getting historical markets for AAAGASMIN-24DEC31...
[46/2840] Getting historical markets for AAAGASMINCA-23DEC31...
[47/2840] Getting historical markets for AAAGASMINCA-24DEC31...
[48/2840] Getting historical markets for AAAGASMINTX-23DEC31...
[49/2840] Getting historical markets for AAAGASMINTX-24DEC31...
[50/2840] Getting historical markets for AAAGASW-23DEC04-US...
[51/2840] Getting historical markets for AAAGASW-23DEC18-US...
[52/2840] Getting historical markets for AAAGASW-23DEC25-US...
[53/2840] Getting historical markets for AAAGASW-23NOV13-US...
[54/2840] Getting historical markets for AAAGASW-23NOV20-US...
[55/2840] Getting historical markets for AAAGASW-23NOV27-US...
[56/2840] Getting historical markets for AAAGASW-23OCT09-US...
[57/2840] Getting historical markets for AAAGASW-23OCT16-US...
[58/2840] Getting historical markets for AAAGASW-23OCT23-US...
[59/2840] Getting historical markets for AAAGASW-24AUG05-US...
[60/2840] Getting historical markets for AAAGASW-24AUG12-US...
[61/2840] Getting historical markets for AAAGASW-24AUG19-US...
[62/2840] Getting historical markets for AAAGASW-24AUG26-US...
[63/2840] Getting historical markets for AAAGASW-24JAN01-US...
[64/2840] Getting historical markets for AAAGASW-24JAN08-US...
[65/2840] Getting historical markets for AAAGASW-24JUL01-US...
[66/2840] Getting historical markets for AAAGASW-24JUL08-US...
[67/2840] Getting historical markets for AAAGASW-24JUL15-US...
[68/2840] Getting historical markets for AAAGASW-24JUL22-US...
[69/2840] Getting historical markets for AAAGASW-24JUL29-US...
[70/2840] Getting historical markets for AAAGASW-24JUN03-US...
[71/2840] Getting historical markets for AAAGASW-24JUN10-US...
[72/2840] Getting historical markets for AAAGASW-24JUN17-US...
[73/2840] Getting historical markets for AAAGASW-24JUN24-US...
[74/2840] Getting historical markets for AAAGASW-24MAY13-US...
[75/2840] Getting historical markets for AAAGASW-24MAY20-US...
[76/2840] Getting historical markets for AAAGASW-24MAY27-US...
[77/2840] Getting historical markets for AAAGASW-24OCT07-US...
[78/2840] Getting historical markets for AAAGASW-24OCT14-US...
[79/2840] Getting historical markets for AAAGASW-24OCT21-US...
[80/2840] Getting historical markets for AAAGASW-24SEP02-US...
[81/2840] Getting historical markets for AAAGASW-24SEP09-US...
[82/2840] Getting historical markets for AAAGASW-24SEP16-US...
[83/2840] Getting historical markets for AAAGASW-24SEP23-US...
[84/2840] Getting historical markets for AAAGASW-24SEP30-US...
[85/2840] Getting historical markets for ACPI-2023...
[86/2840] Getting historical markets for ACPI-2024...
[87/2840] Getting historical markets for ACPI-22...
[88/2840] Getting historical markets for ACPICORE-2023...
[89/2840] Getting historical markets for ACPICORE-2024...
[90/2840] Getting historical markets for ARGINFLATIONM-24APR...
[91/2840] Getting historical markets for ARGINFLATIONM-24AUG...
[92/2840] Getting historical markets for ARGINFLATIONM-24FEB...
[93/2840] Getting historical markets for ARGINFLATIONM-24JAN...
[94/2840] Getting historical markets for ARGINFLATIONM-24JUL...
[95/2840] Getting historical markets for ARGINFLATIONM-24JUN...
[96/2840] Getting historical markets for ARGINFLATIONM-24MAR...
[97/2840] Getting historical markets for ARGINFLATIONM-24MAY...
[98/2840] Getting historical markets for ARGINFLATIONM-24OCT...
[99/2840] Getting historical markets for ARGINFLATIONM-24SEP...
[100/2840] Getting historical markets for BANKRUPTS-23DEC...
[101/2840] Getting historical markets for BANKRUPTS-23NOV...
[102/2840] Getting historical markets for BANKRUPTS-23OCT...
[103/2840] Getting historical markets for BANKRUPTS-24APR...
[104/2840] Getting historical markets for BANKRUPTS-24AUG...
[105/2840] Getting historical markets for BANKRUPTS-24FEB...
[106/2840] Getting historical markets for BANKRUPTS-24JAN...
[107/2840] Getting historical markets for BANKRUPTS-24JUL...
[108/2840] Getting historical markets for BANKRUPTS-24JUN...
[109/2840] Getting historical markets for BANKRUPTS-24MAR...
[110/2840] Getting historical markets for BANKRUPTS-24MAY...
[111/2840] Getting historical markets for BANKRUPTS-24OCT...
[112/2840] Getting historical markets for BANKRUPTS-24SEP...
[113/2840] Getting historical markets for BANKRUPTSY-24...
[114/2840] Getting historical markets for BOE-23FEB02...
[115/2840] Getting historical markets for BOE-23MAR23...
[116/2840] Getting historical markets for BOE-24AUG01...
[117/2840] Getting historical markets for BOE-24JUN20...
[118/2840] Getting historical markets for BOE-24MAY09...
[119/2840] Getting historical markets for BOE-24NOV07...
[120/2840] Getting historical markets for CHINAUSGDP...
[121/2840] Getting historical markets for CNGDP-21SEP30...
[122/2840] Getting historical markets for CNY-22DEC16...
[123/2840] Getting historical markets for COIN-23DEC31...
[124/2840] Getting historical markets for CPI-21AUG...
[125/2840] Getting historical markets for CPI-21DEC...
[126/2840] Getting historical markets for CPI-21JUL...
[127/2840] Getting historical markets for CPI-21JUN...
[128/2840] Getting historical markets for CPI-21NOV...
[129/2840] Getting historical markets for CPI-21OCT...
[130/2840] Getting historical markets for CPI-21SEP...
[131/2840] Getting historical markets for CPI-22APR...
[132/2840] Getting historical markets for CPI-22AUG...
[133/2840] Getting historical markets for CPI-22DEC...
[134/2840] Getting historical markets for CPI-22FEB...
[135/2840] Getting historical markets for CPI-22JAN...
[136/2840] Getting historical markets for CPI-22JUL...
[137/2840] Getting historical markets for CPI-22JUN...
[138/2840] Getting historical markets for CPI-22MAR...
[139/2840] Getting historical markets for CPI-22MAY...
[140/2840] Getting historical markets for CPI-22NOV...
[141/2840] Getting historical markets for CPI-22OCT...
[142/2840] Getting historical markets for CPI-22SEP...
[143/2840] Getting historical markets for CPI-23APR...
[144/2840] Getting historical markets for CPI-23AUG...
[145/2840] Getting historical markets for CPI-23DEC...
[146/2840] Getting historical markets for CPI-23FEB...
[147/2840] Getting historical markets for CPI-23JAN...
[148/2840] Getting historical markets for CPI-23JUL...
[149/2840] Getting historical markets for CPI-23JUN...
[150/2840] Getting historical markets for CPI-23MAR...
[151/2840] Getting historical markets for CPI-23MAY...
[152/2840] Getting historical markets for CPI-23NOV...
[153/2840] Getting historical markets for CPI-23OCT...
[154/2840] Getting historical markets for CPI-23SEP...
[155/2840] Getting historical markets for CPI-24APR...
[156/2840] Getting historical markets for CPI-24AUG...
[157/2840] Getting historical markets for CPI-24FEB...
[158/2840] Getting historical markets for CPI-24JAN...
[159/2840] Getting historical markets for CPI-24JUL...
[160/2840] Getting historical markets for CPI-24JUN...
[161/2840] Getting historical markets for CPI-24MAR...
[162/2840] Getting historical markets for CPI-24MAY...
[163/2840] Getting historical markets for CPI-24OCT...
[164/2840] Getting historical markets for CPI-24SEP...
[165/2840] Getting historical markets for CPIAPPAREL-23AUG...
[166/2840] Getting historical markets for CPIAPPAREL-23DEC...
[167/2840] Getting historical markets for CPIAPPAREL-23NOV...
[168/2840] Getting historical markets for CPIAPPAREL-23OCT...
[169/2840] Getting historical markets for CPIAPPAREL-23SEP...
[170/2840] Getting historical markets for CPIAPPAREL-24APR...
[171/2840] Getting historical markets for CPIAPPAREL-24AUG...
[172/2840] Getting historical markets for CPIAPPAREL-24FEB...
[173/2840] Getting historical markets for CPIAPPAREL-24JAN...
[174/2840] Getting historical markets for CPIAPPAREL-24JUL...
[175/2840] Getting historical markets for CPIAPPAREL-24JUN...
[176/2840] Getting historical markets for CPIAPPAREL-24MAR...
[177/2840] Getting historical markets for CPIAPPAREL-24MAY...
[178/2840] Getting historical markets for CPIAPPAREL-24OCT...
[179/2840] Getting historical markets for CPIAPPAREL-24SEP...
[180/2840] Getting historical markets for CPIAR-24...
[181/2840] Getting historical markets for CPICN-22...
[182/2840] Getting historical markets for CPICORE-22AUG...
[183/2840] Getting historical markets for CPICORE-22DEC...
[184/2840] Getting historical markets for CPICORE-22JUL...
[185/2840] Getting historical markets for CPICORE-22JUN...
[186/2840] Getting historical markets for CPICORE-22NOV...
[187/2840] Getting historical markets for CPICORE-22OCT...
[188/2840] Getting historical markets for CPICORE-22SEP...
[189/2840] Getting historical markets for CPICORE-23APR...
[190/2840] Getting historical markets for CPICORE-23AUG...
[191/2840] Getting historical markets for CPICORE-23DEC...
[192/2840] Getting historical markets for CPICORE-23FEB...
[193/2840] Getting historical markets for CPICORE-23JAN...
[194/2840] Getting historical markets for CPICORE-23JUL...
[195/2840] Getting historical markets for CPICORE-23JUN...
[196/2840] Getting historical markets for CPICORE-23MAR...
[197/2840] Getting historical markets for CPICORE-23MAY...
[198/2840] Getting historical markets for CPICORE-23NOV...
[199/2840] Getting historical markets for CPICORE-23OCT...
[200/2840] Getting historical markets for CPICORE-23SEP...
[201/2840] Getting historical markets for CPICORE-24APR...
[202/2840] Getting historical markets for CPICORE-24AUG...
[203/2840] Getting historical markets for CPICORE-24FEB...
[204/2840] Getting historical markets for CPICORE-24JAN...
[205/2840] Getting historical markets for CPICORE-24JUL...
[206/2840] Getting historical markets for CPICORE-24JUN...
[207/2840] Getting historical markets for CPICORE-24MAR...
[208/2840] Getting historical markets for CPICORE-24MAY...
[209/2840] Getting historical markets for CPICORE-24OCT...
[210/2840] Getting historical markets for CPICORE-24SEP...
[211/2840] Getting historical markets for CPICOREYOY-22DEC...
[212/2840] Getting historical markets for CPICOREYOY-23APR...
[213/2840] Getting historical markets for CPICOREYOY-23AUG...
[214/2840] Getting historical markets for CPICOREYOY-23DEC...
[215/2840] Getting historical markets for CPICOREYOY-23FEB...
[216/2840] Getting historical markets for CPICOREYOY-23JAN...
[217/2840] Getting historical markets for CPICOREYOY-23JUL...
[218/2840] Getting historical markets for CPICOREYOY-23JUN...
[219/2840] Getting historical markets for CPICOREYOY-23MAR...
[220/2840] Getting historical markets for CPICOREYOY-23MAY...
[221/2840] Getting historical markets for CPICOREYOY-23NOV...
[222/2840] Getting historical markets for CPICOREYOY-23OCT...
[223/2840] Getting historical markets for CPICOREYOY-23SEP...
[224/2840] Getting historical markets for CPICOREYOY-24APR...
[225/2840] Getting historical markets for CPICOREYOY-24AUG...
[226/2840] Getting historical markets for CPICOREYOY-24FEB...
[227/2840] Getting historical markets for CPICOREYOY-24JAN...
[228/2840] Getting historical markets for CPICOREYOY-24JUL...
[229/2840] Getting historical markets for CPICOREYOY-24JUN...
[230/2840] Getting historical markets for CPICOREYOY-24MAR...
[231/2840] Getting historical markets for CPICOREYOY-24MAY...
[232/2840] Getting historical markets for CPICOREYOY-24OCT...
[233/2840] Getting historical markets for CPICOREYOY-24SEP...
[234/2840] Getting historical markets for CPIDELAY...
[235/2840] Getting historical markets for CPIEU-22...
[236/2840] Getting historical markets for CPIFOOD-23AUG...
[237/2840] Getting historical markets for CPIFOOD-23DEC...
[238/2840] Getting historical markets for CPIFOOD-23NOV...
[239/2840] Getting historical markets for CPIFOOD-23OCT...
[240/2840] Getting historical markets for CPIFOOD-23SEP...
[241/2840] Getting historical markets for CPIFOOD-24APR...
[242/2840] Getting historical markets for CPIFOOD-24AUG...
[243/2840] Getting historical markets for CPIFOOD-24FEB...
[244/2840] Getting historical markets for CPIFOOD-24JAN...
[245/2840] Getting historical markets for CPIFOOD-24JUL...
[246/2840] Getting historical markets for CPIFOOD-24JUN...
[247/2840] Getting historical markets for CPIFOOD-24MAR...
[248/2840] Getting historical markets for CPIFOOD-24MAY...
[249/2840] Getting historical markets for CPIFOOD-24OCT...
[250/2840] Getting historical markets for CPIFOOD-24SEP...
[251/2840] Getting historical markets for CPIGAS-23DEC...
[252/2840] Getting historical markets for CPIGAS-24APR...
[253/2840] Getting historical markets for CPIGAS-24AUG...
[254/2840] Getting historical markets for CPIGAS-24FEB...
[255/2840] Getting historical markets for CPIGAS-24JAN...
[256/2840] Getting historical markets for CPIGAS-24JUL...
[257/2840] Getting historical markets for CPIGAS-24JUN...
[258/2840] Getting historical markets for CPIGAS-24MAR...
[259/2840] Getting historical markets for CPIGAS-24MAY...
[260/2840] Getting historical markets for CPIGAS-24OCT...
[261/2840] Getting historical markets for CPIGAS-24SEP...
[262/2840] Getting historical markets for CPISHELTER-23DEC...
[263/2840] Getting historical markets for CPISHELTER-24APR...
[264/2840] Getting historical markets for CPISHELTER-24AUG...
[265/2840] Getting historical markets for CPISHELTER-24FEB...
[266/2840] Getting historical markets for CPISHELTER-24JAN...
[267/2840] Getting historical markets for CPISHELTER-24JUL...
[268/2840] Getting historical markets for CPISHELTER-24JUN...
[269/2840] Getting historical markets for CPISHELTER-24MAR...
[270/2840] Getting historical markets for CPISHELTER-24MAY...
[271/2840] Getting historical markets for CPISHELTER-24OCT...
[272/2840] Getting historical markets for CPISHELTER-24SEP...
[273/2840] Getting historical markets for CPIUSEDCAR-23DEC...
[274/2840] Getting historical markets for CPIUSEDCAR-23NOV...
[275/2840] Getting historical markets for CPIUSEDCAR-23OCT...
[276/2840] Getting historical markets for CPIUSEDCAR-23SEP...
[277/2840] Getting historical markets for CPIUSEDCAR-24APR...
[278/2840] Getting historical markets for CPIUSEDCAR-24AUG...
[279/2840] Getting historical markets for CPIUSEDCAR-24FEB...
[280/2840] Getting historical markets for CPIUSEDCAR-24JAN...
[281/2840] Getting historical markets for CPIUSEDCAR-24JUL...
[282/2840] Getting historical markets for CPIUSEDCAR-24JUN...
[283/2840] Getting historical markets for CPIUSEDCAR-24MAR...
[284/2840] Getting historical markets for CPIUSEDCAR-24MAY...
[285/2840] Getting historical markets for CPIUSEDCAR-24OCT...
[286/2840] Getting historical markets for CPIUSEDCAR-24SEP...
[287/2840] Getting historical markets for CPIYOY-22DEC...
[288/2840] Getting historical markets for CPIYOY-22NOV...
[289/2840] Getting historical markets for CPIYOY-23APR...
[290/2840] Getting historical markets for CPIYOY-23AUG...
[291/2840] Getting historical markets for CPIYOY-23DEC...
[292/2840] Getting historical markets for CPIYOY-23FEB...
[293/2840] Getting historical markets for CPIYOY-23JAN...
[294/2840] Getting historical markets for CPIYOY-23JUL...
[295/2840] Getting historical markets for CPIYOY-23JUN...
[296/2840] Getting historical markets for CPIYOY-23MAR...
[297/2840] Getting historical markets for CPIYOY-23MAY...
[298/2840] Getting historical markets for CPIYOY-23NOV...
[299/2840] Getting historical markets for CPIYOY-23OCT...
[300/2840] Getting historical markets for CPIYOY-23SEP...
[301/2840] Getting historical markets for CPIYOY-24APR...
[302/2840] Getting historical markets for CPIYOY-24AUG...
[303/2840] Getting historical markets for CPIYOY-24FEB...
[304/2840] Getting historical markets for CPIYOY-24JAN...
[305/2840] Getting historical markets for CPIYOY-24JUL...
[306/2840] Getting historical markets for CPIYOY-24JUN...
[307/2840] Getting historical markets for CPIYOY-24MAR...
[308/2840] Getting historical markets for CPIYOY-24MAY...
[309/2840] Getting historical markets for CPIYOY-24OCT...
[310/2840] Getting historical markets for CPIYOY-24SEP...
[311/2840] Getting historical markets for CREDEF-23-Q2...
[312/2840] Getting historical markets for CREDEF-23-Q3...
[313/2840] Getting historical markets for CREDEF-23-Q4...
[314/2840] Getting historical markets for CREDEF-24-Q1...
[315/2840] Getting historical markets for CREDEF-24-Q2...
[316/2840] Getting historical markets for CREDEF-24-Q3...
[317/2840] Getting historical markets for CREDEF-24-Q4...
[318/2840] Getting historical markets for CREDEFMAX-24-Q4...
[319/2840] Getting historical markets for CREDITC-23DEC31...
[320/2840] Getting historical markets for CREDITC-24DEC31...
[321/2840] Getting historical markets for CREDITCDEF-23-Q2...
[322/2840] Getting historical markets for CREDITCDEF-23-Q3...
[323/2840] Getting historical markets for CREDITCDEF-23-Q4...
[324/2840] Getting historical markets for CREDITCDEF-24-Q1...
[325/2840] Getting historical markets for CREDITCDEF-24-Q2...
[326/2840] Getting historical markets for CREDITCDEF-24-Q3...
[327/2840] Getting historical markets for CREDITRATING-23DEC31...
[328/2840] Getting historical markets for CREDITRATING-24DEC31...
[329/2840] Getting historical markets for DEFAULT-23DEC31...
[330/2840] Getting historical markets for DEFAULT-24DEC31...
[331/2840] Getting historical markets for DIESEL-22DEC05...
[332/2840] Getting historical markets for DIESEL-22DEC12...

,can_close_early,close_time,created_time,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,fractional_trading_enabled,last_price_dollars,...,event_ticker_searched,event_title,series_ticker_searched,series_title,category,early_close_condition,fee_waiver_expiration_time,cap_strike,custom_strike,occurrence_datetime
0,True,2023-10-03T13:51:29.310828Z,2023-10-02T13:35:13.614692Z,AAAGASD-23OCT03-US,2023-10-04T14:00:00Z,2023-10-10T14:00:00Z,3.798,3.814,True,0.0000,...,AAAGASD-23OCT03-US,"US gas price up on Oct 3, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
1,True,2023-10-04T13:55:00Z,2023-10-03T13:45:56.854722Z,AAAGASD-23OCT04-US,2023-10-05T14:00:00Z,2023-10-11T14:00:00Z,3.785,3.798,True,0.0000,...,AAAGASD-23OCT04-US,"US gas price up on Oct 4, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
2,True,2023-10-05T13:55:00Z,2023-10-04T13:52:19.965144Z,AAAGASD-23OCT05-US,2023-10-06T14:00:00Z,2023-10-12T14:00:00Z,3.768,3.785,True,0.1100,...,AAAGASD-23OCT05-US,"US gas price up on Oct 5, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
3,True,2023-10-06T13:55:00Z,2023-10-05T13:53:23.418309Z,AAAGASD-23OCT06-US,2023-10-07T14:00:00Z,2023-10-13T14:00:00Z,3.746,3.768,True,0.0300,...,AAAGASD-23OCT06-US,"US gas price up on Oct 6, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
4,True,2023-10-07T13:55:00Z,2023-10-06T13:58:10.71795Z,AAAGASD-23OCT07-US,2023-10-08T14:00:00Z,2023-10-14T14:00:00Z,3.722,3.746,True,0.0000,...,AAAGASD-23OCT07-US,"US gas price up on Oct 7, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
5,True,2023-10-10T13:55:00Z,2023-10-09T14:04:05.744661Z,AAAGASD-23OCT10-US,2023-10-11T14:00:00Z,2023-10-17T14:00:00Z,3.682,3.704,True,0.1000,...,AAAGASD-23OCT10-US,"US gas price up on Oct 10, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
6,True,2023-10-11T13:55:00Z,2023-10-10T13:41:52.799917Z,AAAGASD-23OCT11-US,2023-10-12T14:00:00Z,2023-10-18T14:00:00Z,3.663,3.682,True,0.1200,...,AAAGASD-23OCT11-US,"US gas price up on Oct 11, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
7,True,2023-10-12T13:55:00Z,2023-10-11T13:57:37.582919Z,AAAGASD-23OCT12-US,2023-10-13T14:00:00Z,2023-10-19T14:00:00Z,3.646,3.663,True,0.0000,...,AAAGASD-23OCT12-US,"US gas price up on Oct 12, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
8,True,2023-10-13T13:55:00Z,2023-10-12T13:48:27.1847Z,AAAGASD-23OCT13-US,2023-10-14T14:00:00Z,2023-10-20T14:00:00Z,3.628,3.646,True,0.0000,...,AAAGASD-23OCT13-US,"US gas price up on Oct 13, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
9,True,2023-10-17T13:55:00Z,2023-10-16T15:05:20.510785Z,AAAGASD-23OCT17-US,2023-10-18T14:00:00Z,2023-10-24T14:00:00Z,3.584,3.600,True,0.5000,...,AAAGASD-23OCT17-US,"US gas price up on Oct 17, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
10,True,2023-10-18T13:55:00Z,2023-10-17T14:04:54.823994Z,AAAGASD-23OCT18-US,2023-10-19T14:00:00Z,2023-10-25T14:00:00Z,3.575,3.584,True,0.0300,...,AAAGASD-23OCT18-US,"US gas price up on Oct 18, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
11,True,2023-10-20T13:55:00Z,2023-10-19T13:41:46.564103Z,AAAGASD-23OCT20-US,2023-10-21T14:00:00Z,2023-10-27T14:00:00Z,3.558,3.565,True,0.0300,...,AAAGASD-23OCT20-US,"US gas price up on Oct 20, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
12,True,2023-09-18T13:55:00Z,2023-09-15T16:25:46.961878Z,AAAGASD-23SEP18-US,2023-09-19T14:00:00Z,2023-09-25T14:00:00Z,3.880,3.866,True,0.9500,...,AAAGASD-23SEP18-US,"US gas price up on Sep 18, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
13,True,2023-09-19T13:55:00Z,2023-09-18T14:25:01.953956Z,AAAGASD-23SEP19-US,2023-09-20T14:00:00Z,2023-09-26T14:00:00Z,3.881,3.881,True,0.2900,...,AAAGASD-23SEP19-US,"US gas price up on Sep 19, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
14,True,2023-09-20T13:55:00Z,2023-09-19T14:06:24.963495Z,AAAGASD-23SEP20-US,2023-09-21T14:00:00Z,2023-09-27T14:00:00Z,3.875,3.880,True,0.0100,...,AAAGASD-23SEP20-US,"US gas price up on Sep 20, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
15,True,2023-09-21T13:55:00Z,2023-09-20T16:30:12.238254Z,AAAGASD-23SEP21-US,2023-09-22T14:00:00Z,2023-09-28T14:00:00Z,3.867,3.875,True,0.0000,...,AAAGASD-23SEP21-US,"US gas price up on Sep 21, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
16,True,2023-09-22T13:55:00Z,2023-09-21T13:56:45.584389Z,AAAGASD-23SEP22-US,2023-09-23T14:00:00Z,2023-09-29T14:00:00Z,3.859,3.867,True,0.0900,...,AAAGASD-23SEP22-US,"US gas price up on Sep 22, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
17,True,2023-09-25T13:55:00Z,2023-09-22T15:10:15.689662Z,AAAGASD-23SEP25-US,2023-09-26T14:00:00Z,2023-10-02T14:00:00Z,3.849,3.859,True,0.0500,...,AAAGASD-23SEP25-US,"US gas price up on Sep 25, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
18,True,2023-09-26T13:55:00Z,2023-09-25T13:52:56.241157Z,AAAGASD-23SEP26-US,2023-09-27T14:00:00Z,2023-10-03T14:00:00Z,3.838,3.849,True,0.6900,...,AAAGASD-23SEP26-US,"US gas price up on Sep 26, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
19,True,2023-09-27T13:54:16.215519Z,2023-09-26T13:40:40.898823Z,AAAGASD-23SEP27-US,2023-09-28T14:00:00Z,2023-10-04T14:00:00Z,3.832,3.838,True,0.0000,...,AAAGASD-23SEP27-US,"US gas price up on Sep 27, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
20,True,2023-09-28T13:55:00Z,2023-09-27T13:48:14.375589Z,AAAGASD-23SEP28-US,2023-09-29T14:00:00Z,2023-10-05T14:00:00Z,3.835,3.832,True,0.6000,...,AAAGASD-23SEP28-US,"US gas price up on Sep 28, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
21,True,2023-09-29T13:55:00Z,2023-09-28T13:55:18.570593Z,AAAGASD-23SEP29-US,2023-09-30T14:00:00Z,2023-10-06T14:00:00Z,3.832,3.835,True,0.1100,...,AAAGASD-23SEP29-US,"US gas price up on Sep 29, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
22,True,2023-09-30T13:55:00Z,2023-09-29T14:55:17.081933Z,AAAGASD-23SEP30-US,2023-10-01T14:00:00Z,2023-10-07T14:00:00Z,3.823,3.832,True,0.0100,...,AAAGASD-23SEP30-US,"US gas price up on Sep 30, 2023?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
23,True,2024-05-07T03:59:00Z,2024-05-06T14:33:42.272172Z,AAAGASD-24MAY07-US,2024-05-07T14:00:00Z,2024-05-14T14:00:00Z,3.640,3.651,True,0.0000,...,AAAGASD-24MAY07-US,"Gas prices up on May 7, 2024?",KXAAAGASD,None,Economics,NaN,NaN,NaN,NaN,NaN
24,True,2023-12-31T14:55:00Z,2023-12-01T15:07:55.301846Z,AAAGASM-23DEC31-US,2024-01-01T15:00:00Z,2024-01-07T15:00:00Z,3.112,3.246,True,0.0200,...,AAAGASM-23DEC31-US,Gas prices up in the US in Dec 2023?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
25,True,2023-12-01T04:59:00Z,2023-11-02T19:07:00.558851Z,AAAGASM-23NOV30-US,2023-12-02T04:59:00Z,2023-12-08T04:59:00Z,3.246,3.478,True,0.1000,...,AAAGASM-23NOV30-US,US gas price up in Nov 2023?,KXAAAGASW,None,Economics,NaN,NaN,NaN,NaN,NaN
26,True,2023-10-31T13:55:00Z,2023-10-24T15:27:22.959158Z,AAAGASM-23OCT31-US,2023-11-01T14:00:00Z,2023-11-07T14:00:00Z,3.478,3.530,True,0.0100,...,AAAGASM-23OCT31-US,US gas price up in Oct 2023?,KXAAAGASW,None,Economics,NaN,NaN,NaN,NaN,NaN
27,True,2024-04-30T13:55:00Z,2024-03-31T12:42:50.135304Z,AAAGASM-24APR30-US,2024-05-01T14:00:00Z,2024-05-07T14:00:00Z,3.657,3.690,True,0.0100,...,AAAGASM-24APR30-US,Gas prices in the US in Apr 2024?,KXAAAGASM,None,Economics,.,NaN,NaN,NaN,NaN
28,True,2024-08-31T03:59:00Z,2024-07-29T16:36:36.966369Z,AAAGASM-24AUG31-US,2024-08-31T14:00:00Z,2024-09-07T14:00:00Z,3.339,3.250,True,0.8000,...,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
29,True,2024-08-31T03:59:00Z,2024-07-29T16:36:36.966369Z,AAAGASM-24AUG31-US,2024-08-31T14:00:00Z,2024-09-07T14:00:00Z,3.339,3.300,True,0.9200,...,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
30,True,2024-08-31T03:59:00Z,2024-07-29T16:36:36.966369Z,AAAGASM-24AUG31-US,2024-08-31T14:00:00Z,2024-09-07T14:00:00Z,3.339,3.350,True,0.1000,...,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
31,True,2024-08-31T03:59:00Z,2024-07-29T16:36:36.966369Z,AAAGASM-24AUG31-US,2024-08-31T14:00:00Z,2024-09-07T14:00:00Z,3.339,3.400,True,0.0900,...,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
32,True,2024-08-31T03:59:00Z,2024-07-29T16:36:36.966369Z,AAAGASM-24AUG31-US,2024-08-31T14:00:00Z,2024-09-07T14:00:00Z,3.339,3.450,True,0.0100,...,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
33,True,2024-08-31T03:59:00Z,2024-07-29T16:36:36.966369Z,AAAGASM-24AUG31-US,2024-08-31T14:00:00Z,2024-09-07T14:00:00Z,3.339,3.500,True,0.0100,...,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
34,True,2024-08-31T03:59:00Z,2024-07-29T16:36:36.966369Z,AAAGASM-24AUG31-US,2024-08-31T14:00:00Z,2024-09-07T14:00:00Z,3.339,3.550,True,0.0100,...,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
35,True,2024-08-31T03:59:00Z,2024-07-29T16:36:36.966369Z,AAAGASM-24AUG31-US,2024-08-31T14:00:00Z,2024-09-07T14:00:00Z,3.339,3.600,True,0.0100,...,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
36,True,2024-08-31T03:59:00Z,2024-07-29T16:36:36.96637Z,AAAGASM-24AUG31-US,2024-08-31T14:00:00Z,2024-09-07T14:00:00Z,3.339,3.650,True,0.0100,...,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
37,True,2024-08-31T03:59:00Z,2024-07-29T16:36:36.96637Z,AAAGASM-24AUG31-US,2024-08-31T14:00:00Z,2024-09-07T14:00:00Z,3.339,3.700,True,0.0100,...,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
38,True,2024-02-29T14:55:00Z,2024-01-31T14:51:29.052361Z,AAAGASM-24FEB29-US,2024-03-01T15:00:00Z,2024-03-07T15:00:00Z,3.319,3.291,True,0.8600,...,AAAGASM-24FEB29-US,Gas prices in the US in Feb 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
39,True,2024-01-31T14:55:00Z,2024-01-04T14:31:02.385212Z,AAAGASM-24JAN31-US,2024-02-01T15:00:00Z,2024-02-07T15:00:00Z,3.141,3.112,True,0.0100,...,AAAGASM-24JAN31-US,Gas prices in the US in Jan 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
40,True,2024-07-31T03:59:00Z,2024-06-21T14:56:15.438455Z,AAAGASM-24JUL31-US,2024-07-31T14:00:00Z,2024-08-07T14:00:00Z,3.492,3.250,True,0.9900,...,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
41,True,2024-07-31T03:59:00Z,2024-06-21T14:56:15.438455Z,AAAGASM-24JUL31-US,2024-07-31T14:00:00Z,2024-08-07T14:00:00Z,3.492,3.300,True,0.9900,...,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
42,True,2024-07-31T03:59:00Z,2024-06-21T14:56:15.438455Z,AAAGASM-24JUL31-US,2024-07-31T14:00:00Z,2024-08-07T14:00:00Z,3.492,3.350,True,0.9900,...,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
43,True,2024-07-31T03:59:00Z,2024-06-21T14:56:15.438455Z,AAAGASM-24JUL31-US,2024-07-31T14:00:00Z,2024-08-07T14:00:00Z,3.492,3.400,True,0.9900,...,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
44,True,2024-07-31T03:59:00Z,2024-06-21T14:56:15.438455Z,AAAGASM-24JUL31-US,2024-07-31T14:00:00Z,2024-08-07T14:00:00Z,3.492,3.450,True,0.9100,...,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
45,True,2024-07-31T03:59:00Z,2024-06-21T14:56:15.438455Z,AAAGASM-24JUL31-US,2024-07-31T14:00:00Z,2024-08-07T14:00:00Z,3.492,3.500,True,0.3800,...,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
46,True,2024-07-31T03:59:00Z,2024-06-21T14:56:15.438455Z,AAAGASM-24JUL31-US,2024-07-31T14:00:00Z,2024-08-07T14:00:00Z,3.492,3.550,True,0.0100,...,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
47,True,2024-07-31T03:59:00Z,2024-06-21T14:56:15.438455Z,AAAGASM-24JUL31-US,2024-07-31T14:00:00Z,2024-08-07T14:00:00Z,3.492,3.600,True,0.0100,...,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
48,True,2024-07-31T03:59:00Z,2024-07-01T17:37:56.96218Z,AAAGASM-24JUL31-US,2024-07-31T14:00:00Z,2024-08-07T14:00:00Z,3.492,3.650,True,0.0100,...,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN
49,True,2024-07-31T03:59:00Z,2024-07-01T17:38:13.753306Z,AAAGASM-24JUL31-US,2024-07-31T14:00:00Z,2024-08-07T14:00:00Z,3.492,3.700,True,0.0100,...,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,NaN,NaN,NaN,NaN,NaN

,ticker,event_ticker,event_ticker_searched,event_title,series_ticker_searched,series_title,category,title,subtitle,status,open_time,close_time,expiration_time,settlement_ts
0,AAAGASD-23OCT03-US-3.814,AAAGASD-23OCT03-US,AAAGASD-23OCT03-US,"US gas price up on Oct 3, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.814?,>$3.814,finalized,2023-10-02T14:00:00Z,2023-10-03T13:51:29.310828Z,2023-10-10T14:00:00Z,2023-10-03T15:01:00.388905Z
1,AAAGASD-23OCT04-US-3.798,AAAGASD-23OCT04-US,AAAGASD-23OCT04-US,"US gas price up on Oct 4, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.798?,>$3.798,finalized,2023-10-03T14:00:00Z,2023-10-04T13:55:00Z,2023-10-11T14:00:00Z,2023-10-04T15:15:00.329165Z
2,AAAGASD-23OCT05-US-3.785,AAAGASD-23OCT05-US,AAAGASD-23OCT05-US,"US gas price up on Oct 5, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.785?,>$3.785,finalized,2023-10-04T14:00:00Z,2023-10-05T13:55:00Z,2023-10-12T14:00:00Z,2023-10-05T15:03:00.543954Z
3,AAAGASD-23OCT06-US-3.768,AAAGASD-23OCT06-US,AAAGASD-23OCT06-US,"US gas price up on Oct 6, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.768?,>$3.768,finalized,2023-10-05T14:00:00Z,2023-10-06T13:55:00Z,2023-10-13T14:00:00Z,2023-10-06T18:52:00.869807Z
4,AAAGASD-23OCT07-US-3.746,AAAGASD-23OCT07-US,AAAGASD-23OCT07-US,"US gas price up on Oct 7, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.746?,>$3.746,finalized,2023-10-06T14:00:00Z,2023-10-07T13:55:00Z,2023-10-14T14:00:00Z,2023-10-09T16:19:00.490268Z
5,AAAGASD-23OCT10-US-3.704,AAAGASD-23OCT10-US,AAAGASD-23OCT10-US,"US gas price up on Oct 10, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.704?,>$3.704,finalized,2023-10-09T14:05:00Z,2023-10-10T13:55:00Z,2023-10-17T14:00:00Z,2023-10-11T23:22:00.365814Z
6,AAAGASD-23OCT11-US-3.682,AAAGASD-23OCT11-US,AAAGASD-23OCT11-US,"US gas price up on Oct 11, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.682?,>$3.682,finalized,2023-10-10T14:00:00Z,2023-10-11T13:55:00Z,2023-10-18T14:00:00Z,2023-10-11T23:22:00.381093Z
7,AAAGASD-23OCT12-US-3.663,AAAGASD-23OCT12-US,AAAGASD-23OCT12-US,"US gas price up on Oct 12, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.663?,>$3.663,finalized,2023-10-11T14:00:00Z,2023-10-12T13:55:00Z,2023-10-19T14:00:00Z,2023-10-12T16:22:00.630388Z
8,AAAGASD-23OCT13-US-3.646,AAAGASD-23OCT13-US,AAAGASD-23OCT13-US,"US gas price up on Oct 13, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.646?,>$3.646,finalized,2023-10-12T14:00:00Z,2023-10-13T13:55:00Z,2023-10-20T14:00:00Z,2023-10-13T22:07:00.812829Z
9,AAAGASD-23OCT17-US-3.600,AAAGASD-23OCT17-US,AAAGASD-23OCT17-US,"US gas price up on Oct 17, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.600?,>$3.600,finalized,2023-10-16T15:10:00Z,2023-10-17T13:55:00Z,2023-10-24T14:00:00Z,2023-10-17T22:19:00.332769Z
10,AAAGASD-23OCT18-US-3.584,AAAGASD-23OCT18-US,AAAGASD-23OCT18-US,"US gas price up on Oct 18, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.584?,>$3.584,finalized,2023-10-17T14:05:00Z,2023-10-18T13:55:00Z,2023-10-25T14:00:00Z,2023-10-19T01:16:00.688472Z
11,AAAGASD-23OCT20-US-3.565,AAAGASD-23OCT20-US,AAAGASD-23OCT20-US,"US gas price up on Oct 20, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.565?,>$3.565,finalized,2023-10-19T14:00:00Z,2023-10-20T13:55:00Z,2023-10-27T14:00:00Z,2023-12-08T02:06:00.397683Z
12,AAAGASD-23SEP18-US-3.866,AAAGASD-23SEP18-US,AAAGASD-23SEP18-US,"US gas price up on Sep 18, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.866?,>$3.866,finalized,2023-09-15T17:00:00Z,2023-09-18T13:55:00Z,2023-09-25T14:00:00Z,2023-09-19T17:37:00.411814Z
13,AAAGASD-23SEP19-US-3.881,AAAGASD-23SEP19-US,AAAGASD-23SEP19-US,"US gas price up on Sep 19, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.881?,>$3.881,finalized,2023-09-18T14:30:00Z,2023-09-19T13:55:00Z,2023-09-26T14:00:00Z,2023-09-20T18:47:00.392221Z
14,AAAGASD-23SEP20-US-3.880,AAAGASD-23SEP20-US,AAAGASD-23SEP20-US,"US gas price up on Sep 20, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.880?,>$3.880,finalized,2023-09-19T14:15:00Z,2023-09-20T13:55:00Z,2023-09-27T14:00:00Z,2023-12-08T02:08:00.388014Z
15,AAAGASD-23SEP21-US-3.875,AAAGASD-23SEP21-US,AAAGASD-23SEP21-US,"US gas price up on Sep 21, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.875?,>$3.875,finalized,2023-09-20T16:30:00Z,2023-09-21T13:55:00Z,2023-09-28T14:00:00Z,2023-09-21T17:20:00.782641Z
16,AAAGASD-23SEP22-US-3.867,AAAGASD-23SEP22-US,AAAGASD-23SEP22-US,"US gas price up on Sep 22, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.867?,>$3.867,finalized,2023-09-21T14:00:00Z,2023-09-22T13:55:00Z,2023-09-29T14:00:00Z,2023-09-22T17:03:00.581167Z
17,AAAGASD-23SEP25-US-3.859,AAAGASD-23SEP25-US,AAAGASD-23SEP25-US,"US gas price up on Sep 25, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.859?,>$3.859,finalized,2023-09-22T15:15:00Z,2023-09-25T13:55:00Z,2023-10-02T14:00:00Z,2023-09-25T21:24:00.305716Z
18,AAAGASD-23SEP26-US-3.849,AAAGASD-23SEP26-US,AAAGASD-23SEP26-US,"US gas price up on Sep 26, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.849?,>$3.849,finalized,2023-09-25T14:00:00Z,2023-09-26T13:55:00Z,2023-10-03T14:00:00Z,2023-09-26T17:06:00.841487Z
19,AAAGASD-23SEP27-US-3.838,AAAGASD-23SEP27-US,AAAGASD-23SEP27-US,"US gas price up on Sep 27, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.838?,>$3.838,finalized,2023-09-26T14:00:00Z,2023-09-27T13:54:16.215519Z,2023-10-04T14:00:00Z,2023-09-27T16:02:00.359268Z
20,AAAGASD-23SEP28-US-3.832,AAAGASD-23SEP28-US,AAAGASD-23SEP28-US,"US gas price up on Sep 28, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.832?,>$3.832,finalized,2023-09-27T14:00:00Z,2023-09-28T13:55:00Z,2023-10-05T14:00:00Z,2023-09-28T16:03:00.50386Z
21,AAAGASD-23SEP29-US-3.835,AAAGASD-23SEP29-US,AAAGASD-23SEP29-US,"US gas price up on Sep 29, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.835?,>$3.835,finalized,2023-09-28T14:00:00Z,2023-09-29T13:55:00Z,2023-10-06T14:00:00Z,2023-09-29T16:28:00.649511Z
22,AAAGASD-23SEP30-US-3.832,AAAGASD-23SEP30-US,AAAGASD-23SEP30-US,"US gas price up on Sep 30, 2023?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.832?,>$3.832,finalized,2023-09-29T15:00:00Z,2023-09-30T13:55:00Z,2023-10-07T14:00:00Z,2023-10-02T22:14:00.738738Z
23,AAAGASD-24MAY07-US-3.651,AAAGASD-24MAY07-US,AAAGASD-24MAY07-US,"Gas prices up on May 7, 2024?",KXAAAGASD,None,Economics,Will average **gas prices** be above $3.651?,3.651,finalized,2024-05-06T15:00:00Z,2024-05-07T03:59:00Z,2024-05-14T14:00:00Z,2024-05-14T18:26:00.220776Z
24,AAAGASM-23DEC31-US-3.246,AAAGASM-23DEC31-US,AAAGASM-23DEC31-US,Gas prices up in the US in Dec 2023?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.246?,>$3.246,finalized,2023-12-01T15:10:00Z,2023-12-31T14:55:00Z,2024-01-07T15:00:00Z,2024-01-02T02:02:00.949906Z
25,AAAGASM-23NOV30-US-3.478,AAAGASM-23NOV30-US,AAAGASM-23NOV30-US,US gas price up in Nov 2023?,KXAAAGASW,None,Economics,Will average **gas prices** be above $3.478?,3.478,finalized,2023-11-02T19:15:00Z,2023-12-01T04:59:00Z,2023-12-08T04:59:00Z,2023-12-08T14:29:00.235914Z
26,AAAGASM-23OCT31-US-3.53,AAAGASM-23OCT31-US,AAAGASM-23OCT31-US,US gas price up in Oct 2023?,KXAAAGASW,None,Economics,Will average **gas prices** be above $3.53?,$3.53,finalized,2023-10-24T15:30:00Z,2023-10-31T13:55:00Z,2023-11-07T14:00:00Z,2023-11-02T18:07:00.736223Z
27,AAAGASM-24APR30-US-3.69,AAAGASM-24APR30-US,AAAGASM-24APR30-US,Gas prices in the US in Apr 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.69?,3.69,finalized,2024-03-31T14:00:00Z,2024-04-30T13:55:00Z,2024-05-07T14:00:00Z,2024-04-30T16:10:00.953321Z
28,AAAGASM-24AUG31-US-3.25,AAAGASM-24AUG31-US,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.25?,3.25,finalized,2024-07-29T17:00:00Z,2024-08-31T03:59:00Z,2024-09-07T14:00:00Z,2024-09-02T13:13:00.650908Z
29,AAAGASM-24AUG31-US-3.30,AAAGASM-24AUG31-US,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.30?,3.30,finalized,2024-07-29T17:00:00Z,2024-08-31T03:59:00Z,2024-09-07T14:00:00Z,2024-09-02T13:12:00.780732Z
30,AAAGASM-24AUG31-US-3.35,AAAGASM-24AUG31-US,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.35?,3.35,finalized,2024-07-29T17:00:00Z,2024-08-31T03:59:00Z,2024-09-07T14:00:00Z,2024-09-02T13:12:00.8008Z
31,AAAGASM-24AUG31-US-3.40,AAAGASM-24AUG31-US,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.40?,3.40,finalized,2024-07-29T17:00:00Z,2024-08-31T03:59:00Z,2024-09-07T14:00:00Z,2024-09-02T13:12:00.810821Z
32,AAAGASM-24AUG31-US-3.45,AAAGASM-24AUG31-US,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.45?,3.45,finalized,2024-07-29T17:00:00Z,2024-08-31T03:59:00Z,2024-09-07T14:00:00Z,2024-09-02T13:12:00.820873Z
33,AAAGASM-24AUG31-US-3.50,AAAGASM-24AUG31-US,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.50?,3.50,finalized,2024-07-29T17:00:00Z,2024-08-31T03:59:00Z,2024-09-07T14:00:00Z,2024-09-02T13:12:00.839992Z
34,AAAGASM-24AUG31-US-3.55,AAAGASM-24AUG31-US,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.55?,3.55,finalized,2024-07-29T17:00:00Z,2024-08-31T03:59:00Z,2024-09-07T14:00:00Z,2024-09-02T13:12:00.850076Z
35,AAAGASM-24AUG31-US-3.60,AAAGASM-24AUG31-US,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.60?,3.60,finalized,2024-07-29T17:00:00Z,2024-08-31T03:59:00Z,2024-09-07T14:00:00Z,2024-09-02T13:13:00.660991Z
36,AAAGASM-24AUG31-US-3.65,AAAGASM-24AUG31-US,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.65?,3.65,finalized,2024-07-29T17:00:00Z,2024-08-31T03:59:00Z,2024-09-07T14:00:00Z,2024-09-02T13:12:00.860314Z
37,AAAGASM-24AUG31-US-3.70,AAAGASM-24AUG31-US,AAAGASM-24AUG31-US,Gas prices in the US in Aug 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.70?,3.70,finalized,2024-07-29T17:00:00Z,2024-08-31T03:59:00Z,2024-09-07T14:00:00Z,2024-09-02T13:12:00.880268Z
38,AAAGASM-24FEB29-US-3.291,AAAGASM-24FEB29-US,AAAGASM-24FEB29-US,Gas prices in the US in Feb 2024?,KXAAAGASM,None,Economics,Will **gas prices** be above $3.291?,3.291,finalized,2024-01-31T15:00:00Z,2024-02-29T14:55:00Z,2024-03-07T15:00:00Z,2024-03-01T02:24:00.403785Z
39,AAAGASM-24JAN31-US-3.112,AAAGASM-24JAN31-US,AAAGASM-24JAN31-US,Gas prices in the US in Jan 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.112?,3.112,finalized,2024-01-04T15:00:00Z,2024-01-31T14:55:00Z,2024-02-07T15:00:00Z,2024-02-01T17:35:01.294902Z
40,AAAGASM-24JUL31-US-3.25,AAAGASM-24JUL31-US,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.25?,3.25,finalized,2024-06-30T14:00:00Z,2024-07-31T03:59:00Z,2024-08-07T14:00:00Z,2024-07-31T18:27:00.426927Z
41,AAAGASM-24JUL31-US-3.30,AAAGASM-24JUL31-US,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.30?,3.30,finalized,2024-06-30T14:00:00Z,2024-07-31T03:59:00Z,2024-08-07T14:00:00Z,2024-07-31T18:19:00.851708Z
42,AAAGASM-24JUL31-US-3.35,AAAGASM-24JUL31-US,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.35?,3.35,finalized,2024-06-30T14:00:00Z,2024-07-31T03:59:00Z,2024-08-07T14:00:00Z,2024-07-31T18:19:00.866799Z
43,AAAGASM-24JUL31-US-3.40,AAAGASM-24JUL31-US,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.40?,3.40,finalized,2024-06-30T14:00:00Z,2024-07-31T03:59:00Z,2024-08-07T14:00:00Z,2024-07-31T18:19:00.881624Z
44,AAAGASM-24JUL31-US-3.45,AAAGASM-24JUL31-US,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.45?,3.45,finalized,2024-06-30T14:00:00Z,2024-07-31T03:59:00Z,2024-08-07T14:00:00Z,2024-07-31T18:19:01.356656Z
45,AAAGASM-24JUL31-US-3.50,AAAGASM-24JUL31-US,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.50?,3.50,finalized,2024-06-30T14:00:00Z,2024-07-31T03:59:00Z,2024-08-07T14:00:00Z,2024-07-31T18:19:01.336441Z
46,AAAGASM-24JUL31-US-3.55,AAAGASM-24JUL31-US,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.55?,3.55,finalized,2024-06-30T14:00:00Z,2024-07-31T03:59:00Z,2024-08-07T14:00:00Z,2024-07-31T18:19:00.901752Z
47,AAAGASM-24JUL31-US-3.60,AAAGASM-24JUL31-US,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.60?,3.60,finalized,2024-06-30T14:00:00Z,2024-07-31T03:59:00Z,2024-08-07T14:00:00Z,2024-07-31T18:19:00.916578Z
48,AAAGASM-24JUL31-US-3.65,AAAGASM-24JUL31-US,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.65?,3.65,finalized,2024-07-01T18:00:00Z,2024-07-31T03:59:00Z,2024-08-07T14:00:00Z,2024-07-31T18:27:01.421661Z
49,AAAGASM-24JUL31-US-3.70,AAAGASM-24JUL31-US,AAAGASM-24JUL31-US,Gas prices in the US in Jul 2024?,KXAAAGASM,None,Economics,Will average **gas prices** be above $3.70?,3.70,finalized,2024-07-01T18:00:00Z,2024-07-31T03:59:00Z,2024-08-07T14:00:00Z,2024-07-31T18:19:00.976706Z

In [ ]:
df_historical_economics_market_tickers.shape

(12606, 14)

In [ ]:
df_historical_economics_market_tickers.columns

Index(['ticker', 'event_ticker', 'event_ticker_searched', 'event_title',
       'series_ticker_searched', 'series_title', 'category', 'title',
       'subtitle', 'status', 'open_time', 'close_time', 'expiration_time',
       'settlement_ts'],
      dtype='object')

In [ ]:
df_historical_economics_market_tickers.tail(50)

,ticker,event_ticker,event_ticker_searched,event_title,series_ticker_searched,series_title,category,title,subtitle,status,open_time,close_time,expiration_time,settlement_ts
12440,U3-24MAR-T3.9,U3-24MAR,U3-24MAR,Unemployment in Mar 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.9%...,3.9%:: Feb 2024 result: 3.9,finalized,2024-02-23T15:00:00Z,2024-04-05T12:25:00Z,2024-04-12T14:00:00Z,2024-04-05T16:41:01.355403Z
12441,U3-24MAR-T4.0,U3-24MAR,U3-24MAR,Unemployment in Mar 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.0%...,4.0%,finalized,2024-02-23T15:00:00Z,2024-04-05T12:25:00Z,2024-04-12T14:00:00Z,2024-04-05T16:41:01.379918Z
12442,U3-24MAR-T4.1,U3-24MAR,U3-24MAR,Unemployment in Mar 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.1%...,4.1%,finalized,2024-02-23T15:00:00Z,2024-04-05T12:25:00Z,2024-04-12T14:00:00Z,2024-04-05T16:41:01.439552Z
12443,U3-24MAR-T4.2,U3-24MAR,U3-24MAR,Unemployment in Mar 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.2%...,4.2%,finalized,2024-02-23T15:00:00Z,2024-04-05T12:25:00Z,2024-04-12T14:00:00Z,2024-04-05T16:41:01.425181Z
12444,U3-24MAY-T3.3,U3-24MAY,U3-24MAY,Unemployment in May 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.3%...,3.3%,finalized,2024-04-19T14:00:00Z,2024-06-07T12:25:00Z,2024-06-14T14:00:00Z,2024-06-07T16:03:00.847618Z
12445,U3-24MAY-T3.4,U3-24MAY,U3-24MAY,Unemployment in May 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.4%...,3.4%,finalized,2024-04-19T14:00:00Z,2024-06-07T12:25:00Z,2024-06-14T14:00:00Z,2024-06-07T16:07:00.548103Z
12446,U3-24MAY-T3.5,U3-24MAY,U3-24MAY,Unemployment in May 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.5%...,3.5%,finalized,2024-04-19T14:00:00Z,2024-06-07T12:25:00Z,2024-06-14T14:00:00Z,2024-06-07T16:07:00.56307Z
12447,U3-24MAY-T3.6,U3-24MAY,U3-24MAY,Unemployment in May 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.6%...,3.6%,finalized,2024-04-19T14:00:00Z,2024-06-07T12:25:00Z,2024-06-14T14:00:00Z,2024-06-07T16:07:00.572593Z
12448,U3-24MAY-T3.7,U3-24MAY,U3-24MAY,Unemployment in May 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.7%...,3.7%,finalized,2024-04-19T14:00:00Z,2024-06-07T12:25:00Z,2024-06-14T14:00:00Z,2024-06-07T16:07:01.148081Z
12449,U3-24MAY-T3.8,U3-24MAY,U3-24MAY,Unemployment in May 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.8%...,3.8%,finalized,2024-04-19T14:00:00Z,2024-06-07T12:25:00Z,2024-06-14T14:00:00Z,2024-06-07T16:03:00.868117Z
12450,U3-24MAY-T3.9,U3-24MAY,U3-24MAY,Unemployment in May 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.9%...,3.9%,finalized,2024-04-19T14:00:00Z,2024-06-07T12:25:00Z,2024-06-14T14:00:00Z,2024-06-07T16:07:00.977374Z
12451,U3-24MAY-T4.0,U3-24MAY,U3-24MAY,Unemployment in May 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.0%...,4.0%,finalized,2024-04-19T14:00:00Z,2024-06-07T12:25:00Z,2024-06-14T14:00:00Z,2024-06-07T16:03:01.093174Z
12452,U3-24MAY-T4.1,U3-24MAY,U3-24MAY,Unemployment in May 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.1%...,4.1%,finalized,2024-04-19T14:00:00Z,2024-06-07T12:25:00Z,2024-06-14T14:00:00Z,2024-06-07T16:07:01.002973Z
12453,U3-24MAY-T4.2,U3-24MAY,U3-24MAY,Unemployment in May 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.2%...,4.2%,finalized,2024-04-19T14:00:00Z,2024-06-07T12:25:00Z,2024-06-14T14:00:00Z,2024-06-07T16:07:00.988061Z
12454,U3-24OCT-T3.6,U3-24OCT,U3-24OCT,Unemployment in Oct 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.6%...,3.6%,finalized,2024-09-20T14:00:00Z,2024-11-01T12:25:00Z,2024-11-08T14:00:00Z,2024-11-01T17:18:00.708172Z
12455,U3-24OCT-T3.7,U3-24OCT,U3-24OCT,Unemployment in Oct 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.7%...,3.7%,finalized,2024-09-20T14:00:00Z,2024-11-01T12:25:00Z,2024-11-08T14:00:00Z,2024-11-01T17:18:00.717974Z
12456,U3-24OCT-T3.8,U3-24OCT,U3-24OCT,Unemployment in Oct 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.8%...,3.8%,finalized,2024-09-20T14:00:00Z,2024-11-01T12:25:00Z,2024-11-08T14:00:00Z,2024-11-01T17:18:00.73836Z
12457,U3-24OCT-T3.9,U3-24OCT,U3-24OCT,Unemployment in Oct 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.9%...,3.9%,finalized,2024-09-20T14:00:00Z,2024-11-01T12:25:00Z,2024-11-08T14:00:00Z,2024-11-01T17:19:00.748493Z
12458,U3-24OCT-T4.0,U3-24OCT,U3-24OCT,Unemployment in Oct 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.0%...,4.0%,finalized,2024-09-20T14:00:00Z,2024-11-01T12:25:00Z,2024-11-08T14:00:00Z,2024-11-01T17:18:00.758109Z
12459,U3-24OCT-T4.1,U3-24OCT,U3-24OCT,Unemployment in Oct 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.1%...,4.1%,finalized,2024-09-20T14:00:00Z,2024-11-01T12:25:00Z,2024-11-08T14:00:00Z,2024-11-01T17:18:00.778028Z
12460,U3-24OCT-T4.2,U3-24OCT,U3-24OCT,Unemployment in Oct 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.2%...,4.2%,finalized,2024-09-20T14:00:00Z,2024-11-01T12:25:00Z,2024-11-08T14:00:00Z,2024-11-01T17:18:00.787923Z
12461,U3-24OCT-T4.3,U3-24OCT,U3-24OCT,Unemployment in Oct 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.3%...,4.3%,finalized,2024-09-20T14:00:00Z,2024-11-01T12:25:00Z,2024-11-08T14:00:00Z,2024-11-01T17:18:00.803351Z
12462,U3-24OCT-T4.4,U3-24OCT,U3-24OCT,Unemployment in Oct 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.4%...,4.4%,finalized,2024-09-20T14:00:00Z,2024-11-01T12:25:00Z,2024-11-08T14:00:00Z,2024-11-01T17:18:00.818691Z
12463,U3-24OCT-T4.5,U3-24OCT,U3-24OCT,Unemployment in Oct 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.5%...,4.5%,finalized,2024-09-20T14:00:00Z,2024-11-01T12:25:00Z,2024-11-08T14:00:00Z,2024-11-01T17:18:00.827969Z
12464,U3-24SEP-T3.7,U3-24SEP,U3-24SEP,Unemployment in Sep 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.7%...,3.7%,finalized,2024-08-23T14:00:00Z,2024-10-04T12:25:00Z,2024-10-11T14:00:00Z,2024-10-04T16:15:01.442327Z
12465,U3-24SEP-T3.8,U3-24SEP,U3-24SEP,Unemployment in Sep 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.8%...,3.8%,finalized,2024-08-23T14:00:00Z,2024-10-04T12:25:00Z,2024-10-11T14:00:00Z,2024-10-04T16:15:01.371935Z
12466,U3-24SEP-T3.9,U3-24SEP,U3-24SEP,Unemployment in Sep 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 3.9%...,3.9%,finalized,2024-08-23T14:00:00Z,2024-10-04T12:25:00Z,2024-10-11T14:00:00Z,2024-10-04T16:15:01.321987Z
12467,U3-24SEP-T4.0,U3-24SEP,U3-24SEP,Unemployment in Sep 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.0%...,4.0%,finalized,2024-08-23T14:00:00Z,2024-10-04T12:25:00Z,2024-10-11T14:00:00Z,2024-10-04T16:15:01.291662Z
12468,U3-24SEP-T4.1,U3-24SEP,U3-24SEP,Unemployment in Sep 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.1%...,4.1%,finalized,2024-08-23T14:00:00Z,2024-10-04T12:25:00Z,2024-10-11T14:00:00Z,2024-10-04T16:16:01.087307Z
12469,U3-24SEP-T4.2,U3-24SEP,U3-24SEP,Unemployment in Sep 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.2%...,4.2%,finalized,2024-08-23T14:00:00Z,2024-10-04T12:25:00Z,2024-10-11T14:00:00Z,2024-10-04T16:16:01.067091Z
12470,U3-24SEP-T4.3,U3-24SEP,U3-24SEP,Unemployment in Sep 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.3%...,4.3%,finalized,2024-08-23T14:00:00Z,2024-10-04T12:25:00Z,2024-10-11T14:00:00Z,2024-10-04T16:16:01.032236Z
12471,U3-24SEP-T4.4,U3-24SEP,U3-24SEP,Unemployment in Sep 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.4%...,4.4%,finalized,2024-08-23T14:00:00Z,2024-10-04T12:25:00Z,2024-10-11T14:00:00Z,2024-10-04T16:16:01.011654Z
12472,U3-24SEP-T4.5,U3-24SEP,U3-24SEP,Unemployment in Sep 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.5%...,4.5%,finalized,2024-08-23T14:00:00Z,2024-10-04T12:25:00Z,2024-10-11T14:00:00Z,2024-10-04T16:16:00.981892Z
12473,U3-24SEP-T4.6,U3-24SEP,U3-24SEP,Unemployment in Sep 2024?,KXU3,None,Economics,Will the unemployment rate (U-3) be above 4.6%...,4.6%,finalized,2024-08-23T14:00:00Z,2024-10-04T12:25:00Z,2024-10-11T14:00:00Z,2024-10-04T16:16:00.382344Z
12474,U3MAX-22-P6.0,U3MAX-22,U3MAX-22,Unemployment spike in any month in 2022?,KXU3MAX,None,Economics,Will the **unemployment rate** be above 6.0% i...,>6.0%,finalized,2022-02-10T15:00:00Z,2023-01-06T13:25:00Z,2023-03-07T15:00:00Z,2023-01-06T18:04:00.9325Z
12475,U3MIN-22-N3.5,U3MIN-22,U3MIN-22,Unemployment keeps falling in any month in 2022?,KXU3MIN,None,Economics,Will the **unemployment rate** be below 3.5% i...,<3.5%,finalized,2022-02-10T15:00:00Z,2023-01-06T13:25:00Z,2023-03-07T15:00:00Z,2023-01-06T18:06:00.68306Z
12476,USEDCAR-23AUG-T-2,USEDCAR-23AUG,USEDCAR-23AUG,"US CPI print on used cars, Aug 2023?",KXUSEDCAR,None,Economics,Will used car prices rise more than -2% in Aug...,>-2%,finalized,2023-08-15T14:00:00Z,2023-09-13T12:25:00Z,2023-09-20T14:00:00Z,2023-09-13T17:10:00.932779Z
12477,USEDCAR-23AUG-T-3,USEDCAR-23AUG,USEDCAR-23AUG,"US CPI print on used cars, Aug 2023?",KXUSEDCAR,None,Economics,Will used car prices rise more than -3% in Aug...,>-3%,finalized,2023-08-21T23:00:00Z,2023-09-13T12:25:00Z,2023-09-20T14:00:00Z,2023-09-13T17:10:00.967298Z
12478,USEDCAR-23AUG-T-4,USEDCAR-23AUG,USEDCAR-23AUG,"US CPI print on used cars, Aug 2023?",KXUSEDCAR,None,Economics,Will used car prices rise more than -4% in Aug...,>-4%,finalized,2023-08-15T14:00:00Z,2023-09-13T12:25:00Z,2023-09-20T14:00:00Z,2023-09-13T17:10:00.317758Z
12479,USEDCAR-23AUG-T0,USEDCAR-23AUG,USEDCAR-23AUG,"US CPI print on used cars, Aug 2023?",KXUSEDCAR,None,Economics,Will used car prices rise more than 0% in Augu...,>0%,finalized,2023-08-15T14:00:00Z,2023-09-13T12:25:00Z,2023-09-20T14:00:00Z,2023-09-13T17:10:00.848138Z
12480,USEDCAR-23AUG-T2,USEDCAR-23AUG,USEDCAR-23AUG,"US CPI print on used cars, Aug 2023?",KXUSEDCAR,None,Economics,Will used car prices rise more than 2% in Augu...,>2%,finalized,2023-08-15T14:00:00Z,2023-09-13T12:25:00Z,2023-09-20T14:00:00Z,2023-09-13T17:10:00.872155Z
12481,USEDCAR-23AUG-T4,USEDCAR-23AUG,USEDCAR-23AUG,"US CPI print on used cars, Aug 2023?",KXUSEDCAR,None,Economics,Will used car prices rise more than 4% in Augu...,>4%,finalized,2023-08-15T14:00:00Z,2023-09-13T12:25:00Z,2023-09-20T14:00:00Z,2023-09-13T17:10:00.923052Z
12482,USEDCAR-23AUG-T5,USEDCAR-23AUG,USEDCAR-23AUG,"US CPI print on used cars, Aug 2023?",KXUSEDCAR,None,Economics,Will used car CPI rise more than 5% in August ...,>5%,finalized,2023-08-21T23:00:00Z,2023-09-13T12:25:00Z,2023-09-20T14:00:00Z,2023-09-13T17:10:00.948087Z
12483,USEDCAR-23JUL-T-2,USEDCAR-23JUL,USEDCAR-23JUL,US CPI print on used cars in Jul 2023?,KXUSEDCAR,None,Economics,Will used car prices rise more than -2% in Jul...,>-2%,finalized,2023-08-02T14:00:00Z,2023-08-10T12:25:00Z,2023-08-17T14:00:00Z,2023-08-10T16:19:00.521671Z
12484,USEDCAR-23JUL-T-4,USEDCAR-23JUL,USEDCAR-23JUL,US CPI print on used cars in Jul 2023?,KXUSEDCAR,None,Economics,Will used car prices rise more than -4% in Jul...,-4%,finalized,2023-08-02T14:00:00Z,2023-08-10T12:25:00Z,2023-08-17T14:00:00Z,2023-08-10T16:13:00.326872Z
12485,USEDCAR-23JUL-T0,USEDCAR-23JUL,USEDCAR-23JUL,US CPI print on used cars in Jul 2023?,KXUSEDCAR,None,Economics,Will used car prices rise more than 0% in July...,>0%,finalized,2023-08-02T14:00:00Z,2023-08-10T12:25:00Z,2023-08-17T14:00:00Z,2023-08-10T16:12:00.631596Z
12486,USEDCAR-23JUL-T2,USEDCAR-23JUL,USEDCAR-23JUL,US CPI print on used cars in Jul 2023?,KXUSEDCAR,None,Economics,Will used car prices rise more than 2% in July...,>2%,finalized,2023-08-02T14:00:00Z,2023-08-10T12:25:00Z,2023-08-17T14:00:00Z,2023-08-10T16:19:00.506269Z
12487,USEDCAR-23JUL-T4,USEDCAR-23JUL,USEDCAR-23JUL,US CPI print on used cars in Jul 2023?,KXUSEDCAR,None,Economics,Will used car prices rise more than 4% in July...,>4%,finalized,2023-08-02T14:00:00Z,2023-08-10T12:25:00Z,2023-08-17T14:00:00Z,2023-08-10T16:12:00.61703Z
12488,WHEAT-22APR-T7.50,WHEAT-22APR,WHEAT-22APR,"Average wheat price in April, 2022?",KXWHEAT,None,Economics,What will the price of wheat be?,>$7.50,finalized,2022-04-01T14:00:00Z,2022-04-08T15:55:00Z,2022-04-22T14:00:00Z,2022-04-09T17:05:00.554334Z
12489,WRECSS-26-GER,WRECSS-26,WRECSS-26,Which countries will have a recession before 2...,KXWRECSS,None,Economics,Which countries will have recessions?,Germany,finalized,2024-04-23T12:00:00Z,2025-11-03T18:12:29.373203Z,2027-12-31T15:00:00Z,2025-11-03T19:12:32.482306Z

In [ ]:
df_historical_economics_market_tickers.open_time.min()

'2021-06-30T14:00:00Z'

In [ ]:
df_historical_economics_market_tickers.close_time.min()

'2021-07-01T23:00:00Z'

In [ ]:
df_historical_economics_market_tickers.close_time.max()

'2026-04-23T14:32:14Z'

In [ ]:
df_historical_economics_market_tickers.open_time.max()

'2026-04-22T12:40:00Z'

In [ ]:
df_historical_economics_market_tickers.ticker.values

array(['AAAGASD-23OCT03-US-3.814', 'AAAGASD-23OCT04-US-3.798',
       'AAAGASD-23OCT05-US-3.785', ..., 'USEDCAR-23JUL-T4',
       'WHEAT-22APR-T7.50', 'WRECSS-26-GER'], dtype=object)

# Specific Attributes

In [ ]:
import time
import pandas as pd

# Your NumPy array of historical market tickers
historical_market_tickers = df_historical_economics_market_tickers.ticker.values

wanted_attrs = [
    "ticker",
    "event_ticker",
    "series_ticker",
    "yes_sub_title",
    "no_sub_title",
    "created_time",
    "open_time",
    "close_time",
    "status",
    "result",
    "notional_value_dollars",
    "rules_primary",
    "rules_secondary",
    "title",
    "volume_fp",
    "volume_24h_fp",
]

market_rows = []
failed_tickers = []

for i, ticker in enumerate(historical_market_tickers, start=1):
    ticker = str(ticker).strip()

    print(f"[{i}/{len(historical_market_tickers)}] Getting historical market {ticker}...")

    try:
        data = get_json(f"/historical/markets/{ticker}")
        market = data.get("market", data)

        row = {attr: market.get(attr) for attr in wanted_attrs}

        # Fallback: if series_ticker is not returned by the endpoint,
        # try to recover it from your existing DataFrame.
        if not row.get("series_ticker") and "series_ticker_searched" in df_historical_economics_market_tickers.columns:
            match = df_historical_economics_market_tickers[
                df_historical_economics_market_tickers["ticker"].astype(str).str.strip() == ticker
            ]

            if not match.empty:
                row["series_ticker"] = match.iloc[0].get("series_ticker_searched")

        market_rows.append(row)

    except Exception as e:
        print(f"Skipping {ticker}: {e}")
        failed_tickers.append({
            "ticker": ticker,
            "error": str(e)
        })

    time.sleep(0.25)

df_historical_market_selected_attributes = pd.DataFrame(
    market_rows,
    columns=wanted_attrs
)

display(df_historical_market_selected_attributes)

print("Markets extracted:", len(df_historical_market_selected_attributes))
print("Failed tickers:", len(failed_tickers))

df_historical_market_selected_attributes.to_csv(
    "kalshi_historical_market_selected_attributes.csv",
    index=False
)

if failed_tickers:
    df_failed_historical_market_tickers = pd.DataFrame(failed_tickers)
    display(df_failed_historical_market_tickers)

    df_failed_historical_market_tickers.to_csv(
        "kalshi_failed_historical_market_tickers.csv",
        index=False
    )

[1/12606] Getting historical market AAAGASD-23OCT03-US-3.814...
[2/12606] Getting historical market AAAGASD-23OCT04-US-3.798...
[3/12606] Getting historical market AAAGASD-23OCT05-US-3.785...
[4/12606] Getting historical market AAAGASD-23OCT06-US-3.768...
[5/12606] Getting historical market AAAGASD-23OCT07-US-3.746...
[6/12606] Getting historical market AAAGASD-23OCT10-US-3.704...
[7/12606] Getting historical market AAAGASD-23OCT11-US-3.682...
[8/12606] Getting historical market AAAGASD-23OCT12-US-3.663...
[9/12606] Getting historical market AAAGASD-23OCT13-US-3.646...
[10/12606] Getting historical market AAAGASD-23OCT17-US-3.600...
[11/12606] Getting historical market AAAGASD-23OCT18-US-3.584...
[12/12606] Getting historical market AAAGASD-23OCT20-US-3.565...
[13/12606] Getting historical market AAAGASD-23SEP18-US-3.866...
[14/12606] Getting historical market AAAGASD-23SEP19-US-3.881...
[15/12606] Getting historical market AAAGASD-23SEP20-US-3.880...
[16/12606] Getting historical market AAAGASD-23SEP21-US-3.875...
[17/12606] Getting historical market AAAGASD-23SEP22-US-3.867...
[18/12606] Getting historical market AAAGASD-23SEP25-US-3.859...
[19/12606] Getting historical market AAAGASD-23SEP26-US-3.849...
[20/12606] Getting historical market AAAGASD-23SEP27-US-3.838...
[21/12606] Getting historical market AAAGASD-23SEP28-US-3.832...
[22/12606] Getting historical market AAAGASD-23SEP29-US-3.835...
[23/12606] Getting historical market AAAGASD-23SEP30-US-3.832...
[24/12606] Getting historical market AAAGASD-24MAY07-US-3.651...
[25/12606] Getting historical market AAAGASM-23DEC31-US-3.246...
[26/12606] Getting historical market AAAGASM-23NOV30-US-3.478...
[27/12606] Getting historical market AAAGASM-23OCT31-US-3.53...
[28/12606] Getting historical market AAAGASM-24APR30-US-3.69...
[29/12606] Getting historical market AAAGASM-24AUG31-US-3.25...
[30/12606] Getting historical market AAAGASM-24AUG31-US-3.30...
[31/12606] Getting historical market AAAGASM-24AUG31-US-3.35...
[32/12606] Getting historical market AAAGASM-24AUG31-US-3.40...
[33/12606] Getting historical market AAAGASM-24AUG31-US-3.45...
[34/12606] Getting historical market AAAGASM-24AUG31-US-3.50...
[35/12606] Getting historical market AAAGASM-24AUG31-US-3.55...
[36/12606] Getting historical market AAAGASM-24AUG31-US-3.60...
[37/12606] Getting historical market AAAGASM-24AUG31-US-3.65...
[38/12606] Getting historical market AAAGASM-24AUG31-US-3.70...
[39/12606] Getting historical market AAAGASM-24FEB29-US-3.291...
[40/12606] Getting historical market AAAGASM-24JAN31-US-3.112...
[41/12606] Getting historical market AAAGASM-24JUL31-US-3.25...
[42/12606] Getting historical market AAAGASM-24JUL31-US-3.30...
[43/12606] Getting historical market AAAGASM-24JUL31-US-3.35...
[44/12606] Getting historical market AAAGASM-24JUL31-US-3.40...
[45/12606] Getting historical market AAAGASM-24JUL31-US-3.45...
[46/12606] Getting historical market AAAGASM-24JUL31-US-3.50...
[47/12606] Getting historical market AAAGASM-24JUL31-US-3.55...
[48/12606] Getting historical market AAAGASM-24JUL31-US-3.60...
[49/12606] Getting historical market AAAGASM-24JUL31-US-3.65...
[50/12606] Getting historical market AAAGASM-24JUL31-US-3.70...
[51/12606] Getting historical market AAAGASM-24JUN30-US-3.35...
[52/12606] Getting historical market AAAGASM-24JUN30-US-3.40...
[53/12606] Getting historical market AAAGASM-24JUN30-US-3.45...
[54/12606] Getting historical market AAAGASM-24JUN30-US-3.50...
[55/12606] Getting historical market AAAGASM-24JUN30-US-3.55...
[56/12606] Getting historical market AAAGASM-24JUN30-US-3.60...
[57/12606] Getting historical market AAAGASM-24JUN30-US-3.65...
[58/12606] Getting historical market AAAGASM-24JUN30-US-3.70...
[59/12606] Getting historical market AAAGASM-24MAR31-US-3.469...
[60/12606] Getting historical market AAAGASM-24MAY31-US-3.50...
[61/12606] Getting historical market AAAGASM-24MAY31-US-3.55...
[62/12606] Getting historical market AAAGASM-24MAY31-US-3.60...
[63/12606] Getting historical market AAAGASM-24MAY31-US-3.65...
[64/12606] Getting historical market AAAGASM-24MAY31-US-3.70...
[65/12606] Getting historical market AAAGASM-24MAY31-US-3.75...
[66/12606] Getting historical market AAAGASM-24MAY31-US-3.80...
[67/12606] Getting historical market AAAGASM-24OCT31-US-2.95...
[68/12606] Getting historical market AAAGASM-24OCT31-US-3.00...
[69/12606] Getting historical market AAAGASM-24OCT31-US-3.05...
[70/12606] Getting historical market AAAGASM-24OCT31-US-3.10...
[71/12606] Getting historical market AAAGASM-24OCT31-US-3.15...
[72/12606] Getting historical market AAAGASM-24OCT31-US-3.20...
[73/12606] Getting historical market AAAGASM-24OCT31-US-3.25...
[74/12606] Getting historical market AAAGASM-24OCT31-US-3.30...
[75/12606] Getting historical market AAAGASM-24SEP30-US-3.10...
[76/12606] Getting historical market AAAGASM-24SEP30-US-3.15...
[77/12606] Getting historical market AAAGASM-24SEP30-US-3.20...
[78/12606] Getting historical market AAAGASM-24SEP30-US-3.25...
[79/12606] Getting historical market AAAGASM-24SEP30-US-3.30...
[80/12606] Getting historical market AAAGASM-24SEP30-US-3.35...
[81/12606] Getting historical market AAAGASM-24SEP30-US-3.40...
[82/12606] Getting historical market AAAGASM-24SEP30-US-3.45...
[83/12606] Getting historical market AAAGASM-24SEP30-US-3.50...
[84/12606] Getting historical market AAAGASM-24SEP30-US-3.55...
[85/12606] Getting historical market AAAGASMAX-23DEC31-5.016...
[86/12606] Getting historical market AAAGASMAX-24DEC31-4...
[87/12606] Getting historical market AAAGASMAX-24DEC31-5.016...
[88/12606] Getting historical market AAAGASMAXCA-23DEC31-6...
[89/12606] Getting historical market AAAGASMAXCA-23DEC31-6.438...
[90/12606] Getting historical market AAAGASMAXCA-24DEC31-5.438...
[91/12606] Getting historical market AAAGASMAXCA-24DEC31-6.438...
[92/12606] Getting historical market AAAGASMAXTX-23DEC31-4...
[93/12606] Getting historical market AAAGASMAXTX-23DEC31-4.69...
[94/12606] Getting historical market AAAGASMAXTX-24DEC31-3.69...
[95/12606] Getting historical market AAAGASMAXTX-24DEC31-4.69...
[96/12606] Getting historical market AAAGASMIN-23DEC31-3.30...
[97/12606] Getting historical market AAAGASMIN-24DEC31-2.25...
[98/12606] Getting historical market AAAGASMIN-24DEC31-2.50...
[99/12606] Getting historical market AAAGASMINCA-23DEC31-5...
[100/12606] Getting historical market AAAGASMINCA-24DEC31-4...
[101/12606] Getting historical market AAAGASMINCA-24DEC31-4.25...
[102/12606] Getting historical market AAAGASMINCA-24DEC31-4.50...
[103/12606] Getting historical market AAAGASMINTX-23DEC31-3.22...
[104/12606] Getting historical market AAAGASMINTX-24DEC31-2...
[105/12606] Getting historical market AAAGASMINTX-24DEC31-2.25...
[106/12606] Getting historical market AAAGASMINTX-24DEC31-2.50...
[107/12606] Getting historical market AAAGASW-23DEC04-US-3.253...
[108/12606] Getting historical market AAAGASW-23DEC18-US-3.153...
[109/12606] Getting historical market AAAGASW-23DEC25-US-3.066...
[110/12606] Getting historical market AAAGASW-23NOV13-US-3.4...
[111/12606] Getting historical market AAAGASW-23NOV13-US-3.494...
[112/12606] Getting historical market AAAGASW-23NOV13-US-3.6...
[113/12606] Getting historical market AAAGASW-23NOV20-US-3.365...
[114/12606] Getting historical market AAAGASW-23NOV27-US-3.308...
[115/12606] Getting historical market AAAGASW-23OCT09-US-3.70...
[116/12606] Getting historical market AAAGASW-23OCT09-US-3.75...
[117/12606] Getting historical market AAAGASW-23OCT09-US-3.80...
[118/12606] Getting historical market AAAGASW-23OCT09-US-3.85...
[119/12606] Getting historical market AAAGASW-23OCT09-US-3.90...
[120/12606] Getting historical market AAAGASW-23OCT16-US-3.55...
[121/12606] Getting historical market AAAGASW-23OCT16-US-3.60...
[122/12606] Getting historical market AAAGASW-23OCT16-US-3.65...
[123/12606] Getting historical market AAAGASW-23OCT16-US-3.70...
[124/12606] Getting historical market AAAGASW-23OCT16-US-3.75...
[125/12606] Getting historical market AAAGASW-23OCT23-US-3.55...
[126/12606] Getting historical market AAAGASW-23OCT23-US-3.60...
[127/12606] Getting historical market AAAGASW-23OCT23-US-3.65...
[128/12606] Getting historical market AAAGASW-23OCT23-US-3.70...
[129/12606] Getting historical market AAAGASW-23OCT23-US-3.75...
[130/12606] Getting historical market AAAGASW-24AUG05-US-3.505...
[131/12606] Getting historical market AAAGASW-24AUG12-US-3.472...
[132/12606] Getting historical market AAAGASW-24AUG19-US-3.443...
[133/12606] Getting historical market AAAGASW-24AUG26-US-3.411...
[134/12606] Getting historical market AAAGASW-24JAN01-US-3.127...
[135/12606] Getting historical market AAAGASW-24JAN08-US-3.110...
[136/12606] Getting historical market AAAGASW-24JUL01-US-3.448...
[137/12606] Getting historical market AAAGASW-24JUL08-US-3.491...
[138/12606] Getting historical market AAAGASW-24JUL15-US-3.506...
[139/12606] Getting historical market AAAGASW-24JUL22-US-3.521...
[140/12606] Getting historical market AAAGASW-24JUL29-US-3.501...
[141/12606] Getting historical market AAAGASW-24JUN03-US-3.592...
[142/12606] Getting historical market AAAGASW-24JUN10-US-3.532...
[143/12606] Getting historical market AAAGASW-24JUN17-US-3.445...
[144/12606] Getting historical market AAAGASW-24JUN24-US-3.447...
[145/12606] Getting historical market AAAGASW-24MAY13-US-3.651...
[146/12606] Getting historical market AAAGASW-24MAY20-US-3.619...
[147/12606] Getting historical market AAAGASW-24MAY27-US-3.590...
[148/12606] Getting historical market AAAGASW-24OCT07-US-3.216...
[149/12606] Getting historical market AAAGASW-24OCT14-US-3.174...
[150/12606] Getting historical market AAAGASW-24OCT21-US-3.203...
[151/12606] Getting historical market AAAGASW-24SEP02-US-3.351...
[152/12606] Getting historical market AAAGASW-24SEP09-US-3.331...
[153/12606] Getting historical market AAAGASW-24SEP16-US-3.270...
[154/12606] Getting historical market AAAGASW-24SEP23-US-3.208...
[155/12606] Getting historical market AAAGASW-24SEP30-US-3.214...
[156/12606] Getting historical market ACPI-22-B3.5...
[157/12606] Getting historical market ACPI-22-B4.5...
[158/12606] Getting historical market ACPI-22-B5.5...
[159/12606] Getting historical market ACPI-22-B6.5...
[160/12606] Getting historical market ACPI-22-B7.5...
[161/12606] Getting historical market ACPI-22-B8.5...
[162/12606] Getting historical market ACPI-22-C3.0...
[163/12606] Getting historical market ACPI-22-C8.9...
[164/12606] Getting historical market ACPI-23-A6.5...
[165/12606] Getting historical market ACPI-23-B1.5...
[166/12606] Getting historical market ACPI-23-B2.5...
[167/12606] Getting historical market ACPI-23-B3.5...
[168/12606] Getting historical market ACPI-23-B4.5...
[169/12606] Getting historical market ACPI-23-B5.0...
[170/12606] Getting historical market ACPI-23-B7.5...
[171/12606] Getting historical market ACPI-23-B8.5...
[172/12606] Getting historical market ACPI-23-B9.5...
[173/12606] Getting historical market ACPI-23-C1.0...
[174/12606] Getting historical market ACPI-23-C10.0...
[175/12606] Getting historical market ACPI-24-B1.5...
[176/12606] Getting historical market ACPI-24-B2.5...
[177/12606] Getting historical market ACPI-24-B3.5...
[178/12606] Getting historical market ACPI-24-B4.5...
[179/12606] Getting historical market ACPI-24-B5.5...
[180/12606] Getting historical market ACPI-24-B6.5...
[181/12606] Getting historical market ACPI-24-C1.0...
[182/12606] Getting historical market ACPI-24-C7.0...
[183/12606] Getting historical market ACPICORE-23-B1.5...
[184/12606] Getting historical market ACPICORE-23-B2.5...
[185/12606] Getting historical market ACPICORE-23-B3.5...
[186/12606] Getting historical market ACPICORE-23-B4.5...
[187/12606] Getting historical market ACPICORE-23-B5.5...
[188/12606] Getting historical market ACPICORE-23-B6.5...
[189/12606] Getting historical market ACPICORE-23-C1.0...
[190/12606] Getting historical market ACPICORE-23-C7.0...
[191/12606] Getting historical market ACPICORE-24-B1.5...
[192/12606] Getting historical market ACPICORE-24-B2.5...
[193/12606] Getting historical market ACPICORE-24-B3.5...
[194/12606] Getting historical market ACPICORE-24-B4.5...
[195/12606] Getting historical market ACPICORE-24-B5.5...
[196/12606] Getting historical market ACPICORE-24-B6.5...
[197/12606] Getting historical market ACPICORE-24-C1.0...
[198/12606] Getting historical market ACPICORE-24-C7.0...
[199/12606] Getting historical market ARGINFLATIONM-24APR-T150...
[200/12606] Getting historical market ARGINFLATIONM-24APR-T200...
[201/12606] Getting historical market ARGINFLATIONM-24APR-T250...
[202/12606] Getting historical market ARGINFLATIONM-24APR-T300...
[203/12606] Getting historical market ARGINFLATIONM-24AUG-T225...
[204/12606] Getting historical market ARGINFLATIONM-24AUG-T250...
[205/12606] Getting historical market ARGINFLATIONM-24AUG-T275...
[206/12606] Getting historical market ARGINFLATIONM-24AUG-T300...
[207/12606] Getting historical market ARGINFLATIONM-24FEB-T150...
[208/12606] Getting historical market ARGINFLATIONM-24FEB-T200...
[209/12606] Getting historical market ARGINFLATIONM-24FEB-T254.25...
[210/12606] Getting historical market ARGINFLATIONM-24FEB-T300...
[211/12606] Getting historical market ARGINFLATIONM-24JAN-T150...
[212/12606] Getting historical market ARGINFLATIONM-24JAN-T200...
[213/12606] Getting historical market ARGINFLATIONM-24JAN-T211.4...
[214/12606] Getting historical market ARGINFLATIONM-24JAN-T250...
[215/12606] Getting historical market ARGINFLATIONM-24JAN-T300...
[216/12606] Getting historical market ARGINFLATIONM-24JUL-T250...
[217/12606] Getting historical market ARGINFLATIONM-24JUL-T275...
[218/12606] Getting historical market ARGINFLATIONM-24JUL-T300...
[219/12606] Getting historical market ARGINFLATIONM-24JUL-T325...
[220/12606] Getting historical market ARGINFLATIONM-24JUN-T250...
[221/12606] Getting historical market ARGINFLATIONM-24JUN-T275...
[222/12606] Getting historical market ARGINFLATIONM-24JUN-T300...
[223/12606] Getting historical market ARGINFLATIONM-24JUN-T325...
[224/12606] Getting historical market ARGINFLATIONM-24MAR-T150...
[225/12606] Getting historical market ARGINFLATIONM-24MAR-T200...
[226/12606] Getting historical market ARGINFLATIONM-24MAR-T250...
[227/12606] Getting historical market ARGINFLATIONM-24MAR-T276.22...
[228/12606] Getting historical market ARGINFLATIONM-24MAR-T300...
[229/12606] Getting historical market ARGINFLATIONM-24MAY-T250...
[230/12606] Getting historical market ARGINFLATIONM-24MAY-T275...
[231/12606] Getting historical market ARGINFLATIONM-24MAY-T289.40...
[232/12606] Getting historical market ARGINFLATIONM-24MAY-T300...
[233/12606] Getting historical market ARGINFLATIONM-24MAY-T325...
[234/12606] Getting historical market ARGINFLATIONM-24OCT-T150...
[235/12606] Getting historical market ARGINFLATIONM-24OCT-T200...
[236/12606] Getting historical market ARGINFLATIONM-24OCT-T250...
[237/12606] Getting historical market ARGINFLATIONM-24OCT-T300...
[238/12606] Getting historical market ARGINFLATIONM-24SEP-T150...
[239/12606] Getting historical market ARGINFLATIONM-24SEP-T200...
[240/12606] Getting historical market ARGINFLATIONM-24SEP-T225...
[241/12606] Getting historical market ARGINFLATIONM-24SEP-T250...
[242/12606] Getting historical market ARGINFLATIONM-24SEP-T300...
[243/12606] Getting historical market BANKRUPTS-23DEC-34...
[244/12606] Getting historical market BANKRUPTS-23DEC-50...
[245/12606] Getting historical market BANKRUPTS-23DEC-60...
[246/12606] Getting historical market BANKRUPTS-23DEC-70...
[247/12606] Getting historical market BANKRUPTS-23NOV-50...
[248/12606] Getting historical market BANKRUPTS-23NOV-60...
[249/12606] Getting historical market BANKRUPTS-23NOV-70...
[250/12606] Getting historical market BANKRUPTS-23OCT-50...
[251/12606] Getting historical market BANKRUPTS-23OCT-60...
[252/12606] Getting historical market BANKRUPTS-23OCT-62...
[253/12606] Getting historical market BANKRUPTS-23OCT-70...
[254/12606] Getting historical market BANKRUPTS-24APR-30...
[255/12606] Getting historical market BANKRUPTS-24APR-40...
[256/12606] Getting historical market BANKRUPTS-24APR-50...
[257/12606] Getting historical market BANKRUPTS-24APR-60...
[258/12606] Getting historical market BANKRUPTS-24APR-70...
[259/12606] Getting historical market BANKRUPTS-24APR-80...
[260/12606] Getting historical market BANKRUPTS-24AUG-30...
[261/12606] Getting historical market BANKRUPTS-24AUG-40...
[262/12606] Getting historical market BANKRUPTS-24AUG-50...
[263/12606] Getting historical market BANKRUPTS-24AUG-60...
[264/12606] Getting historical market BANKRUPTS-24AUG-70...
[265/12606] Getting historical market BANKRUPTS-24AUG-80...
[266/12606] Getting historical market BANKRUPTS-24FEB-30...
[267/12606] Getting historical market BANKRUPTS-24FEB-36...
[268/12606] Getting historical market BANKRUPTS-24FEB-40...
[269/12606] Getting historical market BANKRUPTS-24FEB-50...
[270/12606] Getting historical market BANKRUPTS-24FEB-60...
[271/12606] Getting historical market BANKRUPTS-24JAN-30...
[272/12606] Getting historical market BANKRUPTS-24JAN-40...
[273/12606] Getting historical market BANKRUPTS-24JAN-50...
[274/12606] Getting historical market BANKRUPTS-24JAN-60...
[275/12606] Getting historical market BANKRUPTS-24JUL-30...
[276/12606] Getting historical market BANKRUPTS-24JUL-40...
[277/12606] Getting historical market BANKRUPTS-24JUL-50...
[278/12606] Getting historical market BANKRUPTS-24JUL-60...
[279/12606] Getting historical market BANKRUPTS-24JUL-70...
[280/12606] Getting historical market BANKRUPTS-24JUL-80...
[281/12606] Getting historical market BANKRUPTS-24JUL-90...
[282/12606] Getting historical market BANKRUPTS-24JUN-30...
[283/12606] Getting historical market BANKRUPTS-24JUN-40...
[284/12606] Getting historical market BANKRUPTS-24JUN-50...
[285/12606] Getting historical market BANKRUPTS-24JUN-60...
[286/12606] Getting historical market BANKRUPTS-24JUN-70...
[287/12606] Getting historical market BANKRUPTS-24MAR-30...
[288/12606] Getting historical market BANKRUPTS-24MAR-40...
[289/12606] Getting historical market BANKRUPTS-24MAR-50...
[290/12606] Getting historical market BANKRUPTS-24MAR-60...
[291/12606] Getting historical market BANKRUPTS-24MAR-70...
[292/12606] Getting historical market BANKRUPTS-24MAY-30...
[293/12606] Getting historical market BANKRUPTS-24MAY-40...
[294/12606] Getting historical market BANKRUPTS-24MAY-50...
[295/12606] Getting historical market BANKRUPTS-24MAY-60...
[296/12606] Getting historical market BANKRUPTS-24MAY-70...
[297/12606] Getting historical market BANKRUPTS-24OCT-30...
[298/12606] Getting historical market BANKRUPTS-24OCT-40...
[299/12606] Getting historical market BANKRUPTS-24OCT-50...
[300/12606] Getting historical market BANKRUPTS-24OCT-60...
[301/12606] Getting historical market BANKRUPTS-24SEP-30...
[302/12606] Getting historical market BANKRUPTS-24SEP-40...
[303/12606] Getting historical market BANKRUPTS-24SEP-50...
[304/12606] Getting historical market BANKRUPTS-24SEP-60...
[305/12606] Getting historical market BANKRUPTS-24SEP-70...
[306/12606] Getting historical market BANKRUPTS-24SEP-80...
[307/12606] Getting historical market BANKRUPTSY-24-300...
[308/12606] Getting historical market BANKRUPTSY-24-400...
[309/12606] Getting historical market BANKRUPTSY-24-500...
[310/12606] Getting historical market BANKRUPTSY-24-642...
[311/12606] Getting historical market BOE-23FEB02-T3.49...
[312/12606] Getting historical market BOE-23FEB02-T3.74...
[313/12606] Getting historical market BOE-23FEB02-T3.99...
[314/12606] Getting historical market BOE-23FEB02-T4.24...
[315/12606] Getting historical market BOE-23FEB02-T4.49...
[316/12606] Getting historical market BOE-23MAR23-T3.99...
[317/12606] Getting historical market BOE-23MAR23-T4.24...
[318/12606] Getting historical market BOE-23MAR23-T4.49...
[319/12606] Getting historical market BOE-23MAR23-T4.74...
[320/12606] Getting historical market BOE-23MAR23-T4.99...

# Candlesticks for a historical market

https://docs.kalshi.com/api-reference/historical/get-historical-market$0



this info can be extracted, given a ticker:

{
  "market": {
    "ticker": "<string>",

    "event_ticker": "<string>",

    "yes_sub_title": "<string>",

    "no_sub_title": "<string>",

    "created_time": "2023-11-07T05:31:56Z",

    "updated_time": "2023-11-07T05:31:56Z",

    "open_time": "2023-11-07T05:31:56Z",

    "close_time": "2023-11-07T05:31:56Z",

    "latest_expiration_time": "2023-11-07T05:31:56Z",

    "settlement_timer_seconds": 123,

    "yes_bid_dollars": "0.5600",

    "yes_bid_size_fp": "10.00",

    "yes_ask_dollars": "0.5600",

    "yes_ask_size_fp": "10.00",

    "no_bid_dollars": "0.5600",

    "no_ask_dollars": "0.5600",

    "last_price_dollars": "0.5600",

    "volume_fp": "10.00",

    "volume_24h_fp": "10.00",

    "can_close_early": true,

    "fractional_trading_enabled": true,

    "open_interest_fp": "10.00",

    "notional_value_dollars": "0.5600",

    "previous_yes_bid_dollars": "0.5600",

    "previous_yes_ask_dollars": "0.5600",

    "previous_price_dollars": "0.5600",

    "liquidity_dollars": "0.5600",

    "expiration_value": "<string>",

    "rules_primary": "<string>",

    "rules_secondary": "<string>",

    "price_level_structure": "<string>",

    "price_ranges": [
      {
        "start": "<string>",
        "end": "<string>",
        "step": "<string>"
      }
    ],
    "title": "<string>",
    "subtitle": "<string>",
    "expected_expiration_time": "2023-11-07T05:31:56Z",
    "expiration_time": "2023-11-07T05:31:56Z",
    "response_price_units": "usd_cent",
    "settlement_value_dollars": "0.5600",
    "settlement_ts": "2023-11-07T05:31:56Z",
    "occurrence_datetime": "2023-11-07T05:31:56Z",
    "fee_waiver_expiration_time": "2023-11-07T05:31:56Z",
    "early_close_condition": "<string>",
    "floor_strike": 123,
    "cap_strike": 123,
    "functional_strike": "<string>",
    "custom_strike": {},
    "mve_collection_ticker": "<string>",
    "mve_selected_legs": [
      {
        "event_ticker": "<string>",
        "market_ticker": "<string>",
        "side": "<string>",
        "yes_settlement_value_dollars": "0.5600"
      }
    ],
    "primary_participant_key": "<string>",
    "is_provisional": true,
    "exchange_index": 0
  }
}

In [ ]:
import requests
import pandas as pd
from urllib.parse import urljoin
import time

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-daily-candlesticks-colab/1.0"
})

def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        if resp.status_code >= 400:
            print("Bad request URL:", resp.url)
            print("Kalshi response:", resp.text)
            resp.raise_for_status()

        return resp.json()

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


# Put your historical market ticker here
market_ticker = "WRECSS-26-GER"

# Get market details so we can use its open/close dates
market_data = get_json(f"/historical/markets/{market_ticker}")
market = market_data.get("market", market_data)

open_time = pd.to_datetime(market.get("open_time"), utc=True, errors="coerce")
close_time = pd.to_datetime(market.get("close_time"), utc=True, errors="coerce")

start_ts = int(open_time.timestamp())
end_ts = int(close_time.timestamp())

# Get daily candlesticks
candles_data = get_json(
    f"/historical/markets/{market_ticker}/candlesticks",
    params={
        "start_ts": start_ts,
        "end_ts": end_ts,
        "period_interval": 1440
    }
)

df_daily_candlesticks = pd.DataFrame(candles_data.get("candlesticks", []))

display(df_daily_candlesticks)

print("Market ticker:", market_ticker)
print("Open time:", open_time)
print("Close time:", close_time)
print("Daily candlesticks:", len(df_daily_candlesticks))

,end_period_ts,open_interest,price,volume,yes_ask,yes_bid
0,1713931200,1000.00,"{'close': '0.1400', 'high': '0.1400', 'low': '...",1000.00,"{'close': '0.5000', 'high': '1.0000', 'low': '...","{'close': '0.0400', 'high': '0.0400', 'low': '..."
1,1714017600,1040.00,"{'close': '0.2400', 'high': '0.2400', 'low': '...",40.00,"{'close': '0.2400', 'high': '0.5000', 'low': '...","{'close': '0.1700', 'high': '0.1700', 'low': '..."
2,1714104000,1120.00,"{'close': '0.2400', 'high': '0.2400', 'low': '...",80.00,"{'close': '0.2400', 'high': '0.3600', 'low': '...","{'close': '0.1700', 'high': '0.1700', 'low': '..."
3,1714363200,1120.00,"{'close': '0.1700', 'high': '0.1700', 'low': '...",1.00,"{'close': '0.2400', 'high': '0.2400', 'low': '...","{'close': '0.1700', 'high': '0.1700', 'low': '..."
4,1714881600,1139.00,"{'close': '0.2400', 'high': '0.2400', 'low': '...",19.00,"{'close': '0.2400', 'high': '0.2400', 'low': '...","{'close': '0.1800', 'high': '0.1800', 'low': '..."
...,...,...,...,...,...,...
407,1761796800,3053.00,"{'close': '0.5200', 'high': '0.5200', 'low': '...",3.00,"{'close': '0.5200', 'high': '0.5200', 'low': '...","{'close': '0.4700', 'high': '0.4700', 'low': '..."
408,1761883200,5125.00,"{'close': '0.6700', 'high': '0.6700', 'low': '...",2072.00,"{'close': '0.6400', 'high': '0.8400', 'low': '...","{'close': '0.5800', 'high': '0.5800', 'low': '..."
409,1761969600,6035.00,"{'close': '0.9200', 'high': '0.9600', 'low': '...",5349.00,"{'close': '0.9200', 'high': '0.9700', 'low': '...","{'close': '0.8600', 'high': '0.9300', 'low': '..."
410,1762056000,6008.00,"{'close': '0.8500', 'high': '0.9300', 'low': '...",57.00,"{'close': '0.8900', 'high': '0.9300', 'low': '...","{'close': '0.8500', 'high': '0.8800', 'low': '..."
411,1762142400,6008.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.8900', 'high': '0.8900', 'low': '...","{'close': '0.8600', 'high': '0.8600', 'low': '..."

Market ticker: WRECSS-26-GER
Open time: 2024-04-23 12:00:00+00:00
Close time: 2025-11-03 18:12:29.373203+00:00
Daily candlesticks: 412

In [ ]:
#Getting Economics category tickers for all events CODE FROM EARLIER - Check
import requests
import pandas as pd
import time
from typing import Optional, Dict, Any, List

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"
CATEGORY = "Economics"


def kalshi_get(path: str, params: Optional[Dict[str, Any]] = None, max_retries: int = 3) -> Dict[str, Any]:
    """
    Simple GET helper with basic retry handling.
    Public market-data endpoints do not require authentication.
    """
    url = f"{BASE_URL}{path}"
    params = params or {}

    for attempt in range(max_retries):
        try:
            response = requests.get(url, params=params, timeout=30)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            if attempt == max_retries - 1:
                raise
            time.sleep(1.5 * (attempt + 1))


def get_series_by_category(category: str = "Economics") -> List[Dict[str, Any]]:
    """
    Get all Kalshi series in a category.
    """
    data = kalshi_get(
        "/series",
        params={
            "category": category,
            "include_product_metadata": "true",
            "include_volume": "true",
        },
    )
    return data.get("series", [])


def get_events_for_series(
    series_ticker: str,
    status: Optional[str] = None,
    with_nested_markets: bool = True,
) -> List[Dict[str, Any]]:
    """
    Get all events for one series ticker, handling cursor pagination.

    status options:
      None      -> all statuses
      "unopened"
      "open"
      "closed"
      "settled"
    """
    all_events = []
    cursor = None

    while True:
        params = {
            "series_ticker": series_ticker,
            "limit": 200,
            "with_nested_markets": str(with_nested_markets).lower(),
        }

        if status is not None:
            params["status"] = status

        if cursor:
            params["cursor"] = cursor

        data = kalshi_get("/events", params=params)

        events = data.get("events", [])
        all_events.extend(events)

        cursor = data.get("cursor")
        if not cursor:
            break

    return all_events


def economics_events_markets_df(
    category: str = "Economics",
    status: Optional[str] = None,
) -> pd.DataFrame:
    """
    Returns one row per market.

    If an event has no nested markets returned, it still creates one row
    with market fields set to None so you do not lose the event.
    """
    series_list = get_series_by_category(category)
    rows = []

    print(f"Found {len(series_list)} series in category={category!r}")

    for i, series in enumerate(series_list, start=1):
        series_ticker = series.get("ticker")
        series_title = series.get("title")

        print(f"[{i}/{len(series_list)}] Fetching events for {series_ticker}: {series_title}")

        events = get_events_for_series(
            series_ticker=series_ticker,
            status=status,
            with_nested_markets=True,
        )

        for event in events:
            markets = event.get("markets") or []

            event_base = {
                "category": event.get("category"),
                "series_ticker": event.get("series_ticker"),
                "series_title": series.get("title"),
                "series_frequency": series.get("frequency"),
                "series_tags": series.get("tags"),
                "event_ticker": event.get("event_ticker"),
                "event_title": event.get("title"),
                "event_sub_title": event.get("sub_title"),
                "event_strike_date": event.get("strike_date"),
                "event_strike_period": event.get("strike_period"),
                "event_last_updated_ts": event.get("last_updated_ts"),
                "event_product_metadata": event.get("product_metadata"),
            }

            if not markets:
                rows.append({
                    **event_base,
                    "market_ticker": None,
                    "market_question": None,
                    "market_title": None,
                    "market_subtitle": None,
                    "yes_sub_title": None,
                    "no_sub_title": None,
                    "market_status_open_time": None,
                    "market_close_time": None,
                    "market_expiration_time": None,
                    "yes_bid_dollars": None,
                    "yes_ask_dollars": None,
                    "no_bid_dollars": None,
                    "no_ask_dollars": None,
                    "last_price_dollars": None,
                    "volume_fp": None,
                    "volume_24h_fp": None,
                    "open_interest_fp": None,
                    "liquidity_dollars": None,
                    "rules_primary": None,
                    "rules_secondary": None,
                })
            else:
                for market in markets:
                    rows.append({
                        **event_base,
                        "market_ticker": market.get("ticker"),
                        # Kalshi's user-facing market question is usually the market title.
                        "market_question": market.get("title"),
                        "market_title": market.get("title"),
                        "market_subtitle": market.get("subtitle"),
                        "yes_sub_title": market.get("yes_sub_title"),
                        "no_sub_title": market.get("no_sub_title"),
                        "market_status_open_time": market.get("open_time"),
                        "market_close_time": market.get("close_time"),
                        "market_expiration_time": market.get("expiration_time"),
                        "yes_bid_dollars": market.get("yes_bid_dollars"),
                        "yes_ask_dollars": market.get("yes_ask_dollars"),
                        "no_bid_dollars": market.get("no_bid_dollars"),
                        "no_ask_dollars": market.get("no_ask_dollars"),
                        "last_price_dollars": market.get("last_price_dollars"),
                        "volume_fp": market.get("volume_fp"),
                        "volume_24h_fp": market.get("volume_24h_fp"),
                        "open_interest_fp": market.get("open_interest_fp"),
                        "liquidity_dollars": market.get("liquidity_dollars"),
                        "rules_primary": market.get("rules_primary"),
                        "rules_secondary": market.get("rules_secondary"),
                    })

    df = pd.DataFrame(rows)

    # Optional cleanup: remove duplicate market rows if pagination/API overlap ever occurs.
    if not df.empty:
        df = df.drop_duplicates(
            subset=["series_ticker", "event_ticker", "market_ticker"],
            keep="first",
        ).reset_index(drop=True)

    return df


# Use status=None for all events regardless of status.
# Use status="open" if you only want currently open economics markets.
df = economics_events_markets_df(
    category="Economics",
    status=None,
)

print("Rows:", len(df))
print("Unique series:", df["series_ticker"].nunique() if not df.empty else 0)
print("Unique events:", df["event_ticker"].nunique() if not df.empty else 0)
print("Unique markets:", df["market_ticker"].nunique() if not df.empty else 0)

Found 589 series in category='Economics'
[1/589] Fetching events for KXSHELTERCPI: US shelter CPI in [month]
[2/589] Fetching events for KXACPI: US annual inflation
[3/589] Fetching events for U3MAX: Unemployment spike
[4/589] Fetching events for KXPPICPI: PPI YoY exceeds CPI YoY for [time period]
[5/589] Fetching events for KXGOVTSPEND: Government budget increases
[6/589] Fetching events for KXJPCPIYOY: Japan Inflation Rate YoY
[7/589] Fetching events for KXPAYROLLS: Jobs numbers
[8/589] Fetching events for KXTECHLAYOFF: Tech layoffs up
[9/589] Fetching events for KXCBDECISIONEU: EU CENTRAL BANK POLICY INTEREST RATE
[10/589] Fetching events for GDPW: Global GDP growth
[11/589] Fetching events for PPISEMI: Semiconductor PPI
[12/589] Fetching events for KXHOMEUSY: US housing prices up
[13/589] Fetching events for KXECONSTATCORECPIYOY: year over year core inflation
[14/589] Fetching events for KXMORTGAGERATE: Mortgage Rate
[15/589] Fetching events for LOWESTRATE: Fed funds lowest rate
[16/589] Fetching events for KXGASMIN: EIA Gas lowest price yearly
[17/589] Fetching events for KXMEDIANRENTMIA: MEDIAN RENT MIAMI
[18/589] Fetching events for TERMINALRATE: Fed funds highest rate
[19/589] Fetching events for KXRUCRUDEX: Russia crude exports in [month] below x.x mbpd?
[20/589] Fetching events for KXAUTODELQ: Auto-loan delinquencies in QX?
[21/589] Fetching events for AAAGASMAX: US highest gas price yearly
[22/589] Fetching events for KXINDIAVJAPAN: Higher GDP: India vs Japan
[23/589] Fetching events for KXCANCUTS: Number of BoC rate cuts in [year]?
[24/589] Fetching events for KXLCPIYOY: Inflation surge this year
[25/589] Fetching events for KXTRUFCPI: Truflation US CPI Inflation Index
[26/589] Fetching events for RENTNYCM: Rent price increase in NYC monthly
[27/589] Fetching events for KXPAYROLLCANCEL: Payrolls cancelled
[28/589] Fetching events for KXFRMMAX: Mortgage rate high
[29/589] Fetching events for KXHIGHINFLATION: Highest Inflation
[30/589] Fetching events for LCPIMIN: High inflation ends
[31/589] Fetching events for KXNURSESTRIKE: When will the NYC nurse strike end?
[32/589] Fetching events for KXLCPIMIN: High inflation ends
[33/589] Fetching events for KXCBDECISIONMEXICO: Bank Of MEXICO policy interest rate decision
[34/589] Fetching events for KXCHNBSPMI: China NBS Manufacturing PMI
[35/589] Fetching events for KXFEDEMPLOYEES: Federal government employee count
[36/589] Fetching events for KXTRILLIONAIRE: First trillionaire
[37/589] Fetching events for KXFRCPIPREL: France Inflation Rate YoY Prel
[38/589] Fetching events for KXTOKENUST: Tokenized Treasuries
[39/589] Fetching events for KXHOUSELENGTH: US house average sale length
[40/589] Fetching events for LAYOFFSYINFO: Tech layoffs
[41/589] Fetching events for KXCPICORE: CPI core
[42/589] Fetching events for KXEASTCOASTPORTSTRIKE: ILA strike
[43/589] Fetching events for KXMUSKX: Musk Manipulating X
[44/589] Fetching events for POWELLLEAVE: Powell leaving
[45/589] Fetching events for KXFERT: Fertilizer prices
[46/589] Fetching events for KXJOBREVISION: Job revisions
[47/589] Fetching events for KXECONSTATCPIYOY: year over year inflation
[48/589] Fetching events for KXHELIUMIMP: US helium imports
[49/589] Fetching events for KXTRUFBPPI: Truflation Bitcoin Purchasing Power Index
[50/589] Fetching events for RECSSNBER: Recession
[51/589] Fetching events for KXJPMOMINF: Japan inflation MoM in [month]
[52/589] Fetching events for KXUSHOMEVAL: US Metro typical home value for date
[53/589] Fetching events for KXNYCRENTSM: NYC rent monthly increase
[54/589] Fetching events for KXCPIUSEDCAR: CPI on used cars
[55/589] Fetching events for DIESEL: Diesel price this week
[56/589] Fetching events for KXRATECUTCOUNT: Number of rate cuts
[57/589] Fetching events for KXDEGDPYOYF: Germany GDP Growth Rate YoY Flash (quarterly)
[58/589] Fetching events for KXAIJOBLOSS: Total AI-linked job losses this week
[59/589] Fetching events for KXEHSHARE: Existing home sales in time period
[60/589] Fetching events for KXUSMICHCSP: United States Michigan Consumer Sentiment Prel
[61/589] Fetching events for KXJPTRADEBAL: Japan Balance of Trade
[62/589] Fetching events for WEALTHY: Wealthiest person in world
[63/589] Fetching events for KXCREDEFMAX: Commercial real estate highest default rate
[64/589] Fetching events for KXHOUSESTART: US housing starts rise
[65/589] Fetching events for HPI: Housing Price Index
[66/589] Fetching events for KXZERORATE: Zero rates
[67/589] Fetching events for KXBARRLES: Oil barrels
[68/589] Fetching events for KXCOREUND: Will Core CPI fall below x.x% in 2026?
[69/589] Fetching events for KXCACPIYOY: Canada Inflation Rate YoY
[70/589] Fetching events for CPIUSEDCAR: CPI on used cars
[71/589] Fetching events for KXTDEFFICITBY: Deficit Amount by Date
[72/589] Fetching events for KXEGGPRICEM: Egg prices monthly
[73/589] Fetching events for SPRMAX: SPRMAX
[74/589] Fetching events for KXBRINFHIGH: How high will Brazil inflation rate get this year?
[75/589] Fetching events for KXNGASW: Natural gas price max and min weekly
[76/589] Fetching events for KXSEAHOMEVAL: Seattle typical home value for date
[77/589] Fetching events for KXDENHOMEVAL: Denver typical home value for date
[78/589] Fetching events for KXSARETAIL: South Africa retail sales MoM
[79/589] Fetching events for KXARINFLATIONM: Argentina inflation
[80/589] Fetching events for KXNYCRENTSY: NYC rent yearly increase
[81/589] Fetching events for BIGBANKLAYOFF: Big banks layoffs
[82/589] Fetching events for HOUSELENGTH: US house average sale length
[83/589] Fetching events for KXCREDEFMINMAX: Commercial real estate lowest default rate
[84/589] Fetching events for KXPROLLS: Jobs numbers
[85/589] Fetching events for KXCCDELINQ: Credit-card delinquency rate above X% in QX?
[86/589] Fetching events for KXUSPPI: United States PPI MoM
[87/589] Fetching events for KXWAGESAT: Will wage satisfaction hit a new low in [year]?
[88/589] Fetching events for KXTRUFAIDP: Truflation AI & DePIN Index
[89/589] Fetching events for KXCANUSTRIPS: Canadian trips to U.S. down X% in [year]?
[90/589] Fetching events for KXFED: Fed funds rate
[91/589] Fetching events for KXFEDDISSENT: Fed Dissent
[92/589] Fetching events for GDPUSMAX: US GDP peak
[93/589] Fetching events for USEDCAR: US CPI print on used cars
[94/589] Fetching events for WCPI-TR: Turkey inflation
[95/589] Fetching events for KXTRUFCCI: Truflation US Consumer Confidence Index
[96/589] Fetching events for KXGAS: Gas weekly
[97/589] Fetching events for KXISMPMI: ISM PMI
[98/589] Fetching events for KXMAJORPROTEST: Major protest?
[99/589] Fetching events for KXTRUFTSA: Number of Airport Passenger Screened
[100/589] Fetching events for KXCREDITRATING: US credit rating downgrade
[101/589] Fetching events for KXHPI: Housing Price Index
[102/589] Fetching events for KXWILDSHT: Which wildlife will appear on the BoE banknote shortlist
[103/589] Fetching events for KXGDPCN: China GDP growth
[104/589] Fetching events for BOE: Bank of England bank rate
[105/589] Fetching events for TRDDEFCN: US-China trade deficit
[106/589] Fetching events for HOUSESTART: US housing starts rise
[107/589] Fetching events for KXAAAGASMINCA: California lowest gas price yearly
[108/589] Fetching events for KXUSDEBT: U.S. debt to GDP ratio
[109/589] Fetching events for MORTGAGEDEF: Mortgage defaults
[110/589] Fetching events for KXHLENDREDM: Will BlackRock HLEND suspend repurchases by [date]
[111/589] Fetching events for KXHALFTRIL: Half-trillionaire
[112/589] Fetching events for KXCPICOREA: Core CPI annually
[113/589] Fetching events for BANKRUPTS: Companies going bankrupt
[114/589] Fetching events for KXBOEGOLD: BOE gold withdrawals
[115/589] Fetching events for KXAKSALMON: Alaska salmon harvest
[116/589] Fetching events for WHEAT: Average wheat price
[117/589] Fetching events for KXCPI: CPI
[118/589] Fetching events for PROLLS: Jobs numbers
[119/589] Fetching events for AAAGASD: US gas price up
[120/589] Fetching events for KXFAOFPI: FAO Food Price Index in [month]?
[121/589] Fetching events for KXCBRATEHIKES: Which central banks will hike before 2027?
[122/589] Fetching events for KXUSDURABLE: United States Durable Goods Orders MoM
[123/589] Fetching events for KXSPRUSE: SPR use
[124/589] Fetching events for KXLAYOFFSYPBS: Professional and Business Services layoffs
[125/589] Fetching events for KXREVETH: REV ETH
[126/589] Fetching events for KXCPICOREYOY: Core inflation
[127/589] Fetching events for KXACPICORE-: US annual core inflation
[128/589] Fetching events for KXBOSHOMEVAL: Boston typical home value for date
[129/589] Fetching events for KXTRUFBFST: Truflation Breakfast Commodity Index
[130/589] Fetching events for COIN: Trillion dollar coin minted
[131/589] Fetching events for KXDEBTSHRINK: U.S. debt shrink
[132/589] Fetching events for KXGDPUSMAX: US GDP peak
[133/589] Fetching events for KXAIRFARECPI: US airline fares CPI in [month]
[134/589] Fetching events for KXCPIAPPAREL: CPI on apparel
[135/589] Fetching events for KXEZGDPYOYF: Euro Area GDP Growth Rate YoY Flash
[136/589] Fetching events for KXFEDDECISION: Fed meeting
[137/589] Fetching events for KXFTAPER: Fed tapering
[138/589] Fetching events for KXTDEFICITHALF: U.S. BOP
[139/589] Fetching events for KXCHGDPYOY: China GDP Growth Rate YoY (quarterly)
[140/589] Fetching events for KXSAGDPQOQ: South Africa GDP growth QoQ
[141/589] Fetching events for KXAILABDIS: AI disrupt labor market
[142/589] Fetching events for KXGAS-MONTH: Gas monthly
[143/589] Fetching events for KXBANKRUPTS: Companies going bankrupt
[144/589] Fetching events for ECB: European Central Bank main refinancing rate
[145/589] Fetching events for KXUSGASCPI: US gasoline CPI in [month]
[146/589] Fetching events for KXSPXFOMC: S&P 500 move on July FOMC day?
[147/589] Fetching events for KXEZDEPRATE: Euro Area Deposit Facility Rate (varied dates)
[148/589] Fetching events for OIL: Price of oil monthly
[149/589] Fetching events for KXMUSKNW: Elon Musk net worth on [date]
[150/589] Fetching events for FEDFACILITY: Fed facility
[151/589] Fetching events for KXBUILDPERMS: Building permits for month
[152/589] Fetching events for KXJPY: U.S. Dollar/Japanese yen exchange rate
[153/589] Fetching events for KXPPISEMI: Semiconductor PPI
[154/589] Fetching events for KXMANHEIMUSEDCAR: Manheim Used Vehicle Value Index
[155/589] Fetching events for LCPIYOY: Inflation surge this year
[156/589] Fetching events for KXAUNABCONF: Australia NAB Business Confidence
[157/589] Fetching events for ARINFLATIONM: Argentina inflation
[158/589] Fetching events for KXARMOMINF: Argentina inflation MoM in [month]
[159/589] Fetching events for KXBANKRUPTCY: Bankruptcy
[160/589] Fetching events for KXDEFAULT: US defaults
[161/589] Fetching events for KXITGDPYOYA: Italy GDP Growth Rate YoY Adv (quarterly)
[162/589] Fetching events for KXUMICHOVR: Michigan consumer sentiment above X in [year]?
[163/589] Fetching events for KXAAAGASD: US gas price up
[164/589] Fetching events for KXBRAZILJOBS: Brazil New Caged net formal job creation
[165/589] Fetching events for NGASMAX: Natural gas price peak
[166/589] Fetching events for KXAAAGASMAXTX: Texas highest gas price yearly
[167/589] Fetching events for KXNBERRECESSQ: Next recession start
[168/589] Fetching events for KXGDPSHAREMANU: GDP share manufacturing
[169/589] Fetching events for KXREALWAGES: Real wage growth
[170/589] Fetching events for KXBRAZILGDP: Brazilian GDP Growth
[171/589] Fetching events for KXOIL: Price of oil monthly
[172/589] Fetching events for KXCBDECISIONCANADA: Bank Of Canada policy interest rate decision
[173/589] Fetching events for KXCNGDP: China quarterly GDP change in 2021 Q2
[174/589] Fetching events for KXDEGFK: Germany GfK Consumer Confidence
[175/589] Fetching events for KX30YUSTW: Where will the 30Y US Treasury Yield close this week?
[176/589] Fetching events for KXETHETF: ETH ETF listed
[177/589] Fetching events for KXCHCUTS: US Challenger job cuts in [month]
[178/589] Fetching events for KXUSPINCOME: United States Personal Income MoM
[179/589] Fetching events for KXNGDPQ: Quarterly NGDP growth
[180/589] Fetching events for COSTCOHOTDOG: Costco hot dog price increase
[181/589] Fetching events for KXCHINAUSGDP: China overtakes US GDP
[182/589] Fetching events for LCPIMAXYOY: Inflation surge this year
[183/589] Fetching events for PAYROLLS: Jobs numbers
[184/589] Fetching events for KXRUBLE: Price of Ruble
[185/589] Fetching events for KXARGINFLATIONM: Argentina inflation
[186/589] Fetching events for KXNETWORTHKAICENAT: WILL KAI CENAT BECOME A BILLIONAIRE THIS YEAR
[187/589] Fetching events for KXEZGDPQOQF: Euro Area GDP Growth Rate QoQ
[188/589] Fetching events for KXFRGDPYOYP: France GDP Growth Rate YoY Prel (quarterly)
[189/589] Fetching events for NYCRENTSM: NYC rent monthly increase
[190/589] Fetching events for ACPICORE: Annual core inflation
[191/589] Fetching events for KXCNIMPORT: US imports of goods from China
[192/589] Fetching events for KXGASMAX: EIA Gas highest price yearly
[193/589] Fetching events for KXCBRATEHIKE: Which central banks will hike this year?
[194/589] Fetching events for KXSAHM: Will the Sahm Rule trigger in [year]?
[195/589] Fetching events for GDPCN: China GDP growth
[196/589] Fetching events for KXEDMHOME: Edmonton home price below x in [year]
[197/589] Fetching events for KXCPICORE220: Will the BLS Core CPI YoY print below 2.20%
[198/589] Fetching events for KXRATECUTE: Rate cut at November 2024 meeting
[199/589] Fetching events for KXNYCBILLIONAIRES: Billionaires lost
[200/589] Fetching events for KXHOUHOMEVAL: Houston typical home value for date
[201/589] Fetching events for KXRATEHIKE: Number of Fed rate hikes
[202/589] Fetching events for SEMIPRODH: US Semiconductor production
[203/589] Fetching events for KXPCECORE: US Core PCE inflation
[204/589] Fetching events for KXCHCPIYOY: China Inflation Rate YoY
[205/589] Fetching events for KXNETWORTHROYLEE: Will Roy Lee become a Billionaire by 2029
[206/589] Fetching events for KXTRUFEGGS: Truflation US CPI Eggs Index
[207/589] Fetching events for KXCOIN: Trillion dollar coin minted
[208/589] Fetching events for KXFOMCDISSENTCOUNT: FOMC dissent count
[209/589] Fetching events for FRM: Mortgage 30-yr rate this week
[210/589] Fetching events for KXJOBLESS: Initial jobless claims
[211/589] Fetching events for KXADP: ADP employment change
[212/589] Fetching events for REALWAGES: Real wage growth
[213/589] Fetching events for KXTRADEDEFICIT: Trade Deficit by Date
[214/589] Fetching events for KXUKUNRATE: United Kingdom Unemployment Rate
[215/589] Fetching events for KXCBDECISIONKOREA: Bank Of KOREA policy interest rate decision
[216/589] Fetching events for AAAGASY: US gas price up
[217/589] Fetching events for KXNYSEOPEN: Will NYSE be open?
[218/589] Fetching events for KXUSEDCAR: US CPI print on used cars
[219/589] Fetching events for U3MIN: Unemployment keeps falling
[220/589] Fetching events for KXRATECUT: Fed rate cut
[221/589] Fetching events for KXDEBTGROWTH: U.S. debt growth
[222/589] Fetching events for KXTEMPHELP: Will temporary-help employment increase in [month]?
[223/589] Fetching events for KXOFAC: New Iran OFAC action by [date]
[224/589] Fetching events for CHINAUSGDP: China overtakes US GDP
[225/589] Fetching events for KXQRECESS: Recession start
[226/589] Fetching events for KXCHIMPORTS: China Imports YoY
[227/589] Fetching events for NGDP: Annual NGDP growth
[228/589] Fetching events for KXJUSTATEST: Just a test
[229/589] Fetching events for KXUSTYLD: Treasury note yield on date
[230/589] Fetching events for KXCH11: Commercial chapter 11 filings per month
[231/589] Fetching events for CPIYOY: Inflation
[232/589] Fetching events for KXCPIEU: Euro area inflation
[233/589] Fetching events for KXUST5: UST5
[234/589] Fetching events for KXGDPNOM: Nominal GDP
[235/589] Fetching events for KXJPYINT: Will Japan buy yen in official intervention by [date]?
[236/589] Fetching events for KXCREDITCDEF: Credit card defaults up
[237/589] Fetching events for KXLOWESTRATE: Fed funds lowest rate
[238/589] Fetching events for KXOPECCUTS: Oil production cuts
[239/589] Fetching events for KXTRUFHOUCPI: Truflation US CPI Housing Inflation Index
[240/589] Fetching events for KXDEBTGROWTH25: U.S. debt growth IN 2025
[241/589] Fetching events for KXBRAZILU: Brazil unemployment
[242/589] Fetching events for HOME: New home sales
[243/589] Fetching events for KXECONSTATU3: UNEMPLOYMENT RATE MONTHLY
[244/589] Fetching events for RHIKE: Rate hikes
[245/589] Fetching events for ECONPATH: State of the economy
[246/589] Fetching events for AAAGASMAXTX: Texas highest gas price yearly
[247/589] Fetching events for KXAAAGASY: US gas price up
[248/589] Fetching events for KXRBWSTRIKE: NYC RBW Strike
[249/589] Fetching events for KXLAYOFFSY: layoffs
[250/589] Fetching events for TBILL: Treasury bill rate
[251/589] Fetching events for KXISMSERVICES: ISM Services PMI
[252/589] Fetching events for KXUE: Monthly Unemployment
[253/589] Fetching events for KXAAAGASMAXFL: Florida highest gas price yearly
[254/589] Fetching events for PCECORE: US Core PCE inflation
[255/589] Fetching events for KXUSISMSERV: United States ISM Services PMI
[256/589] Fetching events for SPRMIN: SPRMIN
[257/589] Fetching events for KXDIESELM: Diesel price this month
[258/589] Fetching events for KXLIRRSTRIKE: LIRR strike
[259/589] Fetching events for CNY: USD/RMB exchange rate
[260/589] Fetching events for KXRBADECISION: RBA decision
[261/589] Fetching events for KXTSAW: TSA check-ins this week
[262/589] Fetching events for BANKRUPTSY: Companies going bankrupt yearly
[263/589] Fetching events for KXUSFLYCAN: US flight cancellations this week
[264/589] Fetching events for KXMSTRSELL: Will MicroStrategy sell any Bitcoin before date
[265/589] Fetching events for KXFEDCHGCOUNT: Number of rate changes
[266/589] Fetching events for FEDDECISION: Fed meeting
[267/589] Fetching events for KXCPIFOOD: CPI on food
[268/589] Fetching events for KXCHEXPORTS: China Exports YoY
[269/589] Fetching events for GDPEU: European Union GDP growth
[270/589] Fetching events for KXAUWPCC: Australia Westpac Consumer Confidence Change
[271/589] Fetching events for KXSAMSUNGSTRIKE: Samsung Electronics labor union strike
[272/589] Fetching events for KXOTTAWAHOME: Ottawa home price below X in [year]?
[273/589] Fetching events for WCPI-RU: Russian inflation
[274/589] Fetching events for KXCPISHELTER: CPI on shelter
[275/589] Fetching events for KXILPENDEBT: Illinois pension debt above X in fiscal year X?
[276/589] Fetching events for GDPUSMIN: Negative US GDP growth
[277/589] Fetching events for KXUSPSPEND: United States Personal Spending MoM
[278/589] Fetching events for KXAAAGASMINFL: Florida lowest gas price yearly
[279/589] Fetching events for KXUKCPIYOY: United Kingdom Inflation Rate YoY
[280/589] Fetching events for KXECONSTATCPI: month over month inflation
[281/589] Fetching events for KXJPCONCONF: Japan Consumer Confidence
[282/589] Fetching events for CPIGAS: CPI on gas
[283/589] Fetching events for KXSPRLVL: SPR level on date
[284/589] Fetching events for KXMEDIANRENTCHI: MEDIAN RENT CHICAGO
[285/589] Fetching events for KXTORCONDO: Toronto condo price below $X in [year]?
[286/589] Fetching events for GASD: Gas daily
[287/589] Fetching events for KXDOTPLOT: fed dot plot
[288/589] Fetching events for KXCHRETAIL: China Retail Sales YoY
[289/589] Fetching events for KXMIAHOMEVAL: Miami typical home value for date
[290/589] Fetching events for SFRENTSY: SF yearly rent growth
[291/589] Fetching events for KXFEDFACILITY: Fed facility
[292/589] Fetching events for ACPICORE-: US annual core inflation
[293/589] Fetching events for KXNEXTTRILLIONAIRE: Who will be the world's second trillionaire?
[294/589] Fetching events for KXCANHOUSTART: Canada housing starts above X in [year]?
[295/589] Fetching events for AAAGASMINCA: California lowest gas price yearly
[296/589] Fetching events for CREDEF: Commercial real estate defaults

# GET /historical/markets/{ticker}

In [ ]:
import requests
import pandas as pd
import json
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

market_ticker = "WRECSS-26-GER"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-historical-market-attributes-test/1.0"
})

url = urljoin(BASE_URL + "/", f"historical/markets/{market_ticker}")

resp = session.get(url, timeout=30)

print("URL:", resp.url)
print("Status code:", resp.status_code)

try:
    data = resp.json()
except Exception:
    data = None
    print(resp.text)

if resp.status_code >= 400:
    print("Kalshi error response:")
    print(json.dumps(data, indent=2))
else:
    print("Raw response:")
    print(json.dumps(data, indent=2)[:5000])

    # Kalshi may return {"market": {...}}
    market = data.get("market", data)

    # Print all available attributes
    print("\nAttributes returned:")
    for key in sorted(market.keys()):
        print(key)

    # Put the market into a one-row DataFrame
    df_historical_market_attributes = pd.DataFrame([market])

    display(df_historical_market_attributes)

    print("\nNumber of attributes:", len(df_historical_market_attributes.columns))
    print("\nColumns:")
    print(df_historical_market_attributes.columns.tolist())

URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/WRECSS-26-GER
Status code: 200
Raw response:
{
  "market": {
    "can_close_early": true,
    "close_time": "2025-11-03T18:12:29.373203Z",
    "created_time": "2024-04-22T23:39:53.037748Z",
    "custom_strike": {
      "Country": "Germany"
    },
    "early_close_condition": "If this event occurs, the market will close the following 10:00 AM ET.",
    "event_ticker": "WRECSS-26",
    "expected_expiration_time": "2026-12-31T15:00:00Z",
    "expiration_time": "2027-12-31T15:00:00Z",
    "expiration_value": "Yes",
    "fractional_trading_enabled": true,
    "last_price_dollars": "0.8500",
    "latest_expiration_time": "2027-12-31T15:00:00Z",
    "liquidity_dollars": "0.0000",
    "market_type": "binary",
    "no_ask_dollars": "1.0000",
    "no_bid_dollars": "0.0000",
    "no_sub_title": "Germany",
    "notional_value_dollars": "1.0000",
    "open_interest_fp": "0.00",
    "open_time": "2024-04-23T12:00:00Z",
    "previous_price_dollars": "0.8500",
    "previous_yes_ask_dollars": "1.0000",
    "previous_yes_bid_dollars": "0.0000",
    "price_level_structure": "deci_cent",
    "price_ranges": [
      {
        "end": "1.0000",
        "start": "0.0000",
        "step": "0.0010"
      }
    ],
    "response_price_units": "usd_cent",
    "result": "yes",
    "rules_primary": "If Germany has two consecutive quarters of negative real GDP growth between Jan 1, 2024 and Dec 31, 2026, then the market resolves to Yes.",
    "rules_secondary": "The exact dataset for Germany is Gross Domestic Product, Real, Seasonally Adjusted, Domestic Currency from the IMF.",
    "settlement_timer_seconds": 3600,
    "settlement_ts": "2025-11-03T19:12:32.482306Z",
    "settlement_value_dollars": "1.0000",
    "status": "finalized",
    "strike_type": "custom",
    "subtitle": "Germany",
    "ticker": "WRECSS-26-GER",
    "title": "Which countries will have recessions?",
    "updated_time": "2026-03-23T22:26:48.576397Z",
    "volume_24h_fp": "0.00",
    "volume_fp": "22433.00",
    "yes_ask_dollars": "1.0000",
    "yes_ask_size_fp": "0.00",
    "yes_bid_dollars": "0.0000",
    "yes_bid_size_fp": "0.00",
    "yes_sub_title": "Germany"
  }
}

Attributes returned:
can_close_early
close_time
created_time
custom_strike
early_close_condition
event_ticker
expected_expiration_time
expiration_time
expiration_value
fractional_trading_enabled
last_price_dollars
latest_expiration_time
liquidity_dollars
market_type
no_ask_dollars
no_bid_dollars
no_sub_title
notional_value_dollars
open_interest_fp
open_time
previous_price_dollars
previous_yes_ask_dollars
previous_yes_bid_dollars
price_level_structure
price_ranges
response_price_units
result
rules_primary
rules_secondary
settlement_timer_seconds
settlement_ts
settlement_value_dollars
status
strike_type
subtitle
ticker
title
updated_time
volume_24h_fp
volume_fp
yes_ask_dollars
yes_ask_size_fp
yes_bid_dollars
yes_bid_size_fp
yes_sub_title

,can_close_early,close_time,created_time,custom_strike,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,fractional_trading_enabled,...,ticker,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title
0,True,2025-11-03T18:12:29.373203Z,2024-04-22T23:39:53.037748Z,{'Country': 'Germany'},"If this event occurs, the market will close th...",WRECSS-26,2026-12-31T15:00:00Z,2027-12-31T15:00:00Z,Yes,True,...,WRECSS-26-GER,Which countries will have recessions?,2026-03-23T22:26:48.576397Z,0.00,22433.00,1.0000,0.00,0.0000,0.00,Germany

Number of attributes: 45

Columns:
['can_close_early', 'close_time', 'created_time', 'custom_strike', 'early_close_condition', 'event_ticker', 'expected_expiration_time', 'expiration_time', 'expiration_value', 'fractional_trading_enabled', 'last_price_dollars', 'latest_expiration_time', 'liquidity_dollars', 'market_type', 'no_ask_dollars', 'no_bid_dollars', 'no_sub_title', 'notional_value_dollars', 'open_interest_fp', 'open_time', 'previous_price_dollars', 'previous_yes_ask_dollars', 'previous_yes_bid_dollars', 'price_level_structure', 'price_ranges', 'response_price_units', 'result', 'rules_primary', 'rules_secondary', 'settlement_timer_seconds', 'settlement_ts', 'settlement_value_dollars', 'status', 'strike_type', 'subtitle', 'ticker', 'title', 'updated_time', 'volume_24h_fp', 'volume_fp', 'yes_ask_dollars', 'yes_ask_size_fp', 'yes_bid_dollars', 'yes_bid_size_fp', 'yes_sub_title']

In [ ]:
import requests
import pandas as pd
import json
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"
market_ticker = "WRECSS-26-GER"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-historical-market-attributes-test/1.0"
})

# Call GET /historical/markets/{ticker}
url = urljoin(BASE_URL + "/", f"historical/markets/{market_ticker}")

resp = session.get(url, timeout=30)

print("URL:", resp.url)
print("Status code:", resp.status_code)

try:
    data = resp.json()
except Exception:
    print("Non-JSON response:")
    print(resp.text)
    raise

if resp.status_code >= 400:
    print("Kalshi error response:")
    print(json.dumps(data, indent=2))
    raise ValueError(f"{market_ticker} was not found in /historical/markets/{{ticker}}")

# Kalshi usually returns {"market": {...}}
market = data.get("market", data)

print("\nRaw response:")
print(json.dumps(data, indent=2)[:10000])

print("\nAttributes returned:")
for key in sorted(market.keys()):
    print(key)

# DataFrame 1: one row with all market attributes as columns
df_historical_market = pd.DataFrame([market])

display(df_historical_market)

print("\nNumber of attributes:", len(df_historical_market.columns))
print("Columns:")
print(df_historical_market.columns.tolist())

# DataFrame 2: easier-to-read attribute/value table
df_historical_market_attributes = pd.DataFrame([
    {
        "attribute": key,
        "value": value
    }
    for key, value in market.items()
])

display(df_historical_market_attributes)

# Save both
df_historical_market.to_csv(
    f"historical_market_{market_ticker}_all_attributes.csv",
    index=False
)

df_historical_market_attributes.to_csv(
    f"historical_market_{market_ticker}_attribute_values.csv",
    index=False
)

URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/WRECSS-26-GER
Status code: 200

Raw response:
{
  "market": {
    "can_close_early": true,
    "close_time": "2025-11-03T18:12:29.373203Z",
    "created_time": "2024-04-22T23:39:53.037748Z",
    "custom_strike": {
      "Country": "Germany"
    },
    "early_close_condition": "If this event occurs, the market will close the following 10:00 AM ET.",
    "event_ticker": "WRECSS-26",
    "expected_expiration_time": "2026-12-31T15:00:00Z",
    "expiration_time": "2027-12-31T15:00:00Z",
    "expiration_value": "Yes",
    "fractional_trading_enabled": true,
    "last_price_dollars": "0.8500",
    "latest_expiration_time": "2027-12-31T15:00:00Z",
    "liquidity_dollars": "0.0000",
    "market_type": "binary",
    "no_ask_dollars": "1.0000",
    "no_bid_dollars": "0.0000",
    "no_sub_title": "Germany",
    "notional_value_dollars": "1.0000",
    "open_interest_fp": "0.00",
    "open_time": "2024-04-23T12:00:00Z",
    "previous_price_dollars": "0.8500",
    "previous_yes_ask_dollars": "1.0000",
    "previous_yes_bid_dollars": "0.0000",
    "price_level_structure": "deci_cent",
    "price_ranges": [
      {
        "end": "1.0000",
        "start": "0.0000",
        "step": "0.0010"
      }
    ],
    "response_price_units": "usd_cent",
    "result": "yes",
    "rules_primary": "If Germany has two consecutive quarters of negative real GDP growth between Jan 1, 2024 and Dec 31, 2026, then the market resolves to Yes.",
    "rules_secondary": "The exact dataset for Germany is Gross Domestic Product, Real, Seasonally Adjusted, Domestic Currency from the IMF.",
    "settlement_timer_seconds": 3600,
    "settlement_ts": "2025-11-03T19:12:32.482306Z",
    "settlement_value_dollars": "1.0000",
    "status": "finalized",
    "strike_type": "custom",
    "subtitle": "Germany",
    "ticker": "WRECSS-26-GER",
    "title": "Which countries will have recessions?",
    "updated_time": "2026-03-23T22:26:48.576397Z",
    "volume_24h_fp": "0.00",
    "volume_fp": "22433.00",
    "yes_ask_dollars": "1.0000",
    "yes_ask_size_fp": "0.00",
    "yes_bid_dollars": "0.0000",
    "yes_bid_size_fp": "0.00",
    "yes_sub_title": "Germany"
  }
}

Attributes returned:
can_close_early
close_time
created_time
custom_strike
early_close_condition
event_ticker
expected_expiration_time
expiration_time
expiration_value
fractional_trading_enabled
last_price_dollars
latest_expiration_time
liquidity_dollars
market_type
no_ask_dollars
no_bid_dollars
no_sub_title
notional_value_dollars
open_interest_fp
open_time
previous_price_dollars
previous_yes_ask_dollars
previous_yes_bid_dollars
price_level_structure
price_ranges
response_price_units
result
rules_primary
rules_secondary
settlement_timer_seconds
settlement_ts
settlement_value_dollars
status
strike_type
subtitle
ticker
title
updated_time
volume_24h_fp
volume_fp
yes_ask_dollars
yes_ask_size_fp
yes_bid_dollars
yes_bid_size_fp
yes_sub_title

,can_close_early,close_time,created_time,custom_strike,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,fractional_trading_enabled,...,ticker,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title
0,True,2025-11-03T18:12:29.373203Z,2024-04-22T23:39:53.037748Z,{'Country': 'Germany'},"If this event occurs, the market will close th...",WRECSS-26,2026-12-31T15:00:00Z,2027-12-31T15:00:00Z,Yes,True,...,WRECSS-26-GER,Which countries will have recessions?,2026-03-23T22:26:48.576397Z,0.00,22433.00,1.0000,0.00,0.0000,0.00,Germany

Number of attributes: 45
Columns:
['can_close_early', 'close_time', 'created_time', 'custom_strike', 'early_close_condition', 'event_ticker', 'expected_expiration_time', 'expiration_time', 'expiration_value', 'fractional_trading_enabled', 'last_price_dollars', 'latest_expiration_time', 'liquidity_dollars', 'market_type', 'no_ask_dollars', 'no_bid_dollars', 'no_sub_title', 'notional_value_dollars', 'open_interest_fp', 'open_time', 'previous_price_dollars', 'previous_yes_ask_dollars', 'previous_yes_bid_dollars', 'price_level_structure', 'price_ranges', 'response_price_units', 'result', 'rules_primary', 'rules_secondary', 'settlement_timer_seconds', 'settlement_ts', 'settlement_value_dollars', 'status', 'strike_type', 'subtitle', 'ticker', 'title', 'updated_time', 'volume_24h_fp', 'volume_fp', 'yes_ask_dollars', 'yes_ask_size_fp', 'yes_bid_dollars', 'yes_bid_size_fp', 'yes_sub_title']

,attribute,value
0,can_close_early,True
1,close_time,2025-11-03T18:12:29.373203Z
2,created_time,2024-04-22T23:39:53.037748Z
3,custom_strike,{'Country': 'Germany'}
4,early_close_condition,"If this event occurs, the market will close th..."
5,event_ticker,WRECSS-26
6,expected_expiration_time,2026-12-31T15:00:00Z
7,expiration_time,2027-12-31T15:00:00Z
8,expiration_value,Yes
9,fractional_trading_enabled,True
10,last_price_dollars,0.8500
11,latest_expiration_time,2027-12-31T15:00:00Z
12,liquidity_dollars,0.0000
13,market_type,binary
14,no_ask_dollars,1.0000
15,no_bid_dollars,0.0000
16,no_sub_title,Germany
17,notional_value_dollars,1.0000
18,open_interest_fp,0.00
19,open_time,2024-04-23T12:00:00Z
20,previous_price_dollars,0.8500
21,previous_yes_ask_dollars,1.0000
22,previous_yes_bid_dollars,0.0000
23,price_level_structure,deci_cent
24,price_ranges,"[{'end': '1.0000', 'start': '0.0000', 'step': ..."
25,response_price_units,usd_cent
26,result,yes
27,rules_primary,If Germany has two consecutive quarters of neg...
28,rules_secondary,The exact dataset for Germany is Gross Domesti...
29,settlement_timer_seconds,3600
30,settlement_ts,2025-11-03T19:12:32.482306Z
31,settlement_value_dollars,1.0000
32,status,finalized
33,strike_type,custom
34,subtitle,Germany
35,ticker,WRECSS-26-GER
36,title,Which countries will have recessions?
37,updated_time,2026-03-23T22:26:48.576397Z
38,volume_24h_fp,0.00
39,volume_fp,22433.00
40,yes_ask_dollars,1.0000
41,yes_ask_size_fp,0.00
42,yes_bid_dollars,0.0000
43,yes_bid_size_fp,0.00
44,yes_sub_title,Germany

# GET /historical/markets/{ticker}/candlesticks

In [ ]:
import requests
import pandas as pd
import json
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

market_ticker = "WRECSS-26-GER"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-historical-candlesticks-test/1.0"
})


def get_json_raw(path, params=None):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    resp = session.get(url, params=params or {}, timeout=30)

    print("URL:", resp.url)
    print("Status code:", resp.status_code)

    try:
        data = resp.json()
    except Exception:
        data = None
        print(resp.text)
        return resp, data

    if resp.status_code >= 400:
        print("Kalshi error response:")
        print(json.dumps(data, indent=2))
    else:
        print("Top-level keys:", list(data.keys()) if isinstance(data, dict) else type(data))

    return resp, data


# 1. Get historical market details first
market_resp, market_data = get_json_raw(f"/historical/markets/{market_ticker}")

if market_resp.status_code >= 400:
    raise ValueError("Market was not found in /historical/markets/{ticker}. Cannot request historical candlesticks.")

market = market_data.get("market", market_data)

open_time = pd.to_datetime(market.get("open_time"), utc=True, errors="coerce")
close_time = pd.to_datetime(
    market.get("close_time") or market.get("expiration_time") or market.get("settlement_ts"),
    utc=True,
    errors="coerce"
)

start_ts = int(open_time.timestamp())
end_ts = int(close_time.timestamp())

print("Market title:", market.get("title"))
print("Open time:", open_time)
print("End time:", close_time)

# 2. Get daily historical candlesticks
candles_resp, candles_data = get_json_raw(
    f"/historical/markets/{market_ticker}/candlesticks",
    params={
        "start_ts": start_ts,
        "end_ts": end_ts,
        "period_interval": 1440
    }
)

if candles_resp.status_code < 400:
    print("Raw candlestick response:")
    print(json.dumps(candles_data, indent=2)[:5000])

    df_historical_candlesticks = pd.DataFrame(
        candles_data.get("candlesticks", [])
    )

    print("Candlestick rows:", len(df_historical_candlesticks))
    print("Candlestick columns:", df_historical_candlesticks.columns.tolist())

    display(df_historical_candlesticks)

    df_historical_candlesticks.to_csv(
        f"kalshi_historical_daily_candlesticks_{market_ticker}.csv",
        index=False
    )

URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/WRECSS-26-GER
Status code: 200
Top-level keys: ['market']
Market title: Which countries will have recessions?
Open time: 2024-04-23 12:00:00+00:00
End time: 2025-11-03 18:12:29.373203+00:00
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/WRECSS-26-GER/candlesticks?start_ts=1713873600&end_ts=1762193549&period_interval=1440
Status code: 200
Top-level keys: ['candlesticks', 'ticker']
Raw candlestick response:
{
  "candlesticks": [
    {
      "end_period_ts": 1713931200,
      "open_interest": "1000.00",
      "price": {
        "close": "0.1400",
        "high": "0.1400",
        "low": "0.1200",
        "mean": "0.1320",
        "open": "0.1200",
        "previous": null
      },
      "volume": "1000.00",
      "yes_ask": {
        "close": "0.5000",
        "high": "1.0000",
        "low": "0.1200",
        "open": "1.0000"
      },
      "yes_bid": {
        "close": "0.0400",
        "high": "0.0400",
        "low": "0.0100",
        "open": "0.0100"
      }
    },
    {
      "end_period_ts": 1714017600,
      "open_interest": "1040.00",
      "price": {
        "close": "0.2400",
        "high": "0.2400",
        "low": "0.2400",
        "mean": "0.2400",
        "open": "0.2400",
        "previous": "0.1400"
      },
      "volume": "40.00",
      "yes_ask": {
        "close": "0.2400",
        "high": "0.5000",
        "low": "0.2400",
        "open": "0.5000"
      },
      "yes_bid": {
        "close": "0.1700",
        "high": "0.1700",
        "low": "0.0400",
        "open": "0.0400"
      }
    },
    {
      "end_period_ts": 1714104000,
      "open_interest": "1120.00",
      "price": {
        "close": "0.2400",
        "high": "0.2400",
        "low": "0.2400",
        "mean": "0.2400",
        "open": "0.2400",
        "previous": "0.2400"
      },
      "volume": "80.00",
      "yes_ask": {
        "close": "0.2400",
        "high": "0.3600",
        "low": "0.2400",
        "open": "0.2400"
      },
      "yes_bid": {
        "close": "0.1700",
        "high": "0.1700",
        "low": "0.0700",
        "open": "0.1700"
      }
    },
    {
      "end_period_ts": 1714363200,
      "open_interest": "1120.00",
      "price": {
        "close": "0.1700",
        "high": "0.1700",
        "low": "0.1700",
        "mean": "0.1700",
        "open": "0.1700",
        "previous": "0.2400"
      },
      "volume": "1.00",
      "yes_ask": {
        "close": "0.2400",
        "high": "0.2400",
        "low": "0.2400",
        "open": "0.2400"
      },
      "yes_bid": {
        "close": "0.1700",
        "high": "0.1700",
        "low": "0.1700",
        "open": "0.1700"
      }
    },
    {
      "end_period_ts": 1714881600,
      "open_interest": "1139.00",
      "price": {
        "close": "0.2400",
        "high": "0.2400",
        "low": "0.2400",
        "mean": "0.2400",
        "open": "0.2400",
        "previous": "0.1700"
      },
      "volume": "19.00",
      "yes_ask": {
        "close": "0.2400",
        "high": "0.2400",
        "low": "0.2400",
        "open": "0.2400"
      },
      "yes_bid": {
        "close": "0.1800",
        "high": "0.1800",
        "low": "0.1700",
        "open": "0.1700"
      }
    },
    {
      "end_period_ts": 1715140800,
      "open_interest": "1139.00",
      "price": {
        "close": null,
        "high": null,
        "low": null,
        "mean": null,
        "open": null,
        "previous": "0.2400"
      },
      "volume": "0.00",
      "yes_ask": {
        "close": "0.2400",
        "high": "0.2600",
        "low": "0.2400",
        "open": "0.2400"
      },
      "yes_bid": {
        "close": "0.1800",
        "high": "0.1800",
        "low": "0.1800",
        "open": "0.1800"
      }
    },
    {
      "end_period_ts": 1715400000,
      "open_interest": "1139.00",
      "price": {
        "close": null,
        "high": null,
        "low": null,
        "mean": null,
        "open": null,
        "previous": "0.2400"
      },
      "volume": "0.00",
      "yes_ask": {
        "close": "0.2400",
        "high": "0.2400",
        "low": "0.2400",
        "open": "0.2400"
      },
      "yes_bid": {
        "close": "0.1800",
        "high": "0.1900",
        "low": "0.1800",
        "open": "0.1800"
      }
    },
    {
      "end_period_ts": 1715659200,
      "open_interest": "1149.00",
      "price": {
        "close": "0.2400",
        "high": "0.2400",
        "low": "0.2400",
        "mean": "0.2400",
        "open": "0.2400",
        "previous": "0.2400"
      },
      "volume": "10.00",
      "yes_ask": {
        "close": "0.2400",
        "high": "0.2400",
        "low": "0.2400",
        "open": "0.2400"
      },
      "yes_bid": {
        "close": "0.1800",
        "high": "0.1800",
        "low": "0.1800",
        "open": "0.1800"
      }
    },
    {
      "end_period_ts": 1715745600,
      "open_interest": "1119.00",
      "price": {
        "close": "0.1700",
        "high": "0.1800",
        "low": "0.1700",
        "mean": "0.1725",
        "open": "0.1800",
        "previous": "0.2400"
      },
      "volume": "40.00",
      "yes_ask": {
        "close": "0.2300",
        "high": "0.2400",
        "low": "0.2300",
        "open": "0.2400"
      },
      "yes_bid": {
        "close": "0.1700",
        "high": "0.1800",
        "low": "0.1700",
        "open": "0.1800"
      }
    },
    {
      "end_period_ts": 1715832000,

Candlestick rows: 412
Candlestick columns: ['end_period_ts', 'open_interest', 'price', 'volume', 'yes_ask', 'yes_bid']

,end_period_ts,open_interest,price,volume,yes_ask,yes_bid
0,1713931200,1000.00,"{'close': '0.1400', 'high': '0.1400', 'low': '...",1000.00,"{'close': '0.5000', 'high': '1.0000', 'low': '...","{'close': '0.0400', 'high': '0.0400', 'low': '..."
1,1714017600,1040.00,"{'close': '0.2400', 'high': '0.2400', 'low': '...",40.00,"{'close': '0.2400', 'high': '0.5000', 'low': '...","{'close': '0.1700', 'high': '0.1700', 'low': '..."
2,1714104000,1120.00,"{'close': '0.2400', 'high': '0.2400', 'low': '...",80.00,"{'close': '0.2400', 'high': '0.3600', 'low': '...","{'close': '0.1700', 'high': '0.1700', 'low': '..."
3,1714363200,1120.00,"{'close': '0.1700', 'high': '0.1700', 'low': '...",1.00,"{'close': '0.2400', 'high': '0.2400', 'low': '...","{'close': '0.1700', 'high': '0.1700', 'low': '..."
4,1714881600,1139.00,"{'close': '0.2400', 'high': '0.2400', 'low': '...",19.00,"{'close': '0.2400', 'high': '0.2400', 'low': '...","{'close': '0.1800', 'high': '0.1800', 'low': '..."
...,...,...,...,...,...,...
407,1761796800,3053.00,"{'close': '0.5200', 'high': '0.5200', 'low': '...",3.00,"{'close': '0.5200', 'high': '0.5200', 'low': '...","{'close': '0.4700', 'high': '0.4700', 'low': '..."
408,1761883200,5125.00,"{'close': '0.6700', 'high': '0.6700', 'low': '...",2072.00,"{'close': '0.6400', 'high': '0.8400', 'low': '...","{'close': '0.5800', 'high': '0.5800', 'low': '..."
409,1761969600,6035.00,"{'close': '0.9200', 'high': '0.9600', 'low': '...",5349.00,"{'close': '0.9200', 'high': '0.9700', 'low': '...","{'close': '0.8600', 'high': '0.9300', 'low': '..."
410,1762056000,6008.00,"{'close': '0.8500', 'high': '0.9300', 'low': '...",57.00,"{'close': '0.8900', 'high': '0.9300', 'low': '...","{'close': '0.8500', 'high': '0.8800', 'low': '..."
411,1762142400,6008.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.8900', 'high': '0.8900', 'low': '...","{'close': '0.8600', 'high': '0.8600', 'low': '..."

# Trying to get Candlesticks + Volume Data

In [1]:
import time
import json
import requests
import pandas as pd
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

MARKET_TICKER = "KXELECTIONMOVZOHRAN-25-ZMAM-B7.5"
EVENT_TICKER = "KXELECTIONMOVZOHRAN-25"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-closed-market-full-data-colab/1.0"
})


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        if 500 <= resp.status_code < 600:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Server error {resp.status_code}. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        try:
            data = resp.json()
        except Exception:
            data = {"raw_text": resp.text}

        return {
            "ok": resp.ok,
            "status_code": resp.status_code,
            "url": resp.url,
            "data": data
        }

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def paginate(path, collection_key, params=None, limit=200, sleep_s=0.25):
    params = dict(params or {})
    params["limit"] = limit

    rows = []
    cursor = None

    while True:
        if cursor:
            params["cursor"] = cursor
        else:
            params.pop("cursor", None)

        result = get_json(path, params=params)

        if not result["ok"]:
            print("Bad URL:", result["url"])
            print("Response:", json.dumps(result["data"], indent=2)[:3000])
            break

        data = result["data"]
        rows.extend(data.get(collection_key, []))

        cursor = data.get("cursor")
        if not cursor:
            break

        time.sleep(sleep_s)

    return rows


def extract_object(data, key):
    if isinstance(data, dict):
        return data.get(key, data)
    return {}


def to_number(x):
    return pd.to_numeric(x, errors="coerce")


# ------------------------------------------------------------
# 1. Get market details: try historical first, then live/recent
# ------------------------------------------------------------
historical_market_resp = get_json(f"/historical/markets/{MARKET_TICKER}")

if historical_market_resp["ok"]:
    market_source = "historical"
    market = extract_object(historical_market_resp["data"], "market")
else:
    print("Not found in historical endpoint. Trying live/recent endpoint...")
    print("Historical response:", json.dumps(historical_market_resp["data"], indent=2)[:2000])

    live_market_resp = get_json(f"/markets/{MARKET_TICKER}")

    if not live_market_resp["ok"]:
        print("Live/recent response:", json.dumps(live_market_resp["data"], indent=2)[:2000])
        raise ValueError("Market was not found in historical or live/recent market endpoints.")

    market_source = "live"
    market = extract_object(live_market_resp["data"], "market")

df_market_details = pd.DataFrame([market])
print("Market source:", market_source)
print("Market detail columns:", df_market_details.columns.tolist())
display(df_market_details)

df_market_details.to_csv(f"market_details_{MARKET_TICKER}.csv", index=False)


# ------------------------------------------------------------
# 2. Get event details
# ------------------------------------------------------------
event_resp = get_json(f"/events/{EVENT_TICKER}")

if event_resp["ok"]:
    event = extract_object(event_resp["data"], "event")
    df_event_details = pd.DataFrame([event])
else:
    print("Event details error:", json.dumps(event_resp["data"], indent=2)[:2000])
    event = {}
    df_event_details = pd.DataFrame()

display(df_event_details)

if not df_event_details.empty:
    df_event_details.to_csv(f"event_details_{EVENT_TICKER}.csv", index=False)


# ------------------------------------------------------------
# 3. Get event metadata, if available
# ------------------------------------------------------------
event_metadata_resp = get_json(f"/events/{EVENT_TICKER}/metadata")

if event_metadata_resp["ok"]:
    event_metadata = event_metadata_resp["data"]
    df_event_metadata = pd.DataFrame([event_metadata])
else:
    print("Event metadata not available or errored:")
    print(json.dumps(event_metadata_resp["data"], indent=2)[:2000])
    df_event_metadata = pd.DataFrame()

display(df_event_metadata)

if not df_event_metadata.empty:
    df_event_metadata.to_csv(f"event_metadata_{EVENT_TICKER}.csv", index=False)


# ------------------------------------------------------------
# 4. Get all markets in this event: live/recent + historical
# ------------------------------------------------------------
live_event_markets = paginate(
    "/markets",
    "markets",
    params={
        "event_ticker": EVENT_TICKER
    },
    limit=200
)

for m in live_event_markets:
    m["_source"] = "live"

historical_event_markets = paginate(
    "/historical/markets",
    "markets",
    params={
        "event_ticker": EVENT_TICKER
    },
    limit=200
)

for m in historical_event_markets:
    m["_source"] = "historical"

markets_by_ticker = {}

for m in live_event_markets + historical_event_markets:
    t = m.get("ticker")
    if t:
        markets_by_ticker[t] = m

all_event_markets = list(markets_by_ticker.values())

df_event_markets = pd.DataFrame(all_event_markets)

print("Live/recent event markets:", len(live_event_markets))
print("Historical event markets:", len(historical_event_markets))
print("Unique event markets:", len(df_event_markets))

display(df_event_markets)

df_event_markets.to_csv(f"all_markets_for_event_{EVENT_TICKER}.csv", index=False)


# ------------------------------------------------------------
# 5. Determine time range and series ticker
# ------------------------------------------------------------
series_ticker = (
    market.get("series_ticker")
    or event.get("series_ticker")
)

if not series_ticker:
    # Fallback guess from event ticker: KXELECTIONMOVZOHRAN-25 -> KXELECTIONMOVZOHRAN
    series_ticker = EVENT_TICKER.rsplit("-", 1)[0]

print("Series ticker:", series_ticker)

open_time = pd.to_datetime(market.get("open_time"), utc=True, errors="coerce")

end_time = pd.to_datetime(
    market.get("close_time") or market.get("expiration_time") or market.get("settlement_ts"),
    utc=True,
    errors="coerce"
)

if pd.isna(open_time):
    raise ValueError("Market open_time is missing, so start_ts cannot be created.")

if pd.isna(end_time):
    end_time = pd.Timestamp.now(tz="UTC")

start_ts = int(open_time.timestamp())
end_ts = int(end_time.timestamp())

print("Candlestick start:", open_time)
print("Candlestick end:", end_time)


# ------------------------------------------------------------
# 6. Get market candlesticks: daily + all valid intervals
# ------------------------------------------------------------
# Kalshi valid intervals:
# 1 = 1 minute
# 60 = 1 hour
# 1440 = 1 day

intervals = {
    1: "1min",
    60: "hourly",
    1440: "daily"
}

market_candle_dfs = {}

for period_interval, label in intervals.items():
    print(f"Getting market {label} candlesticks...")

    if market_source == "historical":
        candle_path = f"/historical/markets/{MARKET_TICKER}/candlesticks"
    else:
        candle_path = f"/series/{series_ticker}/markets/{MARKET_TICKER}/candlesticks"

    candle_resp = get_json(
        candle_path,
        params={
            "start_ts": start_ts,
            "end_ts": end_ts,
            "period_interval": period_interval
        }
    )

    print(label, "status:", candle_resp["status_code"])
    print(label, "URL:", candle_resp["url"])

    if candle_resp["ok"]:
        df_candles = pd.DataFrame(candle_resp["data"].get("candlesticks", []))
        df_candles["market_ticker"] = MARKET_TICKER
        df_candles["event_ticker"] = EVENT_TICKER
        df_candles["series_ticker"] = series_ticker
        df_candles["period_interval"] = period_interval
        df_candles["period_label"] = label

        market_candle_dfs[label] = df_candles

        print(label, "rows:", len(df_candles))
        print(label, "columns:", df_candles.columns.tolist())
        display(df_candles.head())

        df_candles.to_csv(
            f"market_{label}_candlesticks_{MARKET_TICKER}.csv",
            index=False
        )
    else:
        print(f"{label} candlestick error:")
        print(json.dumps(candle_resp["data"], indent=2)[:3000])

if market_candle_dfs:
    df_all_market_candlesticks = pd.concat(
        market_candle_dfs.values(),
        ignore_index=True
    )
else:
    df_all_market_candlesticks = pd.DataFrame()

display(df_all_market_candlesticks)
df_all_market_candlesticks.to_csv(
    f"all_market_candlesticks_{MARKET_TICKER}.csv",
    index=False
)

df_daily_market_candlesticks = market_candle_dfs.get("daily", pd.DataFrame())
display(df_daily_market_candlesticks)


# ------------------------------------------------------------
# 7. Add cumulative daily volume if daily candle volume exists
# ------------------------------------------------------------
df_daily_market_candlesticks_with_cumulative = df_daily_market_candlesticks.copy()

if not df_daily_market_candlesticks_with_cumulative.empty:
    volume_cols = [
        c for c in df_daily_market_candlesticks_with_cumulative.columns
        if "volume" in c.lower()
    ]

    print("Daily candlestick volume-like columns:", volume_cols)

    for col in volume_cols:
        numeric_col = f"{col}_numeric"
        cumulative_col = f"cumulative_{col}"

        df_daily_market_candlesticks_with_cumulative[numeric_col] = to_number(
            df_daily_market_candlesticks_with_cumulative[col]
        )

        df_daily_market_candlesticks_with_cumulative[cumulative_col] = (
            df_daily_market_candlesticks_with_cumulative[numeric_col]
            .fillna(0)
            .cumsum()
        )

display(df_daily_market_candlesticks_with_cumulative)

df_daily_market_candlesticks_with_cumulative.to_csv(
    f"daily_market_candlesticks_with_cumulative_{MARKET_TICKER}.csv",
    index=False
)


# ------------------------------------------------------------
# 8. Event-level daily candlesticks
# ------------------------------------------------------------
event_daily_resp = get_json(
    f"/series/{series_ticker}/events/{EVENT_TICKER}/candlesticks",
    params={
        "start_ts": start_ts,
        "end_ts": end_ts,
        "period_interval": 1440
    }
)

print("Event daily candlesticks status:", event_daily_resp["status_code"])
print("Event daily candlesticks URL:", event_daily_resp["url"])

if event_daily_resp["ok"]:
    df_event_daily_candlesticks = pd.DataFrame(
        event_daily_resp["data"].get("candlesticks", [])
    )
    df_event_daily_candlesticks["event_ticker"] = EVENT_TICKER
    df_event_daily_candlesticks["series_ticker"] = series_ticker

    display(df_event_daily_candlesticks)

    df_event_daily_candlesticks.to_csv(
        f"event_daily_candlesticks_{EVENT_TICKER}.csv",
        index=False
    )
else:
    print("Event daily candlesticks error:")
    print(json.dumps(event_daily_resp["data"], indent=2)[:3000])
    df_event_daily_candlesticks = pd.DataFrame()


# ------------------------------------------------------------
# 9. Event-level volume summary across all markets
# ------------------------------------------------------------
df_event_volume_summary = pd.DataFrame()

if not df_event_markets.empty:
    dfv = df_event_markets.copy()

    if "volume_fp" in dfv.columns:
        dfv["volume_contracts"] = to_number(dfv["volume_fp"])
    elif "volume" in dfv.columns:
        dfv["volume_contracts"] = to_number(dfv["volume"])
    else:
        dfv["volume_contracts"] = pd.NA

    if "volume_24h_fp" in dfv.columns:
        dfv["volume_24h_contracts"] = to_number(dfv["volume_24h_fp"])
    elif "volume_24h" in dfv.columns:
        dfv["volume_24h_contracts"] = to_number(dfv["volume_24h"])
    else:
        dfv["volume_24h_contracts"] = pd.NA

    if "notional_value_dollars" in dfv.columns:
        dfv["notional_value_dollars_numeric"] = to_number(dfv["notional_value_dollars"])
    else:
        dfv["notional_value_dollars_numeric"] = 1.0

    # This is NOT exact cash spent. It is notional contract volume.
    dfv["estimated_notional_volume_dollars"] = (
        dfv["volume_contracts"] * dfv["notional_value_dollars_numeric"]
    )

    df_event_volume_by_market = dfv[[
        c for c in [
            "ticker",
            "_source",
            "title",
            "status",
            "result",
            "volume_fp",
            "volume_contracts",
            "volume_24h_fp",
            "volume_24h_contracts",
            "notional_value_dollars",
            "estimated_notional_volume_dollars"
        ]
        if c in dfv.columns
    ]].copy()

    display(df_event_volume_by_market)

    df_event_volume_summary = pd.DataFrame([{
        "event_ticker": EVENT_TICKER,
        "series_ticker": series_ticker,
        "n_markets": len(dfv),
        "total_volume_contracts": dfv["volume_contracts"].sum(skipna=True),
        "total_24h_volume_contracts": dfv["volume_24h_contracts"].sum(skipna=True),
        "estimated_total_notional_volume_dollars": dfv["estimated_notional_volume_dollars"].sum(skipna=True),
        "note": "Dollar value is not exact cash paid; it is contract volume multiplied by notional value when available."
    }])

    display(df_event_volume_summary)

    df_event_volume_by_market.to_csv(
        f"event_volume_by_market_{EVENT_TICKER}.csv",
        index=False
    )

    df_event_volume_summary.to_csv(
        f"event_volume_summary_{EVENT_TICKER}.csv",
        index=False
    )

print("Done.")

Market source: historical
Market detail columns: ['can_close_early', 'cap_strike', 'close_time', 'created_time', 'early_close_condition', 'event_ticker', 'expected_expiration_time', 'expiration_time', 'expiration_value', 'floor_strike', 'fractional_trading_enabled', 'last_price_dollars', 'latest_expiration_time', 'liquidity_dollars', 'market_type', 'no_ask_dollars', 'no_bid_dollars', 'no_sub_title', 'notional_value_dollars', 'open_interest_fp', 'open_time', 'previous_price_dollars', 'previous_yes_ask_dollars', 'previous_yes_bid_dollars', 'price_level_structure', 'price_ranges', 'response_price_units', 'result', 'rules_primary', 'rules_secondary', 'settlement_timer_seconds', 'settlement_ts', 'settlement_value_dollars', 'status', 'strike_type', 'ticker', 'title', 'updated_time', 'volume_24h_fp', 'volume_fp', 'yes_ask_dollars', 'yes_ask_size_fp', 'yes_bid_dollars', 'yes_bid_size_fp', 'yes_sub_title']

,can_close_early,cap_strike,close_time,created_time,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,...,ticker,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title
0,True,8.99,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,6,...,KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,Margin of victory for Zohran Mamdani in the Ma...,2026-03-04T22:43:52.624601Z,0.00,3398478.00,1.0000,0.00,0.0000,0.00,6-8.99%

,available_on_brokers,category,collateral_return_type,event_ticker,last_updated_ts,mutually_exclusive,series_ticker,settlement_sources,strike_period,sub_title,title
0,True,Elections,MECNET,KXELECTIONMOVZOHRAN-25,0001-01-01T00:00:00Z,True,KXELECTIONMOVZOHRAN,[{'name': 'Board of Elections in the City of N...,,In 2025,Margin of victory for Zohran Mamdani in the NY...

,featured_image_url,image_url,market_details,settlement_sources
0,https://kalshi-fallback-images.s3.amazonaws.co...,https://kalshi-public-docs.s3.amazonaws.com/se...,"[{'color_code': '#AA00FF', 'image_url': 'https...",[{'name': 'Board of Elections in the City of N...

Live/recent event markets: 0
Historical event markets: 10
Unique event markets: 10

,can_close_early,close_time,created_time,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,fractional_trading_enabled,...,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,_source,cap_strike,subtitle
0,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,24.0,True,...,0.00,2715311.00,1.0000,0.00,0.0000,0.00,24% or more,historical,NaN,NaN
1,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,6.0,True,...,0.00,3398478.00,1.0000,0.00,0.0000,0.00,6-8.99%,historical,8.99,NaN
2,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,21.0,True,...,0.00,922621.00,1.0000,0.00,0.0000,0.00,21-23.99%,historical,23.99,NaN
3,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,18.0,True,...,0.00,819153.00,1.0000,0.00,0.0000,0.00,18-20.99%,historical,20.99,NaN
4,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,15.0,True,...,0.00,923736.00,1.0000,0.00,0.0000,0.00,15-17.99%,historical,17.99,NaN
5,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,12.0,True,...,0.00,1454986.00,1.0000,0.00,0.0000,0.00,12-14.99%,historical,14.99,NaN
6,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,9.0,True,...,0.00,2641908.00,1.0000,0.00,0.0000,0.00,9-11.99%,historical,11.99,NaN
7,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,NaN,True,...,0.00,1488079.00,1.0000,0.00,0.0000,0.00,Less than 0%,historical,0.00,:: Loses
8,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,3.0,True,...,0.00,1689089.00,1.0000,0.00,0.0000,0.00,3-5.99%,historical,5.99,NaN
9,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,0.0,True,...,0.00,1256254.00,1.0000,0.00,0.0000,0.00,0-2.99%,historical,2.99,NaN

Series ticker: KXELECTIONMOVZOHRAN
Candlestick start: 2025-08-13 14:00:00+00:00
Candlestick end: 2025-12-03 01:44:48.719034+00:00
Getting market 1min candlesticks...
1min status: 400
1min URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B7.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
1min candlestick error:
{
  "error": {
    "code": "bad_request",
    "message": "bad request",
    "details": "requested time range with candlesticks: 160544.800000, max candlesticks: 5000"
  }
}
Getting market hourly candlesticks...
hourly status: 200
hourly URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B7.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=60
hourly rows: 2630
hourly columns: ['end_period_ts', 'open_interest', 'price', 'volume', 'yes_ask', 'yes_bid', 'market_ticker', 'event_ticker', 'series_ticker', 'period_interval', 'period_label']

,end_period_ts,open_interest,price,volume,yes_ask,yes_bid,market_ticker,event_ticker,series_ticker,period_interval,period_label
0,1755097200,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.1100', 'high': '1.0000', 'low': '...","{'close': '0.0400', 'high': '0.0400', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,60,hourly
1,1755100800,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.1100', 'high': '0.1100', 'low': '...","{'close': '0.0400', 'high': '0.0400', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,60,hourly
2,1755104400,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.1100', 'high': '0.1100', 'low': '...","{'close': '0.0400', 'high': '0.0400', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,60,hourly
3,1755108000,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.1000', 'high': '0.1100', 'low': '...","{'close': '0.0300', 'high': '0.0400', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,60,hourly
4,1755111600,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.1000', 'low': '...","{'close': '0.0300', 'high': '0.0300', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,60,hourly

Getting market daily candlesticks...
daily status: 200
daily URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B7.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440
daily rows: 111
daily columns: ['end_period_ts', 'open_interest', 'price', 'volume', 'yes_ask', 'yes_bid', 'market_ticker', 'event_ticker', 'series_ticker', 'period_interval', 'period_label']

,end_period_ts,open_interest,price,volume,yes_ask,yes_bid,market_ticker,event_ticker,series_ticker,period_interval,period_label
0,1755144000,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '1.0000', 'low': '...","{'close': '0.0100', 'high': '0.0400', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
1,1755230400,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.1100', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
2,1755316800,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.1100', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
3,1755403200,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.0800', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
4,1755489600,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.0800', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily

,end_period_ts,open_interest,price,volume,yes_ask,yes_bid,market_ticker,event_ticker,series_ticker,period_interval,period_label
0,1755097200,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.1100', 'high': '1.0000', 'low': '...","{'close': '0.0400', 'high': '0.0400', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,60,hourly
1,1755100800,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.1100', 'high': '0.1100', 'low': '...","{'close': '0.0400', 'high': '0.0400', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,60,hourly
2,1755104400,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.1100', 'high': '0.1100', 'low': '...","{'close': '0.0400', 'high': '0.0400', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,60,hourly
3,1755108000,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.1000', 'high': '0.1100', 'low': '...","{'close': '0.0300', 'high': '0.0400', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,60,hourly
4,1755111600,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.1000', 'low': '...","{'close': '0.0300', 'high': '0.0300', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,60,hourly
...,...,...,...,...,...,...,...,...,...,...,...
2736,1764306000,848491.00,"{'close': '0.3400', 'high': '0.3700', 'low': '...",5074.00,"{'close': '0.3400', 'high': '0.3700', 'low': '...","{'close': '0.3300', 'high': '0.3600', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
2737,1764392400,850772.00,"{'close': '0.3200', 'high': '0.3700', 'low': '...",5156.00,"{'close': '0.3300', 'high': '0.3700', 'low': '...","{'close': '0.3200', 'high': '0.3600', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
2738,1764478800,850025.00,"{'close': '0.3200', 'high': '0.3300', 'low': '...",4502.00,"{'close': '0.3200', 'high': '0.3300', 'low': '...","{'close': '0.3100', 'high': '0.3200', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
2739,1764565200,857026.00,"{'close': '0.3100', 'high': '0.3900', 'low': '...",10842.00,"{'close': '0.3200', 'high': '0.3900', 'low': '...","{'close': '0.3100', 'high': '0.3800', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
2740,1764651600,857517.00,"{'close': '0.3200', 'high': '0.3400', 'low': '...",5106.00,"{'close': '0.3300', 'high': '0.3500', 'low': '...","{'close': '0.3200', 'high': '0.3300', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily

,end_period_ts,open_interest,price,volume,yes_ask,yes_bid,market_ticker,event_ticker,series_ticker,period_interval,period_label
0,1755144000,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '1.0000', 'low': '...","{'close': '0.0100', 'high': '0.0400', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
1,1755230400,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.1100', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
2,1755316800,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.1100', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
3,1755403200,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.0800', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
4,1755489600,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.0800', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
...,...,...,...,...,...,...,...,...,...,...,...
106,1764306000,848491.00,"{'close': '0.3400', 'high': '0.3700', 'low': '...",5074.00,"{'close': '0.3400', 'high': '0.3700', 'low': '...","{'close': '0.3300', 'high': '0.3600', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
107,1764392400,850772.00,"{'close': '0.3200', 'high': '0.3700', 'low': '...",5156.00,"{'close': '0.3300', 'high': '0.3700', 'low': '...","{'close': '0.3200', 'high': '0.3600', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
108,1764478800,850025.00,"{'close': '0.3200', 'high': '0.3300', 'low': '...",4502.00,"{'close': '0.3200', 'high': '0.3300', 'low': '...","{'close': '0.3100', 'high': '0.3200', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
109,1764565200,857026.00,"{'close': '0.3100', 'high': '0.3900', 'low': '...",10842.00,"{'close': '0.3200', 'high': '0.3900', 'low': '...","{'close': '0.3100', 'high': '0.3800', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily
110,1764651600,857517.00,"{'close': '0.3200', 'high': '0.3400', 'low': '...",5106.00,"{'close': '0.3300', 'high': '0.3500', 'low': '...","{'close': '0.3200', 'high': '0.3300', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily

Daily candlestick volume-like columns: ['volume']

,end_period_ts,open_interest,price,volume,yes_ask,yes_bid,market_ticker,event_ticker,series_ticker,period_interval,period_label,volume_numeric,cumulative_volume
0,1755144000,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '1.0000', 'low': '...","{'close': '0.0100', 'high': '0.0400', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily,0.0,0.0
1,1755230400,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.1100', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily,0.0,0.0
2,1755316800,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.1100', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily,0.0,0.0
3,1755403200,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.0800', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily,0.0,0.0
4,1755489600,0.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0800', 'high': '0.0800', 'low': '...","{'close': '0.0100', 'high': '0.0100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,1764306000,848491.00,"{'close': '0.3400', 'high': '0.3700', 'low': '...",5074.00,"{'close': '0.3400', 'high': '0.3700', 'low': '...","{'close': '0.3300', 'high': '0.3600', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily,5074.0,3255893.0
107,1764392400,850772.00,"{'close': '0.3200', 'high': '0.3700', 'low': '...",5156.00,"{'close': '0.3300', 'high': '0.3700', 'low': '...","{'close': '0.3200', 'high': '0.3600', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily,5156.0,3261049.0
108,1764478800,850025.00,"{'close': '0.3200', 'high': '0.3300', 'low': '...",4502.00,"{'close': '0.3200', 'high': '0.3300', 'low': '...","{'close': '0.3100', 'high': '0.3200', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily,4502.0,3265551.0
109,1764565200,857026.00,"{'close': '0.3100', 'high': '0.3900', 'low': '...",10842.00,"{'close': '0.3200', 'high': '0.3900', 'low': '...","{'close': '0.3100', 'high': '0.3800', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily,10842.0,3276393.0
110,1764651600,857517.00,"{'close': '0.3200', 'high': '0.3400', 'low': '...",5106.00,"{'close': '0.3300', 'high': '0.3500', 'low': '...","{'close': '0.3200', 'high': '0.3300', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,1440,daily,5106.0,3281499.0

Event daily candlesticks status: 200
Event daily candlesticks URL: https://external-api.kalshi.com/trade-api/v2/series/KXELECTIONMOVZOHRAN/events/KXELECTIONMOVZOHRAN-25/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440

Empty DataFrame
Columns: [event_ticker, series_ticker]
Index: []

,ticker,_source,title,status,result,volume_fp,volume_contracts,volume_24h_fp,volume_24h_contracts,notional_value_dollars,estimated_notional_volume_dollars
0,KXELECTIONMOVZOHRAN-25-ZMAM-T24,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2715311.00,2715311.0,0.00,0.0,1.0000,2715311.0
1,KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,3398478.00,3398478.0,0.00,0.0,1.0000,3398478.0
2,KXELECTIONMOVZOHRAN-25-ZMAM-B22.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,922621.00,922621.0,0.00,0.0,1.0000,922621.0
3,KXELECTIONMOVZOHRAN-25-ZMAM-B19.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,819153.00,819153.0,0.00,0.0,1.0000,819153.0
4,KXELECTIONMOVZOHRAN-25-ZMAM-B16.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,923736.00,923736.0,0.00,0.0,1.0000,923736.0
5,KXELECTIONMOVZOHRAN-25-ZMAM-B13.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1454986.00,1454986.0,0.00,0.0,1.0000,1454986.0
6,KXELECTIONMOVZOHRAN-25-ZMAM-B10.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,yes,2641908.00,2641908.0,0.00,0.0,1.0000,2641908.0
7,KXELECTIONMOVZOHRAN-25-ZMAM-T0,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1488079.00,1488079.0,0.00,0.0,1.0000,1488079.0
8,KXELECTIONMOVZOHRAN-25-ZMAM-B4.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1689089.00,1689089.0,0.00,0.0,1.0000,1689089.0
9,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1256254.00,1256254.0,0.00,0.0,1.0000,1256254.0

,event_ticker,series_ticker,n_markets,total_volume_contracts,total_24h_volume_contracts,estimated_total_notional_volume_dollars,note
0,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,10,17309615.0,0.0,17309615.0,Dollar value is not exact cash paid; it is con...

Done.

In [2]:
import time
import json
import requests
import pandas as pd
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"
EVENT_TICKER = "KXELECTIONMOVZOHRAN-25"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-event-markets-colab/1.0"
})


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        if 500 <= resp.status_code < 600:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Server error {resp.status_code}. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        try:
            data = resp.json()
        except Exception:
            data = {"raw_text": resp.text}

        if resp.status_code >= 400:
            print("Bad URL:", resp.url)
            print("Kalshi response:", json.dumps(data, indent=2)[:3000])
            resp.raise_for_status()

        return data

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def paginate(path, collection_key, params=None, limit=200, sleep_s=0.25):
    params = dict(params or {})
    params["limit"] = limit

    rows = []
    cursor = None

    while True:
        if cursor:
            params["cursor"] = cursor
        else:
            params.pop("cursor", None)

        data = get_json(path, params=params)
        rows.extend(data.get(collection_key, []))

        cursor = data.get("cursor")
        if not cursor:
            break

        time.sleep(sleep_s)

    return rows


# 1. Get event details
event_data = get_json(f"/events/{EVENT_TICKER}")
event = event_data.get("event", event_data)

df_event_details = pd.DataFrame([event])
display(df_event_details)

series_ticker = event.get("series_ticker")
print("Series ticker:", series_ticker)


# 2. Get live/recent markets for this event
live_markets = []

try:
    live_markets = paginate(
        "/markets",
        "markets",
        params={
            "event_ticker": EVENT_TICKER
        },
        limit=200
    )

    for m in live_markets:
        m["_source"] = "live_or_recent"

except Exception as e:
    print("Could not fetch live/recent markets:", e)


# 3. Get historical markets for this event
historical_markets = []

try:
    historical_markets = paginate(
        "/historical/markets",
        "markets",
        params={
            "event_ticker": EVENT_TICKER
        },
        limit=200
    )

    for m in historical_markets:
        m["_source"] = "historical"

except Exception as e:
    print("Could not fetch historical markets:", e)


# 4. Combine and deduplicate by market ticker
markets_by_ticker = {}

for market in live_markets + historical_markets:
    ticker = market.get("ticker")
    if ticker:
        if ticker in markets_by_ticker:
            old_source = markets_by_ticker[ticker].get("_source", "")
            new_source = market.get("_source", "")
            market["_source"] = f"{old_source}+{new_source}"
        markets_by_ticker[ticker] = market

all_markets = list(markets_by_ticker.values())

df_event_markets = pd.DataFrame(all_markets)

print("Live/recent markets:", len(live_markets))
print("Historical markets:", len(historical_markets))
print("Unique markets total:", len(df_event_markets))

display(df_event_markets)

# 5. Cleaner ticker table
wanted_cols = [
    "ticker",
    "event_ticker",
    "series_ticker",
    "_source",
    "title",
    "subtitle",
    "yes_sub_title",
    "no_sub_title",
    "status",
    "result",
    "created_time",
    "open_time",
    "close_time",
    "expiration_time",
    "settlement_ts",
    "notional_value_dollars",
    "volume",
    "volume_fp",
    "volume_24h",
    "volume_24h_fp",
    "open_interest",
    "liquidity",
    "yes_bid",
    "yes_ask",
    "no_bid",
    "no_ask",
    "last_price",
    "rules_primary",
    "rules_secondary"
]

existing_cols = [c for c in wanted_cols if c in df_event_markets.columns]

df_event_market_summary = df_event_markets[existing_cols].copy()

display(df_event_market_summary)

# 6. Save files
df_event_details.to_csv(
    f"kalshi_event_details_{EVENT_TICKER}.csv",
    index=False
)

df_event_markets.to_csv(
    f"kalshi_all_markets_for_event_{EVENT_TICKER}.csv",
    index=False
)

df_event_market_summary.to_csv(
    f"kalshi_market_summary_for_event_{EVENT_TICKER}.csv",
    index=False
)

,available_on_brokers,category,collateral_return_type,event_ticker,last_updated_ts,mutually_exclusive,series_ticker,settlement_sources,strike_period,sub_title,title
0,True,Elections,MECNET,KXELECTIONMOVZOHRAN-25,0001-01-01T00:00:00Z,True,KXELECTIONMOVZOHRAN,[{'name': 'Board of Elections in the City of N...,,In 2025,Margin of victory for Zohran Mamdani in the NY...

Series ticker: KXELECTIONMOVZOHRAN
Live/recent markets: 0
Historical markets: 10
Unique markets total: 10

,can_close_early,close_time,created_time,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,fractional_trading_enabled,...,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,_source,cap_strike,subtitle
0,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,24.0,True,...,0.00,2715311.00,1.0000,0.00,0.0000,0.00,24% or more,historical,NaN,NaN
1,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,6.0,True,...,0.00,3398478.00,1.0000,0.00,0.0000,0.00,6-8.99%,historical,8.99,NaN
2,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,21.0,True,...,0.00,922621.00,1.0000,0.00,0.0000,0.00,21-23.99%,historical,23.99,NaN
3,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,18.0,True,...,0.00,819153.00,1.0000,0.00,0.0000,0.00,18-20.99%,historical,20.99,NaN
4,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,15.0,True,...,0.00,923736.00,1.0000,0.00,0.0000,0.00,15-17.99%,historical,17.99,NaN
5,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,12.0,True,...,0.00,1454986.00,1.0000,0.00,0.0000,0.00,12-14.99%,historical,14.99,NaN
6,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,9.0,True,...,0.00,2641908.00,1.0000,0.00,0.0000,0.00,9-11.99%,historical,11.99,NaN
7,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,NaN,True,...,0.00,1488079.00,1.0000,0.00,0.0000,0.00,Less than 0%,historical,0.00,:: Loses
8,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,3.0,True,...,0.00,1689089.00,1.0000,0.00,0.0000,0.00,3-5.99%,historical,5.99,NaN
9,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,0.0,True,...,0.00,1256254.00,1.0000,0.00,0.0000,0.00,0-2.99%,historical,2.99,NaN

,ticker,event_ticker,_source,title,subtitle,yes_sub_title,no_sub_title,status,result,created_time,open_time,close_time,expiration_time,settlement_ts,notional_value_dollars,volume_fp,volume_24h_fp,rules_primary,rules_secondary
0,KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,24% or more,24% or more,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,2715311.00,0.00,If the popular vote margin of victory is 24% o...,The margin of victory is calculated by taking ...
1,KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,6-8.99%,6-8.99%,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,3398478.00,0.00,If the popular vote margin of victory is 6-8.9...,The margin of victory is calculated by taking ...
2,KXELECTIONMOVZOHRAN-25-ZMAM-B22.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,21-23.99%,21-23.99%,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,922621.00,0.00,If the popular vote margin of victory is 21-23...,The margin of victory is calculated by taking ...
3,KXELECTIONMOVZOHRAN-25-ZMAM-B19.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,18-20.99%,18-20.99%,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,819153.00,0.00,If the popular vote margin of victory is 18-20...,The margin of victory is calculated by taking ...
4,KXELECTIONMOVZOHRAN-25-ZMAM-B16.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,15-17.99%,15-17.99%,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,923736.00,0.00,If the popular vote margin of victory is 15-17...,The margin of victory is calculated by taking ...
5,KXELECTIONMOVZOHRAN-25-ZMAM-B13.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,12-14.99%,12-14.99%,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,1454986.00,0.00,If the popular vote margin of victory is 12-14...,The margin of victory is calculated by taking ...
6,KXELECTIONMOVZOHRAN-25-ZMAM-B10.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,9-11.99%,9-11.99%,finalized,yes,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,2641908.00,0.00,If the popular vote margin of victory is 9-11....,The margin of victory is calculated by taking ...
7,KXELECTIONMOVZOHRAN-25-ZMAM-T0,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,:: Loses,Less than 0%,Less than 0%,finalized,no,2025-08-12T21:46:06.121613Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,1488079.00,0.00,If the popular vote margin of victory is 0% or...,The margin of victory is calculated by taking ...
8,KXELECTIONMOVZOHRAN-25-ZMAM-B4.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,3-5.99%,3-5.99%,finalized,no,2025-08-12T21:46:06.121613Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,1689089.00,0.00,If the popular vote margin of victory is 3-5.9...,The margin of victory is calculated by taking ...
9,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,0-2.99%,0-2.99%,finalized,no,2025-08-12T21:46:06.121613Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,1256254.00,0.00,If the popular vote margin of victory is 0-2.9...,The margin of victory is calculated by taking ...

In [4]:
import time
import json
import requests
import pandas as pd
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

EVENT_TICKER = "KXELECTIONMOVZOHRAN-25"
SERIES_TICKER = "KXELECTIONMOVZOHRAN"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-event-candlesticks-colab/1.0"
})


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        try:
            data = resp.json()
        except Exception:
            data = {"raw_text": resp.text}

        if resp.status_code >= 400:
            print("Bad URL:", resp.url)
            print("Kalshi response:", json.dumps(data, indent=2)[:3000])
            resp.raise_for_status()

        return data

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


# 1. Get event details so we can use its dates
event_data = get_json(f"/events/{EVENT_TICKER}")
event = event_data.get("event", event_data)

df_event_details = pd.DataFrame([event])
display(df_event_details)

# If the API returns series_ticker, use it
SERIES_TICKER = event.get("series_ticker", SERIES_TICKER)

print("Series ticker:", SERIES_TICKER)
print("Event ticker:", EVENT_TICKER)

# 2. Choose date range
# Try event dates first; if unavailable, use a wide fallback range.
start_time = pd.to_datetime(
    event.get("open_time") or event.get("created_time"),
    utc=True,
    errors="coerce"
)

end_time = pd.to_datetime(
    event.get("close_time") or event.get("expiration_time") or event.get("settlement_ts"),
    utc=True,
    errors="coerce"
)

if pd.isna(start_time):
    # fallback: 1 year ago
    start_time = pd.Timestamp.now(tz="UTC") - pd.Timedelta(days=365)

if pd.isna(end_time):
    end_time = pd.Timestamp.now(tz="UTC")

start_ts = int(start_time.timestamp())
end_ts = int(end_time.timestamp())

print("Start:", start_time)
print("End:", end_time)

# 3. Get daily event candlesticks
# period_interval:
# 1    = 1 minute
# 60   = hourly
# 1440 = daily

event_candles_data = get_json(
    f"/series/{SERIES_TICKER}/events/{EVENT_TICKER}/candlesticks",
    params={
        "start_ts": start_ts,
        "end_ts": end_ts,
        "period_interval": 1440
    }
)

df_event_daily_candlesticks = pd.DataFrame(
    event_candles_data.get("candlesticks", [])
)

df_event_daily_candlesticks["event_ticker"] = EVENT_TICKER
df_event_daily_candlesticks["series_ticker"] = SERIES_TICKER
df_event_daily_candlesticks["period_interval"] = 1440
df_event_daily_candlesticks["period_label"] = "daily"

display(df_event_daily_candlesticks)

print("Daily event candlesticks:", len(df_event_daily_candlesticks))
print("Columns:", df_event_daily_candlesticks.columns.tolist())

df_event_daily_candlesticks.to_csv(
    f"kalshi_event_daily_candlesticks_{EVENT_TICKER}.csv",
    index=False
)

,available_on_brokers,category,collateral_return_type,event_ticker,last_updated_ts,mutually_exclusive,series_ticker,settlement_sources,strike_period,sub_title,title
0,True,Elections,MECNET,KXELECTIONMOVZOHRAN-25,0001-01-01T00:00:00Z,True,KXELECTIONMOVZOHRAN,[{'name': 'Board of Elections in the City of N...,,In 2025,Margin of victory for Zohran Mamdani in the NY...

Series ticker: KXELECTIONMOVZOHRAN
Event ticker: KXELECTIONMOVZOHRAN-25
Start: 2025-06-24 14:50:05.074690+00:00
End: 2026-06-24 14:50:05.074845+00:00

Empty DataFrame
Columns: [event_ticker, series_ticker, period_interval, period_label]
Index: []

Daily event candlesticks: 0
Columns: ['event_ticker', 'series_ticker', 'period_interval', 'period_label']

In [6]:
import time
import json
import requests
import pandas as pd
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

EVENT_TICKER = "KXELECTIONMOVZOHRAN-25"
SERIES_TICKER = "KXELECTIONMOVZOHRAN"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-event-candlesticks-colab/1.0"
})


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        try:
            data = resp.json()
        except Exception:
            data = {"raw_text": resp.text}

        if resp.status_code >= 400:
            print("Bad URL:", resp.url)
            print("Kalshi response:", json.dumps(data, indent=2)[:3000])
            resp.raise_for_status()

        print("URL:", resp.url)
        return data

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def paginate(path, collection_key, params=None, limit=200, sleep_s=0.25):
    params = dict(params or {})
    params["limit"] = limit

    rows = []
    cursor = None

    while True:
        if cursor:
            params["cursor"] = cursor
        else:
            params.pop("cursor", None)

        data = get_json(path, params=params)
        rows.extend(data.get(collection_key, []))

        cursor = data.get("cursor")
        if not cursor:
            break

        time.sleep(sleep_s)

    return rows


# 1. Get event details
event_data = get_json(f"/events/{EVENT_TICKER}")
event = event_data.get("event", event_data)

df_event_details = pd.DataFrame([event])
display(df_event_details)

SERIES_TICKER = event.get("series_ticker", SERIES_TICKER)

print("Series ticker:", SERIES_TICKER)
print("Event ticker:", EVENT_TICKER)


# 2. Get all markets for this event to determine real date range
live_markets = paginate(
    "/markets",
    "markets",
    params={"event_ticker": EVENT_TICKER},
    limit=200
)

historical_markets = paginate(
    "/historical/markets",
    "markets",
    params={"event_ticker": EVENT_TICKER},
    limit=200
)

all_markets = live_markets + historical_markets
df_event_markets = pd.DataFrame(all_markets)

display(df_event_markets)

print("Live/recent markets:", len(live_markets))
print("Historical markets:", len(historical_markets))
print("Total market rows:", len(df_event_markets))


# 3. Build start_ts and end_ts from market dates
for col in ["open_time", "close_time", "expiration_time", "settlement_ts"]:
    if col in df_event_markets.columns:
        df_event_markets[col] = pd.to_datetime(
            df_event_markets[col],
            utc=True,
            errors="coerce"
        )

start_time = df_event_markets["open_time"].min()

end_time = pd.concat([
    df_event_markets[c]
    for c in ["close_time", "expiration_time", "settlement_ts"]
    if c in df_event_markets.columns
]).max()

start_ts = int(start_time.timestamp())
end_ts = int(end_time.timestamp())

print("Candlestick start:", start_time)
print("Candlestick end:", end_time)


# 4. Get daily event candlesticks
event_daily_data = get_json(
    f"/series/{SERIES_TICKER}/events/{EVENT_TICKER}/candlesticks",
    params={
        "start_ts": start_ts,
        "end_ts": end_ts,
        "period_interval": 1440
    }
)

df_event_daily_candlesticks = pd.DataFrame(
    event_daily_data.get("candlesticks", [])
)

df_event_daily_candlesticks["event_ticker"] = EVENT_TICKER
df_event_daily_candlesticks["series_ticker"] = SERIES_TICKER
df_event_daily_candlesticks["period_interval"] = 1440
df_event_daily_candlesticks["period_label"] = "daily"

display(df_event_daily_candlesticks)

print("Daily event candlesticks:", len(df_event_daily_candlesticks))
print("Columns:", df_event_daily_candlesticks.columns.tolist())

df_event_daily_candlesticks.to_csv(
    f"kalshi_event_daily_candlesticks_{EVENT_TICKER}.csv",
    index=False
)


# 5. Optional: get all valid event candlestick intervals
intervals = {
    1: "1min",
    60: "hourly",
    1440: "daily"
}

event_candlestick_dfs = {}

for period_interval, label in intervals.items():
    print(f"Getting {label} event candlesticks...")

    data = get_json(
        f"/series/{SERIES_TICKER}/events/{EVENT_TICKER}/candlesticks",
        params={
            "start_ts": start_ts,
            "end_ts": end_ts,
            "period_interval": period_interval
        }
    )

    df_tmp = pd.DataFrame(data.get("candlesticks", []))
    df_tmp["event_ticker"] = EVENT_TICKER
    df_tmp["series_ticker"] = SERIES_TICKER
    df_tmp["period_interval"] = period_interval
    df_tmp["period_label"] = label

    event_candlestick_dfs[label] = df_tmp

    print(label, "rows:", len(df_tmp))
    display(df_tmp.head())

    df_tmp.to_csv(
        f"kalshi_event_{label}_candlesticks_{EVENT_TICKER}.csv",
        index=False
    )

df_all_event_candlesticks = pd.concat(
    event_candlestick_dfs.values(),
    ignore_index=True
)

display(df_all_event_candlesticks)

df_all_event_candlesticks.to_csv(
    f"kalshi_all_event_candlesticks_{EVENT_TICKER}.csv",
    index=False
)

URL: https://external-api.kalshi.com/trade-api/v2/events/KXELECTIONMOVZOHRAN-25

,available_on_brokers,category,collateral_return_type,event_ticker,last_updated_ts,mutually_exclusive,series_ticker,settlement_sources,strike_period,sub_title,title
0,True,Elections,MECNET,KXELECTIONMOVZOHRAN-25,0001-01-01T00:00:00Z,True,KXELECTIONMOVZOHRAN,[{'name': 'Board of Elections in the City of N...,,In 2025,Margin of victory for Zohran Mamdani in the NY...

Series ticker: KXELECTIONMOVZOHRAN
Event ticker: KXELECTIONMOVZOHRAN-25
URL: https://external-api.kalshi.com/trade-api/v2/markets?event_ticker=KXELECTIONMOVZOHRAN-25&limit=200
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets?event_ticker=KXELECTIONMOVZOHRAN-25&limit=200

,can_close_early,close_time,created_time,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,fractional_trading_enabled,...,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,cap_strike,subtitle
0,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,24.0,True,...,2026-03-04T22:43:52.878979Z,0.00,2715311.00,1.0000,0.00,0.0000,0.00,24% or more,NaN,NaN
1,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,6.0,True,...,2026-03-04T22:43:52.624601Z,0.00,3398478.00,1.0000,0.00,0.0000,0.00,6-8.99%,8.99,NaN
2,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,21.0,True,...,2026-03-04T22:43:52.829531Z,0.00,922621.00,1.0000,0.00,0.0000,0.00,21-23.99%,23.99,NaN
3,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,18.0,True,...,2026-03-04T22:43:52.77753Z,0.00,819153.00,1.0000,0.00,0.0000,0.00,18-20.99%,20.99,NaN
4,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,15.0,True,...,2026-03-04T22:43:52.739289Z,0.00,923736.00,1.0000,0.00,0.0000,0.00,15-17.99%,17.99,NaN
5,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,12.0,True,...,2026-03-04T22:43:52.700178Z,0.00,1454986.00,1.0000,0.00,0.0000,0.00,12-14.99%,14.99,NaN
6,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,9.0,True,...,2026-03-04T22:43:52.661638Z,0.00,2641908.00,1.0000,0.00,0.0000,0.00,9-11.99%,11.99,NaN
7,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,NaN,True,...,2026-03-04T22:43:52.494901Z,0.00,1488079.00,1.0000,0.00,0.0000,0.00,Less than 0%,0.00,:: Loses
8,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,3.0,True,...,2026-03-04T22:43:52.57737Z,0.00,1689089.00,1.0000,0.00,0.0000,0.00,3-5.99%,5.99,NaN
9,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,0.0,True,...,2026-03-04T22:43:52.539059Z,0.00,1256254.00,1.0000,0.00,0.0000,0.00,0-2.99%,2.99,NaN

Live/recent markets: 0
Historical markets: 10
Total market rows: 10
Candlestick start: 2025-08-13 14:00:00+00:00
Candlestick end: 2026-11-04 15:00:00+00:00
URL: https://external-api.kalshi.com/trade-api/v2/series/KXELECTIONMOVZOHRAN/events/KXELECTIONMOVZOHRAN-25/candlesticks?start_ts=1755093600&end_ts=1793804400&period_interval=1440

Empty DataFrame
Columns: [event_ticker, series_ticker, period_interval, period_label]
Index: []

Daily event candlesticks: 0
Columns: ['event_ticker', 'series_ticker', 'period_interval', 'period_label']
Getting 1min event candlesticks...
URL: https://external-api.kalshi.com/trade-api/v2/series/KXELECTIONMOVZOHRAN/events/KXELECTIONMOVZOHRAN-25/candlesticks?start_ts=1755093600&end_ts=1793804400&period_interval=1
1min rows: 0

Empty DataFrame
Columns: [event_ticker, series_ticker, period_interval, period_label]
Index: []

Getting hourly event candlesticks...
URL: https://external-api.kalshi.com/trade-api/v2/series/KXELECTIONMOVZOHRAN/events/KXELECTIONMOVZOHRAN-25/candlesticks?start_ts=1755093600&end_ts=1793804400&period_interval=60
hourly rows: 0

Empty DataFrame
Columns: [event_ticker, series_ticker, period_interval, period_label]
Index: []

Getting daily event candlesticks...
Rate limited. Sleeping 5s...
URL: https://external-api.kalshi.com/trade-api/v2/series/KXELECTIONMOVZOHRAN/events/KXELECTIONMOVZOHRAN-25/candlesticks?start_ts=1755093600&end_ts=1793804400&period_interval=1440
daily rows: 0

Empty DataFrame
Columns: [event_ticker, series_ticker, period_interval, period_label]
Index: []

Empty DataFrame
Columns: [event_ticker, series_ticker, period_interval, period_label]
Index: []

In [7]:
# Get daily historical market candlesticks for every market in this event

all_market_daily_candles = []

for i, row in df_event_markets.iterrows():
    market_ticker = row["ticker"]

    open_time = pd.to_datetime(row.get("open_time"), utc=True, errors="coerce")
    close_time = pd.to_datetime(
        row.get("close_time") or row.get("expiration_time") or row.get("settlement_ts"),
        utc=True,
        errors="coerce"
    )

    if pd.isna(open_time) or pd.isna(close_time):
        print(f"Skipping {market_ticker}: missing open/close time")
        continue

    start_ts = int(open_time.timestamp())
    end_ts = int(close_time.timestamp())

    print(f"[{i+1}/{len(df_event_markets)}] Getting daily candles for {market_ticker}...")

    try:
        data = get_json(
            f"/historical/markets/{market_ticker}/candlesticks",
            params={
                "start_ts": start_ts,
                "end_ts": end_ts,
                "period_interval": 1440
            }
        )

        candles = data.get("candlesticks", [])

        for candle in candles:
            candle["market_ticker"] = market_ticker
            candle["event_ticker"] = EVENT_TICKER
            candle["series_ticker"] = SERIES_TICKER
            candle["market_title"] = row.get("title")
            candle["market_status"] = row.get("status")
            candle["market_result"] = row.get("result")
            candle["period_interval"] = 1440
            candle["period_label"] = "daily"

        all_market_daily_candles.extend(candles)

    except Exception as e:
        print(f"Skipping {market_ticker}: {e}")

    time.sleep(0.25)

df_event_market_daily_candlesticks = pd.DataFrame(all_market_daily_candles)

display(df_event_market_daily_candlesticks)

print("Total daily market candlesticks:", len(df_event_market_daily_candlesticks))
print("Columns:", df_event_market_daily_candlesticks.columns.tolist())

df_event_market_daily_candlesticks.to_csv(
    f"kalshi_market_daily_candlesticks_for_event_{EVENT_TICKER}.csv",
    index=False
)

[1/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-T24...
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-T24/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440
[2/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B7.5...
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B7.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440
[3/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B22.5...
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B22.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440
[4/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B19.5...
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B19.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440
[5/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B16.5...
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B16.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440
[6/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B13.5...
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B13.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440
[7/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B10.5...
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B10.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440
[8/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-T0...
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-T0/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440
[9/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B4.5...
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B4.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440
[10/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B1.5...
URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B1.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1440

,end_period_ts,open_interest,price,volume,yes_ask,yes_bid,market_ticker,event_ticker,series_ticker,market_title,market_status,market_result,period_interval,period_label
0,1755144000,5154.00,"{'close': '0.4100', 'high': '0.7400', 'low': '...",5433.00,"{'close': '0.4500', 'high': '1.0000', 'low': '...","{'close': '0.4100', 'high': '0.4700', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily
1,1755230400,6394.00,"{'close': '0.4000', 'high': '0.7000', 'low': '...",1858.00,"{'close': '0.4800', 'high': '0.7900', 'low': '...","{'close': '0.4000', 'high': '0.4500', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily
2,1755316800,6429.00,"{'close': '0.3900', 'high': '0.4000', 'low': '...",90.00,"{'close': '0.4700', 'high': '0.4800', 'low': '...","{'close': '0.4100', 'high': '0.4100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily
3,1755403200,6429.00,"{'close': '0.4800', 'high': '0.4800', 'low': '...",4.00,"{'close': '0.4700', 'high': '0.4800', 'low': '...","{'close': '0.4200', 'high': '0.4200', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily
4,1755489600,6840.00,"{'close': '0.4100', 'high': '0.4200', 'low': '...",468.00,"{'close': '0.4600', 'high': '0.4800', 'low': '...","{'close': '0.4100', 'high': '0.4200', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1105,1764306000,921513.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...",348.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily
1106,1764392400,921514.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...",1.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily
1107,1764478800,921514.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily
1108,1764565200,921514.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily
1109,1764651600,921614.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...",100.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily

Total daily market candlesticks: 1110
Columns: ['end_period_ts', 'open_interest', 'price', 'volume', 'yes_ask', 'yes_bid', 'market_ticker', 'event_ticker', 'series_ticker', 'market_title', 'market_status', 'market_result', 'period_interval', 'period_label']

In [10]:
import requests
import pandas as pd

EVENT_TICKER = "KXELECTIONMOVZOHRAN-25"
SERIES_TICKER = "KXELECTIONMOVZOHRAN"

START_TS = 1755093600   # 2025-08-13 14:00:00 UTC
END_TS = 1764727200     # 2025-12-03 02:00:00 UTC
PERIOD_INTERVAL = 1440  # 1 = minute, 60 = hour, 1440 = day

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

url = (
    f"{BASE_URL}/series/{SERIES_TICKER}"
    f"/events/{EVENT_TICKER}/candlesticks"
)

params = {
    "start_ts": START_TS,
    "end_ts": END_TS,
    "period_interval": PERIOD_INTERVAL,
}

response = requests.get(
    url,
    params=params,
    headers={"Accept": "application/json"},
    timeout=30,
)

response.raise_for_status()
data = response.json()

rows = []

for market_ticker, candles in zip(
    data["market_tickers"],
    data["market_candlesticks"]
):
    for candle in candles:
        row = {
            "market_ticker": market_ticker,
            "end_period_ts": candle.get("end_period_ts"),
            "end_period_datetime": pd.to_datetime(
                candle.get("end_period_ts"),
                unit="s",
                utc=True
            ),
            "volume": candle.get("volume_fp"),
            "open_interest": candle.get("open_interest_fp"),
        }

        for group in ["yes_bid", "yes_ask", "price"]:
            values = candle.get(group, {})
            for key, value in values.items():
                row[f"{group}_{key}"] = value

        rows.append(row)

df = pd.DataFrame(rows)

df

Empty DataFrame
Columns: []
Index: []

In [14]:
import time
import json
import requests
import pandas as pd
from urllib.parse import urljoin

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

EVENT_TICKER = "KXELECTIONMOVZOHRAN-25"
SERIES_TICKER = "KXELECTIONMOVZOHRAN"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-all-event-market-data-colab/1.0"
})


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        try:
            data = resp.json()
        except Exception:
            data = {"raw_text": resp.text}

        if resp.status_code >= 400:
            print("Bad URL:", resp.url)
            print("Kalshi response:", json.dumps(data, indent=2)[:3000])
            resp.raise_for_status()

        return data

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def paginate(path, collection_key, params=None, limit=200, sleep_s=0.25):
    params = dict(params or {})
    params["limit"] = limit

    rows = []
    cursor = None

    while True:
        if cursor:
            params["cursor"] = cursor
        else:
            params.pop("cursor", None)

        data = get_json(path, params=params)
        rows.extend(data.get(collection_key, []))

        cursor = data.get("cursor")
        if not cursor:
            break

        time.sleep(sleep_s)

    return rows


def to_number(x):
    return pd.to_numeric(x, errors="coerce")


# 1. Event details
event_data = get_json(f"/events/{EVENT_TICKER}")
event = event_data.get("event", event_data)

df_event_details = pd.DataFrame([event])
display(df_event_details)

SERIES_TICKER = event.get("series_ticker", SERIES_TICKER)

df_event_details.to_csv(
    f"kalshi_event_details_{EVENT_TICKER}.csv",
    index=False
)


# 2. Event metadata
try:
    event_metadata = get_json(f"/events/{EVENT_TICKER}/metadata")
    df_event_metadata = pd.DataFrame([event_metadata])
    display(df_event_metadata)

    df_event_metadata.to_csv(
        f"kalshi_event_metadata_{EVENT_TICKER}.csv",
        index=False
    )
except Exception as e:
    print("Could not fetch event metadata:", e)
    df_event_metadata = pd.DataFrame()


# 3. All markets for event: live/recent + historical
live_markets = []

try:
    live_markets = paginate(
        "/markets",
        "markets",
        params={"event_ticker": EVENT_TICKER},
        limit=200
    )

    for m in live_markets:
        m["_source"] = "live_or_recent"

except Exception as e:
    print("Could not fetch live/recent markets:", e)


historical_markets = []

try:
    historical_markets = paginate(
        "/historical/markets",
        "markets",
        params={"event_ticker": EVENT_TICKER},
        limit=200
    )

    for m in historical_markets:
        m["_source"] = "historical"

except Exception as e:
    print("Could not fetch historical markets:", e)


markets_by_ticker = {}

for m in live_markets + historical_markets:
    ticker = m.get("ticker")
    if ticker:
        markets_by_ticker[ticker] = m

df_event_markets = pd.DataFrame(list(markets_by_ticker.values()))

print("Live/recent markets:", len(live_markets))
print("Historical markets:", len(historical_markets))
print("Unique markets:", len(df_event_markets))

display(df_event_markets)

df_event_markets.to_csv(
    f"kalshi_all_markets_for_event_{EVENT_TICKER}.csv",
    index=False
)


# 4. Full market details for each market ticker
full_market_rows = []
failed_market_details = []

for i, row in df_event_markets.iterrows():
    market_ticker = row["ticker"]
    source = row.get("_source", "")

    print(f"[{i+1}/{len(df_event_markets)}] Fetching full market details for {market_ticker}...")

    try:
        if source == "historical":
            data = get_json(f"/historical/markets/{market_ticker}")
        else:
            data = get_json(f"/markets/{market_ticker}")

        market = data.get("market", data)
        market["_source"] = source
        full_market_rows.append(market)

    except Exception as e:
        print(f"Failed {market_ticker}: {e}")
        failed_market_details.append({
            "ticker": market_ticker,
            "source": source,
            "error": str(e)
        })

    time.sleep(0.25)

df_full_market_details = pd.DataFrame(full_market_rows)

display(df_full_market_details)

df_full_market_details.to_csv(
    f"kalshi_full_market_details_for_event_{EVENT_TICKER}.csv",
    index=False
)

if failed_market_details:
    df_failed_market_details = pd.DataFrame(failed_market_details)
    display(df_failed_market_details)

    df_failed_market_details.to_csv(
        f"kalshi_failed_market_details_{EVENT_TICKER}.csv",
        index=False
    )


# 5. Clean market summary
summary_cols = [
    "ticker",
    "event_ticker",
    "series_ticker",
    "_source",
    "title",
    "subtitle",
    "yes_sub_title",
    "no_sub_title",
    "status",
    "result",
    "created_time",
    "open_time",
    "close_time",
    "expiration_time",
    "settlement_ts",
    "notional_value_dollars",
    "volume",
    "volume_fp",
    "volume_24h",
    "volume_24h_fp",
    "open_interest",
    "liquidity",
    "yes_bid",
    "yes_ask",
    "no_bid",
    "no_ask",
    "last_price",
    "rules_primary",
    "rules_secondary"
]

existing_summary_cols = [
    c for c in summary_cols
    if c in df_full_market_details.columns
]

df_market_summary = df_full_market_details[existing_summary_cols].copy()

display(df_market_summary)

df_market_summary.to_csv(
    f"kalshi_market_summary_for_event_{EVENT_TICKER}.csv",
    index=False
)


# 6. Candlesticks for every market: 1min, hourly, daily
intervals = {
    1: "1min",
    60: "hourly",
    1440: "daily"
}

all_candles_by_interval = {
    "1min": [],
    "hourly": [],
    "daily": []
}

failed_candles = []

for i, row in df_full_market_details.iterrows():
    market_ticker = row["ticker"]
    source = row.get("_source", "")

    open_time = pd.to_datetime(row.get("open_time"), utc=True, errors="coerce")
    end_time = pd.to_datetime(
        row.get("close_time") or row.get("expiration_time") or row.get("settlement_ts"),
        utc=True,
        errors="coerce"
    )

    if pd.isna(open_time) or pd.isna(end_time):
        print(f"Skipping candles for {market_ticker}: missing date range")
        continue

    start_ts = int(open_time.timestamp())
    end_ts = int(end_time.timestamp())

    for period_interval, label in intervals.items():
        print(f"[{i+1}/{len(df_full_market_details)}] Getting {label} candles for {market_ticker}...")

        try:
            if source == "historical":
                path = f"/historical/markets/{market_ticker}/candlesticks"
            else:
                path = f"/series/{SERIES_TICKER}/markets/{market_ticker}/candlesticks"

            data = get_json(
                path,
                params={
                    "start_ts": start_ts,
                    "end_ts": end_ts,
                    "period_interval": period_interval
                }
            )

            candles = data.get("candlesticks", [])

            for candle in candles:
                candle["market_ticker"] = market_ticker
                candle["event_ticker"] = EVENT_TICKER
                candle["series_ticker"] = SERIES_TICKER
                candle["market_title"] = row.get("title")
                candle["market_status"] = row.get("status")
                candle["market_result"] = row.get("result")
                candle["period_interval"] = period_interval
                candle["period_label"] = label
                candle["_source"] = source

            all_candles_by_interval[label].extend(candles)

        except Exception as e:
            print(f"Failed candles for {market_ticker} {label}: {e}")
            failed_candles.append({
                "ticker": market_ticker,
                "period_label": label,
                "error": str(e)
            })

        time.sleep(0.25)


df_1min_candles = pd.DataFrame(all_candles_by_interval["1min"])
df_hourly_candles = pd.DataFrame(all_candles_by_interval["hourly"])
df_daily_candles = pd.DataFrame(all_candles_by_interval["daily"])

display(df_daily_candles)

df_1min_candles.to_csv(
    f"kalshi_1min_market_candlesticks_for_event_{EVENT_TICKER}.csv",
    index=False
)

df_hourly_candles.to_csv(
    f"kalshi_hourly_market_candlesticks_for_event_{EVENT_TICKER}.csv",
    index=False
)

df_daily_candles.to_csv(
    f"kalshi_daily_market_candlesticks_for_event_{EVENT_TICKER}.csv",
    index=False
)

if failed_candles:
    df_failed_candles = pd.DataFrame(failed_candles)
    display(df_failed_candles)

    df_failed_candles.to_csv(
        f"kalshi_failed_market_candlesticks_{EVENT_TICKER}.csv",
        index=False
    )


# 7. Event volume summary
dfv = df_full_market_details.copy()

if "volume_fp" in dfv.columns:
    dfv["volume_contracts"] = to_number(dfv["volume_fp"])
elif "volume" in dfv.columns:
    dfv["volume_contracts"] = to_number(dfv["volume"])
else:
    dfv["volume_contracts"] = pd.NA

if "volume_24h_fp" in dfv.columns:
    dfv["volume_24h_contracts"] = to_number(dfv["volume_24h_fp"])
elif "volume_24h" in dfv.columns:
    dfv["volume_24h_contracts"] = to_number(dfv["volume_24h"])
else:
    dfv["volume_24h_contracts"] = pd.NA

if "notional_value_dollars" in dfv.columns:
    dfv["notional_value_dollars_numeric"] = to_number(dfv["notional_value_dollars"])
else:
    dfv["notional_value_dollars_numeric"] = 1.0

dfv["estimated_notional_volume_dollars"] = (
    dfv["volume_contracts"] * dfv["notional_value_dollars_numeric"]
)

volume_by_market_cols = [
    "ticker",
    "_source",
    "title",
    "status",
    "result",
    "volume_fp",
    "volume_contracts",
    "volume_24h_fp",
    "volume_24h_contracts",
    "notional_value_dollars",
    "estimated_notional_volume_dollars"
]

existing_volume_cols = [
    c for c in volume_by_market_cols
    if c in dfv.columns
]

df_event_volume_by_market = dfv[existing_volume_cols].copy()

df_event_volume_summary = pd.DataFrame([{
    "event_ticker": EVENT_TICKER,
    "series_ticker": SERIES_TICKER,
    "n_markets": len(dfv),
    "total_volume_contracts": dfv["volume_contracts"].sum(skipna=True),
    "total_24h_volume_contracts": dfv["volume_24h_contracts"].sum(skipna=True),
    "estimated_total_notional_volume_dollars": dfv["estimated_notional_volume_dollars"].sum(skipna=True),
    "note": "This is not exact cash spent. Exact dollars would require trade-level price * quantity data."
}])

display(df_event_volume_by_market)
display(df_event_volume_summary)

df_event_volume_by_market.to_csv(
    f"kalshi_event_volume_by_market_{EVENT_TICKER}.csv",
    index=False
)

df_event_volume_summary.to_csv(
    f"kalshi_event_volume_summary_{EVENT_TICKER}.csv",
    index=False
)

print("Done. CSV files saved.")

,available_on_brokers,category,collateral_return_type,event_ticker,last_updated_ts,mutually_exclusive,series_ticker,settlement_sources,strike_period,sub_title,title
0,True,Elections,MECNET,KXELECTIONMOVZOHRAN-25,0001-01-01T00:00:00Z,True,KXELECTIONMOVZOHRAN,[{'name': 'Board of Elections in the City of N...,,In 2025,Margin of victory for Zohran Mamdani in the NY...

,featured_image_url,image_url,market_details,settlement_sources
0,https://kalshi-fallback-images.s3.amazonaws.co...,https://kalshi-public-docs.s3.amazonaws.com/se...,"[{'color_code': '#AA00FF', 'image_url': 'https...",[{'name': 'Board of Elections in the City of N...

Live/recent markets: 0
Historical markets: 10
Unique markets: 10

,can_close_early,close_time,created_time,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,fractional_trading_enabled,...,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,_source,cap_strike,subtitle
0,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,24.0,True,...,0.00,2715311.00,1.0000,0.00,0.0000,0.00,24% or more,historical,NaN,NaN
1,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,6.0,True,...,0.00,3398478.00,1.0000,0.00,0.0000,0.00,6-8.99%,historical,8.99,NaN
2,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,21.0,True,...,0.00,922621.00,1.0000,0.00,0.0000,0.00,21-23.99%,historical,23.99,NaN
3,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,18.0,True,...,0.00,819153.00,1.0000,0.00,0.0000,0.00,18-20.99%,historical,20.99,NaN
4,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,15.0,True,...,0.00,923736.00,1.0000,0.00,0.0000,0.00,15-17.99%,historical,17.99,NaN
5,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,12.0,True,...,0.00,1454986.00,1.0000,0.00,0.0000,0.00,12-14.99%,historical,14.99,NaN
6,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,9.0,True,...,0.00,2641908.00,1.0000,0.00,0.0000,0.00,9-11.99%,historical,11.99,NaN
7,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,NaN,True,...,0.00,1488079.00,1.0000,0.00,0.0000,0.00,Less than 0%,historical,0.00,:: Loses
8,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,3.0,True,...,0.00,1689089.00,1.0000,0.00,0.0000,0.00,3-5.99%,historical,5.99,NaN
9,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,0.0,True,...,0.00,1256254.00,1.0000,0.00,0.0000,0.00,0-2.99%,historical,2.99,NaN

[1/10] Fetching full market details for KXELECTIONMOVZOHRAN-25-ZMAM-T24...
[2/10] Fetching full market details for KXELECTIONMOVZOHRAN-25-ZMAM-B7.5...
[3/10] Fetching full market details for KXELECTIONMOVZOHRAN-25-ZMAM-B22.5...
[4/10] Fetching full market details for KXELECTIONMOVZOHRAN-25-ZMAM-B19.5...
[5/10] Fetching full market details for KXELECTIONMOVZOHRAN-25-ZMAM-B16.5...
[6/10] Fetching full market details for KXELECTIONMOVZOHRAN-25-ZMAM-B13.5...
[7/10] Fetching full market details for KXELECTIONMOVZOHRAN-25-ZMAM-B10.5...
[8/10] Fetching full market details for KXELECTIONMOVZOHRAN-25-ZMAM-T0...
[9/10] Fetching full market details for KXELECTIONMOVZOHRAN-25-ZMAM-B4.5...
[10/10] Fetching full market details for KXELECTIONMOVZOHRAN-25-ZMAM-B1.5...

,can_close_early,close_time,created_time,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,fractional_trading_enabled,...,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,_source,cap_strike,subtitle
0,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,24.0,True,...,0.00,2715311.00,1.0000,0.00,0.0000,0.00,24% or more,historical,NaN,NaN
1,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,6.0,True,...,0.00,3398478.00,1.0000,0.00,0.0000,0.00,6-8.99%,historical,8.99,NaN
2,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,21.0,True,...,0.00,922621.00,1.0000,0.00,0.0000,0.00,21-23.99%,historical,23.99,NaN
3,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,18.0,True,...,0.00,819153.00,1.0000,0.00,0.0000,0.00,18-20.99%,historical,20.99,NaN
4,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,15.0,True,...,0.00,923736.00,1.0000,0.00,0.0000,0.00,15-17.99%,historical,17.99,NaN
5,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,12.0,True,...,0.00,1454986.00,1.0000,0.00,0.0000,0.00,12-14.99%,historical,14.99,NaN
6,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,9.0,True,...,0.00,2641908.00,1.0000,0.00,0.0000,0.00,9-11.99%,historical,11.99,NaN
7,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,NaN,True,...,0.00,1488079.00,1.0000,0.00,0.0000,0.00,Less than 0%,historical,0.00,:: Loses
8,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,3.0,True,...,0.00,1689089.00,1.0000,0.00,0.0000,0.00,3-5.99%,historical,5.99,NaN
9,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,0.0,True,...,0.00,1256254.00,1.0000,0.00,0.0000,0.00,0-2.99%,historical,2.99,NaN

,ticker,event_ticker,_source,title,subtitle,yes_sub_title,no_sub_title,status,result,created_time,open_time,close_time,expiration_time,settlement_ts,notional_value_dollars,volume_fp,volume_24h_fp,rules_primary,rules_secondary
0,KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,24% or more,24% or more,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,2715311.00,0.00,If the popular vote margin of victory is 24% o...,The margin of victory is calculated by taking ...
1,KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,6-8.99%,6-8.99%,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,3398478.00,0.00,If the popular vote margin of victory is 6-8.9...,The margin of victory is calculated by taking ...
2,KXELECTIONMOVZOHRAN-25-ZMAM-B22.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,21-23.99%,21-23.99%,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,922621.00,0.00,If the popular vote margin of victory is 21-23...,The margin of victory is calculated by taking ...
3,KXELECTIONMOVZOHRAN-25-ZMAM-B19.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,18-20.99%,18-20.99%,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,819153.00,0.00,If the popular vote margin of victory is 18-20...,The margin of victory is calculated by taking ...
4,KXELECTIONMOVZOHRAN-25-ZMAM-B16.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,15-17.99%,15-17.99%,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,923736.00,0.00,If the popular vote margin of victory is 15-17...,The margin of victory is calculated by taking ...
5,KXELECTIONMOVZOHRAN-25-ZMAM-B13.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,12-14.99%,12-14.99%,finalized,no,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,1454986.00,0.00,If the popular vote margin of victory is 12-14...,The margin of victory is calculated by taking ...
6,KXELECTIONMOVZOHRAN-25-ZMAM-B10.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,9-11.99%,9-11.99%,finalized,yes,2025-08-12T21:46:06.121614Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,2641908.00,0.00,If the popular vote margin of victory is 9-11....,The margin of victory is calculated by taking ...
7,KXELECTIONMOVZOHRAN-25-ZMAM-T0,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,:: Loses,Less than 0%,Less than 0%,finalized,no,2025-08-12T21:46:06.121613Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,1488079.00,0.00,If the popular vote margin of victory is 0% or...,The margin of victory is calculated by taking ...
8,KXELECTIONMOVZOHRAN-25-ZMAM-B4.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,3-5.99%,3-5.99%,finalized,no,2025-08-12T21:46:06.121613Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,1689089.00,0.00,If the popular vote margin of victory is 3-5.9...,The margin of victory is calculated by taking ...
9,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,historical,Margin of victory for Zohran Mamdani in the Ma...,NaN,0-2.99%,0-2.99%,finalized,no,2025-08-12T21:46:06.121613Z,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1.0000,1256254.00,0.00,If the popular vote margin of victory is 0-2.9...,The margin of victory is calculated by taking ...

[1/10] Getting 1min candles for KXELECTIONMOVZOHRAN-25-ZMAM-T24...
Bad URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-T24/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
Kalshi response: {
  "error": {
    "code": "bad_request",
    "message": "bad request",
    "details": "requested time range with candlesticks: 160544.800000, max candlesticks: 5000"
  }
}
Failed candles for KXELECTIONMOVZOHRAN-25-ZMAM-T24 1min: 400 Client Error: Bad Request for url: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-T24/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
[1/10] Getting hourly candles for KXELECTIONMOVZOHRAN-25-ZMAM-T24...
[1/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-T24...
[2/10] Getting 1min candles for KXELECTIONMOVZOHRAN-25-ZMAM-B7.5...
Bad URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B7.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
Kalshi response: {
  "error": {
    "code": "bad_request",
    "message": "bad request",
    "details": "requested time range with candlesticks: 160544.800000, max candlesticks: 5000"
  }
}
Failed candles for KXELECTIONMOVZOHRAN-25-ZMAM-B7.5 1min: 400 Client Error: Bad Request for url: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B7.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
[2/10] Getting hourly candles for KXELECTIONMOVZOHRAN-25-ZMAM-B7.5...
[2/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B7.5...
[3/10] Getting 1min candles for KXELECTIONMOVZOHRAN-25-ZMAM-B22.5...
Bad URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B22.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
Kalshi response: {
  "error": {
    "code": "bad_request",
    "message": "bad request",
    "details": "requested time range with candlesticks: 160544.800000, max candlesticks: 5000"
  }
}
Failed candles for KXELECTIONMOVZOHRAN-25-ZMAM-B22.5 1min: 400 Client Error: Bad Request for url: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B22.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
[3/10] Getting hourly candles for KXELECTIONMOVZOHRAN-25-ZMAM-B22.5...
[3/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B22.5...
[4/10] Getting 1min candles for KXELECTIONMOVZOHRAN-25-ZMAM-B19.5...
Bad URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B19.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
Kalshi response: {
  "error": {
    "code": "bad_request",
    "message": "bad request",
    "details": "requested time range with candlesticks: 160544.800000, max candlesticks: 5000"
  }
}
Failed candles for KXELECTIONMOVZOHRAN-25-ZMAM-B19.5 1min: 400 Client Error: Bad Request for url: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B19.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
[4/10] Getting hourly candles for KXELECTIONMOVZOHRAN-25-ZMAM-B19.5...
[4/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B19.5...
[5/10] Getting 1min candles for KXELECTIONMOVZOHRAN-25-ZMAM-B16.5...
Bad URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B16.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
Kalshi response: {
  "error": {
    "code": "bad_request",
    "message": "bad request",
    "details": "requested time range with candlesticks: 160544.800000, max candlesticks: 5000"
  }
}
Failed candles for KXELECTIONMOVZOHRAN-25-ZMAM-B16.5 1min: 400 Client Error: Bad Request for url: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B16.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
[5/10] Getting hourly candles for KXELECTIONMOVZOHRAN-25-ZMAM-B16.5...
[5/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B16.5...
[6/10] Getting 1min candles for KXELECTIONMOVZOHRAN-25-ZMAM-B13.5...
Bad URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B13.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
Kalshi response: {
  "error": {
    "code": "bad_request",
    "message": "bad request",
    "details": "requested time range with candlesticks: 160544.800000, max candlesticks: 5000"
  }
}
Failed candles for KXELECTIONMOVZOHRAN-25-ZMAM-B13.5 1min: 400 Client Error: Bad Request for url: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B13.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
[6/10] Getting hourly candles for KXELECTIONMOVZOHRAN-25-ZMAM-B13.5...
[6/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B13.5...
[7/10] Getting 1min candles for KXELECTIONMOVZOHRAN-25-ZMAM-B10.5...
Bad URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B10.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
Kalshi response: {
  "error": {
    "code": "bad_request",
    "message": "bad request",
    "details": "requested time range with candlesticks: 160544.800000, max candlesticks: 5000"
  }
}
Failed candles for KXELECTIONMOVZOHRAN-25-ZMAM-B10.5 1min: 400 Client Error: Bad Request for url: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B10.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
[7/10] Getting hourly candles for KXELECTIONMOVZOHRAN-25-ZMAM-B10.5...
[7/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B10.5...
[8/10] Getting 1min candles for KXELECTIONMOVZOHRAN-25-ZMAM-T0...
Bad URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-T0/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
Kalshi response: {
  "error": {
    "code": "bad_request",
    "message": "bad request",
    "details": "requested time range with candlesticks: 160544.800000, max candlesticks: 5000"
  }
}
Failed candles for KXELECTIONMOVZOHRAN-25-ZMAM-T0 1min: 400 Client Error: Bad Request for url: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-T0/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
[8/10] Getting hourly candles for KXELECTIONMOVZOHRAN-25-ZMAM-T0...
[8/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-T0...
[9/10] Getting 1min candles for KXELECTIONMOVZOHRAN-25-ZMAM-B4.5...
Bad URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B4.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
Kalshi response: {
  "error": {
    "code": "bad_request",
    "message": "bad request",
    "details": "requested time range with candlesticks: 160544.800000, max candlesticks: 5000"
  }
}
Failed candles for KXELECTIONMOVZOHRAN-25-ZMAM-B4.5 1min: 400 Client Error: Bad Request for url: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B4.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
[9/10] Getting hourly candles for KXELECTIONMOVZOHRAN-25-ZMAM-B4.5...
[9/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B4.5...
[10/10] Getting 1min candles for KXELECTIONMOVZOHRAN-25-ZMAM-B1.5...
Bad URL: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B1.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
Kalshi response: {
  "error": {
    "code": "bad_request",
    "message": "bad request",
    "details": "requested time range with candlesticks: 160544.800000, max candlesticks: 5000"
  }
}
Failed candles for KXELECTIONMOVZOHRAN-25-ZMAM-B1.5 1min: 400 Client Error: Bad Request for url: https://external-api.kalshi.com/trade-api/v2/historical/markets/KXELECTIONMOVZOHRAN-25-ZMAM-B1.5/candlesticks?start_ts=1755093600&end_ts=1764726288&period_interval=1
[10/10] Getting hourly candles for KXELECTIONMOVZOHRAN-25-ZMAM-B1.5...
[10/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B1.5...

,end_period_ts,open_interest,price,volume,yes_ask,yes_bid,market_ticker,event_ticker,series_ticker,market_title,market_status,market_result,period_interval,period_label,_source
0,1755144000,5154.00,"{'close': '0.4100', 'high': '0.7400', 'low': '...",5433.00,"{'close': '0.4500', 'high': '1.0000', 'low': '...","{'close': '0.4100', 'high': '0.4700', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily,historical
1,1755230400,6394.00,"{'close': '0.4000', 'high': '0.7000', 'low': '...",1858.00,"{'close': '0.4800', 'high': '0.7900', 'low': '...","{'close': '0.4000', 'high': '0.4500', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily,historical
2,1755316800,6429.00,"{'close': '0.3900', 'high': '0.4000', 'low': '...",90.00,"{'close': '0.4700', 'high': '0.4800', 'low': '...","{'close': '0.4100', 'high': '0.4100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily,historical
3,1755403200,6429.00,"{'close': '0.4800', 'high': '0.4800', 'low': '...",4.00,"{'close': '0.4700', 'high': '0.4800', 'low': '...","{'close': '0.4200', 'high': '0.4200', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily,historical
4,1755489600,6840.00,"{'close': '0.4100', 'high': '0.4200', 'low': '...",468.00,"{'close': '0.4600', 'high': '0.4800', 'low': '...","{'close': '0.4100', 'high': '0.4200', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily,historical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1105,1764306000,921513.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...",348.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily,historical
1106,1764392400,921514.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...",1.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily,historical
1107,1764478800,921514.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily,historical
1108,1764565200,921514.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily,historical
1109,1764651600,921614.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...",100.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1440,daily,historical

,ticker,period_label,error
0,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1min,400 Client Error: Bad Request for url: https:/...
1,KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,1min,400 Client Error: Bad Request for url: https:/...
2,KXELECTIONMOVZOHRAN-25-ZMAM-B22.5,1min,400 Client Error: Bad Request for url: https:/...
3,KXELECTIONMOVZOHRAN-25-ZMAM-B19.5,1min,400 Client Error: Bad Request for url: https:/...
4,KXELECTIONMOVZOHRAN-25-ZMAM-B16.5,1min,400 Client Error: Bad Request for url: https:/...
5,KXELECTIONMOVZOHRAN-25-ZMAM-B13.5,1min,400 Client Error: Bad Request for url: https:/...
6,KXELECTIONMOVZOHRAN-25-ZMAM-B10.5,1min,400 Client Error: Bad Request for url: https:/...
7,KXELECTIONMOVZOHRAN-25-ZMAM-T0,1min,400 Client Error: Bad Request for url: https:/...
8,KXELECTIONMOVZOHRAN-25-ZMAM-B4.5,1min,400 Client Error: Bad Request for url: https:/...
9,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,1min,400 Client Error: Bad Request for url: https:/...

,ticker,_source,title,status,result,volume_fp,volume_contracts,volume_24h_fp,volume_24h_contracts,notional_value_dollars,estimated_notional_volume_dollars
0,KXELECTIONMOVZOHRAN-25-ZMAM-T24,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2715311.00,2715311.0,0.00,0.0,1.0000,2715311.0
1,KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,3398478.00,3398478.0,0.00,0.0,1.0000,3398478.0
2,KXELECTIONMOVZOHRAN-25-ZMAM-B22.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,922621.00,922621.0,0.00,0.0,1.0000,922621.0
3,KXELECTIONMOVZOHRAN-25-ZMAM-B19.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,819153.00,819153.0,0.00,0.0,1.0000,819153.0
4,KXELECTIONMOVZOHRAN-25-ZMAM-B16.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,923736.00,923736.0,0.00,0.0,1.0000,923736.0
5,KXELECTIONMOVZOHRAN-25-ZMAM-B13.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1454986.00,1454986.0,0.00,0.0,1.0000,1454986.0
6,KXELECTIONMOVZOHRAN-25-ZMAM-B10.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,yes,2641908.00,2641908.0,0.00,0.0,1.0000,2641908.0
7,KXELECTIONMOVZOHRAN-25-ZMAM-T0,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1488079.00,1488079.0,0.00,0.0,1.0000,1488079.0
8,KXELECTIONMOVZOHRAN-25-ZMAM-B4.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1689089.00,1689089.0,0.00,0.0,1.0000,1689089.0
9,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,historical,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,1256254.00,1256254.0,0.00,0.0,1.0000,1256254.0

,event_ticker,series_ticker,n_markets,total_volume_contracts,total_24h_volume_contracts,estimated_total_notional_volume_dollars,note
0,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,10,17309615.0,0.0,17309615.0,This is not exact cash spent. Exact dollars wo...

Done. CSV files saved.

In [17]:
import zipfile
from google.colab import files
import glob

files.download("kalshi_full_market_details_for_event_KXELECTIONMOVZOHRAN-25.csv")
files.download("kalshi_market_summary_for_event_KXELECTIONMOVZOHRAN-25.csv")
files.download("kalshi_daily_market_candlesticks_for_event_KXELECTIONMOVZOHRAN-25.csv")
files.download("kalshi_event_volume_summary_KXELECTIONMOVZOHRAN-25.csv")

In [18]:
import time
import json
import re
import os
import zipfile
import requests
import pandas as pd
from urllib.parse import urljoin
from google.colab import files

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"
EVENT_TICKER = "KXELECTIONMOVZOHRAN-25"

OUT_DIR = f"kalshi_markets_for_{EVENT_TICKER}"
os.makedirs(OUT_DIR, exist_ok=True)

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-event-market-export-colab/1.0"
})


def safe_filename(x):
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(x))


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        if resp.status_code >= 400:
            print("Bad URL:", resp.url)
            print("Kalshi response:", resp.text[:3000])
            resp.raise_for_status()

        return resp.json()

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def paginate(path, collection_key, params=None, limit=200, sleep_s=0.25):
    params = dict(params or {})
    params["limit"] = limit

    rows = []
    cursor = None

    while True:
        if cursor:
            params["cursor"] = cursor
        else:
            params.pop("cursor", None)

        data = get_json(path, params=params)
        rows.extend(data.get(collection_key, []))

        cursor = data.get("cursor")
        if not cursor:
            break

        time.sleep(sleep_s)

    return rows


def flatten_dict(d, parent_key=""):
    out = {}

    for k, v in d.items():
        key = f"{parent_key}.{k}" if parent_key else k

        if isinstance(v, dict):
            out.update(flatten_dict(v, key))
        elif isinstance(v, list):
            out[key] = json.dumps(v)
        else:
            out[key] = v

    return out


# 1. Get event details
event_data = get_json(f"/events/{EVENT_TICKER}")
event = event_data.get("event", event_data)

df_event_details = pd.DataFrame([event])
df_event_details.to_csv(
    f"{OUT_DIR}/event_details_{EVENT_TICKER}.csv",
    index=False
)

display(df_event_details)


# 2. Get markets from both live/recent and historical endpoints
live_markets = paginate(
    "/markets",
    "markets",
    params={"event_ticker": EVENT_TICKER},
    limit=200
)

for m in live_markets:
    m["_source"] = "live_or_recent"

historical_markets = paginate(
    "/historical/markets",
    "markets",
    params={"event_ticker": EVENT_TICKER},
    limit=200
)

for m in historical_markets:
    m["_source"] = "historical"


# 3. Deduplicate by market ticker
markets_by_ticker = {}

for market in live_markets + historical_markets:
    ticker = market.get("ticker")
    if ticker:
        markets_by_ticker[ticker] = market

event_markets = list(markets_by_ticker.values())

print("Live/recent markets:", len(live_markets))
print("Historical markets:", len(historical_markets))
print("Unique markets:", len(event_markets))


# 4. Fetch full details for every market
full_market_rows = []
failed_markets = []

for i, market in enumerate(event_markets, start=1):
    ticker = market["ticker"]
    source = market.get("_source")

    print(f"[{i}/{len(event_markets)}] Fetching full details for {ticker}...")

    try:
        if source == "historical":
            data = get_json(f"/historical/markets/{ticker}")
            detail_endpoint = f"/historical/markets/{ticker}"
        else:
            data = get_json(f"/markets/{ticker}")
            detail_endpoint = f"/markets/{ticker}"

        full_market = data.get("market", data)

        full_market["_source"] = source
        full_market["_detail_endpoint"] = detail_endpoint
        full_market["_event_ticker_requested"] = EVENT_TICKER

        full_market_rows.append(full_market)

    except Exception as e:
        print(f"Failed {ticker}: {e}")
        failed_markets.append({
            "ticker": ticker,
            "source": source,
            "error": str(e)
        })

    time.sleep(0.25)


# 5. Combined full market CSV
df_full_market_details = pd.DataFrame(full_market_rows)

display(df_full_market_details)

df_full_market_details.to_csv(
    f"{OUT_DIR}/all_market_details_for_event_{EVENT_TICKER}.csv",
    index=False
)


# 6. One separate CSV per market
market_file_index = []

for market in full_market_rows:
    ticker = market.get("ticker")
    flat_market = flatten_dict(market)

    df_one_market = pd.DataFrame([flat_market])

    filename = f"market_{safe_filename(ticker)}.csv"
    filepath = f"{OUT_DIR}/{filename}"

    df_one_market.to_csv(filepath, index=False)

    market_file_index.append({
        "ticker": ticker,
        "csv_file": filename,
        "source": market.get("_source"),
        "status": market.get("status"),
        "result": market.get("result"),
        "title": market.get("title")
    })


df_market_file_index = pd.DataFrame(market_file_index)

display(df_market_file_index)

df_market_file_index.to_csv(
    f"{OUT_DIR}/market_file_index_{EVENT_TICKER}.csv",
    index=False
)


# 7. Failed markets CSV, if any
if failed_markets:
    df_failed_markets = pd.DataFrame(failed_markets)
    display(df_failed_markets)

    df_failed_markets.to_csv(
        f"{OUT_DIR}/failed_market_details_{EVENT_TICKER}.csv",
        index=False
    )


# 8. Zip all CSV files and download
zip_name = f"kalshi_all_market_csvs_{EVENT_TICKER}.zip"

with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as z:
    for filename in os.listdir(OUT_DIR):
        filepath = os.path.join(OUT_DIR, filename)
        z.write(filepath, arcname=filename)

print("Created zip:", zip_name)
files.download(zip_name)

,available_on_brokers,category,collateral_return_type,event_ticker,last_updated_ts,mutually_exclusive,series_ticker,settlement_sources,strike_period,sub_title,title
0,True,Elections,MECNET,KXELECTIONMOVZOHRAN-25,0001-01-01T00:00:00Z,True,KXELECTIONMOVZOHRAN,[{'name': 'Board of Elections in the City of N...,,In 2025,Margin of victory for Zohran Mamdani in the NY...

Live/recent markets: 0
Historical markets: 10
Unique markets: 10
[1/10] Fetching full details for KXELECTIONMOVZOHRAN-25-ZMAM-T24...
[2/10] Fetching full details for KXELECTIONMOVZOHRAN-25-ZMAM-B7.5...
[3/10] Fetching full details for KXELECTIONMOVZOHRAN-25-ZMAM-B22.5...
[4/10] Fetching full details for KXELECTIONMOVZOHRAN-25-ZMAM-B19.5...
[5/10] Fetching full details for KXELECTIONMOVZOHRAN-25-ZMAM-B16.5...
[6/10] Fetching full details for KXELECTIONMOVZOHRAN-25-ZMAM-B13.5...
[7/10] Fetching full details for KXELECTIONMOVZOHRAN-25-ZMAM-B10.5...
[8/10] Fetching full details for KXELECTIONMOVZOHRAN-25-ZMAM-T0...
[9/10] Fetching full details for KXELECTIONMOVZOHRAN-25-ZMAM-B4.5...
[10/10] Fetching full details for KXELECTIONMOVZOHRAN-25-ZMAM-B1.5...

,can_close_early,close_time,created_time,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,fractional_trading_enabled,...,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,_source,_detail_endpoint,_event_ticker_requested,cap_strike,subtitle
0,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,24.0,True,...,1.0000,0.00,0.0000,0.00,24% or more,historical,/historical/markets/KXELECTIONMOVZOHRAN-25-ZMA...,KXELECTIONMOVZOHRAN-25,NaN,NaN
1,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,6.0,True,...,1.0000,0.00,0.0000,0.00,6-8.99%,historical,/historical/markets/KXELECTIONMOVZOHRAN-25-ZMA...,KXELECTIONMOVZOHRAN-25,8.99,NaN
2,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,21.0,True,...,1.0000,0.00,0.0000,0.00,21-23.99%,historical,/historical/markets/KXELECTIONMOVZOHRAN-25-ZMA...,KXELECTIONMOVZOHRAN-25,23.99,NaN
3,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,18.0,True,...,1.0000,0.00,0.0000,0.00,18-20.99%,historical,/historical/markets/KXELECTIONMOVZOHRAN-25-ZMA...,KXELECTIONMOVZOHRAN-25,20.99,NaN
4,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,15.0,True,...,1.0000,0.00,0.0000,0.00,15-17.99%,historical,/historical/markets/KXELECTIONMOVZOHRAN-25-ZMA...,KXELECTIONMOVZOHRAN-25,17.99,NaN
5,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,12.0,True,...,1.0000,0.00,0.0000,0.00,12-14.99%,historical,/historical/markets/KXELECTIONMOVZOHRAN-25-ZMA...,KXELECTIONMOVZOHRAN-25,14.99,NaN
6,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,9.0,True,...,1.0000,0.00,0.0000,0.00,9-11.99%,historical,/historical/markets/KXELECTIONMOVZOHRAN-25-ZMA...,KXELECTIONMOVZOHRAN-25,11.99,NaN
7,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,NaN,True,...,1.0000,0.00,0.0000,0.00,Less than 0%,historical,/historical/markets/KXELECTIONMOVZOHRAN-25-ZMA...,KXELECTIONMOVZOHRAN-25,0.00,:: Loses
8,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,3.0,True,...,1.0000,0.00,0.0000,0.00,3-5.99%,historical,/historical/markets/KXELECTIONMOVZOHRAN-25-ZMA...,KXELECTIONMOVZOHRAN-25,5.99,NaN
9,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,0.0,True,...,1.0000,0.00,0.0000,0.00,0-2.99%,historical,/historical/markets/KXELECTIONMOVZOHRAN-25-ZMA...,KXELECTIONMOVZOHRAN-25,2.99,NaN

,ticker,csv_file,source,status,result,title
0,KXELECTIONMOVZOHRAN-25-ZMAM-T24,market_KXELECTIONMOVZOHRAN-25-ZMAM-T24.csv,historical,finalized,no,Margin of victory for Zohran Mamdani in the Ma...
1,KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,market_KXELECTIONMOVZOHRAN-25-ZMAM-B7.5.csv,historical,finalized,no,Margin of victory for Zohran Mamdani in the Ma...
2,KXELECTIONMOVZOHRAN-25-ZMAM-B22.5,market_KXELECTIONMOVZOHRAN-25-ZMAM-B22.5.csv,historical,finalized,no,Margin of victory for Zohran Mamdani in the Ma...
3,KXELECTIONMOVZOHRAN-25-ZMAM-B19.5,market_KXELECTIONMOVZOHRAN-25-ZMAM-B19.5.csv,historical,finalized,no,Margin of victory for Zohran Mamdani in the Ma...
4,KXELECTIONMOVZOHRAN-25-ZMAM-B16.5,market_KXELECTIONMOVZOHRAN-25-ZMAM-B16.5.csv,historical,finalized,no,Margin of victory for Zohran Mamdani in the Ma...
5,KXELECTIONMOVZOHRAN-25-ZMAM-B13.5,market_KXELECTIONMOVZOHRAN-25-ZMAM-B13.5.csv,historical,finalized,no,Margin of victory for Zohran Mamdani in the Ma...
6,KXELECTIONMOVZOHRAN-25-ZMAM-B10.5,market_KXELECTIONMOVZOHRAN-25-ZMAM-B10.5.csv,historical,finalized,yes,Margin of victory for Zohran Mamdani in the Ma...
7,KXELECTIONMOVZOHRAN-25-ZMAM-T0,market_KXELECTIONMOVZOHRAN-25-ZMAM-T0.csv,historical,finalized,no,Margin of victory for Zohran Mamdani in the Ma...
8,KXELECTIONMOVZOHRAN-25-ZMAM-B4.5,market_KXELECTIONMOVZOHRAN-25-ZMAM-B4.5.csv,historical,finalized,no,Margin of victory for Zohran Mamdani in the Ma...
9,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,market_KXELECTIONMOVZOHRAN-25-ZMAM-B1.5.csv,historical,finalized,no,Margin of victory for Zohran Mamdani in the Ma...

Created zip: kalshi_all_market_csvs_KXELECTIONMOVZOHRAN-25.zip

In [21]:
files.download(zip_name)

In [23]:
import time
import os
import re
import zipfile
import pandas as pd
from google.colab import files

EVENT_TICKER = "KXELECTIONMOVZOHRAN-25"
SERIES_TICKER = "KXELECTIONMOVZOHRAN"

OUT_DIR = f"kalshi_daily_candlesticks_for_{EVENT_TICKER}"
os.makedirs(OUT_DIR, exist_ok=True)


def safe_filename(x):
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(x))


# Use df_full_market_details if it exists; otherwise use df_event_markets
try:
    df_markets_for_candles = df_full_market_details.copy()
except NameError:
    df_markets_for_candles = df_event_markets.copy()


all_daily_candles = []
failed_daily_candles = []

for i, row in df_markets_for_candles.iterrows():
    market_ticker = row["ticker"]
    source = row.get("_source", "historical")

    open_time = pd.to_datetime(row.get("open_time"), utc=True, errors="coerce")
    end_time = pd.to_datetime(
        row.get("close_time") or row.get("expiration_time") or row.get("settlement_ts"),
        utc=True,
        errors="coerce"
    )

    if pd.isna(open_time) or pd.isna(end_time):
        print(f"Skipping {market_ticker}: missing open/end time")
        failed_daily_candles.append({
            "ticker": market_ticker,
            "reason": "missing open_time or end_time"
        })
        continue

    start_ts = int(open_time.timestamp())
    end_ts = int(end_time.timestamp())

    print(f"[{i+1}/{len(df_markets_for_candles)}] Getting daily candles for {market_ticker}...")

    try:
        if source == "historical":
            path = f"/historical/markets/{market_ticker}/candlesticks"
        else:
            path = f"/series/{SERIES_TICKER}/markets/{market_ticker}/candlesticks"

        data = get_json(
            path,
            params={
                "start_ts": start_ts,
                "end_ts": end_ts,
                "period_interval": 1440
            }
        )

        candles = data.get("candlesticks", [])

        market_candles = []

        for candle in candles:
            candle["market_ticker"] = market_ticker
            candle["event_ticker"] = EVENT_TICKER
            candle["series_ticker"] = SERIES_TICKER
            candle["market_title"] = row.get("title")
            candle["market_status"] = row.get("status")
            candle["market_result"] = row.get("result")
            candle["market_open_time"] = open_time
            candle["market_end_time"] = end_time
            candle["period_interval"] = 1440
            candle["period_label"] = "daily"
            candle["_source"] = source

            market_candles.append(candle)
            all_daily_candles.append(candle)

        df_one_market_daily = pd.DataFrame(market_candles)

        df_one_market_daily.to_csv(
            f"{OUT_DIR}/daily_candlesticks_{safe_filename(market_ticker)}.csv",
            index=False
        )

    except Exception as e:
        print(f"Failed {market_ticker}: {e}")
        failed_daily_candles.append({
            "ticker": market_ticker,
            "reason": str(e)
        })

    time.sleep(0.25)


df_all_daily_market_candlesticks = pd.DataFrame(all_daily_candles)

display(df_all_daily_market_candlesticks)

print("Total daily candlestick rows:", len(df_all_daily_market_candlesticks))
print("Columns:", df_all_daily_market_candlesticks.columns.tolist())

df_all_daily_market_candlesticks.to_csv(
    f"{OUT_DIR}/all_daily_market_candlesticks_{EVENT_TICKER}.csv",
    index=False
)

if failed_daily_candles:
    df_failed_daily_candles = pd.DataFrame(failed_daily_candles)
    display(df_failed_daily_candles)

    df_failed_daily_candles.to_csv(
        f"{OUT_DIR}/failed_daily_candlesticks_{EVENT_TICKER}.csv",
        index=False
    )


# Zip and download
zip_name = f"kalshi_daily_market_candlesticks_{EVENT_TICKER}.zip"

with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as z:
    for filename in os.listdir(OUT_DIR):
        filepath = os.path.join(OUT_DIR, filename)
        z.write(filepath, arcname=filename)

files.download(zip_name)

[1/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-T24...
[2/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B7.5...
[3/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B22.5...
[4/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B19.5...
[5/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B16.5...
[6/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B13.5...
[7/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B10.5...
[8/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-T0...
[9/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B4.5...
[10/10] Getting daily candles for KXELECTIONMOVZOHRAN-25-ZMAM-B1.5...

,end_period_ts,open_interest,price,volume,yes_ask,yes_bid,market_ticker,event_ticker,series_ticker,market_title,market_status,market_result,market_open_time,market_end_time,period_interval,period_label,_source
0,1755144000,5154.00,"{'close': '0.4100', 'high': '0.7400', 'low': '...",5433.00,"{'close': '0.4500', 'high': '1.0000', 'low': '...","{'close': '0.4100', 'high': '0.4700', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily,historical
1,1755230400,6394.00,"{'close': '0.4000', 'high': '0.7000', 'low': '...",1858.00,"{'close': '0.4800', 'high': '0.7900', 'low': '...","{'close': '0.4000', 'high': '0.4500', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily,historical
2,1755316800,6429.00,"{'close': '0.3900', 'high': '0.4000', 'low': '...",90.00,"{'close': '0.4700', 'high': '0.4800', 'low': '...","{'close': '0.4100', 'high': '0.4100', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily,historical
3,1755403200,6429.00,"{'close': '0.4800', 'high': '0.4800', 'low': '...",4.00,"{'close': '0.4700', 'high': '0.4800', 'low': '...","{'close': '0.4200', 'high': '0.4200', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily,historical
4,1755489600,6840.00,"{'close': '0.4100', 'high': '0.4200', 'low': '...",468.00,"{'close': '0.4600', 'high': '0.4800', 'low': '...","{'close': '0.4100', 'high': '0.4200', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-T24,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily,historical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1105,1764306000,921513.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...",348.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily,historical
1106,1764392400,921514.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...",1.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily,historical
1107,1764478800,921514.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily,historical
1108,1764565200,921514.00,"{'close': None, 'high': None, 'low': None, 'me...",0.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily,historical
1109,1764651600,921614.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...",100.00,"{'close': '0.0100', 'high': '0.0100', 'low': '...","{'close': '0.0000', 'high': '0.0000', 'low': '...",KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,KXELECTIONMOVZOHRAN-25,KXELECTIONMOVZOHRAN,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily,historical

Total daily candlestick rows: 1110
Columns: ['end_period_ts', 'open_interest', 'price', 'volume', 'yes_ask', 'yes_bid', 'market_ticker', 'event_ticker', 'series_ticker', 'market_title', 'market_status', 'market_result', 'market_open_time', 'market_end_time', 'period_interval', 'period_label', '_source']

In [1]:
import json
import time
import requests
import pandas as pd
from urllib.parse import urljoin
from google.colab import files

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

MARKET_TICKER = "KXELECTIONMOVZOHRAN-25-ZMAM-T24"

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-daily-historical-candlesticks-colab/1.0"
})


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        try:
            data = resp.json()
        except Exception:
            data = {"raw_text": resp.text}

        if resp.status_code >= 400:
            print("Bad URL:", resp.url)
            print("Kalshi response:", json.dumps(data, indent=2)[:3000])
            resp.raise_for_status()

        return data

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def flatten_dict(d, parent_key=""):
    out = {}

    for k, v in d.items():
        key = f"{parent_key}.{k}" if parent_key else k

        if isinstance(v, dict):
            out.update(flatten_dict(v, key))
        elif isinstance(v, list):
            out[key] = json.dumps(v)
        else:
            out[key] = v

    return out


# 1. Get historical market details to determine full date range
market_data = get_json(f"/historical/markets/{MARKET_TICKER}")
market = market_data.get("market", market_data)

df_market_details = pd.DataFrame([market])
display(df_market_details)

open_time = pd.to_datetime(market.get("open_time"), utc=True, errors="coerce")

end_time = pd.to_datetime(
    market.get("close_time") or market.get("expiration_time") or market.get("settlement_ts"),
    utc=True,
    errors="coerce"
)

if pd.isna(open_time):
    raise ValueError("Market open_time is missing. Cannot create start_ts.")

if pd.isna(end_time):
    raise ValueError("Market close/expiration/settlement time is missing. Cannot create end_ts.")

start_ts = int(open_time.timestamp())
end_ts = int(end_time.timestamp())

print("Market ticker:", MARKET_TICKER)
print("Start:", open_time)
print("End:", end_time)


# 2. Get DAILY historical candlesticks
candles_data = get_json(
    f"/historical/markets/{MARKET_TICKER}/candlesticks",
    params={
        "start_ts": start_ts,
        "end_ts": end_ts,
        "period_interval": 1440
    }
)

candles = candles_data.get("candlesticks", [])

daily_rows = []

for candle in candles:
    row = flatten_dict(candle)

    row["market_ticker"] = MARKET_TICKER
    row["period_interval"] = 1440
    row["period_label"] = "daily"
    row["market_open_time"] = open_time
    row["market_end_time"] = end_time

    daily_rows.append(row)


# 3. Create DataFrame
df_daily_historical_candlesticks = pd.DataFrame(daily_rows)

display(df_daily_historical_candlesticks)

print("Daily candlestick rows:", len(df_daily_historical_candlesticks))
print("Columns:")
print(df_daily_historical_candlesticks.columns.tolist())


# 4. Save and download CSV
csv_filename = f"kalshi_daily_historical_candlesticks_{MARKET_TICKER}.csv"

df_daily_historical_candlesticks.to_csv(csv_filename, index=False)

files.download(csv_filename)

,can_close_early,close_time,created_time,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,fractional_trading_enabled,...,ticker,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title
0,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,24,True,...,KXELECTIONMOVZOHRAN-25-ZMAM-T24,Margin of victory for Zohran Mamdani in the Ma...,2026-03-04T22:43:52.878979Z,0.00,2715311.00,1.0000,0.00,0.0000,0.00,24% or more

Market ticker: KXELECTIONMOVZOHRAN-25-ZMAM-T24
Start: 2025-08-13 14:00:00+00:00
End: 2025-12-03 01:44:48.719034+00:00

,end_period_ts,open_interest,price.close,price.high,price.low,price.mean,price.open,price.previous,volume,yes_ask.close,...,yes_ask.open,yes_bid.close,yes_bid.high,yes_bid.low,yes_bid.open,market_ticker,period_interval,period_label,market_open_time,market_end_time
0,1755144000,5154.00,0.4100,0.7400,0.1900,0.3164,0.1900,None,5433.00,0.4500,...,1.0000,0.4100,0.4700,0.0800,0.0800,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00
1,1755230400,6394.00,0.4000,0.7000,0.4000,0.4676,0.4100,0.4100,1858.00,0.4800,...,0.4500,0.4000,0.4500,0.3900,0.4100,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00
2,1755316800,6429.00,0.3900,0.4000,0.3900,0.3963,0.4000,0.4000,90.00,0.4700,...,0.4800,0.4100,0.4100,0.3900,0.4000,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00
3,1755403200,6429.00,0.4800,0.4800,0.4700,0.4750,0.4700,0.3900,4.00,0.4700,...,0.4700,0.4200,0.4200,0.4100,0.4100,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00
4,1755489600,6840.00,0.4100,0.4200,0.4100,0.4100,0.4200,0.4800,468.00,0.4600,...,0.4700,0.4100,0.4200,0.4100,0.4200,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,1764306000,1083612.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,904.00,0.0100,...,0.0100,0.0000,0.0000,0.0000,0.0000,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00
107,1764392400,1085458.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,1879.00,0.0100,...,0.0100,0.0000,0.0000,0.0000,0.0000,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00
108,1764478800,1085458.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,298.00,0.0100,...,0.0100,0.0000,0.0000,0.0000,0.0000,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00
109,1764565200,1085458.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,447.00,0.0100,...,0.0100,0.0000,0.0000,0.0000,0.0000,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00
110,1764651600,1085458.00,None,None,None,None,None,0.0100,0.00,0.0100,...,0.0100,0.0000,0.0000,0.0000,0.0000,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00

Daily candlestick rows: 111
Columns:
['end_period_ts', 'open_interest', 'price.close', 'price.high', 'price.low', 'price.mean', 'price.open', 'price.previous', 'volume', 'yes_ask.close', 'yes_ask.high', 'yes_ask.low', 'yes_ask.open', 'yes_bid.close', 'yes_bid.high', 'yes_bid.low', 'yes_bid.open', 'market_ticker', 'period_interval', 'period_label', 'market_open_time', 'market_end_time']

In [2]:
import json
import time
import os
import re
import zipfile
import requests
import pandas as pd
from urllib.parse import urljoin
from google.colab import files

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

market_tickers = [
    "KXELECTIONMOVZOHRAN-25-ZMAM-T24",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B7.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B22.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B19.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B16.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B13.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B10.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-T0",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B4.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B1.5",
]

OUT_DIR = "kalshi_daily_candlesticks_zmam_markets"
os.makedirs(OUT_DIR, exist_ok=True)

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-bulk-daily-historical-candlesticks-colab/1.0"
})


def safe_filename(x):
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(x))


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        try:
            data = resp.json()
        except Exception:
            data = {"raw_text": resp.text}

        if resp.status_code >= 400:
            print("Bad URL:", resp.url)
            print("Kalshi response:", json.dumps(data, indent=2)[:3000])
            resp.raise_for_status()

        return data

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def flatten_dict(d, parent_key=""):
    out = {}

    for k, v in d.items():
        key = f"{parent_key}.{k}" if parent_key else k

        if isinstance(v, dict):
            out.update(flatten_dict(v, key))
        elif isinstance(v, list):
            out[key] = json.dumps(v)
        else:
            out[key] = v

    return out


all_daily_rows = []
market_detail_rows = []
failed_tickers = []

for i, market_ticker in enumerate(market_tickers, start=1):
    print(f"[{i}/{len(market_tickers)}] Processing {market_ticker}...")

    try:
        # 1. Get historical market details
        market_data = get_json(f"/historical/markets/{market_ticker}")
        market = market_data.get("market", market_data)

        market_detail_rows.append(market)

        open_time = pd.to_datetime(
            market.get("open_time"),
            utc=True,
            errors="coerce"
        )

        end_time = pd.to_datetime(
            market.get("close_time") or market.get("expiration_time") or market.get("settlement_ts"),
            utc=True,
            errors="coerce"
        )

        if pd.isna(open_time) or pd.isna(end_time):
            raise ValueError("Missing open_time or end_time")

        start_ts = int(open_time.timestamp())
        end_ts = int(end_time.timestamp())

        print("  Start:", open_time)
        print("  End:", end_time)

        # 2. Get daily candlesticks
        candles_data = get_json(
            f"/historical/markets/{market_ticker}/candlesticks",
            params={
                "start_ts": start_ts,
                "end_ts": end_ts,
                "period_interval": 1440
            }
        )

        candles = candles_data.get("candlesticks", [])
        print("  Daily candles:", len(candles))

        one_market_rows = []

        for candle in candles:
            row = flatten_dict(candle)

            row["market_ticker"] = market_ticker
            row["period_interval"] = 1440
            row["period_label"] = "daily"
            row["market_open_time"] = open_time
            row["market_end_time"] = end_time
            row["market_title"] = market.get("title")
            row["market_status"] = market.get("status")
            row["market_result"] = market.get("result")
            row["event_ticker"] = market.get("event_ticker")
            row["series_ticker"] = market.get("series_ticker")

            one_market_rows.append(row)
            all_daily_rows.append(row)

        # 3. Save individual market CSV
        df_one_market = pd.DataFrame(one_market_rows)

        one_market_csv = f"{OUT_DIR}/daily_candlesticks_{safe_filename(market_ticker)}.csv"
        df_one_market.to_csv(one_market_csv, index=False)

    except Exception as e:
        print(f"  Failed {market_ticker}: {e}")
        failed_tickers.append({
            "ticker": market_ticker,
            "error": str(e)
        })

    time.sleep(0.25)


# 4. Combined daily candlesticks DataFrame
df_all_daily_candlesticks = pd.DataFrame(all_daily_rows)

display(df_all_daily_candlesticks)

print("Total daily candlestick rows:", len(df_all_daily_candlesticks))
print("Columns:", df_all_daily_candlesticks.columns.tolist())

combined_csv = f"{OUT_DIR}/all_daily_candlesticks_zmam_markets.csv"
df_all_daily_candlesticks.to_csv(combined_csv, index=False)


# 5. Market details DataFrame
df_market_details = pd.DataFrame(market_detail_rows)

display(df_market_details)

market_details_csv = f"{OUT_DIR}/market_details_zmam_markets.csv"
df_market_details.to_csv(market_details_csv, index=False)


# 6. Failed ticker DataFrame
if failed_tickers:
    df_failed_tickers = pd.DataFrame(failed_tickers)
    display(df_failed_tickers)

    failed_csv = f"{OUT_DIR}/failed_zmam_market_tickers.csv"
    df_failed_tickers.to_csv(failed_csv, index=False)


# 7. Zip and download everything
zip_name = "kalshi_daily_candlesticks_zmam_markets.zip"

with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as z:
    for filename in os.listdir(OUT_DIR):
        filepath = os.path.join(OUT_DIR, filename)
        z.write(filepath, arcname=filename)

files.download(zip_name)

[1/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-T24...
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[2/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B7.5...
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[3/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B22.5...
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[4/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B19.5...
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[5/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B16.5...
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[6/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B13.5...
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[7/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B10.5...
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[8/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-T0...
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[9/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B4.5...
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[10/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B1.5...
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111

,end_period_ts,open_interest,price.close,price.high,price.low,price.mean,price.open,price.previous,volume,yes_ask.close,...,market_ticker,period_interval,period_label,market_open_time,market_end_time,market_title,market_status,market_result,event_ticker,series_ticker
0,1755144000,5154.00,0.4100,0.7400,0.1900,0.3164,0.1900,None,5433.00,0.4500,...,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,KXELECTIONMOVZOHRAN-25,None
1,1755230400,6394.00,0.4000,0.7000,0.4000,0.4676,0.4100,0.4100,1858.00,0.4800,...,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,KXELECTIONMOVZOHRAN-25,None
2,1755316800,6429.00,0.3900,0.4000,0.3900,0.3963,0.4000,0.4000,90.00,0.4700,...,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,KXELECTIONMOVZOHRAN-25,None
3,1755403200,6429.00,0.4800,0.4800,0.4700,0.4750,0.4700,0.3900,4.00,0.4700,...,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,KXELECTIONMOVZOHRAN-25,None
4,1755489600,6840.00,0.4100,0.4200,0.4100,0.4100,0.4200,0.4800,468.00,0.4600,...,KXELECTIONMOVZOHRAN-25-ZMAM-T24,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,KXELECTIONMOVZOHRAN-25,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1105,1764306000,921513.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,348.00,0.0100,...,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,KXELECTIONMOVZOHRAN-25,None
1106,1764392400,921514.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,1.00,0.0100,...,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,KXELECTIONMOVZOHRAN-25,None
1107,1764478800,921514.00,None,None,None,None,None,0.0100,0.00,0.0100,...,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,KXELECTIONMOVZOHRAN-25,None
1108,1764565200,921514.00,None,None,None,None,None,0.0100,0.00,0.0100,...,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,KXELECTIONMOVZOHRAN-25,None
1109,1764651600,921614.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,100.00,0.0100,...,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,1440,daily,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,Margin of victory for Zohran Mamdani in the Ma...,finalized,no,KXELECTIONMOVZOHRAN-25,None

Total daily candlestick rows: 1110
Columns: ['end_period_ts', 'open_interest', 'price.close', 'price.high', 'price.low', 'price.mean', 'price.open', 'price.previous', 'volume', 'yes_ask.close', 'yes_ask.high', 'yes_ask.low', 'yes_ask.open', 'yes_bid.close', 'yes_bid.high', 'yes_bid.low', 'yes_bid.open', 'market_ticker', 'period_interval', 'period_label', 'market_open_time', 'market_end_time', 'market_title', 'market_status', 'market_result', 'event_ticker', 'series_ticker']

,can_close_early,close_time,created_time,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,fractional_trading_enabled,...,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,cap_strike,subtitle
0,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,24.0,True,...,2026-03-04T22:43:52.878979Z,0.00,2715311.00,1.0000,0.00,0.0000,0.00,24% or more,NaN,NaN
1,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,6.0,True,...,2026-03-04T22:43:52.624601Z,0.00,3398478.00,1.0000,0.00,0.0000,0.00,6-8.99%,8.99,NaN
2,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,21.0,True,...,2026-03-04T22:43:52.829531Z,0.00,922621.00,1.0000,0.00,0.0000,0.00,21-23.99%,23.99,NaN
3,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,18.0,True,...,2026-03-04T22:43:52.77753Z,0.00,819153.00,1.0000,0.00,0.0000,0.00,18-20.99%,20.99,NaN
4,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,15.0,True,...,2026-03-04T22:43:52.739289Z,0.00,923736.00,1.0000,0.00,0.0000,0.00,15-17.99%,17.99,NaN
5,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,12.0,True,...,2026-03-04T22:43:52.700178Z,0.00,1454986.00,1.0000,0.00,0.0000,0.00,12-14.99%,14.99,NaN
6,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121614Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,9.0,True,...,2026-03-04T22:43:52.661638Z,0.00,2641908.00,1.0000,0.00,0.0000,0.00,9-11.99%,11.99,NaN
7,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,NaN,True,...,2026-03-04T22:43:52.494901Z,0.00,1488079.00,1.0000,0.00,0.0000,0.00,Less than 0%,0.00,:: Loses
8,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,3.0,True,...,2026-03-04T22:43:52.57737Z,0.00,1689089.00,1.0000,0.00,0.0000,0.00,3-5.99%,5.99,NaN
9,True,2025-12-03T01:44:48.719034Z,2025-08-12T21:46:06.121613Z,This market will close and expire early if the...,KXELECTIONMOVZOHRAN-25,2025-11-04T15:00:00Z,2026-11-04T15:00:00Z,9-11.99%,0.0,True,...,2026-03-04T22:43:52.539059Z,0.00,1256254.00,1.0000,0.00,0.0000,0.00,0-2.99%,2.99,NaN

In [3]:
import json
import time
import os
import re
import zipfile
import requests
import pandas as pd
from urllib.parse import urljoin
from google.colab import files

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

market_tickers = [
    "KXELECTIONMOVZOHRAN-25-ZMAM-T24",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B7.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B22.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B19.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B16.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B13.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B10.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-T0",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B4.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B1.5",
]

OUT_DIR = "kalshi_zmam_daily_candlesticks_with_market_info"
os.makedirs(OUT_DIR, exist_ok=True)

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-zmam-daily-candlesticks-with-info-colab/1.0"
})


def safe_filename(x):
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(x))


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        try:
            data = resp.json()
        except Exception:
            data = {"raw_text": resp.text}

        if resp.status_code >= 400:
            print("Bad URL:", resp.url)
            print("Kalshi response:", json.dumps(data, indent=2)[:3000])
            resp.raise_for_status()

        return data

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def flatten_dict(d, parent_key=""):
    out = {}

    for k, v in d.items():
        key = f"{parent_key}.{k}" if parent_key else k

        if isinstance(v, dict):
            out.update(flatten_dict(v, key))
        elif isinstance(v, list):
            out[key] = json.dumps(v)
        else:
            out[key] = v

    return out


all_daily_rows = []
market_detail_rows = []
failed_tickers = []

for i, market_ticker in enumerate(market_tickers, start=1):
    print(f"[{i}/{len(market_tickers)}] Processing {market_ticker}...")

    try:
        # 1. Get historical market details
        market_data = get_json(f"/historical/markets/{market_ticker}")
        market = market_data.get("market", market_data)

        market_title = market.get("title")
        event_ticker = market.get("event_ticker")
        series_ticker = market.get("series_ticker")

        market_detail_rows.append({
            "market_ticker": market_ticker,
            "market_title": market_title,
            "event_ticker": event_ticker,
            "series_ticker": series_ticker,
            "status": market.get("status"),
            "result": market.get("result"),
            "open_time": market.get("open_time"),
            "close_time": market.get("close_time"),
            "expiration_time": market.get("expiration_time"),
            "settlement_ts": market.get("settlement_ts"),
            "volume_fp": market.get("volume_fp"),
            "volume_24h_fp": market.get("volume_24h_fp"),
        })

        open_time = pd.to_datetime(
            market.get("open_time"),
            utc=True,
            errors="coerce"
        )

        end_time = pd.to_datetime(
            market.get("close_time") or market.get("expiration_time") or market.get("settlement_ts"),
            utc=True,
            errors="coerce"
        )

        if pd.isna(open_time) or pd.isna(end_time):
            raise ValueError("Missing open_time or end_time")

        start_ts = int(open_time.timestamp())
        end_ts = int(end_time.timestamp())

        print("  Title:", market_title)
        print("  Event:", event_ticker)
        print("  Series:", series_ticker)
        print("  Start:", open_time)
        print("  End:", end_time)

        # 2. Get daily candlesticks
        candles_data = get_json(
            f"/historical/markets/{market_ticker}/candlesticks",
            params={
                "start_ts": start_ts,
                "end_ts": end_ts,
                "period_interval": 1440
            }
        )

        candles = candles_data.get("candlesticks", [])
        print("  Daily candles:", len(candles))

        one_market_rows = []

        for candle in candles:
            row = flatten_dict(candle)

            row["market_ticker"] = market_ticker
            row["market_title"] = market_title
            row["event_ticker"] = event_ticker
            row["series_ticker"] = series_ticker
            row["market_status"] = market.get("status")
            row["market_result"] = market.get("result")
            row["market_open_time"] = open_time
            row["market_end_time"] = end_time
            row["period_interval"] = 1440
            row["period_label"] = "daily"

            one_market_rows.append(row)
            all_daily_rows.append(row)

        # 3. Save individual market CSV
        df_one_market = pd.DataFrame(one_market_rows)

        df_one_market.to_csv(
            f"{OUT_DIR}/daily_candlesticks_{safe_filename(market_ticker)}.csv",
            index=False
        )

    except Exception as e:
        print(f"  Failed {market_ticker}: {e}")
        failed_tickers.append({
            "ticker": market_ticker,
            "error": str(e)
        })

    time.sleep(0.25)


# 4. Combined daily candlesticks DataFrame
df_all_daily_candlesticks = pd.DataFrame(all_daily_rows)

display(df_all_daily_candlesticks)

print("Total daily candlestick rows:", len(df_all_daily_candlesticks))
print("Columns:", df_all_daily_candlesticks.columns.tolist())

df_all_daily_candlesticks.to_csv(
    f"{OUT_DIR}/all_daily_candlesticks_with_market_info.csv",
    index=False
)


# 5. Market detail summary DataFrame
df_market_details = pd.DataFrame(market_detail_rows)

display(df_market_details)

df_market_details.to_csv(
    f"{OUT_DIR}/market_details_summary.csv",
    index=False
)


# 6. Failed ticker DataFrame
if failed_tickers:
    df_failed_tickers = pd.DataFrame(failed_tickers)
    display(df_failed_tickers)

    df_failed_tickers.to_csv(
        f"{OUT_DIR}/failed_market_tickers.csv",
        index=False
    )


# 7. Zip and download everything
zip_name = "kalshi_new_attempt.zip"

with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as z:
    for filename in os.listdir(OUT_DIR):
        filepath = os.path.join(OUT_DIR, filename)
        z.write(filepath, arcname=filename)

files.download(zip_name)

[1/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-T24...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[2/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B7.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[3/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B22.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[4/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B19.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[5/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B16.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[6/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B13.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[7/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B10.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[8/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-T0...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[9/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B4.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[10/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B1.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111

,end_period_ts,open_interest,price.close,price.high,price.low,price.mean,price.open,price.previous,volume,yes_ask.close,...,market_ticker,market_title,event_ticker,series_ticker,market_status,market_result,market_open_time,market_end_time,period_interval,period_label
0,1755144000,5154.00,0.4100,0.7400,0.1900,0.3164,0.1900,None,5433.00,0.4500,...,KXELECTIONMOVZOHRAN-25-ZMAM-T24,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
1,1755230400,6394.00,0.4000,0.7000,0.4000,0.4676,0.4100,0.4100,1858.00,0.4800,...,KXELECTIONMOVZOHRAN-25-ZMAM-T24,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
2,1755316800,6429.00,0.3900,0.4000,0.3900,0.3963,0.4000,0.4000,90.00,0.4700,...,KXELECTIONMOVZOHRAN-25-ZMAM-T24,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
3,1755403200,6429.00,0.4800,0.4800,0.4700,0.4750,0.4700,0.3900,4.00,0.4700,...,KXELECTIONMOVZOHRAN-25-ZMAM-T24,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
4,1755489600,6840.00,0.4100,0.4200,0.4100,0.4100,0.4200,0.4800,468.00,0.4600,...,KXELECTIONMOVZOHRAN-25-ZMAM-T24,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1105,1764306000,921513.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,348.00,0.0100,...,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
1106,1764392400,921514.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,1.00,0.0100,...,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
1107,1764478800,921514.00,None,None,None,None,None,0.0100,0.00,0.0100,...,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
1108,1764565200,921514.00,None,None,None,None,None,0.0100,0.00,0.0100,...,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
1109,1764651600,921614.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,100.00,0.0100,...,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily

Total daily candlestick rows: 1110
Columns: ['end_period_ts', 'open_interest', 'price.close', 'price.high', 'price.low', 'price.mean', 'price.open', 'price.previous', 'volume', 'yes_ask.close', 'yes_ask.high', 'yes_ask.low', 'yes_ask.open', 'yes_bid.close', 'yes_bid.high', 'yes_bid.low', 'yes_bid.open', 'market_ticker', 'market_title', 'event_ticker', 'series_ticker', 'market_status', 'market_result', 'market_open_time', 'market_end_time', 'period_interval', 'period_label']

,market_ticker,market_title,event_ticker,series_ticker,status,result,open_time,close_time,expiration_time,settlement_ts,volume_fp,volume_24h_fp
0,KXELECTIONMOVZOHRAN-25-ZMAM-T24,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,2715311.00,0.00
1,KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,3398478.00,0.00
2,KXELECTIONMOVZOHRAN-25-ZMAM-B22.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,922621.00,0.00
3,KXELECTIONMOVZOHRAN-25-ZMAM-B19.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,819153.00,0.00
4,KXELECTIONMOVZOHRAN-25-ZMAM-B16.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,923736.00,0.00
5,KXELECTIONMOVZOHRAN-25-ZMAM-B13.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1454986.00,0.00
6,KXELECTIONMOVZOHRAN-25-ZMAM-B10.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,yes,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,2641908.00,0.00
7,KXELECTIONMOVZOHRAN-25-ZMAM-T0,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1488079.00,0.00
8,KXELECTIONMOVZOHRAN-25-ZMAM-B4.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1689089.00,0.00
9,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1256254.00,0.00

In [4]:
import json
import time
import os
import re
import zipfile
import requests
import pandas as pd
from urllib.parse import urljoin
from google.colab import files

BASE_URL = "https://external-api.kalshi.com/trade-api/v2"

market_tickers = [
    "KXELECTIONMOVZOHRAN-25-ZMAM-T24",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B7.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B22.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B19.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B16.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B13.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B10.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-T0",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B4.5",
    "KXELECTIONMOVZOHRAN-25-ZMAM-B1.5",
]

OUT_DIR = "kalshi_zmam_daily_candlesticks_with_rules"
os.makedirs(OUT_DIR, exist_ok=True)

session = requests.Session()
session.headers.update({
    "User-Agent": "kalshi-zmam-daily-candlesticks-with-rules-colab/1.0"
})


def safe_filename(x):
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(x))


def get_json(path, params=None, max_retries=10, timeout=30):
    url = urljoin(BASE_URL + "/", path.lstrip("/"))
    params = params or {}

    for attempt in range(max_retries):
        resp = session.get(url, params=params, timeout=timeout)

        if resp.status_code == 429:
            sleep_s = min(5 * (attempt + 1), 60)
            print(f"Rate limited. Sleeping {sleep_s}s...")
            time.sleep(sleep_s)
            continue

        try:
            data = resp.json()
        except Exception:
            data = {"raw_text": resp.text}

        if resp.status_code >= 400:
            print("Bad URL:", resp.url)
            print("Kalshi response:", json.dumps(data, indent=2)[:3000])
            resp.raise_for_status()

        return data

    raise RuntimeError(f"Failed after {max_retries} retries: {url}")


def flatten_dict(d, parent_key=""):
    out = {}

    for k, v in d.items():
        key = f"{parent_key}.{k}" if parent_key else k

        if isinstance(v, dict):
            out.update(flatten_dict(v, key))
        elif isinstance(v, list):
            out[key] = json.dumps(v)
        else:
            out[key] = v

    return out


all_daily_rows = []
market_detail_rows = []
failed_tickers = []

for i, market_ticker in enumerate(market_tickers, start=1):
    print(f"[{i}/{len(market_tickers)}] Processing {market_ticker}...")

    try:
        # 1. Get historical market details
        market_data = get_json(f"/historical/markets/{market_ticker}")
        market = market_data.get("market", market_data)

        market_title = market.get("title")
        event_ticker = market.get("event_ticker")
        series_ticker = market.get("series_ticker")
        no_sub_title = market.get("no_sub_title")
        rules_primary = market.get("rules_primary")
        rules_secondary = market.get("rules_secondary")

        market_detail_rows.append({
            "market_ticker": market_ticker,
            "market_title": market_title,
            "event_ticker": event_ticker,
            "series_ticker": series_ticker,
            "no_sub_title": no_sub_title,
            "rules_primary": rules_primary,
            "rules_secondary": rules_secondary,
            "yes_sub_title": market.get("yes_sub_title"),
            "status": market.get("status"),
            "result": market.get("result"),
            "open_time": market.get("open_time"),
            "close_time": market.get("close_time"),
            "expiration_time": market.get("expiration_time"),
            "settlement_ts": market.get("settlement_ts"),
            "volume_fp": market.get("volume_fp"),
            "volume_24h_fp": market.get("volume_24h_fp"),
        })

        open_time = pd.to_datetime(
            market.get("open_time"),
            utc=True,
            errors="coerce"
        )

        end_time = pd.to_datetime(
            market.get("close_time") or market.get("expiration_time") or market.get("settlement_ts"),
            utc=True,
            errors="coerce"
        )

        if pd.isna(open_time) or pd.isna(end_time):
            raise ValueError("Missing open_time or end_time")

        start_ts = int(open_time.timestamp())
        end_ts = int(end_time.timestamp())

        print("  Title:", market_title)
        print("  Event:", event_ticker)
        print("  Series:", series_ticker)
        print("  No subtitle:", no_sub_title)
        print("  Start:", open_time)
        print("  End:", end_time)

        # 2. Get daily candlesticks
        candles_data = get_json(
            f"/historical/markets/{market_ticker}/candlesticks",
            params={
                "start_ts": start_ts,
                "end_ts": end_ts,
                "period_interval": 1440
            }
        )

        candles = candles_data.get("candlesticks", [])
        print("  Daily candles:", len(candles))

        one_market_rows = []

        for candle in candles:
            row = flatten_dict(candle)

            row["market_ticker"] = market_ticker
            row["market_title"] = market_title
            row["event_ticker"] = event_ticker
            row["series_ticker"] = series_ticker
            row["no_sub_title"] = no_sub_title
            row["rules_primary"] = rules_primary
            row["rules_secondary"] = rules_secondary
            row["yes_sub_title"] = market.get("yes_sub_title")
            row["market_status"] = market.get("status")
            row["market_result"] = market.get("result")
            row["market_open_time"] = open_time
            row["market_end_time"] = end_time
            row["period_interval"] = 1440
            row["period_label"] = "daily"

            one_market_rows.append(row)
            all_daily_rows.append(row)

        # 3. Save individual market CSV
        df_one_market = pd.DataFrame(one_market_rows)

        df_one_market.to_csv(
            f"{OUT_DIR}/daily_candlesticks_{safe_filename(market_ticker)}.csv",
            index=False
        )

    except Exception as e:
        print(f"  Failed {market_ticker}: {e}")
        failed_tickers.append({
            "ticker": market_ticker,
            "error": str(e)
        })

    time.sleep(0.25)


# 4. Combined daily candlesticks DataFrame
df_all_daily_candlesticks = pd.DataFrame(all_daily_rows)

display(df_all_daily_candlesticks)

print("Total daily candlestick rows:", len(df_all_daily_candlesticks))
print("Columns:", df_all_daily_candlesticks.columns.tolist())

df_all_daily_candlesticks.to_csv(
    f"{OUT_DIR}/all_daily_candlesticks_with_rules.csv",
    index=False
)


# 5. Market detail summary DataFrame
df_market_details = pd.DataFrame(market_detail_rows)

display(df_market_details)

df_market_details.to_csv(
    f"{OUT_DIR}/market_details_summary_with_rules.csv",
    index=False
)


# 6. Failed ticker DataFrame
if failed_tickers:
    df_failed_tickers = pd.DataFrame(failed_tickers)
    display(df_failed_tickers)

    df_failed_tickers.to_csv(
        f"{OUT_DIR}/failed_market_tickers.csv",
        index=False
    )


# 7. Zip and download everything
zip_name = "kalshi_again.zip"

with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as z:
    for filename in os.listdir(OUT_DIR):
        filepath = os.path.join(OUT_DIR, filename)
        z.write(filepath, arcname=filename)

files.download(zip_name)

[1/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-T24...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  No subtitle: 24% or more
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[2/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B7.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  No subtitle: 6-8.99%
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[3/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B22.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  No subtitle: 21-23.99%
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[4/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B19.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  No subtitle: 18-20.99%
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[5/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B16.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  No subtitle: 15-17.99%
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[6/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B13.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  No subtitle: 12-14.99%
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[7/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B10.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  No subtitle: 9-11.99%
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[8/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-T0...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  No subtitle: Less than 0%
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[9/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B4.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  No subtitle: 3-5.99%
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111
[10/10] Processing KXELECTIONMOVZOHRAN-25-ZMAM-B1.5...
  Title: Margin of victory for Zohran Mamdani in the Mayoral Election?
  Event: KXELECTIONMOVZOHRAN-25
  Series: None
  No subtitle: 0-2.99%
  Start: 2025-08-13 14:00:00+00:00
  End: 2025-12-03 01:44:48.719034+00:00
  Daily candles: 111

,end_period_ts,open_interest,price.close,price.high,price.low,price.mean,price.open,price.previous,volume,yes_ask.close,...,no_sub_title,rules_primary,rules_secondary,yes_sub_title,market_status,market_result,market_open_time,market_end_time,period_interval,period_label
0,1755144000,5154.00,0.4100,0.7400,0.1900,0.3164,0.1900,None,5433.00,0.4500,...,24% or more,If the popular vote margin of victory is 24% o...,The margin of victory is calculated by taking ...,24% or more,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
1,1755230400,6394.00,0.4000,0.7000,0.4000,0.4676,0.4100,0.4100,1858.00,0.4800,...,24% or more,If the popular vote margin of victory is 24% o...,The margin of victory is calculated by taking ...,24% or more,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
2,1755316800,6429.00,0.3900,0.4000,0.3900,0.3963,0.4000,0.4000,90.00,0.4700,...,24% or more,If the popular vote margin of victory is 24% o...,The margin of victory is calculated by taking ...,24% or more,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
3,1755403200,6429.00,0.4800,0.4800,0.4700,0.4750,0.4700,0.3900,4.00,0.4700,...,24% or more,If the popular vote margin of victory is 24% o...,The margin of victory is calculated by taking ...,24% or more,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
4,1755489600,6840.00,0.4100,0.4200,0.4100,0.4100,0.4200,0.4800,468.00,0.4600,...,24% or more,If the popular vote margin of victory is 24% o...,The margin of victory is calculated by taking ...,24% or more,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1105,1764306000,921513.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,348.00,0.0100,...,0-2.99%,If the popular vote margin of victory is 0-2.9...,The margin of victory is calculated by taking ...,0-2.99%,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
1106,1764392400,921514.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,1.00,0.0100,...,0-2.99%,If the popular vote margin of victory is 0-2.9...,The margin of victory is calculated by taking ...,0-2.99%,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
1107,1764478800,921514.00,None,None,None,None,None,0.0100,0.00,0.0100,...,0-2.99%,If the popular vote margin of victory is 0-2.9...,The margin of victory is calculated by taking ...,0-2.99%,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
1108,1764565200,921514.00,None,None,None,None,None,0.0100,0.00,0.0100,...,0-2.99%,If the popular vote margin of victory is 0-2.9...,The margin of victory is calculated by taking ...,0-2.99%,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily
1109,1764651600,921614.00,0.0100,0.0100,0.0100,0.0100,0.0100,0.0100,100.00,0.0100,...,0-2.99%,If the popular vote margin of victory is 0-2.9...,The margin of victory is calculated by taking ...,0-2.99%,finalized,no,2025-08-13 14:00:00+00:00,2025-12-03 01:44:48.719034+00:00,1440,daily

Total daily candlestick rows: 1110
Columns: ['end_period_ts', 'open_interest', 'price.close', 'price.high', 'price.low', 'price.mean', 'price.open', 'price.previous', 'volume', 'yes_ask.close', 'yes_ask.high', 'yes_ask.low', 'yes_ask.open', 'yes_bid.close', 'yes_bid.high', 'yes_bid.low', 'yes_bid.open', 'market_ticker', 'market_title', 'event_ticker', 'series_ticker', 'no_sub_title', 'rules_primary', 'rules_secondary', 'yes_sub_title', 'market_status', 'market_result', 'market_open_time', 'market_end_time', 'period_interval', 'period_label']

,market_ticker,market_title,event_ticker,series_ticker,no_sub_title,rules_primary,rules_secondary,yes_sub_title,status,result,open_time,close_time,expiration_time,settlement_ts,volume_fp,volume_24h_fp
0,KXELECTIONMOVZOHRAN-25-ZMAM-T24,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,24% or more,If the popular vote margin of victory is 24% o...,The margin of victory is calculated by taking ...,24% or more,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,2715311.00,0.00
1,KXELECTIONMOVZOHRAN-25-ZMAM-B7.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,6-8.99%,If the popular vote margin of victory is 6-8.9...,The margin of victory is calculated by taking ...,6-8.99%,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,3398478.00,0.00
2,KXELECTIONMOVZOHRAN-25-ZMAM-B22.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,21-23.99%,If the popular vote margin of victory is 21-23...,The margin of victory is calculated by taking ...,21-23.99%,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,922621.00,0.00
3,KXELECTIONMOVZOHRAN-25-ZMAM-B19.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,18-20.99%,If the popular vote margin of victory is 18-20...,The margin of victory is calculated by taking ...,18-20.99%,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,819153.00,0.00
4,KXELECTIONMOVZOHRAN-25-ZMAM-B16.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,15-17.99%,If the popular vote margin of victory is 15-17...,The margin of victory is calculated by taking ...,15-17.99%,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,923736.00,0.00
5,KXELECTIONMOVZOHRAN-25-ZMAM-B13.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,12-14.99%,If the popular vote margin of victory is 12-14...,The margin of victory is calculated by taking ...,12-14.99%,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1454986.00,0.00
6,KXELECTIONMOVZOHRAN-25-ZMAM-B10.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,9-11.99%,If the popular vote margin of victory is 9-11....,The margin of victory is calculated by taking ...,9-11.99%,finalized,yes,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,2641908.00,0.00
7,KXELECTIONMOVZOHRAN-25-ZMAM-T0,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,Less than 0%,If the popular vote margin of victory is 0% or...,The margin of victory is calculated by taking ...,Less than 0%,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1488079.00,0.00
8,KXELECTIONMOVZOHRAN-25-ZMAM-B4.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,3-5.99%,If the popular vote margin of victory is 3-5.9...,The margin of victory is calculated by taking ...,3-5.99%,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1689089.00,0.00
9,KXELECTIONMOVZOHRAN-25-ZMAM-B1.5,Margin of victory for Zohran Mamdani in the Ma...,KXELECTIONMOVZOHRAN-25,None,0-2.99%,If the popular vote margin of victory is 0-2.9...,The margin of victory is calculated by taking ...,0-2.99%,finalized,no,2025-08-13T14:00:00Z,2025-12-03T01:44:48.719034Z,2026-11-04T15:00:00Z,2025-12-03T02:14:52.646486Z,1256254.00,0.00