# Google Trends event-word pull pipeline

This notebook uses manually curated `TOP_QUERIES_RAW` and `RISING_QUERIES_RAW`.

Design:
- Keep the query text exactly as written for Google Trends.
- Deduplicate exact duplicate query strings across top/rising so each query is pulled once.
- Preserve source metadata: `top`, `rising`, or `top;rising`.
- Use only folder-name sanitization for Windows-safe query folders.
- Save each query into its own folder with `chunks/`, `diagnostics/`, `stitched/`, and `metadata.json`.

In [ ]:
from pathlib import Path
import json
import random
import re
import time
from datetime import datetime, timedelta
from collections import defaultdict

import pandas as pd

try:
    from pytrends.request import TrendReq
except ImportError as e:
    raise ImportError(
        "pytrends is required. Install it with: pip install pytrends"
    ) from e

In [6]:
# ── Paths ─────────────────────────────────────────────────────────────────────
PROJECT_DIR = Path(r"C:/Python/CSUREMM")
EVENT_WORD_DIR = PROJECT_DIR / "event_words"
BASE_DIR = PROJECT_DIR / "data_events"

EVENT_WORD_DIR.mkdir(parents=True, exist_ok=True)
BASE_DIR.mkdir(parents=True, exist_ok=True)

# ── Google Trends parameters ──────────────────────────────────────────────────
GEO = "US"
START_DATE = "2022-01-01"
END_DATE = "2026-05-31"

# 270-day chunks work well for daily Google Trends pulls.
CHUNK_DAYS = 270

# Overlap helps stitching adjacent chunks.
OVERLAP_DAYS = 30

# Sleep settings: conservative randomized pacing.
STANDARD_SLEEP_RANGE = (12.0, 24.0)
MICRO_NAP_EVERY = 5
MICRO_NAP_RANGE = (45.0, 90.0)

MAX_RETRIES = 5
RETRY_SLEEP_RANGE = (60.0, 300.0)

In [7]:
# ── Hardcoded query lists ─────────────────────────────────────────────────────
# These are manually curated inputs. The notebook does not clean or normalize them.

TOP_QUERIES_RAW = r"""
"""

RISING_QUERIES_RAW = r"""when we were young festival
aaron judge
canelo vs bivol
ime udoka
kohls
obi wan kenobi
southwest airlines
unblocked games
2024 united states presidential election
australian open 2022
facebook login
iran
kansas city chiefs
"""

In [8]:
# ── Minimal parsing, deduplication, and folder-name sanitization ──────────────

def parse_query_block(raw: str) -> list[str]:
    """Split a newline-delimited query block into non-empty strings."""
    return [
        line.strip()
        for line in raw.splitlines()
        if line.strip()
    ]


def folder_name(query: str) -> str:
    """
    Create a Windows-safe folder name.

    Important:
    - This does NOT modify the query sent to Google Trends.
    - It only creates a filesystem-safe folder slug.
    """
    name = query.strip().lower()
    name = re.sub(r'[<>:"/\\|?*]+', "", name)
    name = re.sub(r"\s+", "_", name)
    name = re.sub(r"_+", "_", name)
    name = name.strip("._ ")

    if not name:
        name = "query"

    # Windows path-length protection.
    return name[:120]


def make_unique_folder_slug(query: str, used: set[str]) -> str:
    """Create a unique folder slug, adding suffixes only if needed."""
    base = folder_name(query)
    slug = base
    i = 2

    while slug in used:
        slug = f"{base}_{i}"
        i += 1

    used.add(slug)
    return slug


top_queries = parse_query_block(TOP_QUERIES_RAW)
rising_queries = parse_query_block(RISING_QUERIES_RAW)

# Track exact duplicates within each list.
top_duplicate_rows = (
    pd.Series(top_queries)
    .value_counts()
    .loc[lambda s: s.gt(1)]
    .rename_axis("query")
    .reset_index(name="count")
)

rising_duplicate_rows = (
    pd.Series(rising_queries)
    .value_counts()
    .loc[lambda s: s.gt(1)]
    .rename_axis("query")
    .reset_index(name="count")
)

# Build exact-query source metadata.
sources_by_query = defaultdict(set)

for q in top_queries:
    sources_by_query[q].add("top")

for q in rising_queries:
    sources_by_query[q].add("rising")

# Preserve order: all top queries first, then rising-only queries.
ordered_queries = []
seen = set()

for q in top_queries + rising_queries:
    if q not in seen:
        seen.add(q)
        ordered_queries.append(q)

used_slugs = set()
metadata_rows = []

for q in ordered_queries:
    sources = sorted(sources_by_query[q])
    metadata_rows.append({
        "query": q,
        "folder": make_unique_folder_slug(q, used_slugs),
        "source": ";".join(sources),
        "in_top": "top" in sources,
        "in_rising": "rising" in sources,
    })

query_metadata = pd.DataFrame(metadata_rows)

cross_source_duplicates = (
    query_metadata
    .loc[query_metadata["in_top"] & query_metadata["in_rising"], ["query", "source"]]
    .reset_index(drop=True)
)

query_metadata.to_csv(BASE_DIR / "query_metadata.csv", index=False)
top_duplicate_rows.to_csv(BASE_DIR / "duplicates_within_top.csv", index=False)
rising_duplicate_rows.to_csv(BASE_DIR / "duplicates_within_rising.csv", index=False)
cross_source_duplicates.to_csv(BASE_DIR / "duplicates_across_top_rising.csv", index=False)

print(f"Raw top queries:      {len(top_queries)}")
print(f"Raw rising queries:   {len(rising_queries)}")
print(f"Unique queries pulled:{len(query_metadata)}")
print(f"Within-top duplicates removed:    {len(top_duplicate_rows)}")
print(f"Within-rising duplicates removed: {len(rising_duplicate_rows)}")
print(f"Cross-source duplicates pulled once: {len(cross_source_duplicates)}")

display(query_metadata.head())
display(cross_source_duplicates.head(20))

Raw top queries:      0
Raw rising queries:   13
Unique queries pulled:13
Within-top duplicates removed:    0
Within-rising duplicates removed: 0
Cross-source duplicates pulled once: 0

,query,folder,source,in_top,in_rising
0,when we were young festival,when_we_were_young_festival,rising,False,True
1,aaron judge,aaron_judge,rising,False,True
2,canelo vs bivol,canelo_vs_bivol,rising,False,True
3,ime udoka,ime_udoka,rising,False,True
4,kohls,kohls,rising,False,True

Empty DataFrame
Columns: [query, source]
Index: []

## Deduplication note

The notebook removes only **exact duplicate query strings after stripping outer whitespace**. It does not merge near-duplicates such as `chat gpt` vs `chatgpt`, `s&p 500` vs `sp500`, or curly-apostrophe variants vs straight-apostrophe variants.

Cross-source duplicates are not discarded conceptually: they are pulled once and marked as `source = "rising;top"` in `query_metadata.csv`.

In [9]:
# ── Chunk construction ───────────────────────────────────────────────────────

def make_time_windows(
    start_date: str,
    end_date: str,
    chunk_days: int = 270,
    overlap_days: int = 30,
) -> list[tuple[str, str]]:
    """
    Create overlapping date windows formatted for pytrends timeframe strings.

    Google Trends timeframe end date is inclusive in the string representation.
    """
    start = pd.to_datetime(start_date).date()
    end = pd.to_datetime(end_date).date()

    windows = []
    cur = start

    while cur <= end:
        chunk_end = min(cur + timedelta(days=chunk_days - 1), end)
        windows.append((cur.isoformat(), chunk_end.isoformat()))

        if chunk_end >= end:
            break

        cur = chunk_end - timedelta(days=overlap_days - 1)

    return windows


TIME_WINDOWS = make_time_windows(
    START_DATE,
    END_DATE,
    chunk_days=CHUNK_DAYS,
    overlap_days=OVERLAP_DAYS,
)

TIME_WINDOWS

[('2022-01-01', '2022-09-27'),
 ('2022-08-29', '2023-05-25'),
 ('2023-04-26', '2024-01-20'),
 ('2023-12-22', '2024-09-16'),
 ('2024-08-18', '2025-05-14'),
 ('2025-04-15', '2026-01-09'),
 ('2025-12-11', '2026-05-31')]

In [10]:
# ── Pull helpers ──────────────────────────────────────────────────────────────

def standard_pause(index: int) -> None:
    """Conservative randomized pacing between successful requests."""
    if index > 0 and index % MICRO_NAP_EVERY == 0:
        sleep_time = random.uniform(*MICRO_NAP_RANGE)
        print(f"Micro-nap after {index} requests: {sleep_time:.1f}s")
    else:
        sleep_time = random.uniform(*STANDARD_SLEEP_RANGE)
        print(f"Standard pause: {sleep_time:.1f}s")

    time.sleep(sleep_time)


def build_pytrends() -> TrendReq:
    """
    Create a fresh pytrends object.

    Recreating this periodically is more robust than keeping one long-lived object.
    """
    return TrendReq(
        hl="en-US",
        tz=360,
        timeout=(10, 25),
        retries=0,
        backoff_factor=0,
    )


def pull_one_chunk(
    pytrends: TrendReq,
    query: str,
    start: str,
    end: str,
    geo: str = "US",
    max_retries: int = MAX_RETRIES,
) -> pd.DataFrame:
    """Pull one query over one time window with conservative retry behavior."""
    timeframe = f"{start} {end}"

    for attempt in range(max_retries):
        try:
            pytrends.build_payload(
                kw_list=[query],
                timeframe=timeframe,
                geo=geo,
            )

            df = pytrends.interest_over_time()

            if df is None or df.empty:
                return pd.DataFrame(columns=["Time", query])

            df = df.drop(columns=["isPartial"], errors="ignore")
            df = df.reset_index().rename(columns={"date": "Time"})

            return df

        except Exception as e:
            msg = str(e).lower()
            is_rate_limited = (
                "429" in msg
                or "too many requests" in msg
                or "rate" in msg
                or "quota" in msg
            )

            if attempt == max_retries - 1:
                raise

            if is_rate_limited:
                sleep_time = random.uniform(*RETRY_SLEEP_RANGE)
                print(
                    f"Rate-limit-like error for {query!r}, "
                    f"{start} to {end}, attempt {attempt + 1}/{max_retries}. "
                    f"Sleeping {sleep_time:.1f}s."
                )
                time.sleep(sleep_time)
                pytrends = build_pytrends()
            else:
                sleep_time = random.uniform(20.0, 60.0)
                print(
                    f"Request error for {query!r}, "
                    f"{start} to {end}, attempt {attempt + 1}/{max_retries}: {e}. "
                    f"Sleeping {sleep_time:.1f}s."
                )
                time.sleep(sleep_time)

    raise RuntimeError(f"Failed to pull {query!r} for {start} to {end}.")

In [11]:
# ── Stitching and diagnostics ────────────────────────────────────────────────

def read_chunk_file(path: Path, query: str) -> pd.DataFrame:
    df = pd.read_csv(path, parse_dates=["Time"])

    value_cols = [c for c in df.columns if c != "Time"]
    if not value_cols:
        return pd.DataFrame(columns=["Time", query])

    value_col = value_cols[0]

    return (
        df[["Time", value_col]]
        .rename(columns={value_col: query})
        .sort_values("Time")
        .drop_duplicates("Time")
    )


def stitch_chunks(chunk_files: list[Path], query: str) -> pd.DataFrame:
    """
    Simple overlap-aware stitching.

    The current implementation averages duplicate dates across overlapping chunks.
    This is conservative and transparent. If you later want ratio-rescaling,
    this function is the place to replace the stitching method.
    """
    if not chunk_files:
        return pd.DataFrame(columns=["Time", query])

    pieces = [
        read_chunk_file(path, query)
        for path in sorted(chunk_files)
    ]

    long = pd.concat(pieces, ignore_index=True)
    long[query] = pd.to_numeric(long[query], errors="coerce")

    stitched = (
        long
        .groupby("Time", as_index=False)[query]
        .mean()
        .sort_values("Time")
    )

    return stitched


def make_chunk_diagnostics(
    query: str,
    chunk_files: list[Path],
) -> pd.DataFrame:
    rows = []

    for path in sorted(chunk_files):
        try:
            df = read_chunk_file(path, query)
            rows.append({
                "file": path.name,
                "n_rows": len(df),
                "min_date": df["Time"].min() if not df.empty else pd.NaT,
                "max_date": df["Time"].max() if not df.empty else pd.NaT,
                "missing_values": df[query].isna().sum() if query in df else None,
            })
        except Exception as e:
            rows.append({
                "file": path.name,
                "n_rows": None,
                "min_date": pd.NaT,
                "max_date": pd.NaT,
                "missing_values": None,
                "error": str(e),
            })

    return pd.DataFrame(rows)


def make_stitching_diagnostics(stitched: pd.DataFrame, query: str) -> pd.DataFrame:
    if stitched.empty:
        return pd.DataFrame([{
            "query": query,
            "n_rows": 0,
            "min_date": pd.NaT,
            "max_date": pd.NaT,
            "expected_days": 0,
            "observed_days": 0,
            "missing_days": None,
        }])

    expected = pd.date_range(START_DATE, END_DATE, freq="D")
    observed = pd.DatetimeIndex(stitched["Time"])

    return pd.DataFrame([{
        "query": query,
        "n_rows": len(stitched),
        "min_date": stitched["Time"].min(),
        "max_date": stitched["Time"].max(),
        "expected_days": len(expected),
        "observed_days": observed.nunique(),
        "missing_days": len(expected.difference(observed)),
    }])

In [12]:
# ── Main query runner ────────────────────────────────────────────────────────

def write_query_metadata(row: pd.Series, query_dir: Path) -> None:
    meta = {
        "query": row["query"],
        "folder": row["folder"],
        "source": row["source"],
        "in_top": bool(row["in_top"]),
        "in_rising": bool(row["in_rising"]),
        "geo": GEO,
        "start_date": START_DATE,
        "end_date": END_DATE,
        "chunk_days": CHUNK_DAYS,
        "overlap_days": OVERLAP_DAYS,
        "created_at": datetime.now().isoformat(timespec="seconds"),
    }

    with open(query_dir / "metadata.json", "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)


def run_one_query(row: pd.Series, request_counter_start: int = 0) -> int:
    query = row["query"]
    folder = row["folder"]

    query_dir = BASE_DIR / folder
    chunks_dir = query_dir / "chunks"
    diagnostics_dir = query_dir / "diagnostics"
    stitched_dir = query_dir / "stitched"

    chunks_dir.mkdir(parents=True, exist_ok=True)
    diagnostics_dir.mkdir(parents=True, exist_ok=True)
    stitched_dir.mkdir(parents=True, exist_ok=True)

    write_query_metadata(row, query_dir)

    pytrends = build_pytrends()
    request_counter = request_counter_start

    chunk_files = []

    for start, end in TIME_WINDOWS:
        chunk_path = chunks_dir / f"gt_{folder}_{start}_{end}.csv"
        chunk_files.append(chunk_path)

        if chunk_path.exists():
            print(f"Exists, skipping: {chunk_path.name}")
            continue

        print(f"Pulling {query!r}: {start} to {end}")

        df = pull_one_chunk(
            pytrends=pytrends,
            query=query,
            start=start,
            end=end,
            geo=GEO,
        )

        df.to_csv(chunk_path, index=False)

        request_counter += 1
        standard_pause(request_counter)

    existing_chunk_files = [
        path for path in chunk_files
        if path.exists()
    ]

    chunk_diag = make_chunk_diagnostics(query, existing_chunk_files)
    chunk_diag.to_csv(
        diagnostics_dir / "chunk_diagnostics.csv",
        index=False,
    )

    stitched = stitch_chunks(existing_chunk_files, query)
    stitched_path = stitched_dir / f"gt_stitched_{folder}_{START_DATE}_{END_DATE}.csv"
    stitched.to_csv(stitched_path, index=False)

    stitch_diag = make_stitching_diagnostics(stitched, query)
    stitch_diag.to_csv(
        diagnostics_dir / "stitching_diagnostics.csv",
        index=False,
    )

    return request_counter


def run_all_queries(start_at: int = 0, stop_after: int | None = None) -> None:
    """
    Pull all queries starting at metadata row index `start_at`.

    Use stop_after for testing, e.g. stop_after=2.
    """
    run_log_path = BASE_DIR / "run_log.csv"

    request_counter = 0
    rows = query_metadata.iloc[start_at:]

    if stop_after is not None:
        rows = rows.iloc[:stop_after]

    log_rows = []

    for idx, row in rows.iterrows():
        query = row["query"]
        folder = row["folder"]

        print("=" * 80)
        print(f"[{idx}] {query!r} -> {folder}")

        try:
            request_counter = run_one_query(
                row=row,
                request_counter_start=request_counter,
            )

            status = "done"
            error = ""

        except Exception as e:
            status = "failed"
            error = str(e)
            print(f"FAILED: {query!r}: {error}")

        log_rows.append({
            "index": idx,
            "query": query,
            "folder": folder,
            "source": row["source"],
            "status": status,
            "error": error,
            "timestamp": datetime.now().isoformat(timespec="seconds"),
        })

        pd.DataFrame(log_rows).to_csv(run_log_path, index=False)

    print("Finished run.")

In [13]:
# ── Test run ─────────────────────────────────────────────────────────────────
# Start with 1 or 2 queries to verify file structure and Google Trends access.
# Then set stop_after=None to run the full list.

run_all_queries(
    start_at=0,
    stop_after=None,
)

================================================================================
[0] 'when we were young festival' -> when_we_were_young_festival
Pulling 'when we were young festival': 2022-01-01 to 2022-09-27
Standard pause: 15.7s
Pulling 'when we were young festival': 2022-08-29 to 2023-05-25

KeyboardInterrupt:

In [ ]:
# ── Full run ─────────────────────────────────────────────────────────────────
# Uncomment after the test run works.

# run_all_queries(
#     start_at=0,
#     stop_after=None,
# )

## Expected file structure

```text
C:/Python/CSUREMM/data_events/
    query_metadata.csv
    duplicates_within_top.csv
    duplicates_within_rising.csv
    duplicates_across_top_rising.csv
    run_log.csv

    weather/
        metadata.json
        chunks/
            gt_weather_2022-01-01_2022-09-27.csv
            ...
        diagnostics/
            chunk_diagnostics.csv
            stitching_diagnostics.csv
        stitched/
            gt_stitched_weather_2022-01-01_2026-05-31.csv
```

Each query has exactly one canonical folder, even if it appears in both top and rising lists.

## Section: fixing stitch: gt_fix

In [ ]:
from pathlib import Path
import numpy as np
import pandas as pd


DATA_DIR = Path(r"C:/Python/CSUREMM/data_events")
START_DATE = "2022-01-01"
END_DATE = "2026-05-31"


def read_chunk_file(path: Path, query: str) -> pd.DataFrame:
    df = pd.read_csv(
        path,
        parse_dates=["Time"]
    )

    value_cols = [
        c for c in df.columns
        if c != "Time"
    ]

    if len(value_cols) != 1:
        raise ValueError(
            f"{path.name} has {len(value_cols)} value columns: {value_cols}"
        )

    value_col = value_cols[0]

    df = (
        df[["Time", value_col]]
        .rename(columns={value_col: query})
        .sort_values("Time")
        .drop_duplicates("Time", keep="first")
        .reset_index(drop=True)
    )

    df[query] = pd.to_numeric(
        df[query],
        errors="coerce"
    )

    return df


def estimate_overlap_scale(
    base: pd.DataFrame,
    new: pd.DataFrame,
    query: str,
    min_overlap_days: int = 10,
) -> dict:

    overlap = pd.merge(
        base[["Time", query]].rename(columns={query: "base_value"}),
        new[["Time", query]].rename(columns={query: "new_value"}),
        on="Time",
        how="inner"
    ).dropna(
        subset=["base_value", "new_value"]
    )

    valid = overlap[
        (overlap["base_value"] > 0) &
        (overlap["new_value"] > 0)
    ].copy()

    # exclude spike days from the RATIO estimate only, using the base series'
    # own distribution as the spike threshold
    thresh = valid["base_value"].quantile(spike_pctile / 100)
    calm = valid[valid["base_value"] <= thresh]
    if len(calm) >= min_overlap_days:
        valid = calm  # prefer spike-excluded overlap when enough calm days exist

    if len(overlap) >= 2 and overlap["base_value"].std() > 0 and overlap["new_value"].std() > 0:
        corr = overlap["base_value"].corr(overlap["new_value"])
    else:
        corr = np.nan

    if len(valid) >= min_overlap_days:
        ratio_new_over_base = (
            valid["new_value"] /
            valid["base_value"]
        )

        median_ratio = ratio_new_over_base.median()

        scale_new_to_base = (
            1 / median_ratio
            if median_ratio != 0 and pd.notna(median_ratio)
            else 1.0
        )

        ratio_cv = (
            ratio_new_over_base.std() / ratio_new_over_base.mean()
            if ratio_new_over_base.mean() != 0
            else np.nan
        )

        method = "overlap_ratio"

    else:
        median_ratio = np.nan
        ratio_cv = np.nan
        scale_new_to_base = 1.0
        method = "no_rescale_insufficient_overlap"

    return {
        "overlap_days": len(overlap),
        "valid_ratio_days": len(valid),
        "overlap_corr": corr,
        "median_ratio_new_over_base": median_ratio,
        "scale_new_to_base": scale_new_to_base,
        "ratio_cv": ratio_cv,
        "method": method,
    }


def stitch_chunks_overlap_ratio(
    chunk_files: list[Path],
    query: str,
    min_overlap_days: int = 10,
) -> tuple[pd.DataFrame, pd.DataFrame]:

    chunk_files = sorted(chunk_files)

    if not chunk_files:
        return (
            pd.DataFrame(columns=["Time", query]),
            pd.DataFrame()
        )

    stitched = read_chunk_file(
        chunk_files[0],
        query
    )

    diag_rows = []

    diag_rows.append({
        "step": 0,
        "file": chunk_files[0].name,
        "overlap_days": np.nan,
        "valid_ratio_days": np.nan,
        "overlap_corr": np.nan,
        "median_ratio_new_over_base": np.nan,
        "scale_new_to_base": 1.0,
        "ratio_cv": np.nan,
        "method": "base_chunk",
    })

    for i, path in enumerate(chunk_files[1:], start=1):

        new = read_chunk_file(
            path,
            query
        )

        scale_info = estimate_overlap_scale(
            base=stitched,
            new=new,
            query=query,
            min_overlap_days=min_overlap_days,
        )

        new[query] = (
            new[query]
            * scale_info["scale_new_to_base"]
        )

        combined = pd.concat(
            [stitched, new],
            ignore_index=True
        )

        stitched = (
            combined
            .groupby("Time", as_index=False)[query]
            .mean()
            .sort_values("Time")
            .reset_index(drop=True)
        )

        diag_rows.append({
            "step": i,
            "file": path.name,
            **scale_info,
        })

    stitch_scale_diag = pd.DataFrame(diag_rows)

    return stitched, stitch_scale_diag


def make_stitching_diagnostics(
    stitched: pd.DataFrame,
    query: str
) -> pd.DataFrame:

    s = stitched[query]

    return pd.DataFrame([{
        "query": query,
        "n_rows": len(stitched),
        "min_date": stitched["Time"].min(),
        "max_date": stitched["Time"].max(),
        "missing_values": s.isna().sum(),
        "min_value": s.min(),
        "max_value": s.max(),
        "mean_value": s.mean(),
        "std_value": s.std(),
        "n_zero_values": (s == 0).sum(),
    }])


def fix_one_query_folder(
    query_folder: Path,
    request_counter: int = 0,
) -> int:

    folder = query_folder.name
    query = folder

    chunks_dir = query_folder / "chunks"
    diagnostics_dir = query_folder / "diagnostics"
    stitched_dir = query_folder / "stitched"

    diagnostics_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    stitched_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    chunk_files = sorted(
        chunks_dir.glob("gt_*.csv")
    )

    stitched, scale_diag = stitch_chunks_overlap_ratio(
        chunk_files=chunk_files,
        query=query,
        min_overlap_days=10,
    )

    stitched_path = (
        stitched_dir /
        f"gt_fixed_{folder}_{START_DATE}_{END_DATE}.csv"
    )

    stitched.to_csv(
        stitched_path,
        index=False
    )

    stitch_diag = make_stitching_diagnostics(
        stitched,
        query
    )

    stitch_diag.to_csv(
        diagnostics_dir / "stitching_fixed.csv",
        index=False
    )

    scale_diag.to_csv(
        diagnostics_dir / "overlap_scale_fixed.csv",
        index=False
    )

    print(f"saved: {stitched_path}")

    return request_counter


request_counter = 0

for query_folder in sorted(DATA_DIR.iterdir()):

    if not query_folder.is_dir():
        continue

    if not (query_folder / "chunks").exists():
        continue

    request_counter = fix_one_query_folder(
        query_folder=query_folder,
        request_counter=request_counter,
    )

saved: C:\Python\CSUREMM\data_events\2016_election_results\stitched\gt_fixed_2016_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2020_election_map\stitched\gt_fixed_2020_election_map_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2020_electoral_map\stitched\gt_fixed_2020_electoral_map_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2022_election\stitched\gt_fixed_2022_election_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_election\stitched\gt_fixed_2024_election_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_united_states_elections\stitched\gt_fixed_2024_united_states_elections_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_united_states_presidential_election\stitched\gt_fixed_2024_united_states_presidential_election_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_united_states_presidential_election_in_georgia\stitched\gt_fixed_2024_united_states_presidential_election_in_georgia_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_united_states_presidential_election_results\stitched\gt_fixed_2024_united_states_presidential_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2048\stitched\gt_fixed_2048_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\49ers\stitched\gt_fixed_49ers_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\49ers_vs_broncos\stitched\gt_fixed_49ers_vs_broncos_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\49ers_vs_packers\stitched\gt_fixed_49ers_vs_packers_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\538\stitched\gt_fixed_538_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\_\stitched\gt_fixed___2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\aaron_carter_cause_of_death\stitched\gt_fixed_aaron_carter_cause_of_death_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\academy\stitched\gt_fixed_academy_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\academy_awards_2023\stitched\gt_fixed_academy_awards_2023_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ace_hardware\stitched\gt_fixed_ace_hardware_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adam_frisch\stitched\gt_fixed_adam_frisch_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adam_levine\stitched\gt_fixed_adam_levine_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adam_levine_messages\stitched\gt_fixed_adam_levine_messages_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adam_sandler\stitched\gt_fixed_adam_sandler_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adele\stitched\gt_fixed_adele_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adidas\stitched\gt_fixed_adidas_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adin_ross\stitched\gt_fixed_adin_ross_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adrian_payne\stitched\gt_fixed_adrian_payne_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ai\stitched\gt_fixed_ai_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\alabama_football\stitched\gt_fixed_alabama_football_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\alan_jackson\stitched\gt_fixed_alan_jackson_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\alba_baptista\stitched\gt_fixed_alba_baptista_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\albert_pujols\stitched\gt_fixed_albert_pujols_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\als\stitched\gt_fixed_als_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amazon.com\stitched\gt_fixed_amazon.com_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amazon_prime_day\stitched\gt_fixed_amazon_prime_day_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amazon_prime_video\stitched\gt_fixed_amazon_prime_video_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amber_rose\stitched\gt_fixed_amber_rose_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\american_express\stitched\gt_fixed_american_express_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ame╠ürica_cruz_azul\stitched\gt_fixed_ame╠ürica_cruz_azul_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\américa_cruz_azul\stitched\gt_fixed_américa_cruz_azul_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\andor\stitched\gt_fixed_andor_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\andrew_wiggins\stitched\gt_fixed_andrew_wiggins_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\andy_fletcher\stitched\gt_fixed_andy_fletcher_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\angela_bassett\stitched\gt_fixed_angela_bassett_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\aol_mail\stitched\gt_fixed_aol_mail_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ap_classroom\stitched\gt_fixed_ap_classroom_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ap_election_results\stitched\gt_fixed_ap_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\apple\stitched\gt_fixed_apple_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\archive_81\stitched\gt_fixed_archive_81_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\argentina_vs_colombia\stitched\gt_fixed_argentina_vs_colombia_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ariana_debose\stitched\gt_fixed_ariana_debose_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arizona_basketball\stitched\gt_fixed_arizona_basketball_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arizona_election_results_2022\stitched\gt_fixed_arizona_election_results_2022_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arnold_schwarzenegger\stitched\gt_fixed_arnold_schwarzenegger_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arsenal\stitched\gt_fixed_arsenal_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arsenal_real_madrid\stitched\gt_fixed_arsenal_real_madrid_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ashley_johnson\stitched\gt_fixed_ashley_johnson_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\atlanta_falcons\stitched\gt_fixed_atlanta_falcons_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\atoll\stitched\gt_fixed_atoll_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\austin_butler\stitched\gt_fixed_austin_butler_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\austin_metcalf\stitched\gt_fixed_austin_metcalf_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\autozone\stitched\gt_fixed_autozone_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\avalanche\stitched\gt_fixed_avalanche_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\avatar\stitched\gt_fixed_avatar_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\avatar_2\stitched\gt_fixed_avatar_2_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\az_election_results\stitched\gt_fixed_az_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\az_governor_race\stitched\gt_fixed_az_governor_race_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bangladesh\stitched\gt_fixed_bangladesh_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\basketball_game_tonight\stitched\gt_fixed_basketball_game_tonight_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\batman\stitched\gt_fixed_batman_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bbc_news\stitched\gt_fixed_bbc_news_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bears\stitched\gt_fixed_bears_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bed_bath_and_beyond\stitched\gt_fixed_bed_bath_and_beyond_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bengals_vs_chiefs\stitched\gt_fixed_bengals_vs_chiefs_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bennie_thompson\stitched\gt_fixed_bennie_thompson_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\betty_white\stitched\gt_fixed_betty_white_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\big_lots\stitched\gt_fixed_big_lots_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\big_ten_tournament\stitched\gt_fixed_big_ten_tournament_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bill_hader\stitched\gt_fixed_bill_hader_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bills\stitched\gt_fixed_bills_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bills_vs_chiefs\stitched\gt_fixed_bills_vs_chiefs_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bills_vs_dolphins\stitched\gt_fixed_bills_vs_dolphins_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\billy_kametz\stitched\gt_fixed_billy_kametz_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bing\stitched\gt_fixed_bing_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\biped\stitched\gt_fixed_biped_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bivol\stitched\gt_fixed_bivol_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\black_panther_2\stitched\gt_fixed_black_panther_2_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\blue_ivy\stitched\gt_fixed_blue_ivy_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bob_menendez\stitched\gt_fixed_bob_menendez_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bob_newhart\stitched\gt_fixed_bob_newhart_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\boebert_election\stitched\gt_fixed_boebert_election_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\braves\stitched\gt_fixed_braves_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\breaking_news\stitched\gt_fixed_breaking_news_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\brendan_fraser\stitched\gt_fixed_brendan_fraser_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\broncos\stitched\gt_fixed_broncos_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bronny_james\stitched\gt_fixed_bronny_james_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\browns\stitched\gt_fixed_browns_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\browns_vs_steelers\stitched\gt_fixed_browns_vs_steelers_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bruins\stitched\gt_fixed_bruins_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bts\stitched\gt_fixed_bts_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bubble_tea\stitched\gt_fixed_bubble_tea_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\buffalo_bills\stitched\gt_fixed_buffalo_bills_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\burger_king\stitched\gt_fixed_burger_king_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\california_election_results\stitched\gt_fixed_california_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\california_electoral_votes\stitched\gt_fixed_california_electoral_votes_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\camille_vasquez\stitched\gt_fixed_camille_vasquez_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\candy_montgomery\stitched\gt_fixed_candy_montgomery_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\canelo\stitched\gt_fixed_canelo_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\capisce\stitched\gt_fixed_capisce_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\capisce_meaning\stitched\gt_fixed_capisce_meaning_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\capital_one_login\stitched\gt_fixed_capital_one_login_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cara_delevingne\stitched\gt_fixed_cara_delevingne_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\carhartt\stitched\gt_fixed_carhartt_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\carolina_panthers\stitched\gt_fixed_carolina_panthers_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\casey_white\stitched\gt_fixed_casey_white_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cbs_sports\stitched\gt_fixed_cbs_sports_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\celtics_game\stitched\gt_fixed_celtics_game_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\celtics_vs_heat\stitched\gt_fixed_celtics_vs_heat_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\celtics_vs_warriors\stitched\gt_fixed_celtics_vs_warriors_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\champions_league\stitched\gt_fixed_champions_league_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\charles_oliveira\stitched\gt_fixed_charles_oliveira_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\chase_bank\stitched\gt_fixed_chase_bank_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\chase_login\stitched\gt_fixed_chase_login_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\chase_oliver\stitched\gt_fixed_chase_oliver_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\chat\stitched\gt_fixed_chat_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cheap_flights\stitched\gt_fixed_cheap_flights_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cheesecake_factory\stitched\gt_fixed_cheesecake_factory_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\chiefs_vs_bengals\stitched\gt_fixed_chiefs_vs_bengals_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\chiefs_vs_bills\stitched\gt_fixed_chiefs_vs_bills_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\chilis\stitched\gt_fixed_chilis_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\china_spy_balloon\stitched\gt_fixed_china_spy_balloon_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\chinese_balloon\stitched\gt_fixed_chinese_balloon_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\chivas_vs_galaxy\stitched\gt_fixed_chivas_vs_galaxy_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\chris_paul\stitched\gt_fixed_chris_paul_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\christian_wood\stitched\gt_fixed_christian_wood_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cindy_williams\stitched\gt_fixed_cindy_williams_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\classroom\stitched\gt_fixed_classroom_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\clima_reynosa\stitched\gt_fixed_clima_reynosa_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cma_awards_2022\stitched\gt_fixed_cma_awards_2022_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\college_basketball_scores\stitched\gt_fixed_college_basketball_scores_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\college_football\stitched\gt_fixed_college_football_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\college_football_25\stitched\gt_fixed_college_football_25_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\college_football_scores\stitched\gt_fixed_college_football_scores_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\colombia_vs_argentina\stitched\gt_fixed_colombia_vs_argentina_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\colorado_avalanche\stitched\gt_fixed_colorado_avalanche_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\comet_tonight\stitched\gt_fixed_comet_tonight_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\coolio\stitched\gt_fixed_coolio_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cooper_flagg\stitched\gt_fixed_cooper_flagg_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cooper_kupp\stitched\gt_fixed_cooper_kupp_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cooper_noriega\stitched\gt_fixed_cooper_noriega_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\copa_america\stitched\gt_fixed_copa_america_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\copa_america_final\stitched\gt_fixed_copa_america_final_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cory_booker\stitched\gt_fixed_cory_booker_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\covid_vaccine_near_me\stitched\gt_fixed_covid_vaccine_near_me_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cowboys\stitched\gt_fixed_cowboys_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cowboys_vs_giants\stitched\gt_fixed_cowboys_vs_giants_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\credit_one\stitched\gt_fixed_credit_one_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\creighton_basketball\stitched\gt_fixed_creighton_basketball_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\crowdstrike\stitched\gt_fixed_crowdstrike_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\crowdstrike_outage\stitched\gt_fixed_crowdstrike_outage_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cubs\stitched\gt_fixed_cubs_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\current_election_results\stitched\gt_fixed_current_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\daily_mail\stitched\gt_fixed_daily_mail_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\dairy_queen\stitched\gt_fixed_dairy_queen_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\dall_e\stitched\gt_fixed_dall_e_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\dallas_cowboys\stitched\gt_fixed_dallas_cowboys_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\dallas_mavericks\stitched\gt_fixed_dallas_mavericks_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\daylight_savings\stitched\gt_fixed_daylight_savings_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\daylight_savings_2023\stitched\gt_fixed_daylight_savings_2023_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\decision_desk_hq\stitched\gt_fixed_decision_desk_hq_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\deep_water\stitched\gt_fixed_deep_water_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\delta\stitched\gt_fixed_delta_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\delta_airlines\stitched\gt_fixed_delta_airlines_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\dennis_rodman\stitched\gt_fixed_dennis_rodman_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\denver_broncos\stitched\gt_fixed_denver_broncos_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\descendants_4\stitched\gt_fixed_descendants_4_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\deshaun_watson\stitched\gt_fixed_deshaun_watson_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\detroit_lions\stitched\gt_fixed_detroit_lions_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\detroit_tigers\stitched\gt_fixed_detroit_tigers_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\dicks_sporting_good\stitched\gt_fixed_dicks_sporting_good_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\did_the_groundhog_see_his_shadow\stitched\gt_fixed_did_the_groundhog_see_his_shadow_2022-01-01_2026-05-31.csv

## Fixing stitch: gt_fix2 -- avoiding scaling with spike ratios in the overlapping window.

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd


DATA_DIR = Path(r"C:/Python/CSUREMM/data_events")
START_DATE = "2022-01-01"
END_DATE = "2026-05-31"


def read_chunk_file(path: Path, query: str) -> pd.DataFrame:
    df = pd.read_csv(
        path,
        parse_dates=["Time"]
    )

    value_cols = [
        c for c in df.columns
        if c != "Time"
    ]

    if len(value_cols) != 1:
        raise ValueError(
            f"{path.name} has {len(value_cols)} value columns: {value_cols}"
        )

    value_col = value_cols[0]

    df = (
        df[["Time", value_col]]
        .rename(columns={value_col: query})
        .sort_values("Time")
        .drop_duplicates("Time", keep="first")
        .reset_index(drop=True)
    )

    df[query] = pd.to_numeric(
        df[query],
        errors="coerce"
    )

    return df


def estimate_overlap_scale(
    base: pd.DataFrame,
    new: pd.DataFrame,
    query: str,
    min_overlap_days: int = 10,
    spike_pctile: float = 95.0,
    min_reasonable_scale: float = 0.2,
    max_reasonable_scale: float = 5.0,
    max_ratio_cv: float = 1.0,
    min_overlap_corr: float = 0.3,
) -> dict:

    overlap = pd.merge(
        base[["Time", query]].rename(columns={query: "base_value"}),
        new[["Time", query]].rename(columns={query: "new_value"}),
        on="Time",
        how="inner"
    ).dropna(
        subset=["base_value", "new_value"]
    )

    valid = overlap[
        (overlap["base_value"] > 0) &
        (overlap["new_value"] > 0)
    ].copy()

    valid_before_spike_filter = len(valid)

    if len(valid) >= min_overlap_days:
        base_thresh = valid["base_value"].quantile(spike_pctile / 100)
        new_thresh = valid["new_value"].quantile(spike_pctile / 100)

        calm = valid[
            (valid["base_value"] <= base_thresh) &
            (valid["new_value"] <= new_thresh)
        ]

        if len(calm) >= min_overlap_days:
            valid_for_ratio = calm
            spike_filter_used = True
        else:
            valid_for_ratio = valid
            spike_filter_used = False
    else:
        valid_for_ratio = valid
        spike_filter_used = False

    if (
        len(overlap) >= 2 and
        overlap["base_value"].std() > 0 and
        overlap["new_value"].std() > 0
    ):
        corr = overlap["base_value"].corr(overlap["new_value"])
    else:
        corr = np.nan

    if len(valid_for_ratio) >= min_overlap_days:
        ratio_new_over_base = (
            valid_for_ratio["new_value"] /
            valid_for_ratio["base_value"]
        )

        median_ratio = ratio_new_over_base.median()

        scale_new_to_base = (
            1 / median_ratio
            if median_ratio != 0 and pd.notna(median_ratio)
            else 1.0
        )

        ratio_mean = ratio_new_over_base.mean()
        ratio_cv = (
            ratio_new_over_base.std() / ratio_mean
            if ratio_mean != 0 and pd.notna(ratio_mean)
            else np.nan
        )

        method = (
            "overlap_ratio_spike_filtered"
            if spike_filter_used
            else "overlap_ratio"
        )

    else:
        median_ratio = np.nan
        ratio_cv = np.nan
        scale_new_to_base = 1.0
        method = "no_rescale_insufficient_overlap"

    method_notes = []

    scale_flagged = (
        pd.notna(scale_new_to_base) and
        (
            scale_new_to_base < min_reasonable_scale or
            scale_new_to_base > max_reasonable_scale
        )
    )

    ratio_cv_flagged = (
        pd.notna(ratio_cv) and
        ratio_cv > max_ratio_cv
    )

    corr_flagged = (
        pd.notna(corr) and
        corr < min_overlap_corr
    )

    insufficient_overlap_flagged = (
        len(valid_for_ratio) < min_overlap_days
    )

    if scale_flagged:
        method_notes.append("extreme_scale_factor")

    if ratio_cv_flagged:
        method_notes.append("unstable_overlap_ratio")

    if corr_flagged:
        method_notes.append("low_overlap_corr")

    if insufficient_overlap_flagged:
        method_notes.append("insufficient_valid_overlap")

    return {
        "overlap_days": len(overlap),
        "valid_ratio_days_before_spike_filter": valid_before_spike_filter,
        "valid_ratio_days": len(valid_for_ratio),
        "spike_pctile": spike_pctile,
        "spike_filter_used": spike_filter_used,
        "overlap_corr": corr,
        "median_ratio_new_over_base": median_ratio,
        "scale_new_to_base": scale_new_to_base,
        "scale_flagged": scale_flagged,
        "ratio_cv": ratio_cv,
        "ratio_cv_flagged": ratio_cv_flagged,
        "corr_flagged": corr_flagged,
        "insufficient_overlap_flagged": insufficient_overlap_flagged,
        "method": method,
        "method_notes": ";".join(method_notes),
    }


def stitch_chunks_overlap_ratio(
    chunk_files: list[Path],
    query: str,
    min_overlap_days: int = 10,
) -> tuple[pd.DataFrame, pd.DataFrame]:

    chunk_files = sorted(chunk_files)

    if not chunk_files:
        return (
            pd.DataFrame(columns=["Time", query]),
            pd.DataFrame()
        )

    stitched = read_chunk_file(
        chunk_files[0],
        query
    )

    diag_rows = []

    diag_rows.append({
        "step": 0,
        "file": chunk_files[0].name,
        "overlap_days": np.nan,
        "valid_ratio_days": np.nan,
        "overlap_corr": np.nan,
        "median_ratio_new_over_base": np.nan,
        "scale_new_to_base": 1.0,
        "ratio_cv": np.nan,
        "method": "base_chunk",
    })

    for i, path in enumerate(chunk_files[1:], start=1):

        new = read_chunk_file(
            path,
            query
        )

        scale_info = estimate_overlap_scale(
            base=stitched,
            new=new,
            query=query,
            min_overlap_days=min_overlap_days,
        )

        new[query] = (
            new[query]
            * scale_info["scale_new_to_base"]
        )

        combined = pd.concat(
            [stitched, new],
            ignore_index=True
        )

        stitched = (
            combined
            .groupby("Time", as_index=False)[query]
            .mean()
            .sort_values("Time")
            .reset_index(drop=True)
        )

        diag_rows.append({
            "step": i,
            "file": path.name,
            **scale_info,
        })

    stitch_scale_diag = pd.DataFrame(diag_rows)

    return stitched, stitch_scale_diag


def fix_one_query_folder(
    query_folder: Path,
    request_counter: int = 0,
) -> int:

    folder = query_folder.name
    query = folder

    chunks_dir = query_folder / "chunks"
    diagnostics_dir = query_folder / "diagnostics"
    stitched_dir = query_folder / "stitched"

    diagnostics_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    stitched_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    chunk_files = sorted(
        chunks_dir.glob("gt_*.csv")
    )

    stitched, scale_diag = stitch_chunks_overlap_ratio(
        chunk_files=chunk_files,
        query=query,
        min_overlap_days=10,
    )

    stitched_path = (
        stitched_dir /
        f"gt_fixed02_{folder}_{START_DATE}_{END_DATE}.csv"
    )

    stitched.to_csv(
        stitched_path,
        index=False
    )

    print(f"saved: {stitched_path}")

    return request_counter


# -----------------------------------------------------------------------------
# Stitch all queries and aggregate diagnostics
# -----------------------------------------------------------------------------

request_counter = 0
all_scale_diagnostics = []

for query_folder in sorted(DATA_DIR.iterdir()):

    if not query_folder.is_dir():
        continue

    if not (query_folder / "chunks").exists():
        continue

    folder = query_folder.name

    request_counter = fix_one_query_folder(
        query_folder=query_folder,
        request_counter=request_counter,
    )

    # Read the diagnostics returned during stitching
    _, scale_diag = stitch_chunks_overlap_ratio(
        chunk_files=sorted((query_folder / "chunks").glob("gt_*.csv")),
        query=folder,
        min_overlap_days=10,
    )

    scale_diag = scale_diag.copy()
    scale_diag.insert(0, "query", folder)

    all_scale_diagnostics.append(scale_diag)

# -----------------------------------------------------------------------------
# Save one master diagnostics table
# -----------------------------------------------------------------------------

if all_scale_diagnostics:

    master_scale_diag = (
        pd.concat(
            all_scale_diagnostics,
            ignore_index=True
        )
        .sort_values(
            ["query", "step"]
        )
        .reset_index(drop=True)
    )

    master_path = (
        DATA_DIR /
        "scale_diagnostics.csv"
    )

    master_scale_diag.to_csv(
        master_path,
        index=False
    )

    print(f"saved: {master_path}")

saved: C:\Python\CSUREMM\data_events\2016_election_results\stitched\gt_fixed02_2016_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2020_election_map\stitched\gt_fixed02_2020_election_map_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2020_election_results\stitched\gt_fixed02_2020_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2020_electoral_map\stitched\gt_fixed02_2020_electoral_map_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2022_election\stitched\gt_fixed02_2022_election_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2022_election_results\stitched\gt_fixed02_2022_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_election\stitched\gt_fixed02_2024_election_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_election_results\stitched\gt_fixed02_2024_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_presidential_election\stitched\gt_fixed02_2024_presidential_election_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_united_states_elections\stitched\gt_fixed02_2024_united_states_elections_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_united_states_elections_results\stitched\gt_fixed02_2024_united_states_elections_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_united_states_presidential_election\stitched\gt_fixed02_2024_united_states_presidential_election_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_united_states_presidential_election_in_georgia\stitched\gt_fixed02_2024_united_states_presidential_election_in_georgia_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_united_states_presidential_election_results\stitched\gt_fixed02_2024_united_states_presidential_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2024_us_election_results\stitched\gt_fixed02_2024_us_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\2048\stitched\gt_fixed02_2048_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\49ers\stitched\gt_fixed02_49ers_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\49ers_vs_broncos\stitched\gt_fixed02_49ers_vs_broncos_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\49ers_vs_packers\stitched\gt_fixed02_49ers_vs_packers_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\538\stitched\gt_fixed02_538_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\80_for_brady\stitched\gt_fixed02_80_for_brady_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\_\stitched\gt_fixed02___2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\aaron_carter_cause_of_death\stitched\gt_fixed02_aaron_carter_cause_of_death_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\aaron_judge\stitched\gt_fixed02_aaron_judge_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\aaron_rodgers\stitched\gt_fixed02_aaron_rodgers_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\abcya\stitched\gt_fixed02_abcya_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\academy\stitched\gt_fixed02_academy_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\academy_awards_2023\stitched\gt_fixed02_academy_awards_2023_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\accuweather\stitched\gt_fixed02_accuweather_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ace_hardware\stitched\gt_fixed02_ace_hardware_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adam_frisch\stitched\gt_fixed02_adam_frisch_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adam_levine\stitched\gt_fixed02_adam_levine_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adam_levine_messages\stitched\gt_fixed02_adam_levine_messages_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adam_sandler\stitched\gt_fixed02_adam_sandler_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adele\stitched\gt_fixed02_adele_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adidas\stitched\gt_fixed02_adidas_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adin_ross\stitched\gt_fixed02_adin_ross_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\adrian_payne\stitched\gt_fixed02_adrian_payne_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ai\stitched\gt_fixed02_ai_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\airbnb\stitched\gt_fixed02_airbnb_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\alabama_basketball\stitched\gt_fixed02_alabama_basketball_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\alabama_football\stitched\gt_fixed02_alabama_football_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\alan_jackson\stitched\gt_fixed02_alan_jackson_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\alba_baptista\stitched\gt_fixed02_alba_baptista_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\albert_pujols\stitched\gt_fixed02_albert_pujols_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\all_quiet_on_the_western_front\stitched\gt_fixed02_all_quiet_on_the_western_front_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\als\stitched\gt_fixed02_als_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amanda_aldridge\stitched\gt_fixed02_amanda_aldridge_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amazon\stitched\gt_fixed02_amazon_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amazon.com\stitched\gt_fixed02_amazon.com_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amazon_prime\stitched\gt_fixed02_amazon_prime_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amazon_prime_day\stitched\gt_fixed02_amazon_prime_day_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amazon_prime_video\stitched\gt_fixed02_amazon_prime_video_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amazon_stock\stitched\gt_fixed02_amazon_stock_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amber_heard\stitched\gt_fixed02_amber_heard_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amber_rose\stitched\gt_fixed02_amber_rose_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\amc\stitched\gt_fixed02_amc_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\american_airlines\stitched\gt_fixed02_american_airlines_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\american_express\stitched\gt_fixed02_american_express_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ame╠ürica_cruz_azul\stitched\gt_fixed02_ame╠ürica_cruz_azul_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\américa_cruz_azul\stitched\gt_fixed02_américa_cruz_azul_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\andor\stitched\gt_fixed02_andor_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\andrew_wiggins\stitched\gt_fixed02_andrew_wiggins_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\andy_fletcher\stitched\gt_fixed02_andy_fletcher_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\angela_bassett\stitched\gt_fixed02_angela_bassett_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\aol_mail\stitched\gt_fixed02_aol_mail_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ap_classroom\stitched\gt_fixed02_ap_classroom_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ap_election_results\stitched\gt_fixed02_ap_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\apple\stitched\gt_fixed02_apple_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\apple_stock\stitched\gt_fixed02_apple_stock_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\archive_81\stitched\gt_fixed02_archive_81_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\argentina_vs_colombia\stitched\gt_fixed02_argentina_vs_colombia_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ariana_debose\stitched\gt_fixed02_ariana_debose_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arizona_basketball\stitched\gt_fixed02_arizona_basketball_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arizona_election_results\stitched\gt_fixed02_arizona_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arizona_election_results_2022\stitched\gt_fixed02_arizona_election_results_2022_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arizona_governor_race\stitched\gt_fixed02_arizona_governor_race_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arnold_schwarzenegger\stitched\gt_fixed02_arnold_schwarzenegger_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arsenal\stitched\gt_fixed02_arsenal_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arsenal_real_madrid\stitched\gt_fixed02_arsenal_real_madrid_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\arsenal_vs_real_madrid\stitched\gt_fixed02_arsenal_vs_real_madrid_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\artistic_swimming_olympics\stitched\gt_fixed02_artistic_swimming_olympics_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\ashley_johnson\stitched\gt_fixed02_ashley_johnson_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\atlanta_braves\stitched\gt_fixed02_atlanta_braves_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\atlanta_falcons\stitched\gt_fixed02_atlanta_falcons_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\atoll\stitched\gt_fixed02_atoll_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\auburn_basketball\stitched\gt_fixed02_auburn_basketball_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\austin_butler\stitched\gt_fixed02_austin_butler_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\austin_metcalf\stitched\gt_fixed02_austin_metcalf_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\australian_open\stitched\gt_fixed02_australian_open_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\australian_open_2022\stitched\gt_fixed02_australian_open_2022_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\autozone\stitched\gt_fixed02_autozone_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\avalanche\stitched\gt_fixed02_avalanche_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\avatar\stitched\gt_fixed02_avatar_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\avatar_2\stitched\gt_fixed02_avatar_2_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\az_election_results\stitched\gt_fixed02_az_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\az_governor_race\stitched\gt_fixed02_az_governor_race_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\baker_mayfield\stitched\gt_fixed02_baker_mayfield_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bangladesh\stitched\gt_fixed02_bangladesh_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bank_of_america\stitched\gt_fixed02_bank_of_america_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\basketball_game_tonight\stitched\gt_fixed02_basketball_game_tonight_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bath_and_body_works\stitched\gt_fixed02_bath_and_body_works_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\batman\stitched\gt_fixed02_batman_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bbc_news\stitched\gt_fixed02_bbc_news_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bears\stitched\gt_fixed02_bears_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bed_bath_and_beyond\stitched\gt_fixed02_bed_bath_and_beyond_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bengals\stitched\gt_fixed02_bengals_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bengals_vs_chiefs\stitched\gt_fixed02_bengals_vs_chiefs_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bennie_thompson\stitched\gt_fixed02_bennie_thompson_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\best_buy\stitched\gt_fixed02_best_buy_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\betty_white\stitched\gt_fixed02_betty_white_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\biden\stitched\gt_fixed02_biden_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\big_lots\stitched\gt_fixed02_big_lots_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\big_ten_tournament\stitched\gt_fixed02_big_ten_tournament_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bill_hader\stitched\gt_fixed02_bill_hader_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bills\stitched\gt_fixed02_bills_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bills_vs_chiefs\stitched\gt_fixed02_bills_vs_chiefs_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bills_vs_dolphins\stitched\gt_fixed02_bills_vs_dolphins_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\billy_kametz\stitched\gt_fixed02_billy_kametz_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bing\stitched\gt_fixed02_bing_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\biped\stitched\gt_fixed02_biped_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bitcoin\stitched\gt_fixed02_bitcoin_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bitcoin_price\stitched\gt_fixed02_bitcoin_price_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bivol\stitched\gt_fixed02_bivol_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\black_panther\stitched\gt_fixed02_black_panther_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\black_panther_2\stitched\gt_fixed02_black_panther_2_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\blooket\stitched\gt_fixed02_blooket_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\blooket_join\stitched\gt_fixed02_blooket_join_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\blue_ivy\stitched\gt_fixed02_blue_ivy_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bob_menendez\stitched\gt_fixed02_bob_menendez_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bob_newhart\stitched\gt_fixed02_bob_newhart_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\boebert\stitched\gt_fixed02_boebert_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\boebert_election\stitched\gt_fixed02_boebert_election_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\boston_celtics\stitched\gt_fixed02_boston_celtics_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\braves\stitched\gt_fixed02_braves_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\breakfast_near_me\stitched\gt_fixed02_breakfast_near_me_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\breaking_news\stitched\gt_fixed02_breaking_news_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\brendan_fraser\stitched\gt_fixed02_brendan_fraser_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\britney_spears\stitched\gt_fixed02_britney_spears_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\broncos\stitched\gt_fixed02_broncos_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bronny_james\stitched\gt_fixed02_bronny_james_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\browns\stitched\gt_fixed02_browns_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\browns_vs_steelers\stitched\gt_fixed02_browns_vs_steelers_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bruins\stitched\gt_fixed02_bruins_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\btc\stitched\gt_fixed02_btc_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\btc_price\stitched\gt_fixed02_btc_price_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bts\stitched\gt_fixed02_bts_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\bubble_tea\stitched\gt_fixed02_bubble_tea_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\buffalo_bills\stitched\gt_fixed02_buffalo_bills_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\buffalo_wild_wings\stitched\gt_fixed02_buffalo_wild_wings_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\burger_king\stitched\gt_fixed02_burger_king_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\calculator\stitched\gt_fixed02_calculator_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\california_election_results\stitched\gt_fixed02_california_election_results_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\california_electoral_votes\stitched\gt_fixed02_california_electoral_votes_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\camille_vasquez\stitched\gt_fixed02_camille_vasquez_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\candy_hulu\stitched\gt_fixed02_candy_hulu_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\candy_montgomery\stitched\gt_fixed02_candy_montgomery_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\canelo\stitched\gt_fixed02_canelo_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\canelo_vs_bivol\stitched\gt_fixed02_canelo_vs_bivol_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\canva\stitched\gt_fixed02_canva_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\capisce\stitched\gt_fixed02_capisce_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\capisce_meaning\stitched\gt_fixed02_capisce_meaning_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\capital_one\stitched\gt_fixed02_capital_one_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\capital_one_login\stitched\gt_fixed02_capital_one_login_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cara_delevingne\stitched\gt_fixed02_cara_delevingne_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\carhartt\stitched\gt_fixed02_carhartt_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\carolina_panthers\stitched\gt_fixed02_carolina_panthers_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\carvana\stitched\gt_fixed02_carvana_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\casey_white\stitched\gt_fixed02_casey_white_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\cbs_sports\stitched\gt_fixed02_cbs_sports_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\celtics\stitched\gt_fixed02_celtics_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\celtics_game\stitched\gt_fixed02_celtics_game_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\celtics_vs_heat\stitched\gt_fixed02_celtics_vs_heat_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\celtics_vs_warriors\stitched\gt_fixed02_celtics_vs_warriors_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\champions_league\stitched\gt_fixed02_champions_league_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\charles_oliveira\stitched\gt_fixed02_charles_oliveira_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\charles_schwab\stitched\gt_fixed02_charles_schwab_2022-01-01_2026-05-31.csv
saved: C:\Python\CSUREMM\data_events\chase\stitched\gt_fixed02_chase_2022-01-01_2026-05-31.csv

In [6]:
# fixing temporary stitch for primitive words

from pathlib import Path
import numpy as np
import pandas as pd


DATA_DIR = Path(r"C:/Python/CSUREMM/dictionary V0.0/data_primitive")
START_DATE = "2022-01-01"
END_DATE = "2026-05-31"


def read_chunk_file(path: Path, query: str) -> pd.DataFrame:
    df = pd.read_csv(
        path,
        parse_dates=["Time"]
    )

    value_cols = [
        c for c in df.columns
        if c != "Time"
    ]

    if len(value_cols) != 1:
        raise ValueError(
            f"{path.name} has {len(value_cols)} value columns: {value_cols}"
        )

    value_col = value_cols[0]

    df = (
        df[["Time", value_col]]
        .rename(columns={value_col: query})
        .sort_values("Time")
        .drop_duplicates("Time", keep="first")
        .reset_index(drop=True)
    )

    df[query] = pd.to_numeric(
        df[query],
        errors="coerce"
    )

    return df


def estimate_overlap_scale(
    base: pd.DataFrame,
    new: pd.DataFrame,
    query: str,
    min_overlap_days: int = 10,
) -> dict:

    overlap = pd.merge(
        base[["Time", query]].rename(columns={query: "base_value"}),
        new[["Time", query]].rename(columns={query: "new_value"}),
        on="Time",
        how="inner"
    ).dropna(
        subset=["base_value", "new_value"]
    )

    valid = overlap[
        (overlap["base_value"] > 0) &
        (overlap["new_value"] > 0)
    ].copy()

    if len(overlap) >= 2 and overlap["base_value"].std() > 0 and overlap["new_value"].std() > 0:
        corr = overlap["base_value"].corr(overlap["new_value"])
    else:
        corr = np.nan

    if len(valid) >= min_overlap_days:
        ratio_new_over_base = (
            valid["new_value"] /
            valid["base_value"]
        )

        median_ratio = ratio_new_over_base.median()

        scale_new_to_base = (
            1 / median_ratio
            if median_ratio != 0 and pd.notna(median_ratio)
            else 1.0
        )

        ratio_cv = (
            ratio_new_over_base.std() / ratio_new_over_base.mean()
            if ratio_new_over_base.mean() != 0
            else np.nan
        )

        method = "overlap_ratio"

    else:
        median_ratio = np.nan
        ratio_cv = np.nan
        scale_new_to_base = 1.0
        method = "no_rescale_insufficient_overlap"

    return {
        "overlap_days": len(overlap),
        "valid_ratio_days": len(valid),
        "overlap_corr": corr,
        "median_ratio_new_over_base": median_ratio,
        "scale_new_to_base": scale_new_to_base,
        "ratio_cv": ratio_cv,
        "method": method,
    }


def stitch_chunks_overlap_ratio(
    chunk_files: list[Path],
    query: str,
    min_overlap_days: int = 10,
) -> tuple[pd.DataFrame, pd.DataFrame]:

    chunk_files = sorted(chunk_files)

    if not chunk_files:
        return (
            pd.DataFrame(columns=["Time", query]),
            pd.DataFrame()
        )

    stitched = read_chunk_file(
        chunk_files[0],
        query
    )

    diag_rows = []

    diag_rows.append({
        "step": 0,
        "file": chunk_files[0].name,
        "overlap_days": np.nan,
        "valid_ratio_days": np.nan,
        "overlap_corr": np.nan,
        "median_ratio_new_over_base": np.nan,
        "scale_new_to_base": 1.0,
        "ratio_cv": np.nan,
        "method": "base_chunk",
    })

    for i, path in enumerate(chunk_files[1:], start=1):

        new = read_chunk_file(
            path,
            query
        )

        scale_info = estimate_overlap_scale(
            base=stitched,
            new=new,
            query=query,
            min_overlap_days=min_overlap_days,
        )

        new[query] = (
            new[query]
            * scale_info["scale_new_to_base"]
        )

        combined = pd.concat(
            [stitched, new],
            ignore_index=True
        )

        stitched = (
            combined
            .groupby("Time", as_index=False)[query]
            .mean()
            .sort_values("Time")
            .reset_index(drop=True)
        )

        diag_rows.append({
            "step": i,
            "file": path.name,
            **scale_info,
        })

    stitch_scale_diag = pd.DataFrame(diag_rows)

    return stitched, stitch_scale_diag


def make_stitching_diagnostics(
    stitched: pd.DataFrame,
    query: str
) -> pd.DataFrame:

    s = stitched[query]

    return pd.DataFrame([{
        "query": query,
        "n_rows": len(stitched),
        "min_date": stitched["Time"].min(),
        "max_date": stitched["Time"].max(),
        "missing_values": s.isna().sum(),
        "min_value": s.min(),
        "max_value": s.max(),
        "mean_value": s.mean(),
        "std_value": s.std(),
        "n_zero_values": (s == 0).sum(),
    }])


def fix_one_query_folder(query_folder: Path):

    folder = query_folder.name
    query = folder

    stitched_dir = Path(
        r"C:/Python/CSUREMM/dictionary V0.0/data_primitive_events"
    )
    stitched_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    chunk_files = sorted(
        query_folder.glob("gt_daily_*.csv")
    )

    if len(chunk_files) == 0:
        print(f"Skipping {folder}: no gt_daily_*.csv files found.")
        return

    stitched, _ = stitch_chunks_overlap_ratio(
        chunk_files=chunk_files,
        query=query,
        min_overlap_days=10,
    )

    stitched.to_csv(
        stitched_dir / f"gt_fixed_{folder}.csv",
        index=False
    )

    print(f"Saved {folder}: {len(stitched)} rows")


for query_folder in sorted(DATA_DIR.iterdir()):

    if not query_folder.is_dir():
        continue

    fix_one_query_folder(query_folder)

Saved accrue: 1612 rows
Saved advantage: 1612 rows
Saved affluence: 1612 rows
Saved affluent: 1612 rows
Saved afloat: 1612 rows
Saved allowance: 1612 rows
Saved aristocracy: 1612 rows
Saved aristocrat: 1612 rows
Saved aristocratic: 1612 rows
Saved associate: 1612 rows
Saved backer: 1612 rows
Saved backward: 1612 rows
Saved backwardness: 1612 rows
Saved bankrupt: 1612 rows
Saved bankruptcy: 1612 rows
Saved bargain: 1612 rows
Saved beggar: 1612 rows
Saved benefactor: 1612 rows
Saved beneficiary: 1612 rows
Saved benefit: 1612 rows
Saved benevolence: 1612 rows
Saved benevolent: 1612 rows
Saved bequeath: 1612 rows
Saved betroth: 1612 rows
Saved betrothal: 1612 rows
Saved blackmail: 1612 rows
Saved bonus: 1612 rows
Saved boom: 1612 rows
Saved breadwinner: 1612 rows
Saved bribe: 1612 rows
Saved broke: 1612 rows
Saved bum: 1612 rows
Saved buy: 1612 rows
Saved capitalize: 1612 rows
Saved charitable: 1612 rows
Saved charity: 1612 rows
Saved cheap: 1612 rows
Saved colony: 1612 rows
Saved commoner: 1612 rows
Saved community: 1612 rows
Saved compensate: 1612 rows
Saved compensation: 1612 rows
Saved contribute: 1612 rows
Saved contribution: 1612 rows
Saved cooperative: 1612 rows
Saved corrupt: 1612 rows
Saved cost: 1612 rows
Saved costly: 1612 rows
Saved crisis: 1612 rows
Skipping data_primitive_missing: no gt_daily_*.csv files found.
Saved debtor: 1612 rows
Saved default: 1612 rows
Saved deficit: 1612 rows
Saved depreciation: 1612 rows
Saved depression: 1612 rows
Saved destitute: 1612 rows
Saved domination: 1612 rows
Saved donate: 1612 rows
Saved donation: 1612 rows
Saved economize: 1612 rows
Saved endow: 1612 rows
Saved entrepreneurial: 1612 rows
Saved equity: 1612 rows
Saved expense: 1612 rows
Saved expensive: 1612 rows
Saved extravagant: 1612 rows
Saved fellowship: 1612 rows
Saved fine: 1612 rows
Saved fire: 1612 rows
Saved frugal: 1612 rows
Saved gain: 1612 rows
Saved gamble: 1612 rows
Saved generosity: 1612 rows
Saved ghetto: 1612 rows
Saved gift: 1612 rows
Saved gold: 1612 rows
Saved guide: 1612 rows
Saved hole: 1612 rows
Saved hustle: 1612 rows
Saved hustler: 1612 rows
Saved inexpensive: 1612 rows
Saved inflation: 1612 rows
Saved inherit: 1612 rows
Saved intervention: 1612 rows
Saved invaluable: 1612 rows
Saved jobless: 1612 rows
Saved laid: 1612 rows
Saved lay: 1612 rows
Saved legal: 1612 rows
Saved liquidate: 1612 rows
Saved liquidation: 1612 rows
Saved lucrative: 1612 rows
Saved luxury: 1612 rows
Saved meritorious: 1612 rows
Saved miser: 1612 rows
Saved negotiate: 1612 rows
Saved nobility: 1612 rows
Saved nobleman: 1612 rows
Saved owe: 1612 rows
Saved partner: 1612 rows
Saved partnership: 1612 rows
Saved patron: 1612 rows
Saved patronage: 1612 rows
Saved pollution: 1612 rows
Saved poor: 1612 rows
Saved poverty: 1612 rows
Saved precious: 1612 rows
Saved priceless: 1612 rows
Saved privileged: 1612 rows
Saved productive: 1612 rows
Saved productivity: 1612 rows
Saved profit: 1612 rows
Saved profitable: 1612 rows
Saved prosper: 1612 rows
Saved prosperity: 1612 rows
Saved prosperous: 1612 rows
Saved race: 1612 rows
Saved radical: 1612 rows
Saved recession: 1612 rows
Saved recompense: 1612 rows
Saved redemption: 1612 rows
Saved reparation: 1612 rows
Saved reward: 1612 rows
Saved rich: 1612 rows
Saved riches: 1612 rows
Saved richness: 1612 rows
Saved ruin: 1612 rows
Saved savings: 1612 rows
Saved security: 1612 rows
Saved segregation: 1612 rows
Saved shortage: 1612 rows
Saved skill: 1612 rows
Saved squander: 1612 rows
Saved steal: 1612 rows
Saved subsidize: 1612 rows
Saved subsidy: 1612 rows
Saved success: 1612 rows
Saved successful: 1612 rows
Saved tariff: 1612 rows
Saved thrift: 1612 rows
Saved thrifty: 1612 rows
Saved treasure: 1612 rows
Saved underworld: 1612 rows
Saved unemployed: 1612 rows
Saved unprofitable: 1612 rows
Saved vagabond: 1612 rows
Saved vagrant: 1612 rows
Saved valuable: 1612 rows
Saved warfare: 1612 rows
Saved waste: 1612 rows
Saved worth: 1612 rows

In [10]:
from pathlib import Path
import shutil


PRIMITIVE_EVENTS_DIR = Path(
    r"C:/Python/CSUREMM/dictionary V0.0/data_primitive_for_events"
)

DATA_EVENTS_DIR = Path(
    r"C:/Python/CSUREMM/data_events"
)

MASTER_DIR = Path(
    r"C:/Python/CSUREMM/data_primitve_events"
)

MASTER_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# 1. Copy all fixed primitive files
for file in sorted(PRIMITIVE_EVENTS_DIR.glob("gt_fixed_*.csv")):

    dest = MASTER_DIR / file.name

    shutil.copy2(
        file,
        dest
    )

    print(f"Copied primitive fixed: {file.name}")


# 2. Copy all stitched event files
for query_folder in sorted(DATA_EVENTS_DIR.iterdir()):

    if not query_folder.is_dir():
        continue

    stitched_dir = query_folder / "stitched"

    if not stitched_dir.exists():
        continue

    stitched_files = sorted(
        stitched_dir.glob("gt_fixed_*.csv")
    )

    if len(stitched_files) == 0:
        continue

    if len(stitched_files) > 1:
        print(
            f"Warning: multiple stitched files in {query_folder.name}; using first."
        )

    file = stitched_files[0]

    dest = MASTER_DIR / file.name

    shutil.copy2(
        file,
        dest
    )

    print(f"Copied event stitched: {file.name}")


print("Done.")
print(f"Master folder: {MASTER_DIR}")

Copied primitive fixed: gt_fixed_accrue.csv
Copied primitive fixed: gt_fixed_advantage.csv
Copied primitive fixed: gt_fixed_affluence.csv
Copied primitive fixed: gt_fixed_affluent.csv
Copied primitive fixed: gt_fixed_afloat.csv
Copied primitive fixed: gt_fixed_allowance.csv
Copied primitive fixed: gt_fixed_aristocracy.csv
Copied primitive fixed: gt_fixed_aristocrat.csv
Copied primitive fixed: gt_fixed_aristocratic.csv
Copied primitive fixed: gt_fixed_associate.csv
Copied primitive fixed: gt_fixed_backer.csv
Copied primitive fixed: gt_fixed_backward.csv
Copied primitive fixed: gt_fixed_backwardness.csv
Copied primitive fixed: gt_fixed_bankrupt.csv
Copied primitive fixed: gt_fixed_bankruptcy.csv
Copied primitive fixed: gt_fixed_bargain.csv
Copied primitive fixed: gt_fixed_beggar.csv
Copied primitive fixed: gt_fixed_benefactor.csv
Copied primitive fixed: gt_fixed_beneficiary.csv
Copied primitive fixed: gt_fixed_benefit.csv
Copied primitive fixed: gt_fixed_benevolence.csv
Copied primitive fixed: gt_fixed_benevolent.csv
Copied primitive fixed: gt_fixed_bequeath.csv
Copied primitive fixed: gt_fixed_betroth.csv
Copied primitive fixed: gt_fixed_betrothal.csv
Copied primitive fixed: gt_fixed_blackmail.csv
Copied primitive fixed: gt_fixed_bonus.csv
Copied primitive fixed: gt_fixed_boom.csv
Copied primitive fixed: gt_fixed_breadwinner.csv
Copied primitive fixed: gt_fixed_bribe.csv
Copied primitive fixed: gt_fixed_broke.csv
Copied primitive fixed: gt_fixed_bum.csv
Copied primitive fixed: gt_fixed_buy.csv
Copied primitive fixed: gt_fixed_capitalize.csv
Copied primitive fixed: gt_fixed_charitable.csv
Copied primitive fixed: gt_fixed_charity.csv
Copied primitive fixed: gt_fixed_cheap.csv
Copied primitive fixed: gt_fixed_colony.csv
Copied primitive fixed: gt_fixed_commoner.csv
Copied primitive fixed: gt_fixed_community.csv
Copied primitive fixed: gt_fixed_compensate.csv
Copied primitive fixed: gt_fixed_compensation.csv
Copied primitive fixed: gt_fixed_contribute.csv
Copied primitive fixed: gt_fixed_contribution.csv
Copied primitive fixed: gt_fixed_cooperative.csv
Copied primitive fixed: gt_fixed_corrupt.csv
Copied primitive fixed: gt_fixed_cost.csv
Copied primitive fixed: gt_fixed_costly.csv
Copied primitive fixed: gt_fixed_crisis.csv
Copied primitive fixed: gt_fixed_debtor.csv
Copied primitive fixed: gt_fixed_default.csv
Copied primitive fixed: gt_fixed_deficit.csv
Copied primitive fixed: gt_fixed_depreciation.csv
Copied primitive fixed: gt_fixed_depression.csv
Copied primitive fixed: gt_fixed_destitute.csv
Copied primitive fixed: gt_fixed_domination.csv
Copied primitive fixed: gt_fixed_donate.csv
Copied primitive fixed: gt_fixed_donation.csv
Copied primitive fixed: gt_fixed_economize.csv
Copied primitive fixed: gt_fixed_endow.csv
Copied primitive fixed: gt_fixed_entrepreneurial.csv
Copied primitive fixed: gt_fixed_equity.csv
Copied primitive fixed: gt_fixed_expense.csv
Copied primitive fixed: gt_fixed_expensive.csv
Copied primitive fixed: gt_fixed_extravagant.csv
Copied primitive fixed: gt_fixed_fellowship.csv
Copied primitive fixed: gt_fixed_fine.csv
Copied primitive fixed: gt_fixed_fire.csv
Copied primitive fixed: gt_fixed_frugal.csv
Copied primitive fixed: gt_fixed_gain.csv
Copied primitive fixed: gt_fixed_gamble.csv
Copied primitive fixed: gt_fixed_generosity.csv
Copied primitive fixed: gt_fixed_ghetto.csv
Copied primitive fixed: gt_fixed_gift.csv
Copied primitive fixed: gt_fixed_gold.csv
Copied primitive fixed: gt_fixed_guide.csv
Copied primitive fixed: gt_fixed_hole.csv
Copied primitive fixed: gt_fixed_hustle.csv
Copied primitive fixed: gt_fixed_hustler.csv
Copied primitive fixed: gt_fixed_inexpensive.csv
Copied primitive fixed: gt_fixed_inflation.csv
Copied primitive fixed: gt_fixed_inherit.csv
Copied primitive fixed: gt_fixed_intervention.csv
Copied primitive fixed: gt_fixed_invaluable.csv
Copied primitive fixed: gt_fixed_jobless.csv
Copied primitive fixed: gt_fixed_laid.csv
Copied primitive fixed: gt_fixed_lay.csv
Copied primitive fixed: gt_fixed_legal.csv
Copied primitive fixed: gt_fixed_liquidate.csv
Copied primitive fixed: gt_fixed_liquidation.csv
Copied primitive fixed: gt_fixed_lucrative.csv
Copied primitive fixed: gt_fixed_luxury.csv
Copied primitive fixed: gt_fixed_meritorious.csv
Copied primitive fixed: gt_fixed_miser.csv
Copied primitive fixed: gt_fixed_negotiate.csv
Copied primitive fixed: gt_fixed_nobility.csv
Copied primitive fixed: gt_fixed_nobleman.csv
Copied primitive fixed: gt_fixed_owe.csv
Copied primitive fixed: gt_fixed_partner.csv
Copied primitive fixed: gt_fixed_partnership.csv
Copied primitive fixed: gt_fixed_patron.csv
Copied primitive fixed: gt_fixed_patronage.csv
Copied primitive fixed: gt_fixed_pollution.csv
Copied primitive fixed: gt_fixed_poor.csv
Copied primitive fixed: gt_fixed_poverty.csv
Copied primitive fixed: gt_fixed_precious.csv
Copied primitive fixed: gt_fixed_priceless.csv
Copied primitive fixed: gt_fixed_privileged.csv
Copied primitive fixed: gt_fixed_productive.csv
Copied primitive fixed: gt_fixed_productivity.csv
Copied primitive fixed: gt_fixed_profit.csv
Copied primitive fixed: gt_fixed_profitable.csv
Copied primitive fixed: gt_fixed_prosper.csv
Copied primitive fixed: gt_fixed_prosperity.csv
Copied primitive fixed: gt_fixed_prosperous.csv
Copied primitive fixed: gt_fixed_race.csv
Copied primitive fixed: gt_fixed_radical.csv
Copied primitive fixed: gt_fixed_recession.csv
Copied primitive fixed: gt_fixed_recompense.csv
Copied primitive fixed: gt_fixed_redemption.csv
Copied primitive fixed: gt_fixed_reparation.csv
Copied primitive fixed: gt_fixed_reward.csv
Copied primitive fixed: gt_fixed_rich.csv
Copied primitive fixed: gt_fixed_riches.csv
Copied primitive fixed: gt_fixed_richness.csv
Copied primitive fixed: gt_fixed_ruin.csv
Copied primitive fixed: gt_fixed_savings.csv
Copied primitive fixed: gt_fixed_security.csv
Copied primitive fixed: gt_fixed_segregation.csv
Copied primitive fixed: gt_fixed_shortage.csv
Copied primitive fixed: gt_fixed_skill.csv
Copied primitive fixed: gt_fixed_squander.csv
Copied primitive fixed: gt_fixed_steal.csv
Copied primitive fixed: gt_fixed_subsidize.csv
Copied primitive fixed: gt_fixed_subsidy.csv
Copied primitive fixed: gt_fixed_success.csv
Copied primitive fixed: gt_fixed_successful.csv
Copied primitive fixed: gt_fixed_tariff.csv
Copied primitive fixed: gt_fixed_thrift.csv
Copied primitive fixed: gt_fixed_thrifty.csv
Copied primitive fixed: gt_fixed_treasure.csv
Copied primitive fixed: gt_fixed_underworld.csv
Copied primitive fixed: gt_fixed_unemployed.csv
Copied primitive fixed: gt_fixed_unprofitable.csv
Copied primitive fixed: gt_fixed_vagabond.csv
Copied primitive fixed: gt_fixed_vagrant.csv
Copied primitive fixed: gt_fixed_valuable.csv
Copied primitive fixed: gt_fixed_warfare.csv
Copied primitive fixed: gt_fixed_waste.csv
Copied primitive fixed: gt_fixed_worth.csv
Copied event stitched: gt_fixed_2020_election_results_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_2022_election_results_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_2024_election_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_2024_election_results_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_2024_presidential_election_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_2024_united_states_elections_results_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_2024_united_states_presidential_election_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_2024_us_election_results_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_49ers_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_80_for_brady_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_aaron_judge_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_aaron_rodgers_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_abcya_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_accuweather_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_airbnb_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_alabama_basketball_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_all_quiet_on_the_western_front_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_amanda_aldridge_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_amazon_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_amazon_prime_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_amazon_stock_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_amber_heard_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_amber_rose_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_amc_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_american_airlines_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_apple_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_apple_stock_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_arizona_election_results_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_arizona_governor_race_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_arsenal_vs_real_madrid_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_artistic_swimming_olympics_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_atlanta_braves_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_auburn_basketball_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_australian_open_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_australian_open_2022_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_baker_mayfield_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_bank_of_america_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_bath_and_body_works_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_batman_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_bengals_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_best_buy_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_biden_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_bitcoin_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_bitcoin_price_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_black_panther_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_blooket_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_blooket_join_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_boebert_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_boebert_election_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_boston_celtics_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_breakfast_near_me_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_brendan_fraser_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_britney_spears_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_btc_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_btc_price_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_buffalo_wild_wings_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_calculator_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_candy_hulu_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_canelo_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_canelo_vs_bivol_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_canva_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_capital_one_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_carhartt_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_carvana_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_celtics_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_celtics_vs_warriors_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_champions_league_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_charles_schwab_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_chase_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_chat_gpt_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_chatgpt_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_chicago_bears_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_chick_fil_a_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_chiefs_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_chinese_spy_balloon_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_cincinnati_bengals_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_clemson_football_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_cleveland_browns_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_clever_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_clima_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_cnbc_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_cnn_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_cnn_election_results_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_college_basketball_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_colorado_election_results_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_connections_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_cool_math_games_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_copa_del_rey_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_costco_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_covid_vaccine_near_me_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_cowboys_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_craigslist_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_credit_karma_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_crumbl_cookies_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_cvs_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dahmer_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dahmer_netflix_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dall_e_mini_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_davante_adams_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_daylight_savings_2023_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_deadpool_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_delta_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_deshaun_watson_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_desmos_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_diary_of_a_wimpy_kid_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dicks_sporting_goods_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_did_the_groundhog_see_his_shadow_2023_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dire_wolf_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_disney_plus_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_djia_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_docs_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dodgers_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dodgers_vs_phillies_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dollar_general_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dominos_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_don_t_worry_darling_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_donald_trump_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dow_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dow_futures_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dow_jones_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_dow_jones_today_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_duke_basketball_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_easter_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_ebay_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_election_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_election_2024_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_election_map_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_election_polls_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_election_results_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_election_results_2022_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_election_results_2024_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_election_results_so_far_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_elections_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_electoral_map_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_electoral_votes_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_electoral_votes_by_state_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_email_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_english_to_spanish_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_epic_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_espn_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_evan_peters_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_everything_everywhere_all_at_once_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_excessive_heat_warning_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_ezra_miller_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_facebook_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_facebook_login_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_father_s_day_2022_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_fathers_day_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_fedex_tracking_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_feliz_dia_de_la_madre_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_fidelity_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_fidelity_login_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_flights_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_florida_basketball_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_florida_hurricane_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_food_near_me_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_fox_news_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_fox_news_election_results_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_freeze_warning_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_ftx_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_full_moon_june_2022_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_gabby_thomas_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_games_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_gamestop_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_georgia_election_results_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_gimkit_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_gmail_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_gold_price_today_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_golden_state_warriors_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_google_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_google_calendar_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_google_classroom_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_google_docs_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_google_drive_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_google_finance_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_google_flights_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_google_maps_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_google_sheets_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_google_slides_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_google_translate_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_green_bay_packers_2022-01-01_2026-05-31.csv
Copied event stitched: gt_fixed_groundhog_day_2022-01-01_2026-05-31.csv